import { defineTemplate, type TemplateSeed } from "../define.js";

export const FORM_APPLICATION: TemplateSeed[] = [
  defineTemplate({
    slug: "reseller-application-form",
    type: "form",
    category: "application",
    goals: ["generate-leads"],
    roles: ["sales", "operations"],
    searchName: "Reseller application form",
    title: "Reseller application",
    icon: "Store",
    metaDescription:
      "Vet would-be resellers before you sign them: business type, markets, sales channels, similar brands they carry and why they want in. Unregistered sellers exit early.",
    description: "Screen potential resellers on how and where they sell before anyone gets on a call.",
    blurb:
      "Built for a partner manager who gets more reseller requests than they can call back. It asks the questions that separate a real sales channel from a curious buyer, stops early for businesses that are not registered yet, and only asks about competing brands when the applicant already sells some.",
    tags: ["reseller application", "reseller program", "partner application", "dealer application", "branching"],
    greeting: "Thanks for your interest in reselling with us. This takes about four minutes and helps us reply with something useful.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we get back to?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      { ref: "business_name", type: "short_text", title: "What is your business called?", required: true, maxLength: 120 },
      { ref: "website", type: "url", title: "Where can we see your business online?", description: "A website, marketplace store or social page all work.", required: false },
      {
        ref: "registered",
        type: "yes_no",
        title: "Is the business legally registered, with a tax or company number?",
        required: true,
        yesLabel: "Yes, it is",
        noLabel: "Not yet",
      },
      {
        ref: "business_type",
        type: "single_select",
        title: "Which best describes how you sell?",
        required: true,
        allowOther: true,
        options: [
          { label: "Online store of my own" },
          { label: "Marketplace seller" },
          { label: "Physical shop or showroom" },
          { label: "Distributor or wholesaler" },
          { label: "Agency or consultant reselling to clients" },
        ],
      },
      {
        ref: "years_trading",
        type: "dropdown",
        title: "How long have you been trading?",
        required: true,
        options: [{ label: "Less than a year" }, { label: "1 to 3 years" }, { label: "3 to 10 years" }, { label: "More than 10 years" }],
      },
      {
        ref: "location",
        type: "address",
        title: "Where is the business based?",
        required: true,
        fields: ["city", "state", "country"],
      },
      {
        ref: "channels",
        type: "multi_select",
        title: "Which channels would you use to sell our products?",
        required: true,
        minSelections: 1,
        maxSelections: 7,
        allowOther: true,
        options: [
          { label: "Own website" },
          { label: "Online marketplaces" },
          { label: "Retail shop" },
          { label: "Trade shows and events" },
          { label: "Direct sales team" },
          { label: "Social media" },
        ],
      },
      {
        ref: "target_market",
        type: "long_text",
        title: "Who are your customers, and which regions do you cover?",
        description: "For example: small cafes across the north of the country, or home cooks buying online nationwide.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "sells_similar",
        type: "yes_no",
        title: "Do you already sell products similar to ours?",
        required: true,
      },
      {
        ref: "similar_brands",
        type: "long_text",
        title: "Which brands, and how are they selling for you?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "expected_volume",
        type: "single_select",
        title: "Roughly how many units could you sell in a typical month once you are set up?",
        required: true,
        options: [{ label: "Under 50" }, { label: "50 to 200" }, { label: "200 to 1,000" }, { label: "More than 1,000" }, { label: "Too early to say" }],
      },
      {
        ref: "support_needed",
        type: "multi_select",
        title: "What would help you sell well?",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        options: [
          { label: "Product training" },
          { label: "Marketing materials and photos" },
          { label: "Demo or sample stock" },
          { label: "Co-marketing" },
          { label: "A dedicated account contact" },
        ],
      },
      {
        ref: "why_join",
        type: "long_text",
        title: "Why do you want to resell our products in particular?",
        required: true,
        maxLength: 1200,
      },
    ],
    branches: [
      { when: "registered", is: false, then: "end_not_registered" },
      { when: "registered", is: true, then: "business_type" },
      { when: "sells_similar", is: true, then: "similar_brands" },
      { when: "sells_similar", is: false, then: "expected_volume" },
    ],
    endings: [
      {
        ref: "end_not_registered",
        title: "Thanks for getting in touch",
        body: "Our reseller program is open to registered businesses only, so we can't take this application further for now. Once your business is registered, come back and apply again. We'd be glad to hear from you.",
      },
    ],
    ending: {
      title: "Application received 🤝",
      body: "Our partner team reviews every application and will reply by email within a few working days, either way.",
    },
    guide: {
      questionsToConsider: [
        "Do you need resellers to be registered businesses, or can individuals and side businesses apply?",
        "Are there regions or channels you already cover and would not want a new reseller competing in?",
        "Would a reseller who carries a direct competitor be a problem, or a sign they know the market?",
        "What minimum monthly volume makes a reseller worth the onboarding effort for your team?",
      ],
      howToUseResponses:
        "Sort applications by expected volume and business type first, then read the target market and why-join answers for the ones that fit. The similar-brands answer is often the most telling: a reseller already moving a comparable product has customers waiting. Filter the dashboard by country to spot overlap with partners you already have, and export to CSV if a regional manager needs their own shortlist.",
      customizeSteps: [
        "Swap the channel and support options for the ones your program actually offers, and remove the registration gate if you accept individual sellers.",
        "Rewrite the volume ranges in the units you sell, such as licences, cases or subscriptions.",
        "Link the form from your partners page or embed it there, and send approved applicants your onboarding pack by email.",
      ],
      faqs: [
        {
          q: "What should a reseller application form ask?",
          a: "Contact details, the business name and registration, how and where they sell, who their customers are, and why they want your products. Expected volume helps you prioritise which applications to answer first.",
        },
        {
          q: "How do I screen out applicants who are not a fit?",
          a: "Ask the deal-breaker questions early. This form checks registration fourth and ends politely for anyone not registered, so they never fill in the rest.",
        },
        {
          q: "Should I ask resellers about competing brands?",
          a: "Yes. A reseller who already sells a similar product knows the buyers, and knowing which brands they carry tells you how you would sit on their shelf or site.",
        },
        {
          q: "Can I use this as a distributor or dealer application instead?",
          a: "Yes. Copy it with Use this template, rename it, and adjust the business type and volume options. Every question can be edited.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "speaker-submission",
    type: "form",
    category: "application",
    goals: ["run-events"],
    roles: ["marketing", "operations"],
    searchName: "Call for speakers form",
    title: "Call for speakers",
    icon: "Mic",
    metaDescription:
      "Collect conference talk proposals a committee can compare: title, abstract, takeaways, format and bio. Workshops get setup questions, first-timers a mentor offer.",
    description: "Take talk proposals in a shape a review committee can compare at a glance.",
    blurb:
      "Proposals tend to arrive as essays when a committee needs a title, an abstract, a length and a bio side by side. This asks for exactly that, then branches: workshop proposals are asked what only a workshop needs, like room setup and what attendees must install, and first-time speakers are offered a mentor.",
    tags: ["call for speakers", "cfp form", "conference speaker application", "talk proposal", "branching"],
    greeting: "Got a talk in you? Tell us about it. Most people finish in about five minutes.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Who is proposing the talk?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      { ref: "pronouns", type: "short_text", title: "Which pronouns should we use in the programme?", required: false, maxLength: 40 },
      { ref: "talk_title", type: "short_text", title: "What is the talk called?", required: true, maxLength: 120 },
      {
        ref: "abstract",
        type: "long_text",
        title: "Give us the abstract. What is the talk about, and why now?",
        description: "This is what attendees will read in the programme, so write it for them.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "takeaways",
        type: "long_text",
        title: "Name three things someone will be able to do after your session.",
        description: "One per line. Reviewers weigh this more than anything else, so make it concrete.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "format",
        type: "single_select",
        title: "Which format fits the talk best?",
        required: true,
        options: [
          { label: "Lightning talk (10 min)" },
          { label: "Standard talk (30 min)" },
          { label: "Workshop (90 min)" },
        ],
      },

      // Workshops only
      {
        ref: "workshop_prereqs",
        type: "long_text",
        title: "What must attendees install or know before they arrive?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "workshop_capacity",
        type: "number",
        title: "How many people can you teach at once?",
        required: true,
        integerOnly: true,
        min: 5,
        max: 200,
      },
      {
        ref: "workshop_room",
        type: "single_select",
        title: "What room setup do you need?",
        required: false,
        options: [{ label: "Tables in groups" }, { label: "Theatre rows" }, { label: "Horseshoe" }, { label: "Doesn't matter" }],
      },

      // Everyone
      {
        ref: "level",
        type: "single_select",
        title: "Who is the talk for?",
        required: true,
        options: [{ label: "Beginners" }, { label: "Intermediate" }, { label: "Advanced" }, { label: "Everyone" }],
      },
      {
        ref: "bio",
        type: "long_text",
        title: "Write a short speaker bio, in the third person.",
        description: "Two or three sentences, as it would appear on the website.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "headshot",
        type: "file_upload",
        title: "Add a headshot for the programme, if you have one.",
        required: false,
        accept: ["image/*"],
        maxFiles: 1,
        maxSizeMB: 10,
      },
      {
        ref: "spoken_before",
        type: "yes_no",
        title: "Have you spoken at a conference before?",
        required: true,
        yesLabel: "Yes",
        noLabel: "This would be my first",
      },
      { ref: "previous_talk", type: "url", title: "Share a link to a previous talk, video or slides.", required: false },
      {
        ref: "wants_mentor",
        type: "yes_no",
        title: "Would you like a mentor to help you prepare?",
        description: "We pair first-time speakers with someone who has done it before.",
        required: false,
        yesLabel: "Yes please",
        noLabel: "No thanks",
      },
      {
        ref: "travel_support",
        type: "yes_no",
        title: "Would you need help with travel costs?",
        description: "We ask everyone, and it never counts against a proposal.",
        required: false,
      },
      {
        ref: "recording",
        type: "legal_consent",
        title: "Recording",
        required: true,
        allowDecline: true,
        agreeLabel: "Happy to be recorded",
        declineLabel: "Please don't record",
        consentText:
          "If my talk is accepted, I agree that it may be recorded and the video and slides published after the event.",
      },
    ],
    branches: [
      { when: "format", is: "Lightning talk (10 min)", then: "level" },
      { when: "format", is: "Standard talk (30 min)", then: "level" },
      { when: "format", is: "Workshop (90 min)", then: "workshop_prereqs" },
      { when: "spoken_before", is: true, then: "previous_talk" },
      { when: "spoken_before", is: false, then: "wants_mentor" },
      { when: "previous_talk", always: true, then: "travel_support" },
    ],
    ending: {
      title: "Proposal submitted 🎤",
      body: "Thank you. We review proposals in batches after the deadline and reply to everyone, accepted or not.",
    },
    guide: {
      questionsToConsider: [
        "Which formats and lengths does your schedule actually have room for?",
        "Do you review proposals anonymously? If so, keep the bio and headshot out of what reviewers see first.",
        "Can you offer mentoring or travel support, and on what terms?",
        "Will sessions be recorded, and do speakers get a real choice about it?",
        "Do you want topic tracks as a question, so proposals sort themselves?",
      ],
      howToUseResponses:
        "Export the proposals to CSV and give reviewers only the title, abstract, takeaways, format and level, so they judge the talk before the name. Score each proposal on the takeaways, since vague ones usually mean a vague talk. Before building the schedule, pull out the workshop answers for room setup and capacity, and send the prerequisites to workshop attendees well ahead of the day.",
      customizeSteps: [
        "Change the format options to the slot lengths in your schedule, and keep the workshop questions only if you run workshops.",
        "Rewrite the mentor and travel questions to say exactly what you offer, or remove them if you offer neither.",
        "Add your deadline to the greeting, then share the link on your event site and social channels.",
      ],
      faqs: [
        {
          q: "What should a call for speakers form include?",
          a: "Contact details, a talk title, an abstract, concrete takeaways, the format and audience level, and a short bio. Anything else, like a headshot or a past talk, should be optional.",
        },
        {
          q: "How long should a talk abstract be?",
          a: "Long enough to explain what the talk covers and why it matters, short enough to fit in a printed programme. A couple of short paragraphs is usually right.",
        },
        {
          q: "How do I encourage first-time speakers to apply?",
          a: "Say plainly that first-timers are welcome and offer something concrete, like a mentor. This form only offers mentoring to people who have not spoken before, so experienced speakers skip it.",
        },
        {
          q: "Can I ask workshop hosts different questions?",
          a: "Yes. This template branches on the format, so only workshop proposals are asked about prerequisites, capacity and room setup.",
        },
      ],
    },
  }),
];
