import { defineTemplate, type TemplateSeed } from "../define.js";

export const FORM_BUSINESS: TemplateSeed[] = [
  defineTemplate({
    slug: "giveaway-entry-form",
    type: "form",
    category: "business",
    goals: ["generate-leads"],
    roles: ["marketing"],
    searchName: "Giveaway entry form",
    title: "Giveaway entry",
    icon: "Gift",
    metaDescription:
      "Take giveaway entries with an age check up front, one clean record per entrant, how the winner wants the prize, a newsletter opt-in and agreement to the rules.",
    description: "A short, fair entry path that checks eligibility first and records rule acceptance.",
    blurb:
      "Entrants answer the eligibility question before anything else, so anyone under 18 is told kindly and never fills in the rest. Everyone else gets a quick run through contact details, how they would like the prize delivered and a separate newsletter opt-in, so a giveaway entry is never mistaken for marketing consent.",
    tags: ["giveaway entry form", "contest entry", "sweepstakes form", "prize draw", "competition entry"],
    greeting: "You're a couple of minutes away from being entered. Let's check you're eligible first.",
    questions: [
      {
        ref: "over_18",
        type: "yes_no",
        title: "Are you 18 or older?",
        required: true,
        yesLabel: "Yes, I am",
        noLabel: "No, not yet",
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Where should we contact you if you win?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "location",
        type: "address",
        title: "Which country and city do you live in?",
        description: "The rules say where the giveaway is open, and we check before announcing a winner.",
        required: true,
        fields: ["city", "country"],
      },
      {
        ref: "prize_choice",
        type: "single_select",
        title: "If you win, how would you like to receive the prize?",
        description: "We'll confirm the details with the winner before anything is sent.",
        required: true,
        options: [{ label: "Posted to my address" }, { label: "Collected in person" }, { label: "A digital voucher instead" }, { label: "Whatever's easiest" }],
      },
      {
        ref: "heard_about",
        type: "dropdown",
        title: "How did you hear about the giveaway?",
        required: false,
        options: [
          { label: "Instagram" },
          { label: "TikTok" },
          { label: "Facebook" },
          { label: "Email newsletter" },
          { label: "A friend told me" },
          { label: "In store" },
          { label: "Somewhere else" },
        ],
      },
      {
        ref: "why_win",
        type: "long_text",
        title: "In a sentence or two, what would winning mean to you?",
        description: "Optional, and it has no effect on who wins. The draw is random.",
        required: false,
        maxLength: 400,
      },
      {
        ref: "newsletter",
        type: "yes_no",
        title: "Would you also like our newsletter? Saying no won't affect your entry.",
        required: true,
        yesLabel: "Yes, sign me up",
        noLabel: "Just the giveaway",
      },
      {
        ref: "rules",
        type: "legal_consent",
        title: "Official rules",
        required: true,
        consentText:
          "I have read the official giveaway rules, I am entering once, and I understand the winner is picked at random from eligible entries and contacted by email.",
      },
    ],
    branches: [
      { when: "over_18", is: false, then: "end_not_eligible" },
      { when: "over_18", is: true, then: "contact" },
    ],
    endings: [
      {
        ref: "end_not_eligible",
        title: "Sorry, this one is 18+",
        body: "This giveaway is only open to adults, so we haven't recorded an entry. Thanks for your interest, and keep an eye out for future ones.",
      },
    ],
    ending: {
      title: "You're entered 🎉",
      body: "Good luck! We'll pick a winner after the closing date and contact them by email, so check your spam folder around then.",
    },
    guide: {
      questionsToConsider: [
        "What is the minimum age, and which countries or regions can legally enter where you run this?",
        "Is one entry per person the rule, or do referrals earn extra entries?",
        "Is the prize something you post, hand over in person or send digitally, and do you offer a voucher alternative?",
        "Where do your official rules live, and does the consent text link to them clearly?",
      ],
      howToUseResponses:
        "Before the draw, export entries to CSV and remove duplicates by email, then check every remaining entrant's country against your rules. Pick the winner at random from the cleaned list and keep a copy of it in case anyone asks how the draw was run. Only add people who said yes to the newsletter to your mailing list, and use the heard-about answers to see which channel brought in the most entries for next time.",
      customizeSteps: [
        "Name the prize in the greeting, and change the delivery options to the ways you can actually hand it over, or delete that question if there is only one.",
        "Change the age question and the consent text to match your official rules, and add a link to the full rules in the consent wording.",
        "Put the closing date in the greeting, then share the link in your posts or embed it on a landing page.",
      ],
      faqs: [
        {
          q: "What should a giveaway entry form include?",
          a: "An eligibility check, contact details to reach the winner, a location if the giveaway is limited by region, and agreement to the official rules. Keep marketing opt-ins separate and optional.",
        },
        {
          q: "Can I require people to join my newsletter to enter?",
          a: "Privacy laws such as the GDPR expect marketing consent to be freely given, so it is safer to make the newsletter a separate, optional choice. This form asks it as its own question and says the answer won't affect the entry.",
        },
        {
          q: "How do I stop people entering more than once?",
          a: "State one entry per person in the rules, then remove duplicate emails before the draw. The consent line in this form also has entrants confirm they are entering once.",
        },
        {
          q: "How do I pick a winner fairly?",
          a: "Export the eligible entries, number them, and use a random number generator to pick one. Keep the list and the result in case you need to show how it was done.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "online-suggestion-box",
    type: "form",
    category: "business",
    goals: ["collect-feedback"],
    roles: ["hr-people", "operations"],
    searchName: "Online suggestion box",
    title: "Suggestion box",
    icon: "Lightbulb",
    metaDescription:
      "A suggestion box people will actually use: the idea, the problem it solves, who it helps and how much, with an anonymous option and follow-up for named ideas.",
    description: "Collect improvement ideas with enough context to act on, named or anonymous.",
    blurb:
      "A good suggestion names a problem, not just a wish, so this asks for both. People who raised the idea before are asked what happened to it, which is often the most useful answer you'll get. Anyone who wants to stay anonymous can finish without a name, and named contributors are asked if they'd help make it happen.",
    tags: ["online suggestion box", "employee suggestions", "anonymous feedback", "idea submission", "branching"],
    greeting: "Got an idea that would make things better here? We'd like to hear it, big or small.",
    questions: [
      {
        ref: "area",
        type: "single_select",
        title: "What is your suggestion about?",
        required: true,
        allowOther: true,
        options: [
          { label: "How we work day to day" },
          { label: "Tools and equipment" },
          { label: "The customer experience" },
          { label: "The building or workspace" },
          { label: "Team culture and communication" },
        ],
      },
      {
        ref: "suggestion",
        type: "long_text",
        title: "What's your suggestion?",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "problem",
        type: "long_text",
        title: "What problem would it fix, or what would it make better?",
        description: "An example of when you ran into it helps a lot.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "who_benefits",
        type: "multi_select",
        title: "Who would it help?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        options: [{ label: "Me" }, { label: "My team" }, { label: "Everyone here" }, { label: "Customers" }, { label: "Visitors or the wider community" }],
      },
      {
        ref: "impact",
        type: "opinion_scale",
        title: "How big a difference do you think it would make?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "A small tweak",
        labelHigh: "A big change",
      },
      {
        ref: "raised_before",
        type: "yes_no",
        title: "Have you suggested this before, anywhere?",
        required: true,
      },
      {
        ref: "what_happened",
        type: "long_text",
        title: "What happened when you raised it?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "anonymous",
        type: "yes_no",
        title: "Would you like to stay anonymous?",
        required: true,
        yesLabel: "Keep me anonymous",
        noLabel: "Add my name",
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we credit and follow up with?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "help",
        type: "yes_no",
        title: "If we go ahead, would you like to help put it in place?",
        required: false,
        yesLabel: "Count me in",
        noLabel: "Just sharing the idea",
      },
    ],
    branches: [
      { when: "raised_before", is: true, then: "what_happened" },
      { when: "raised_before", is: false, then: "anonymous" },
      { when: "anonymous", is: true, then: "end_anonymous" },
      { when: "anonymous", is: false, then: "contact" },
    ],
    endings: [
      {
        ref: "end_anonymous",
        title: "Thanks, received anonymously",
        body: "Your suggestion arrived without your name. We review every one and share what we decide to act on with everyone.",
      },
    ],
    ending: {
      title: "Thanks for the idea 💡",
      body: "We review suggestions regularly and will let you know what happens with yours, whether or not we go ahead.",
    },
    guide: {
      questionsToConsider: [
        "Who reads the suggestions, and how often will they meet to decide on them?",
        "Should anonymity be the default, or is a name expected in your workplace or community?",
        "Which areas do people most often have ideas about? Those make the best options for the first question.",
        "How will you tell people what happened to their suggestion, including the ones you turn down?",
      ],
      howToUseResponses:
        "Review suggestions on a fixed schedule rather than as they arrive, grouped by area. Weigh the impact score against how many people it would help, and pay close attention to ideas that were raised before, since a repeat means the first answer did not land. Reply to named contributors either way, and post a short summary of accepted and declined ideas so anonymous contributors can see the box leads somewhere.",
      customizeSteps: [
        "Rewrite the area options for your setting, such as departments for a company or facilities for a school or club.",
        "Decide whether to keep the anonymous option, and if you keep it, say who can see names in the greeting.",
        "Share the link somewhere people already look, like an intranet page, a QR code on a noticeboard or a pinned chat message.",
      ],
      faqs: [
        {
          q: "Can an online suggestion box be anonymous?",
          a: "Yes. This one lets each person choose. If they pick anonymous, the form ends without asking for a name or email.",
        },
        {
          q: "How do I get people to actually use a suggestion box?",
          a: "Show that suggestions lead somewhere. Reply to named contributors and share what you decided on the anonymous ones, and people keep using it.",
        },
        {
          q: "What should a suggestion box form ask?",
          a: "The idea, the problem it solves, who it helps and how big a difference it would make. Without the problem, a suggestion is hard to judge.",
        },
        {
          q: "Can I use this for customers instead of staff?",
          a: "Yes. Copy it with Use this template and change the area options to parts of your product or service. Every question can be edited.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "software-incident-report-form",
    type: "form",
    category: "business",
    goals: [],
    roles: ["operations", "product-research"],
    searchName: "Software incident report form",
    title: "Software incident report",
    icon: "Bug",
    metaDescription:
      "Log software incidents in one consistent shape: affected service, severity, start time, impact, what was tried and evidence. Critical ones ask for a callback number.",
    description: "Record what broke, when, how badly and for whom, in a shape your on-call team can triage.",
    blurb:
      "Written for the person who notices a problem, not the engineer who fixes it, so it asks plain questions and turns them into a triage-ready record. A critical report asks for a number the on-call engineer can ring right away, and an incident that has already stopped is asked how it resolved.",
    tags: ["software incident report", "it incident form", "outage report", "service disruption", "branching"],
    greeting: "Something not working? Tell us what you're seeing and we'll get the right person on it.",
    questions: [
      {
        ref: "reporter",
        type: "contact_info",
        title: "Who is reporting this?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "service",
        type: "short_text",
        title: "Which system, app or service is affected?",
        description: "As specific as you can, for example the billing page in the customer portal.",
        required: true,
        maxLength: 200,
      },
      {
        ref: "environment",
        type: "single_select",
        title: "Where is it happening?",
        required: true,
        options: [{ label: "Live, for real users" }, { label: "Staging or test" }, { label: "My own device only" }, { label: "Not sure" }],
      },
      {
        ref: "started_at",
        type: "date",
        title: "When did it start, as best you know?",
        required: true,
        includeTime: true,
        timeStepMinutes: 15,
        timeMin: "00:00",
        timeMax: "23:45",
      },
      {
        ref: "severity",
        type: "single_select",
        title: "How bad is it right now?",
        required: true,
        options: [
          { label: "Critical: it's down or data is at risk", description: "Nobody can use it, or something is being lost or exposed." },
          { label: "Major: a key feature is broken", description: "People can work around it, but not for long." },
          { label: "Minor: annoying but workable" },
          { label: "Already fixed, just logging it" },
        ],
      },
      {
        ref: "callback_phone",
        type: "phone",
        title: "What number can the on-call engineer reach you on right now?",
        required: true,
      },
      {
        ref: "ongoing",
        type: "yes_no",
        title: "Is it still happening?",
        required: true,
      },
      {
        ref: "resolution",
        type: "long_text",
        title: "What made it stop, and roughly when?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "what_happened",
        type: "long_text",
        title: "What exactly are you seeing?",
        description: "Include any error message word for word, and what you were doing when it happened.",
        required: true,
        maxLength: 2000,
        aiQualityCheck: true,
      },
      {
        ref: "who_affected",
        type: "single_select",
        title: "Who is affected?",
        required: true,
        options: [{ label: "All users" }, { label: "Some users or one region" }, { label: "Only our internal team" }, { label: "Just me, as far as I know" }, { label: "Not sure" }],
      },
      {
        ref: "impact",
        type: "multi_select",
        title: "What is it getting in the way of?",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        allowOther: true,
        options: [
          { label: "Signing in" },
          { label: "Taking payments or orders" },
          { label: "Saving or loading data" },
          { label: "Sending emails or notifications" },
          { label: "Internal work only" },
        ],
      },
      {
        ref: "tried",
        type: "long_text",
        title: "What have you or anyone else already tried?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "evidence",
        type: "file_upload",
        title: "Add a screenshot, recording or log file if you have one.",
        required: false,
        accept: ["image/*", "video/*", "text/plain", "application/pdf"],
        maxFiles: 5,
        maxSizeMB: 25,
      },
    ],
    branches: [
      { when: "severity", is: "Critical: it's down or data is at risk", then: "callback_phone" },
      { when: "severity", is: "Major: a key feature is broken", then: "ongoing" },
      { when: "severity", is: "Minor: annoying but workable", then: "ongoing" },
      { when: "severity", is: "Already fixed, just logging it", then: "resolution" },
      { when: "callback_phone", always: true, then: "what_happened" },
      { when: "ongoing", is: false, then: "resolution" },
      { when: "ongoing", is: true, then: "what_happened" },
    ],
    ending: {
      title: "Incident logged 🛠️",
      body: "Thanks. The team has your report and will follow up by email. If it gets worse before then, report it again with the new details.",
    },
    guide: {
      questionsToConsider: [
        "What counts as critical for your service, and does the wording of the severity options match your incident policy?",
        "Is there an urgent channel, like an on-call phone line, that people should use instead of the form for outages?",
        "Which systems do people most often report? A dropdown of them may beat a free-text answer.",
        "Who reads new reports, and during which hours?",
      ],
      howToUseResponses:
        "Triage from the severity and who-is-affected answers first, then assign an owner. Critical reports carry a phone number, so ring back rather than replying by email. Keep the start time and the resolution answer for the incident timeline, and export the reports to CSV each month to see which services break most and whether the same impact keeps coming up.",
      customizeSteps: [
        "Rename the severity levels to match your incident process, keeping the critical option first so it routes to the callback question.",
        "Replace the impact options with the parts of your product people depend on most.",
        "Share the link in your help desk, status page and internal chat so reports land in one place, and review them in the dashboard.",
      ],
      faqs: [
        {
          q: "What should a software incident report include?",
          a: "The affected service, when it started, how severe it is, who is affected, what the person saw and what has been tried. A screenshot or error message makes it much faster to diagnose.",
        },
        {
          q: "Is an incident report the same as a bug report?",
          a: "Not quite. An incident report records a disruption to a running service, while a bug report describes a defect that may never have caused an outage.",
        },
        {
          q: "How do I handle critical incidents reported through a form?",
          a: "Make sure someone is watching for them. This form asks critical reporters for a phone number so the on-call engineer can call straight back.",
        },
        {
          q: "Can non-technical staff use this form?",
          a: "Yes. The questions are in plain language, and in the chat an AI follow-up asks for more detail when a description is too vague to act on.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "client-information-form",
    type: "form",
    category: "business",
    goals: ["onboard-clients"],
    roles: ["freelancers-agencies", "operations"],
    searchName: "Client information form",
    title: "Client information",
    icon: "Building2",
    metaDescription:
      "Gather what you need to start a client project: main contact, legal and billing details, who approves work, which accounts you need and who else to keep informed.",
    description: "One record of who your client is, who to bill and who else to keep in the loop.",
    blurb:
      "Built for agencies and freelancers to send once a client signs, so kickoff doesn't start with a week of emails. It records who approves work and which accounts you'll need access to, asks for a separate billing contact only when someone else pays the invoices, and gathers everyone else on the project in one repeating list.",
    tags: ["client information form", "client intake", "new client form", "client onboarding", "customer information form"],
    greeting: "Welcome aboard! A few details now saves a lot of back and forth later. It takes about five minutes.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Who will be our main contact?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      { ref: "job_title", type: "short_text", title: "What is your role or job title?", required: false, maxLength: 100 },
      { ref: "company", type: "short_text", title: "What is the company's legal name?", description: "As it should appear on contracts and invoices.", required: true, maxLength: 150 },
      { ref: "website", type: "url", title: "What is the company website?", required: false },
      {
        ref: "address",
        type: "address",
        title: "What is the company's registered address?",
        required: true,
        fields: ["street", "city", "state", "postal", "country"],
      },
      { ref: "tax_id", type: "short_text", title: "Do you have a tax or VAT number we should put on invoices?", required: false, maxLength: 40 },
      {
        ref: "industry",
        type: "dropdown",
        title: "Which industry are you in?",
        required: true,
        options: [
          { label: "Retail and ecommerce" },
          { label: "Software and technology" },
          { label: "Professional services" },
          { label: "Health and wellness" },
          { label: "Education" },
          { label: "Hospitality and food" },
          { label: "Manufacturing" },
          { label: "Non-profit" },
          { label: "Real estate" },
          { label: "Something else" },
        ],
      },
      {
        ref: "approver",
        type: "short_text",
        title: "Who has the final say when work needs approving?",
        description: "A name and role. If it's you, just say so.",
        required: true,
        maxLength: 150,
      },
      {
        ref: "access_needed",
        type: "multi_select",
        title: "Which of these will we probably need access to?",
        description: "Just tick them for now. Never send passwords in this form; we'll arrange access safely.",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        allowOther: true,
        options: [
          { label: "Website or content system" },
          { label: "Domain or hosting" },
          { label: "Social media accounts" },
          { label: "Analytics or ad accounts" },
          { label: "Brand files and logos" },
          { label: "Shared drive or documents" },
        ],
      },
      {
        ref: "handles_billing",
        type: "yes_no",
        title: "Should invoices go to you?",
        required: true,
        yesLabel: "Yes, send them to me",
        noLabel: "No, someone else",
      },
      { ref: "billing_name", type: "short_text", title: "Who should receive invoices?", required: true, maxLength: 120 },
      { ref: "billing_email", type: "email", title: "What is their email address?", required: true },
      { ref: "po_number", type: "short_text", title: "Do invoices need a purchase order number?", description: "Leave blank if not.", required: false, maxLength: 60 },
      {
        ref: "other_contacts",
        type: "field_group",
        title: "Who else should we keep in the loop on the project?",
        required: false,
        itemLabel: "Contact",
        minEntries: 1,
        maxEntries: 6,
        fields: [
          { id: "fld_ocname", key: "name", label: "Name", kind: "short_text", required: true },
          { id: "fld_ocrole", key: "role", label: "Role on the project", kind: "short_text" },
          { id: "fld_ocmail", key: "email", label: "Email", kind: "email", required: true },
        ],
      },
      {
        ref: "comms",
        type: "multi_select",
        title: "How do you prefer to hear from us?",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        options: [{ label: "Email" }, { label: "Phone calls" }, { label: "Video calls" }, { label: "A shared chat channel" }],
      },
      {
        ref: "notes",
        type: "long_text",
        title: "Anything else we should know before we start?",
        description: "Working hours, approval steps, people who must sign off, anything that tends to trip projects up.",
        required: false,
        maxLength: 1500,
      },
    ],
    branches: [
      { when: "handles_billing", is: true, then: "po_number" },
      { when: "handles_billing", is: false, then: "billing_name" },
    ],
    ending: {
      title: "All set, thank you 🙌",
      body: "We've saved your details. Your project lead will be in touch shortly with the next steps and a kickoff time.",
    },
    guide: {
      questionsToConsider: [
        "Which details do you need on invoices and contracts in your country, such as a tax number or registered address?",
        "Do clients often have a separate finance team, and do their invoices need a purchase order number?",
        "Is one approver enough, or do your projects usually need sign-off from legal or a second manager too?",
        "Which accounts and files do you chase after kickoff? Those belong in the access question's options.",
      ],
      howToUseResponses:
        "Copy the answers into your client records as soon as they arrive, and check the legal name and address against the signed contract. Set up invoicing from the billing answers, including any purchase order number, so the first invoice is not bounced back. Send access requests for every account the client ticked before kickoff, agree review rounds with the named approver, and add everyone from the other-contacts list to project updates on the channels the client picked.",
      customizeSteps: [
        "Change the access options to the accounts and files your kind of work depends on, and edit or remove the industry question.",
        "Add anything else you always need at kickoff, such as a file upload for brand guidelines or a question about key deadlines.",
        "Send the link in your welcome email right after the contract is signed, and open each response in the dashboard before kickoff.",
      ],
      faqs: [
        {
          q: "What should a client information form include?",
          a: "The main contact, the company's legal name and address, who approves work, which accounts you will need access to, the billing contact and invoice requirements, other people on the project, and how the client likes to communicate.",
        },
        {
          q: "When should I send a client information form?",
          a: "Right after the client agrees to work with you and before kickoff. That way invoicing and communication are sorted before the work starts.",
        },
        {
          q: "Is a client information form the same as a client intake form?",
          a: "They overlap. An intake form usually asks about goals and the project itself, while this one collects the practical details you need to work with and bill the client.",
        },
        {
          q: "Should a client information form ask for passwords or logins?",
          a: "No. Ask which accounts you will need, as this form does, and set up access through each tool's own sharing or user invites. Passwords sitting in form responses are a risk to you and the client.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "estimate-form",
    type: "form",
    category: "business",
    goals: ["generate-leads"],
    roles: ["sales", "operations"],
    searchName: "Estimate form",
    title: "Estimate request",
    icon: "Calculator",
    metaDescription:
      "Collect what you need to price a job before a site visit: the work, the property, size, photos, timing and budget. Urgent jobs are asked for a number to call.",
    description: "Get the job details, photos and timing you need to send a realistic estimate.",
    blurb:
      "For trades and service businesses that lose hours to vague enquiries. It asks what the job is, where, how big and how soon, with room for photos, so you can price it or decide a visit is needed. Urgent jobs are asked for a phone number, and flexible ones skip the start-date question.",
    tags: ["estimate form", "estimate request", "job estimate", "free estimate form", "service quote request"],
    greeting: "Hi! Tell us about the job and we'll come back with an estimate. It takes about three minutes.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Who is the estimate for?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "job_type",
        type: "single_select",
        title: "What kind of job is it?",
        required: true,
        allowOther: true,
        options: [
          { label: "A repair" },
          { label: "A new installation" },
          { label: "A renovation or upgrade" },
          { label: "Regular maintenance" },
          { label: "Not sure yet, I need advice" },
        ],
      },
      {
        ref: "job_details",
        type: "long_text",
        title: "Describe the job in your own words.",
        description: "What needs doing, what's there now, and anything you already know you want, like materials or finish.",
        required: true,
        maxLength: 2000,
        aiQualityCheck: true,
      },
      {
        ref: "property_type",
        type: "single_select",
        title: "What type of property is it?",
        required: true,
        options: [{ label: "House" }, { label: "Apartment or flat" }, { label: "Office or shop" }, { label: "Industrial or warehouse" }, { label: "Something else" }],
      },
      {
        ref: "site_address",
        type: "address",
        title: "Where is the job?",
        required: true,
        fields: ["street", "city", "postal"],
      },
      {
        ref: "size",
        type: "short_text",
        title: "Roughly how big is the area or job?",
        description: "For example: two rooms, 30 square metres, or 12 windows. A rough guess is fine.",
        required: false,
        maxLength: 120,
      },
      {
        ref: "photos",
        type: "file_upload",
        title: "Add photos of the area, if you can.",
        description: "Photos often let us price a job without a visit.",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 6,
        maxSizeMB: 20,
      },
      {
        ref: "timing",
        type: "single_select",
        title: "When do you need it done?",
        required: true,
        options: [{ label: "As soon as possible" }, { label: "Within a month" }, { label: "In 1 to 3 months" }, { label: "I'm flexible" }],
      },
      { ref: "urgent_phone", type: "phone", title: "What's the best number for a quick call about it?", required: true },
      { ref: "start_date", type: "date", title: "Is there a date you'd like the work to start by?", required: false, disablePast: true },
      {
        ref: "budget",
        type: "dropdown",
        title: "Do you have a budget in mind?",
        description: "It helps us suggest options that fit. Pick not sure if you're still exploring.",
        required: false,
        options: [
          { label: "Under 500" },
          { label: "500 to 2,000" },
          { label: "2,000 to 10,000" },
          { label: "More than 10,000" },
          { label: "Not sure yet" },
        ],
      },
      {
        ref: "visit_ok",
        type: "yes_no",
        title: "If we need to see it before pricing, is a site visit okay?",
        required: true,
      },
    ],
    branches: [
      { when: "timing", is: "As soon as possible", then: "urgent_phone" },
      { when: "timing", is: "Within a month", then: "start_date" },
      { when: "timing", is: "In 1 to 3 months", then: "start_date" },
      { when: "timing", is: "I'm flexible", then: "budget" },
      { when: "urgent_phone", always: true, then: "budget" },
    ],
    ending: {
      title: "Request received 📋",
      body: "Thanks! We'll review the details and send your estimate, or get in touch to arrange a visit if the job needs one.",
    },
    guide: {
      questionsToConsider: [
        "Which details change your price the most? Make those required and drop anything that doesn't affect the estimate.",
        "Can you price from photos, or do you always visit? Say so in the photo question.",
        "Do the budget ranges fit the jobs you take on, and are they in your currency?",
        "How quickly can you respond to an urgent job, and is that promise in the ending?",
      ],
      howToUseResponses:
        "Call the urgent requests first, since those people often ask several businesses at once. For the rest, compare the description, size and photos to decide whether you can estimate straight away or need a visit. List your assumptions in the estimate, like materials or access, so the price holds up. Export requests to CSV now and then to see which job types come in most.",
      customizeSteps: [
        "Replace the job type options with the services you actually offer, and adjust the size example to how you measure work.",
        "Set the budget ranges in your currency and at levels that match your typical jobs.",
        "Embed the form on your website's quote page and link it from your listings, then reply to each request from the dashboard.",
      ],
      faqs: [
        {
          q: "What should an estimate request form include?",
          a: "Contact details, what the job is, where it is, how big it is and when it's needed. Photos and a budget range help you price it without a visit.",
        },
        {
          q: "What is the difference between an estimate and a quote?",
          a: "An estimate is an approximate price based on the details you have. A quote is usually a fixed price for an agreed scope, often given after a visit.",
        },
        {
          q: "Should I ask customers for their budget?",
          a: "A range helps you suggest options that fit, as long as it stays optional. Keep a not sure answer for people who are still exploring.",
        },
        {
          q: "Can I use this estimate form for my trade?",
          a: "Yes. It works for most trades and services. Copy it with Use this template and edit the job types and questions to match your work.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "insurance-quote-form",
    type: "form",
    category: "business",
    goals: ["generate-leads"],
    roles: ["sales"],
    searchName: "Insurance quote form",
    title: "Insurance quote request",
    icon: "ShieldCheck",
    metaDescription:
      "Take insurance quote requests that ask the right questions per cover type: home, car, life, health, business or travel, then timing, priorities and contact details.",
    description: "An insurance enquiry that asks different questions for each type of cover.",
    blurb:
      "One form for every line you sell. The first answer decides the next few questions, so a driver is asked about their car, age and claims while a traveller is asked about their trip, and nobody wades through the rest. Everyone then ranks what matters most to them, which tells your advisers where to start the conversation.",
    tags: ["insurance quote form", "insurance enquiry", "insurance lead form", "quote request", "branching"],
    greeting: "Looking for cover? Answer a few questions and one of our advisers will come back with a quote.",
    questions: [
      {
        ref: "cover_type",
        type: "single_select",
        title: "What would you like cover for?",
        required: true,
        options: [
          { label: "Home" },
          { label: "Car" },
          { label: "Life" },
          { label: "Health" },
          { label: "Business" },
          { label: "Travel" },
        ],
      },

      // Home
      {
        ref: "home_status",
        type: "single_select",
        title: "Do you own or rent the home?",
        required: true,
        options: [{ label: "I own it" }, { label: "I rent it" }, { label: "I'm a landlord letting it out" }],
      },
      {
        ref: "home_cover",
        type: "multi_select",
        title: "What should the policy cover?",
        required: true,
        minSelections: 1,
        maxSelections: 2,
        options: [{ label: "The building" }, { label: "Contents and belongings" }],
      },

      // Car
      { ref: "car_details", type: "short_text", title: "What is the make, model and year of the car?", required: true, maxLength: 120 },
      { ref: "car_driver_dob", type: "date", title: "What is the main driver's date of birth?", required: true },
      {
        ref: "car_licence_years",
        type: "number",
        title: "How many years has the main driver held a full licence?",
        required: true,
        integerOnly: true,
        min: 0,
        max: 80,
      },
      {
        ref: "car_claims",
        type: "number",
        title: "How many claims have you made in the last five years?",
        required: true,
        integerOnly: true,
        min: 0,
        max: 20,
      },

      // Life
      { ref: "life_dob", type: "date", title: "What is your date of birth?", required: true },
      { ref: "life_smoker", type: "yes_no", title: "Have you smoked or used nicotine in the last 12 months?", required: true },

      // Health
      {
        ref: "health_who",
        type: "single_select",
        title: "Who needs to be covered?",
        required: true,
        options: [{ label: "Just me" }, { label: "Me and a partner" }, { label: "My family, with children" }, { label: "Employees of my business" }],
      },

      // Business
      { ref: "biz_activity", type: "short_text", title: "What does the business do?", required: true, maxLength: 200 },
      {
        ref: "biz_staff",
        type: "number",
        title: "How many people does it employ?",
        required: true,
        integerOnly: true,
        min: 0,
      },

      // Travel
      {
        ref: "trip_type",
        type: "single_select",
        title: "What kind of travel cover?",
        required: true,
        options: [{ label: "A single trip" }, { label: "Annual cover for several trips" }],
      },
      { ref: "destinations", type: "short_text", title: "Where are you going?", required: true, maxLength: 200 },

      // Everyone
      {
        ref: "currently_insured",
        type: "yes_no",
        title: "Do you have this kind of cover already?",
        description: "If so, we can aim for a start date that matches your renewal.",
        required: true,
      },
      { ref: "start_date", type: "date", title: "When would you like the new cover to start?", required: true, disablePast: true },
      {
        ref: "priorities",
        type: "ranking",
        title: "Put these in order of what matters most to you.",
        required: true,
        items: ["Lowest price", "Most complete cover", "Low excess or deductible", "Easy claims", "Monthly payments"],
      },
      {
        ref: "location",
        type: "address",
        title: "Where do you live?",
        required: true,
        fields: ["postal", "country"],
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should the adviser contact?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "contact_pref",
        type: "single_select",
        title: "How would you like to receive your quote?",
        required: true,
        options: [{ label: "A phone call" }, { label: "By email" }, { label: "Either is fine" }],
      },
      {
        ref: "privacy",
        type: "legal_consent",
        title: "Using your details",
        required: true,
        consentText:
          "I agree that my answers can be used to prepare an insurance quote and to contact me about it. I understand this is a request for a quote, not an application, and no cover is in place until confirmed in writing.",
      },
    ],
    branches: [
      { when: "cover_type", is: "Home", then: "home_status" },
      { when: "cover_type", is: "Car", then: "car_details" },
      { when: "cover_type", is: "Life", then: "life_dob" },
      { when: "cover_type", is: "Health", then: "health_who" },
      { when: "cover_type", is: "Business", then: "biz_activity" },
      { when: "cover_type", is: "Travel", then: "trip_type" },
      { when: "home_cover", always: true, then: "currently_insured" },
      { when: "car_claims", always: true, then: "currently_insured" },
      { when: "life_smoker", always: true, then: "currently_insured" },
      { when: "health_who", always: true, then: "currently_insured" },
      { when: "biz_staff", always: true, then: "currently_insured" },
    ],
    ending: {
      title: "Request received 🛡️",
      body: "Thank you. An adviser will look over your answers and get back to you with a quote, or a few questions if they need more detail.",
    },
    guide: {
      questionsToConsider: [
        "Which lines of cover do you actually sell? Remove the options and their questions for the ones you don't.",
        "What does your underwriting need before a first conversation, and what can wait until the adviser calls?",
        "Does your regulator require specific wording about data use or about a quote not being cover?",
        "Would you rather collect contact details first, so you can follow up on people who stop partway?",
      ],
      howToUseResponses:
        "Route each request to the adviser for that cover type, and start with the priority the person ranked first: someone who put price on top wants a different conversation from someone who put claims service there. Use the current-cover answer and start date to time your follow-up before their renewal. Export requests to CSV to see which lines bring in the most enquiries.",
      customizeSteps: [
        "Delete the cover types you don't offer, along with the questions under each one, and add any detail your underwriters always ask for.",
        "Have your compliance team review the consent wording and the ending before you publish.",
        "Embed the form on each product page, or share one link and let the first question sort people.",
      ],
      faqs: [
        {
          q: "What information is needed for an insurance quote?",
          a: "It depends on the cover. A car quote needs the vehicle, the driver's age, experience and claims history, life cover needs age and smoking status, and home cover needs to know whether you own or rent. This form asks only what fits the cover chosen.",
        },
        {
          q: "Does submitting an insurance quote form put cover in place?",
          a: "No. It is a request for a quote. Cover starts only after the provider confirms it through their own process, and the consent line in this form says so.",
        },
        {
          q: "Can one form handle several types of insurance?",
          a: "Yes. This template branches on the first answer, so each person sees only the questions for their type of cover.",
        },
        {
          q: "Should I ask for date of birth on a quote form?",
          a: "Only where it changes the price, such as life and car cover. This form asks it on those two paths and leaves it out of the others, which keeps them shorter.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "sales-call-log-form",
    type: "form",
    category: "business",
    goals: [],
    roles: ["sales"],
    searchName: "Sales call log",
    title: "Sales call log",
    icon: "Phone",
    metaDescription:
      "Log every sales call while it's fresh: who you spoke to, what came up, objections, next step and date. No-answer and lost calls get their own short path.",
    description: "A quick log reps fill in after each call, with a next step every time.",
    blurb:
      "Reps fill it in straight after a call, so it has to be quick. The outcome decides the path: a missed call just needs a retry date, a lost deal records why, and a live opportunity captures the summary, objections, lead warmth and an agreed next step with a date.",
    tags: ["sales call log", "call log form", "sales activity log", "call report", "branching"],
    greeting: "Just off a call? Log it now while it's fresh. Two minutes, tops.",
    questions: [
      { ref: "rep", type: "short_text", title: "Who made the call?", required: true, maxLength: 80 },
      {
        ref: "call_date",
        type: "date",
        title: "When was the call?",
        required: true,
        includeTime: true,
        timeStepMinutes: 15,
      },
      {
        ref: "prospect",
        type: "contact_info",
        title: "Who did you call?",
        required: true,
        fields: ["first_name", "last_name", "phone"],
      },
      { ref: "company", type: "short_text", title: "Which company are they with?", required: true, maxLength: 150 },
      {
        ref: "call_type",
        type: "single_select",
        title: "What kind of call was it?",
        required: true,
        options: [
          { label: "First outreach" },
          { label: "Discovery" },
          { label: "Demo" },
          { label: "Follow-up" },
          { label: "Negotiation" },
          { label: "Existing customer check-in" },
        ],
      },
      {
        ref: "outcome",
        type: "single_select",
        title: "How did it go?",
        required: true,
        options: [
          { label: "Moving forward" },
          { label: "Interested, needs more time" },
          { label: "Not interested" },
          { label: "No answer or voicemail" },
        ],
      },

      // No answer
      { ref: "retry_date", type: "date", title: "When will you try again?", required: true, disablePast: true },

      // Lost
      {
        ref: "lost_reason",
        type: "single_select",
        title: "What was the main reason?",
        required: true,
        allowOther: true,
        options: [
          { label: "Price" },
          { label: "Went with a competitor" },
          { label: "Bad timing" },
          { label: "No real need" },
          { label: "Missing a feature they need" },
        ],
      },
      { ref: "lost_notes", type: "long_text", title: "Anything worth remembering if they come back later?", required: false, maxLength: 800 },

      // Live conversation
      {
        ref: "summary",
        type: "long_text",
        title: "What did you talk about?",
        description: "Their situation, what they need, and anything that surprised you.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "warmth",
        type: "opinion_scale",
        title: "How warm is this lead now?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Cold",
        labelHigh: "Ready to buy",
      },
      {
        ref: "decision_maker",
        type: "yes_no",
        title: "Did you speak to the person who makes the buying decision?",
        required: true,
      },
      {
        ref: "objections",
        type: "multi_select",
        title: "Which objections came up?",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        allowOther: true,
        options: [
          { label: "Price or budget" },
          { label: "Timing" },
          { label: "Needs sign-off from someone else" },
          { label: "Happy with current supplier" },
          { label: "Missing feature" },
        ],
      },
      {
        ref: "next_step",
        type: "single_select",
        title: "What is the agreed next step?",
        required: true,
        options: [
          { label: "Another call" },
          { label: "Demo" },
          { label: "Send a proposal" },
          { label: "Start a trial" },
          { label: "Close the deal" },
        ],
      },
      { ref: "next_date", type: "date", title: "When is the next step due?", required: true, disablePast: true },
      {
        ref: "deal_value",
        type: "number",
        title: "What is the rough deal value, if you know it?",
        required: false,
        min: 0,
      },
    ],
    branches: [
      { when: "outcome", is: "No answer or voicemail", then: "retry_date" },
      { when: "outcome", is: "Not interested", then: "lost_reason" },
      { when: "outcome", is: "Moving forward", then: "summary" },
      { when: "outcome", is: "Interested, needs more time", then: "summary" },
      { when: "retry_date", always: true, then: "end_no_answer" },
      { when: "lost_notes", always: true, then: "end_lost" },
    ],
    endings: [
      {
        ref: "end_no_answer",
        title: "Logged as no answer",
        body: "Your retry date is saved. A short voicemail and a follow-up email usually help the next attempt land.",
      },
      {
        ref: "end_lost",
        title: "Logged as lost",
        body: "Thanks for recording why. Those reasons are how the team spots patterns in lost deals.",
      },
    ],
    ending: {
      title: "Call logged 📞",
      body: "Saved with the next step and its date. Good luck with the follow-up.",
    },
    guide: {
      questionsToConsider: [
        "Should reps pick their name from a dropdown instead of typing it, so the log stays tidy?",
        "Which call types and next steps match your sales process stages?",
        "What lost reasons does your team actually hear, and would a new one reveal something worth tracking?",
        "Does your team need the deal value on every call, or only once a proposal is sent?",
      ],
      howToUseResponses:
        "Review the log weekly in the dashboard, filtered by rep and outcome. Check that every live opportunity has a next step with a date, and chase any that slip past it. Count the lost reasons and the objections each month: if price keeps coming up, that is a pricing or positioning conversation, not a rep problem. Export to CSV when you need to merge the log with your pipeline.",
      customizeSteps: [
        "Swap the call types, lost reasons and next steps for the stages and language your team already uses.",
        "Turn the rep question into a dropdown of your team's names so every entry is spelled the same way.",
        "Pin the link somewhere reps see it after every call, such as the team chat or a phone home screen.",
      ],
      faqs: [
        {
          q: "What should a sales call log include?",
          a: "Who was called and when, the type of call, the outcome, a short summary, objections, and the agreed next step with a date. Lost deals should record the reason.",
        },
        {
          q: "Why log sales calls in a form instead of a spreadsheet?",
          a: "A form asks the same questions every time and only the ones that fit the outcome, so entries stay consistent and reps actually finish them.",
        },
        {
          q: "Can I use this on my phone after a call?",
          a: "Yes. It runs as a chat, one question at a time, so it's easy to fill in on a phone. Most calls take a couple of minutes to log.",
        },
      ],
    },
  }),
];
