import { defineTemplate, type TemplateSeed } from "../define.js";

export const FORM_BUSINESS_2: TemplateSeed[] = [
  defineTemplate({
    slug: "customer-information-form",
    type: "form",
    category: "business",
    goals: ["onboard-clients"],
    roles: ["customer-success", "operations", "sales"],
    searchName: "Customer information form",
    title: "Customer information",
    icon: "UserCheck",
    metaDescription:
      "Collect a new customer's contact details, address, billing contact and how they like to be reached, with extra questions only for business customers.",
    description: "A tidy record for every new customer, whether they buy for themselves or for a business.",
    blurb:
      "Made for businesses whose customers are mostly people buying for themselves, with the odd company in the mix. It gives your team the record it needs before the first invoice or delivery. Individuals skip straight past the company questions, while business customers are asked for the company name, a tax number and who should receive invoices. It closes by asking how and when they want to hear from you, and records a clear yes or no to marketing.",
    tags: ["customer information", "customer details form", "new customer form", "client record", "branching"],
    greeting: "Thanks for choosing us. A few details and your account is ready.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "First, who are you?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "customer_type",
        type: "single_select",
        title: "Are you signing up for yourself or for a business?",
        required: true,
        options: [{ label: "For myself" }, { label: "For a business" }],
      },

      // Business customers
      { ref: "company_name", type: "short_text", title: "What's the business called?", required: true, maxLength: 160 },
      {
        ref: "job_title",
        type: "short_text",
        title: "And your role there?",
        required: false,
        maxLength: 120,
      },
      {
        ref: "tax_id",
        type: "short_text",
        title: "Do you have a tax or VAT number to put on invoices?",
        required: false,
        maxLength: 40,
      },
      {
        ref: "billing_email",
        type: "email",
        title: "Where should invoices go?",
        description: "Often an accounts address rather than your own.",
        required: true,
      },

      // Everyone
      {
        ref: "address",
        type: "address",
        title: "What address should we have on file?",
        required: true,
        fields: ["street", "city", "state", "postal", "country"],
      },
      {
        ref: "contact_method",
        type: "single_select",
        title: "How do you prefer we get in touch?",
        required: true,
        options: [{ label: "Email" }, { label: "Phone call" }, { label: "Text message" }],
      },
      {
        ref: "contact_time",
        type: "multi_select",
        title: "When are you usually easiest to reach?",
        required: false,
        minSelections: 0,
        maxSelections: 3,
        options: [{ label: "Mornings" }, { label: "Afternoons" }, { label: "Evenings" }],
      },
      {
        ref: "heard_from",
        type: "dropdown",
        title: "How did you first hear about us?",
        required: false,
        options: [
          { label: "A friend or colleague" },
          { label: "Search engine" },
          { label: "Social media" },
          { label: "An event" },
          { label: "Advertising" },
          { label: "Something else" },
        ],
      },
      {
        ref: "marketing_consent",
        type: "legal_consent",
        title: "Updates and offers",
        required: true,
        allowDecline: true,
        consentText:
          "I'm happy to receive occasional news and offers by email. I can unsubscribe at any time. Account and service messages are sent either way.",
        agreeLabel: "Yes, send me updates",
        declineLabel: "No thanks",
      },
      {
        ref: "notes",
        type: "long_text",
        title: "Anything we should note on your account?",
        description: "Access instructions, accessibility needs, a second contact.",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "customer_type", is: "For myself", then: "address" },
      { when: "customer_type", is: "For a business", then: "company_name" },
    ],
    ending: {
      title: "You're all set ✅",
      body: "Your details are saved. If anything changes, just reply to any email from us.",
    },
    guide: {
      questionsToConsider: [
        "Which fields does your invoicing or delivery process actually need, and which are nice to have?",
        "Do you need a tax or VAT number from business customers before you can bill them?",
        "Is a postal address necessary, or only a city and country?",
        "Who on your team owns the customer record once it arrives, and who updates it later?",
      ],
      howToUseResponses:
        "Treat each response as the first version of the customer's record. Copy it into whatever system you bill or deliver from, or export the responses to CSV and import them in a batch. Check the marketing answer before adding anyone to a mailing list, and honour the preferred contact method and time from the first call onwards. The notes field is where access details and special requests hide, so make sure it reaches whoever serves the customer.",
      customizeSteps: [
        "Remove the address fields you never use, or drop the state line if you only serve one country.",
        "Rewrite the consent wording so it names what you actually send and how often.",
        "Send the link as part of your welcome email, or embed it on the page customers land on after they buy.",
      ],
      faqs: [
        {
          q: "What should a customer information form include?",
          a: "Name, email and phone, an address if you deliver or invoice, and how the customer prefers to be contacted. Business customers also need a company name and a billing contact.",
        },
        {
          q: "Do I need consent to email customers?",
          a: "For marketing, in many countries yes. This form asks separately and records a clear yes or no, while service messages about their account go out regardless.",
        },
        {
          q: "Why ask whether the customer is a business?",
          a: "Businesses need extra details such as a tax number and an invoice address. Asking first means individuals never see those questions.",
        },
        {
          q: "Can I export customer information to a spreadsheet?",
          a: "Yes. Every answer appears in your dashboard and can be exported to CSV, with one column per field.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "booking-request-form",
    type: "form",
    category: "business",
    goals: ["onboard-clients", "generate-leads"],
    roles: ["operations", "sales"],
    searchName: "Booking request form",
    title: "Booking request",
    icon: "CalendarCheck",
    metaDescription:
      "Take booking requests for a venue, studio or service with the date, time, group size and extras, plus backup dates so you can confirm without the back-and-forth.",
    description: "Gather everything you need to check availability before you confirm a booking.",
    blurb:
      "Built for places that confirm by hand: a venue, studio, rental or service with limited slots. It collects the preferred date and time, how long, how many people and what extras they need. Anyone who says their date is flexible is asked for a second choice straight away, which saves a round of emails when the first date is taken.",
    tags: ["booking request", "venue booking", "reservation request", "availability", "branching"],
    greeting: "Hi! Tell us what you'd like to book and we'll check availability.",
    questions: [
      {
        ref: "booking_for",
        type: "single_select",
        title: "What's the booking for?",
        required: true,
        allowOther: true,
        options: [
          { label: "A private event" },
          { label: "A meeting or workshop" },
          { label: "A class or rehearsal" },
          { label: "A photo or video shoot" },
        ],
      },
      {
        ref: "preferred_date",
        type: "date",
        title: "Which date and start time would you like?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 30,
        timeMin: "08:00",
        timeMax: "21:00",
      },
      {
        ref: "duration",
        type: "single_select",
        title: "How long do you need it for?",
        required: true,
        options: [
          { label: "Up to 2 hours" },
          { label: "Half a day" },
          { label: "A full day" },
          { label: "More than one day" },
        ],
      },
      {
        ref: "date_flexible",
        type: "yes_no",
        title: "If that date is taken, could you do another?",
        required: true,
        yesLabel: "Yes, I'm flexible",
        noLabel: "No, it has to be that date",
      },
      {
        ref: "backup_date",
        type: "date",
        title: "What would your second choice be?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 30,
        timeMin: "08:00",
        timeMax: "21:00",
      },
      {
        ref: "group_size",
        type: "number",
        title: "How many people, including you?",
        required: true,
        integerOnly: true,
        min: 1,
      },
      {
        ref: "extras",
        type: "multi_select",
        title: "Would you like any of these added?",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        options: [
          { label: "Food or drinks" },
          { label: "Screen, sound or projector" },
          { label: "Tables and chairs set up for you" },
          { label: "Extra time to set up or pack down" },
          { label: "Parking" },
          { label: "None of these" },
        ],
      },
      {
        ref: "details",
        type: "long_text",
        title: "Tell us a little about what you have planned",
        description: "Layout, accessibility needs, anything unusual.",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we send the confirmation to?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
    ],
    branches: [
      { when: "date_flexible", is: true, then: "backup_date" },
      { when: "date_flexible", is: false, then: "group_size" },
    ],
    ending: {
      title: "Request received 📅",
      body: "This isn't confirmed yet. We'll check availability and get back to you with a yes, or with the nearest dates we have.",
    },
    guide: {
      questionsToConsider: [
        "What are the minimum and maximum booking lengths you actually accept?",
        "Which extras cost more, and should the form say so before people tick them?",
        "Is there a group size above which you need to talk to the person before accepting?",
        "How quickly can you promise a reply, so the ending can say it?",
      ],
      howToUseResponses:
        "Sort the requests by preferred date and check each against your calendar. When the first choice is taken and the person gave a backup, offer that before anything else, since they already said it works. Reply to anyone who said their date is fixed first, because they are the ones most likely to book somewhere else. Keep the extras column visible when you confirm so the setup matches what was asked for.",
      customizeSteps: [
        "Change the booking reasons and the time window on the two date questions to match your opening hours.",
        "Replace the extras with the add-ons you really offer.",
        "Put the link on your booking or contact page, or embed it next to your calendar.",
      ],
      faqs: [
        {
          q: "What's the difference between a booking request and a booking?",
          a: "A request asks for a date and waits for you to confirm it. It suits businesses that need to check availability, staff or setup before saying yes.",
        },
        {
          q: "What should a booking request form ask?",
          a: "The date and time, how long, how many people, any extras and a way to reach the person. A second-choice date saves the most time of all.",
        },
        {
          q: "Can the form ask for a backup date only when it's useful?",
          a: "Yes. This template asks whether the date is flexible and only then asks for a second choice.",
        },
        {
          q: "Can I put a booking request form on my website?",
          a: "Yes. Share it as a link or embed it on any page, and requests arrive in your dashboard as they come in.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "catering-inquiry-form",
    type: "form",
    category: "business",
    goals: ["generate-leads"],
    roles: ["sales", "operations"],
    searchName: "Catering inquiry form",
    title: "Catering inquiry",
    icon: "ChefHat",
    metaDescription:
      "Ask about the occasion, date, guest count, venue, service style, dietary needs and budget, so every catering quote you send fits the event from the start.",
    description: "Everything a caterer needs to write a proposal, gathered in one conversation.",
    blurb:
      "Written the way a caterer runs a first planning call, with the logistics a quote depends on. It asks about the event, the guests, the venue and whether food is served indoors or out, then the service style decides what comes next: a drop-off order skips the staffing questions, while a staffed event is asked about the venue kitchen and what equipment you need to bring. Dietary needs and a ranked list of priorities help you pitch the right menu.",
    tags: ["catering inquiry", "catering request form", "event catering", "catering quote", "branching"],
    greeting: "Hello! Walk us through your event and we'll build a menu and quote around it.",
    questions: [
      {
        ref: "occasion",
        type: "single_select",
        title: "What's the occasion?",
        required: true,
        allowOther: true,
        options: [
          { label: "Wedding" },
          { label: "Corporate event" },
          { label: "Birthday or private party" },
          { label: "Memorial or wake" },
          { label: "Conference or meeting" },
        ],
      },
      {
        ref: "event_date",
        type: "date",
        title: "When is it, and roughly what time should food be served?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 30,
        timeMin: "07:00",
        timeMax: "22:00",
      },
      {
        ref: "guests",
        type: "number",
        title: "How many guests are you expecting?",
        required: true,
        integerOnly: true,
        min: 1,
      },
      {
        ref: "venue",
        type: "address",
        title: "Where is the event?",
        required: true,
        fields: ["street", "city", "postal"],
      },
      {
        ref: "venue_setting",
        type: "single_select",
        title: "Will food be served indoors, outdoors or both?",
        required: true,
        options: [{ label: "Indoors" }, { label: "Outdoors" }, { label: "A mix of both" }, { label: "Not decided yet" }],
      },
      {
        ref: "service_style",
        type: "single_select",
        title: "What kind of service are you picturing?",
        required: true,
        options: [
          { label: "Drop-off", description: "We deliver, you serve" },
          { label: "Buffet with staff" },
          { label: "Plated sit-down meal" },
          { label: "Canapés and drinks reception" },
          { label: "Not sure yet" },
        ],
      },

      // Staffed events
      {
        ref: "venue_kitchen",
        type: "single_select",
        title: "Is there a kitchen at the venue we can use?",
        required: true,
        options: [{ label: "Yes, a full kitchen" }, { label: "Just a small prep area" }, { label: "No kitchen" }, { label: "I don't know" }],
      },
      {
        ref: "equipment",
        type: "multi_select",
        title: "Should we bring or provide any of these?",
        required: false,
        minSelections: 0,
        maxSelections: 5,
        options: [
          { label: "Plates, cutlery and glasses" },
          { label: "Tables and linen" },
          { label: "Bar service" },
          { label: "Clearing up afterwards" },
          { label: "The venue provides all of it" },
        ],
      },

      // Everyone
      {
        ref: "menu_style",
        type: "multi_select",
        title: "What sort of food would suit the event?",
        required: false,
        minSelections: 0,
        maxSelections: 4,
        allowOther: true,
        options: [
          { label: "Light bites and finger food" },
          { label: "Classic comfort food" },
          { label: "Mediterranean" },
          { label: "Asian" },
          { label: "Barbecue" },
          { label: "Desserts and cake" },
        ],
      },
      {
        ref: "dietary",
        type: "multi_select",
        title: "Which dietary needs should the menu cover?",
        required: false,
        minSelections: 0,
        maxSelections: 8,
        options: [
          { label: "Vegetarian" },
          { label: "Vegan" },
          { label: "Gluten-free" },
          { label: "Dairy-free" },
          { label: "Nut allergy" },
          { label: "Halal" },
          { label: "Kosher" },
          { label: "None that I know of" },
        ],
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "Put these in order of what matters most to you",
        required: false,
        items: ["The food itself", "Staying on budget", "How it looks on the table", "Everything arriving and running on time"],
      },
      {
        ref: "budget",
        type: "number",
        title: "Roughly what's your budget per guest?",
        description: "A ballpark is fine. It helps us suggest a realistic menu.",
        required: false,
        min: 0,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Where should we send the proposal?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "notes",
        type: "long_text",
        title: "Anything else we should know?",
        description: "A theme, a dish you loved at another event, timings for speeches.",
        required: false,
        maxLength: 1000,
      },
    ],
    branches: [
      { when: "service_style", is: "Drop-off", then: "menu_style" },
      { when: "service_style", is: "Buffet with staff", then: "venue_kitchen" },
      { when: "service_style", is: "Plated sit-down meal", then: "venue_kitchen" },
      { when: "service_style", is: "Canapés and drinks reception", then: "venue_kitchen" },
      { when: "service_style", is: "Not sure yet", then: "venue_kitchen" },
    ],
    ending: {
      title: "Thanks, this is plenty to start 🍽️",
      body: "We'll check the date and come back with menu ideas and a quote.",
    },
    guide: {
      questionsToConsider: [
        "What's the smallest and largest guest count you'll cater, and should the form say so?",
        "Which service styles do you actually offer?",
        "Do you need the venue address to price travel, and does an outdoor event change your equipment list?",
        "Would a tasting session be part of your process for bigger events?",
      ],
      howToUseResponses:
        "Check the date and guest count first, since those decide whether you can take the job at all. Use the service style, kitchen answer and equipment list to work out staffing and what goes in the van. The ranking tells you how to pitch the proposal: someone who put budget first wants two clear price options, someone who put presentation first wants photos. Reply quickly, because people planning events often ask several caterers at once.",
      customizeSteps: [
        "Swap the food styles for the cuisines and menus you're known for.",
        "Set the serving time window on the date question to the hours you work.",
        "Link to the form from your menu page, or embed it on your website's catering page.",
      ],
      faqs: [
        {
          q: "What should a catering inquiry form include?",
          a: "The occasion, date and time, guest count, venue, service style, dietary needs and a budget. With those you can write a proposal without a long phone call first.",
        },
        {
          q: "Why ask for budget per guest rather than a total?",
          a: "Per guest is how most caterers price, and it's easier for a client to estimate. You can still multiply it by the guest count.",
        },
        {
          q: "How do I handle allergies on a catering form?",
          a: "Ask which needs apply, then confirm the exact numbers and severity when you follow up. The notes field is there for anything serious.",
        },
        {
          q: "Can I skip questions that don't apply?",
          a: "Yes. This template already skips the kitchen and equipment questions for drop-off orders, and you can edit or add branches to suit your service.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "interactive-appointment-form",
    type: "form",
    category: "business",
    goals: ["onboard-clients"],
    roles: ["operations", "freelancers-agencies", "customer-success"],
    searchName: "Appointment request form",
    title: "Appointment request",
    icon: "CalendarDays",
    metaDescription:
      "Let clients pick a service, share their availability across the week, choose in person or online and tell you what they need, before you confirm a time.",
    description: "Collect the service, the times that work and the context, in a friendly back-and-forth.",
    blurb:
      "Instead of a single date box, clients tick the mornings, afternoons and evenings that suit them across the week, so you can offer a slot that works the first time. Anyone unsure which service they need describes the problem instead, and first-time clients are asked how they found you while returning clients skip it.",
    tags: ["appointment request", "appointment form", "availability", "client booking", "branching"],
    greeting: "Hi there! Let's find a time that works for you.",
    questions: [
      {
        ref: "service",
        type: "dropdown",
        title: "Which service would you like to book?",
        required: true,
        options: [
          { label: "Initial consultation" },
          { label: "Standard session" },
          { label: "Extended session" },
          { label: "Quick check-in" },
          { label: "I'm not sure yet" },
        ],
      },
      {
        ref: "not_sure_detail",
        type: "long_text",
        title: "No problem. What would you like help with?",
        description: "We'll suggest the right service when we reply.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "returning",
        type: "yes_no",
        title: "Have you had an appointment with us before?",
        required: true,
      },
      {
        ref: "heard_from",
        type: "dropdown",
        title: "Welcome! How did you find us?",
        required: false,
        options: [
          { label: "Recommended by someone" },
          { label: "Search engine" },
          { label: "Social media" },
          { label: "Walked past" },
          { label: "Something else" },
        ],
      },
      {
        ref: "format",
        type: "single_select",
        title: "How would you like to meet?",
        required: true,
        options: [{ label: "In person" }, { label: "Video call" }, { label: "Phone call" }],
      },
      {
        ref: "earliest",
        type: "date",
        title: "What's the earliest date you could come?",
        required: true,
        disablePast: true,
      },
      {
        ref: "availability",
        type: "matrix",
        title: "Which times usually work for you?",
        description: "Tick as many as you like.",
        required: true,
        multiplePerRow: true,
        rows: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        columns: ["Morning", "Afternoon", "Evening"],
      },
      {
        ref: "context",
        type: "long_text",
        title: "Is there anything that would help us prepare?",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "attachments",
        type: "file_upload",
        title: "Any photos or documents to share beforehand?",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 3,
        maxSizeMB: 10,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "How can we reach you to confirm?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "reminder",
        type: "single_select",
        title: "How would you like your reminder?",
        required: false,
        options: [{ label: "Email" }, { label: "Text message" }, { label: "No reminder, thanks" }],
      },
    ],
    branches: [
      { when: "service", is: "I'm not sure yet", then: "not_sure_detail" },
      { when: "service", is: "Initial consultation", then: "returning" },
      { when: "service", is: "Standard session", then: "returning" },
      { when: "service", is: "Extended session", then: "returning" },
      { when: "service", is: "Quick check-in", then: "returning" },
      { when: "returning", is: true, then: "format" },
      { when: "returning", is: false, then: "heard_from" },
    ],
    ending: {
      title: "Thanks! We'll be in touch 👋",
      body: "We'll look at your availability and send you a time to confirm.",
    },
    guide: {
      questionsToConsider: [
        "Which services do you offer, and how long does each one take?",
        "Do you meet online as well as in person, or only one of them?",
        "Which days and times are you really open, so the grid shows no slots you can't offer?",
        "Is there anything clients must bring or send ahead of the first appointment?",
      ],
      howToUseResponses:
        "Read the availability grid against your diary and reply with one specific time rather than a list, since the client has already told you what works. Anyone who chose the not-sure option needs a short reply recommending a service before you book them. Look at the uploads and context before the appointment, and use the reminder choice when you confirm. Over time, the how-did-you-find-us answers show which channels bring new clients.",
      customizeSteps: [
        "Replace the services in the first question with your own, and adjust the days in the grid to your opening days.",
        "Remove the meeting format question if you only work one way.",
        "Share the link from your website, social profiles or email signature.",
      ],
      faqs: [
        {
          q: "What should an appointment request form include?",
          a: "The service, when the person is available, how they want to meet, a way to contact them and any context you need to prepare.",
        },
        {
          q: "Why collect availability instead of one exact time?",
          a: "A grid of times that suit the client lets you pick a slot that fits your diary too, so you rarely have to go back and forth.",
        },
        {
          q: "Is this different from an online booking calendar?",
          a: "Yes. It collects a request that you confirm yourself, which suits businesses whose appointments vary in length or need preparation.",
        },
        {
          q: "Can clients attach files to an appointment request?",
          a: "Yes. This form accepts up to three images or PDFs, and they're stored with the response in your dashboard.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "tattoo-consultation-form",
    type: "form",
    category: "business",
    goals: ["onboard-clients", "generate-leads"],
    roles: ["freelancers-agencies"],
    searchName: "Tattoo consultation form",
    title: "Tattoo consultation",
    icon: "PenTool",
    metaDescription:
      "Gather a client's tattoo idea, style, placement, size, colour and reference images before the consultation, with an age check and cover-up questions built in.",
    description: "Arrive at every tattoo consultation already knowing the idea, the spot and the references.",
    blurb:
      "The questions an artist asks at the start of every consult, answered before it begins. Anyone under 18 is stopped kindly at the start, and cover-ups get their own step asking for a photo of the existing tattoo. Reference images, a flexibility scale and a note on skin or health round it off.",
    tags: ["tattoo consultation", "tattoo booking form", "tattoo inquiry", "tattoo studio", "branching"],
    greeting: "Hey! Tell us about the tattoo you have in mind.",
    questions: [
      {
        ref: "over_18",
        type: "yes_no",
        title: "Are you 18 or older?",
        required: true,
      },
      {
        ref: "first_tattoo",
        type: "yes_no",
        title: "Will this be your first tattoo?",
        required: true,
      },
      {
        ref: "idea",
        type: "long_text",
        title: "Describe the idea in your own words",
        description: "What it shows, what it means to you, anything it must include.",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "style",
        type: "single_select",
        title: "Which style is closest to what you want?",
        required: true,
        options: [
          { label: "Fine line" },
          { label: "Traditional" },
          { label: "Neo-traditional" },
          { label: "Realism" },
          { label: "Blackwork" },
          { label: "Lettering or script" },
          { label: "Not sure, I'd like advice" },
        ],
      },
      {
        ref: "placement",
        type: "dropdown",
        title: "Where on your body would it go?",
        required: true,
        options: [
          { label: "Forearm" },
          { label: "Upper arm or shoulder" },
          { label: "Hand or fingers" },
          { label: "Chest" },
          { label: "Back" },
          { label: "Ribs or side" },
          { label: "Thigh" },
          { label: "Calf or shin" },
          { label: "Ankle or foot" },
          { label: "Neck" },
          { label: "Somewhere else" },
        ],
      },
      {
        ref: "size",
        type: "single_select",
        title: "Roughly how big?",
        required: true,
        options: [
          { label: "Small", description: "About the size of a coin" },
          { label: "Medium", description: "About the size of a palm" },
          { label: "Large", description: "A forearm or calf" },
          { label: "Sleeve or full back piece" },
        ],
      },
      {
        ref: "colour",
        type: "single_select",
        title: "Colour or black and grey?",
        required: true,
        options: [{ label: "Black and grey" }, { label: "Full colour" }, { label: "A touch of colour" }, { label: "Happy to take advice" }],
      },
      {
        ref: "cover_up",
        type: "yes_no",
        title: "Would this cover or rework an existing tattoo?",
        required: true,
      },
      {
        ref: "cover_photo",
        type: "file_upload",
        title: "Please upload a clear photo of the tattoo you want covered",
        description: "Good light, taken straight on, so the artist can see what they're working with.",
        required: true,
        accept: ["image/*"],
        maxFiles: 3,
        maxSizeMB: 10,
      },
      {
        ref: "references",
        type: "file_upload",
        title: "Share any reference images",
        description: "Art you like, other tattoos, photos. Artists use these for inspiration, not to copy.",
        required: false,
        accept: ["image/*"],
        maxFiles: 5,
        maxSizeMB: 10,
      },
      {
        ref: "flexibility",
        type: "opinion_scale",
        title: "How much creative freedom would you give the artist?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Exactly my idea",
        labelHigh: "Artist's call",
      },
      {
        ref: "timing",
        type: "single_select",
        title: "When would you like to get started?",
        required: true,
        options: [{ label: "As soon as possible" }, { label: "In the next couple of months" }, { label: "Later this year" }, { label: "Just exploring" }],
      },
      {
        ref: "artist",
        type: "short_text",
        title: "Is there an artist here you'd like to work with?",
        description: "Leave it blank and we'll match you with whoever suits the style.",
        required: false,
        maxLength: 120,
      },
      {
        ref: "health",
        type: "long_text",
        title: "Anything the artist should know about your skin or health?",
        description: "Allergies, medication, skin conditions, or anything that makes sitting still hard.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "How can the artist get back to you?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
    ],
    branches: [
      { when: "over_18", is: false, then: "end_underage" },
      { when: "over_18", is: true, then: "first_tattoo" },
      { when: "cover_up", is: true, then: "cover_photo" },
      { when: "cover_up", is: false, then: "references" },
    ],
    endings: [
      {
        ref: "end_underage",
        title: "Thanks for thinking of us",
        body: "We only tattoo clients who are 18 or over, so we can't book you in just yet. We'd love to hear from you when you are.",
      },
    ],
    ending: {
      title: "Got it, thank you ✍️",
      body: "The artist will look over your idea and references and get back to you about a consultation.",
    },
    guide: {
      questionsToConsider: [
        "What's the minimum age in your area, and do you ask for ID at the appointment?",
        "Which styles do your artists actually work in, so the options match your portfolio?",
        "Do you take cover-ups, and does every artist do them?",
        "Do you take a deposit, and how will you explain it when you reply?",
      ],
      howToUseResponses:
        "Pass each response to the artist the client asked for, or to whoever's style matches, with the references and any cover-up photos attached. The size, placement and colour answers let them estimate sessions and time before the consult, and the flexibility score tells them how much to push their own design. Read the health notes before booking and follow up on anything that needs a doctor's go-ahead. Clients who are just exploring can wait; those who want to start soon should hear back first.",
      customizeSteps: [
        "Edit the styles to match your artists, and add or remove placements you don't tattoo.",
        "Change the age check if your local minimum differs, and rewrite the ending in your studio's voice.",
        "Put the link in your social profile and on your website's booking page.",
      ],
      faqs: [
        {
          q: "What should I bring to a tattoo consultation?",
          a: "Reference images, a clear idea of placement and size, and photos of any tattoo you want covered. This form collects all of that in advance.",
        },
        {
          q: "What does a tattoo consultation form ask?",
          a: "The design idea, style, placement, size, colour, reference images, timing and any health information the artist needs to know.",
        },
        {
          q: "How do I handle clients who are under 18?",
          a: "Ask first. This form ends politely for anyone under 18, so they never fill in the rest and you never have to turn them down later.",
        },
        {
          q: "Can clients upload reference images?",
          a: "Yes. They can attach up to five images, plus separate photos when it's a cover-up, and you'll see them with the response.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "partnership-inquiry",
    type: "form",
    category: "business",
    goals: ["generate-leads"],
    roles: ["sales", "marketing"],
    searchName: "Partnership inquiry form",
    title: "Partnership inquiry",
    icon: "Handshake",
    metaDescription:
      "Sort real partnership proposals from cold pitches. Each type of partner, from integrations to resellers, is asked the one question that shows it could work.",
    description: "Hear what a would-be partner offers and whether the timing is right, in one conversation.",
    blurb:
      "A partnerships inbox fills with pitches that were never going to fit. Each kind of partnership is asked the one thing that makes it credible: an integration for which way the API calls go, a reseller for the market it sells into, co-marketing for the size of its audience, an agency for its client base. Proposals looking to move in the next few weeks go to their own ending with a faster reply.",
    tags: ["partnership inquiry", "partner application", "business development", "reseller", "branching"],
    greeting: "Thinking of working together? Tell us what you have in mind.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Who are we talking to?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      { ref: "company_name", type: "short_text", title: "And which company?", required: true, maxLength: 160 },
      { ref: "website", type: "url", title: "Link to your website", required: false },
      {
        ref: "partnership_type",
        type: "single_select",
        title: "What kind of partnership?",
        required: true,
        options: [
          { label: "Technology integration" },
          { label: "Reseller or affiliate" },
          { label: "Co-marketing" },
          { label: "Agency or implementation partner" },
          { label: "Something else" },
        ],
      },

      // Integration
      {
        ref: "integration_direction",
        type: "single_select",
        title: "Which way round would it work?",
        required: true,
        options: [
          { label: "You'd call our API" },
          { label: "We'd call yours" },
          { label: "Both" },
          { label: "Not sure yet" },
        ],
      },
      {
        ref: "integration_users",
        type: "number",
        title: "How many of your customers would use it?",
        required: false,
        integerOnly: true,
        min: 0,
      },

      // Reseller
      {
        ref: "reseller_market",
        type: "short_text",
        title: "Which market and region do you sell into?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "reseller_experience",
        type: "yes_no",
        title: "Do you already resell anything similar?",
        required: false,
      },

      // Co-marketing
      {
        ref: "audience_size",
        type: "number",
        title: "Roughly how large is your audience?",
        description: "Newsletter subscribers, followers or monthly visitors, whichever is biggest.",
        required: true,
        integerOnly: true,
        min: 0,
      },
      {
        ref: "comarketing_format",
        type: "multi_select",
        title: "What did you have in mind?",
        required: false,
        minSelections: 0,
        maxSelections: 5,
        options: [
          { label: "A joint webinar" },
          { label: "A guest post or newsletter swap" },
          { label: "A case study together" },
          { label: "An event or sponsorship" },
          { label: "Something else" },
        ],
      },

      // Agency
      {
        ref: "agency_clients",
        type: "single_select",
        title: "How many clients do you look after?",
        required: true,
        options: [{ label: "1–5" }, { label: "6–20" }, { label: "21–50" }, { label: "More than 50" }],
      },
      {
        ref: "agency_services",
        type: "short_text",
        title: "What do you do for them?",
        required: false,
        maxLength: 200,
      },

      // Something else
      {
        ref: "other_idea",
        type: "long_text",
        title: "Tell us what you have in mind",
        required: true,
        maxLength: 1200,
      },

      // Everyone
      {
        ref: "outcome",
        type: "long_text",
        title: "What would a good outcome look like for you?",
        required: true,
        maxLength: 1200,
      },
      {
        ref: "fit",
        type: "opinion_scale",
        title: "How much do our customers and yours overlap?",
        required: false,
        steps: 5,
        startAt: 1,
        labelLow: "Barely",
        labelHigh: "Almost entirely",
      },
      {
        ref: "timeline",
        type: "single_select",
        title: "What sort of timeline are you thinking?",
        required: true,
        options: [{ label: "Next few weeks" }, { label: "This quarter" }, { label: "This year" }, { label: "Exploring for now" }],
      },
    ],
    branches: [
      { when: "partnership_type", is: "Technology integration", then: "integration_direction" },
      { when: "partnership_type", is: "Reseller or affiliate", then: "reseller_market" },
      { when: "partnership_type", is: "Co-marketing", then: "audience_size" },
      { when: "partnership_type", is: "Agency or implementation partner", then: "agency_clients" },
      { when: "partnership_type", is: "Something else", then: "other_idea" },
      { when: "integration_users", always: true, then: "outcome" },
      { when: "reseller_experience", always: true, then: "outcome" },
      { when: "comarketing_format", always: true, then: "outcome" },
      { when: "agency_services", always: true, then: "outcome" },
      { when: "timeline", is: "Next few weeks", then: "end_soon" },
    ],
    endings: [
      {
        ref: "end_soon",
        title: "Thanks. We'll move quickly on this 🤝",
        body: "Since you're hoping to start soon, someone from our partnerships team will reply within a few working days.",
      },
    ],
    ending: {
      title: "Thanks. We'll read it properly",
      body: "If there's a fit, you'll hear from us within a couple of weeks.",
    },
    guide: {
      questionsToConsider: [
        "Which kinds of partnership do you actually want right now, and which should you remove?",
        "What's the one fact that makes each kind of partner worth a call?",
        "Who reads these proposals, and how quickly can they reply to the urgent ones?",
        "Is there a minimum size or market you won't consider, and should the form say so?",
      ],
      howToUseResponses:
        "Group proposals by partnership type, since each one goes to a different person or needs a different yardstick. Answer the fast-timeline proposals first. For the rest, the qualifying answer does most of the sorting: an integration nobody's customers would use, or a co-marketing pitch with a tiny audience, can get a polite no. Keep the declined ones in the export, because a partner who wasn't ready this year may be next year.",
      customizeSteps: [
        "Remove the partnership types you don't offer, along with their follow-up questions.",
        "Change the reply times in both endings to what your team can really keep to.",
        "Link to the form from your partners page or footer instead of publishing a partnerships email address.",
      ],
      faqs: [
        {
          q: "What should a partnership inquiry form ask?",
          a: "Who the company is, what kind of partnership they want, the one detail that shows it could work, what success looks like and their timeline.",
        },
        {
          q: "How do I filter out low-quality partnership pitches?",
          a: "Ask each type of partner a qualifying question, such as audience size for co-marketing or target market for resellers. Weak pitches usually can't answer it.",
        },
        {
          q: "Why do different partners see different questions?",
          a: "An integration partner and a reseller need different things from you. Branching asks each only what matters for their kind of deal.",
        },
        {
          q: "Where should I put a partnership form?",
          a: "On a partners or work-with-us page, linked from your footer. You can embed it directly or share it as a link.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "appointment-booking",
    type: "form",
    category: "business",
    goals: ["onboard-clients"],
    roles: ["operations", "customer-success"],
    searchName: "Appointment booking form",
    title: "Appointment booking",
    icon: "CalendarClock",
    metaDescription:
      "Take appointment bookings with a date and time, and ask each reason the right questions. First visits give background, urgent requests get a call back.",
    description: "Take a booking with the right slot length for the reason.",
    blurb:
      "A date question with time turned on, so the answer is an appointment rather than a day. First visits are asked what they want to discuss, follow-ups what has changed, and a routine check is a few taps. Anyone who needs to be seen today skips the calendar and lands on an ending that promises a call back.",
    tags: ["appointment booking", "booking form", "clinic appointments", "scheduling", "branching"],
    greeting: "Let's find you a time.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Your name and the best number to reach you",
        required: true,
        fields: ["first_name", "last_name", "phone", "email"],
      },
      {
        ref: "reason",
        type: "single_select",
        title: "What's the appointment for?",
        required: true,
        options: [
          { label: "First consultation" },
          { label: "Follow-up" },
          { label: "Routine check" },
          { label: "Something urgent" },
        ],
      },

      // First consultation
      {
        ref: "first_concern",
        type: "long_text",
        title: "What would you like to talk about?",
        description: "A sentence or two. It decides how long we book you in for.",
        required: true,
        maxLength: 1000,
      },
      { ref: "referred_by", type: "short_text", title: "Were you referred by anyone?", required: false, maxLength: 160 },
      {
        ref: "date_of_birth",
        type: "date",
        title: "Date of birth, for your record",
        required: false,
        dateFormat: "DD/MM/YYYY",
      },

      // Follow-up
      {
        ref: "previous_visit",
        type: "date",
        title: "Roughly when were you last in?",
        required: false,
      },
      {
        ref: "since_then",
        type: "long_text",
        title: "What's changed since then?",
        required: false,
        maxLength: 800,
      },

      // Something urgent
      {
        ref: "urgent_detail",
        type: "long_text",
        title: "Tell us what's happening",
        required: true,
        maxLength: 800,
      },
      {
        ref: "urgent_today",
        type: "yes_no",
        title: "Do you need to be seen today?",
        required: true,
        yesLabel: "Yes, today",
        noLabel: "The next few days is fine",
      },

      // Everyone else
      {
        ref: "preferred_slot",
        type: "date",
        title: "When suits you?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 30,
        timeMin: "09:00",
        timeMax: "17:30",
      },
      {
        ref: "backup_slot",
        type: "date",
        title: "And a second choice, in case that's taken?",
        required: false,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 30,
        timeMin: "09:00",
        timeMax: "17:30",
      },
      {
        ref: "access_needs",
        type: "long_text",
        title: "Anything we should arrange for your visit?",
        description: "Step-free access, an interpreter, a longer appointment: just say.",
        required: false,
        maxLength: 500,
      },
      {
        ref: "reminder",
        type: "single_select",
        title: "How should we remind you the day before?",
        required: false,
        options: [{ label: "Text message" }, { label: "Email" }, { label: "No reminder" }],
      },
    ],
    branches: [
      { when: "reason", is: "First consultation", then: "first_concern" },
      { when: "reason", is: "Follow-up", then: "previous_visit" },
      { when: "reason", is: "Routine check", then: "preferred_slot" },
      { when: "reason", is: "Something urgent", then: "urgent_detail" },
      { when: "date_of_birth", always: true, then: "preferred_slot" },
      { when: "since_then", always: true, then: "preferred_slot" },
      { when: "urgent_today", is: true, then: "end_urgent" },
      { when: "urgent_today", is: false, then: "preferred_slot" },
    ],
    endings: [
      {
        ref: "end_urgent",
        title: "We'll call you back as soon as we can ☎️",
        body: "Keep your phone nearby. If it's an emergency, please don't wait for us. Call your local emergency number.",
      },
    ],
    ending: { title: "Request received 🗓️", body: "We'll confirm your time by text or email shortly." },
    guide: {
      questionsToConsider: [
        "How long is each type of appointment, and does the reason list reflect that?",
        "What's the fastest you can really call back someone who needs to be seen today?",
        "Do you need a date of birth or other ID to find a returning client's record?",
        "What hours should the time picker offer, and do they change on some days?",
      ],
      howToUseResponses:
        "Check the urgent requests as they arrive and call back the ones who asked to be seen today first. For everyone else, use the reason to set the slot length: a first consultation needs longer than a routine check. Offer the preferred slot if it's free and the second choice if not. Pass the access needs to whoever greets the client, and send the reminder the way they asked.",
      customizeSteps: [
        "Rename the four reasons to your own appointment types, keeping the urgent one if you handle same-day requests.",
        "Set the time window on both date questions to your opening hours.",
        "Rewrite the urgent ending with the call-back time you can keep, then share the link on your website and booking pages.",
      ],
      faqs: [
        {
          q: "What should an appointment booking form include?",
          a: "Contact details, the reason for the appointment, a preferred date and time, a second choice and anything you need to arrange for the visit.",
        },
        {
          q: "How do I handle urgent appointment requests?",
          a: "Ask whether they need to be seen today and send those people to a separate ending that promises a call back, rather than a calendar.",
        },
        {
          q: "Can the form ask different questions for new and returning clients?",
          a: "Yes. First consultations and follow-ups each get their own questions here, and a routine check goes straight to picking a time.",
        },
        {
          q: "Does the booking confirm automatically?",
          a: "No. It collects a request with a preferred time, which you confirm yourself, so you stay in control of your diary.",
        },
      ],
    },
  }),
];
