import { defineTemplate, type TemplateSeed } from "../define.js";

export const FORM_FILE_UPLOAD: TemplateSeed[] = [
  defineTemplate({
    slug: "music-submission-form",
    type: "form",
    category: "file-upload",
    goals: ["run-events"],
    roles: ["marketing", "operations"],
    searchName: "Music submission form",
    title: "Music submission",
    icon: "Music",
    metaDescription:
      "Receive tracks from artists in one consistent format: the audio, genre, release status, bio and links, plus live setup details when they want a booking.",
    description: "Collect tracks and artist details in one consistent format for review.",
    blurb:
      "For playlists, venues, labels and events that are tired of links scattered across inboxes. Artists upload the track and describe it the same way every time, released tracks add a streaming link, upcoming ones give a release date, and anyone asking for a live slot describes their setup.",
    tags: ["music submission", "demo submission", "artist submission", "playlist submission", "band booking"],
    greeting: "Thanks for sending us your music. This takes about five minutes, and every track gets listened to.",
    questions: [
      { ref: "artist_name", type: "short_text", title: "What's your artist or band name?", required: true, maxLength: 120 },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we contact about this submission?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      { ref: "based_in", type: "short_text", title: "Where are you based?", description: "City and country is plenty.", required: true, maxLength: 120 },
      {
        ref: "submitting_for",
        type: "single_select",
        title: "What are you submitting for?",
        required: true,
        options: [
          { label: "Playlist or radio consideration" },
          { label: "A live booking" },
          { label: "A release on our label" },
          { label: "A feature or review" },
        ],
      },
      {
        ref: "live_setup",
        type: "long_text",
        title: "Tell us about your live show: how many people on stage, set length and anything you need technically.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "genre",
        type: "dropdown",
        title: "Which genre fits best?",
        required: true,
        options: [
          { label: "Pop" },
          { label: "Rock" },
          { label: "Hip-hop or rap" },
          { label: "R&B or soul" },
          { label: "Electronic" },
          { label: "Folk or acoustic" },
          { label: "Jazz" },
          { label: "Classical" },
          { label: "Metal" },
          { label: "Country" },
          { label: "World" },
          { label: "Something else" },
        ],
      },
      {
        ref: "track_title",
        type: "short_text",
        title: "What's the track called?",
        description: "Sending more than one? List the titles in the order you upload them.",
        required: true,
        maxLength: 150,
      },
      {
        ref: "track_file",
        type: "file_upload",
        title: "Upload the track",
        description: "MP3 or WAV. You can add up to three tracks, strongest first.",
        required: true,
        accept: ["audio/*"],
        maxFiles: 3,
        maxSizeMB: 50,
      },
      {
        ref: "release_status",
        type: "single_select",
        title: "Has your main track been released?",
        required: true,
        options: [{ label: "Yes, it's out" }, { label: "It's coming out soon" }, { label: "No, it's unreleased" }],
      },
      {
        ref: "streaming_link",
        type: "url",
        title: "Where can we listen to it online?",
        required: true,
      },
      {
        ref: "release_date",
        type: "date",
        title: "When does it come out?",
        required: true,
        disablePast: true,
      },
      {
        ref: "bio",
        type: "long_text",
        title: "Tell us about yourself and the track in a few sentences.",
        description: "What it's about, who you sound like and anything we should know.",
        required: true,
        maxLength: 1200,
      },
      {
        ref: "press_photo",
        type: "file_upload",
        title: "A press photo or artwork, if you have one",
        required: false,
        accept: ["image/*"],
        maxFiles: 2,
        maxSizeMB: 15,
      },
      {
        ref: "socials",
        type: "url",
        title: "Your main social or website link",
        required: false,
      },
      {
        ref: "rights",
        type: "legal_consent",
        title: "Rights to the music",
        required: true,
        consentText:
          "I wrote this music or have permission from everyone who owns it, including any samples, and I agree that you may listen to and review it. Nothing is published or broadcast without a separate agreement.",
        agreeLabel: "I confirm",
      },
    ],
    branches: [
      { when: "submitting_for", is: "A live booking", then: "live_setup" },
      { when: "submitting_for", is: "Playlist or radio consideration", then: "genre" },
      { when: "submitting_for", is: "A release on our label", then: "genre" },
      { when: "submitting_for", is: "A feature or review", then: "genre" },
      { when: "release_status", is: "Yes, it's out", then: "streaming_link" },
      { when: "release_status", is: "It's coming out soon", then: "release_date" },
      { when: "release_status", is: "No, it's unreleased", then: "bio" },
      { when: "streaming_link", always: true, then: "bio" },
    ],
    ending: {
      title: "Got it, thank you 🎧",
      body: "We listen to every submission. If it's a fit, we'll email you at the address you gave.",
    },
    guide: {
      questionsToConsider: [
        "What are you actually offering: playlist spots, live slots, a release or coverage, and should the options say so?",
        "Do you want the audio file itself, or only a streaming link that is easier to open?",
        "How many tracks do you realistically have time to listen to per artist?",
        "Will you reply to everyone, or only to the artists you take forward?",
      ],
      howToUseResponses:
        "Filter the responses by what the artist is submitting for, so booking requests and playlist pitches don't sit in one pile. Listen in batches by genre, and note a yes, maybe or no in your own column after exporting to CSV. For live bookings, check the setup answer against your stage before listening. Say in the ending how long replies take, and stick to it.",
      customizeSteps: [
        "Edit the submission options and genres to match what your playlist, venue or label handles.",
        "Change the rights wording so it matches how you will use the music, and have it checked if you plan to broadcast.",
        "Share the link on your website or social profiles, or embed it on a submissions page.",
      ],
      faqs: [
        {
          q: "What should a music submission form include?",
          a: "The artist name and contact, the track itself or a streaming link, the genre, whether it's released, a short bio and a confirmation that they own the rights.",
        },
        {
          q: "Should artists upload files or send streaming links?",
          a: "Both have a place. Files work for unreleased music, and links are quicker for released tracks. This form asks for the upload and adds a link question only when the track is already out.",
        },
        {
          q: "How large can uploaded tracks be?",
          a: "Each file can be up to 50 MB here, which covers a high quality MP3 or a short WAV. You can change the limit and the number of files when you edit the question.",
        },
        {
          q: "Can I use one form for playlists and live bookings?",
          a: "Yes. The form asks what the artist is submitting for, and only asks about their live setup when they want a booking.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "photo-contest-entry-form",
    type: "form",
    category: "file-upload",
    goals: ["run-events"],
    roles: ["marketing", "education"],
    searchName: "Photo contest entry form",
    title: "Photo contest entry",
    icon: "Camera",
    metaDescription:
      "Take photography competition entries with the image, category, title and the story behind the shot. Under-18s add a guardian, and composites are screened out.",
    description: "Take contest entries with everything the judges need, and screen out ineligible ones.",
    blurb:
      "Collects the photo along with what judges actually look at: the category, a title, where and when it was taken and the story behind it. Entrants under 18 give a parent or guardian's details, and anyone who has composited their image is told politely before they upload that it isn't eligible.",
    tags: ["photo contest", "photography competition", "contest entry", "photo submission", "image upload"],
    greeting: "Welcome to the photo contest. Entering takes about three minutes. Have your photo ready.",
    questions: [
      {
        ref: "entrant",
        type: "contact_info",
        title: "Who's entering?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "age_group",
        type: "single_select",
        title: "How old are you?",
        required: true,
        options: [{ label: "Under 18" }, { label: "18 or over" }],
      },
      {
        ref: "guardian_name",
        type: "short_text",
        title: "What's the name of your parent or guardian?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "guardian_email",
        type: "email",
        title: "And their email, so we can confirm they're happy for you to enter?",
        required: true,
      },
      {
        ref: "category",
        type: "single_select",
        title: "Which category are you entering?",
        required: true,
        options: [
          { label: "Landscape" },
          { label: "People and portraits" },
          { label: "Street" },
          { label: "Wildlife and nature" },
          { label: "Black and white" },
        ],
      },
      {
        ref: "editing",
        type: "single_select",
        title: "How much has the photo been edited?",
        required: true,
        options: [
          { label: "Not at all" },
          { label: "Basic adjustments like exposure, crop and colour" },
          { label: "Things added, removed or combined from several photos" },
        ],
      },
      {
        ref: "photo",
        type: "file_upload",
        title: "Upload your photo",
        description: "A JPEG or PNG at full resolution, with no watermark or name on it.",
        required: true,
        accept: ["image/jpeg", "image/png"],
        maxFiles: 1,
        maxSizeMB: 25,
      },
      { ref: "photo_title", type: "short_text", title: "What's the photo called?", required: true, maxLength: 100 },
      { ref: "taken_on", type: "date", title: "When did you take it?", required: false },
      { ref: "taken_at", type: "short_text", title: "Where was it taken?", required: false, maxLength: 150 },
      {
        ref: "story",
        type: "long_text",
        title: "What's the story behind the shot?",
        description: "A few sentences for the judges.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "camera",
        type: "short_text",
        title: "What did you shoot it on?",
        required: false,
        maxLength: 100,
        placeholder: "Camera and lens, or phone",
      },
      {
        ref: "entry_terms",
        type: "legal_consent",
        title: "Entry terms",
        required: true,
        consentText:
          "I took this photo myself, I own the rights to it, and anyone recognisable in it is happy for it to be entered. I agree that the organisers may show the photo, credited to me, in connection with this contest. I keep the copyright.",
        agreeLabel: "I agree and want to enter",
      },
    ],
    branches: [
      { when: "age_group", is: "18 or over", then: "category" },
      { when: "age_group", is: "Under 18", then: "guardian_name" },
      { when: "editing", is: "Things added, removed or combined from several photos", then: "end_ineligible" },
    ],
    ending: {
      title: "Your entry is in 📸",
      body: "Good luck. We'll email you once the judges have made their decision.",
    },
    endings: [
      {
        ref: "end_ineligible",
        title: "This one can't be entered",
        body: "The contest only accepts photos without added, removed or combined elements. You're welcome to enter again with a different shot.",
      },
    ],
    guide: {
      questionsToConsider: [
        "Which editing is allowed in your contest, and is the line between basic adjustments and compositing clear to entrants?",
        "Do you accept entries from under-18s, and what does a guardian need to agree to?",
        "How many photos may each person enter, in total and per category?",
        "What rights do you need to show winning photos, and for how long?",
      ],
      howToUseResponses:
        "Export the entries to CSV and filter by category, so each group of judges only sees their own section. Hide the entrant columns before judging if you want scoring to be blind. Email guardians of under-18 entrants to confirm before a photo goes on the shortlist, and check the editing answer again when you look at the full resolution file of any winner.",
      customizeSteps: [
        "Replace the categories with your own, and add the closing date to the greeting.",
        "Rewrite the entry terms to match your contest rules and how you will display the winning photos.",
        "Share the link on your social channels or embed it on the contest page.",
      ],
      faqs: [
        {
          q: "What information should a photo contest entry form collect?",
          a: "The entrant's name and email, the category, the photo at full resolution, a title, and agreement to the entry terms. Where and when it was taken, and the story behind it, help judges too.",
        },
        {
          q: "Do photo contest entrants keep the copyright?",
          a: "Usually yes. Most contests ask only for permission to display the photo with credit, and the entry terms in this form say the photographer keeps copyright. Edit them to match your own rules.",
        },
        {
          q: "Can under-18s enter a photo contest?",
          a: "Many contests allow it with a parent or guardian's permission. This form asks for guardian details from anyone under 18 so you can confirm before shortlisting.",
        },
        {
          q: "How do I stop ineligible entries?",
          a: "Ask the eligibility question before the upload. Here, anyone who has composited their image is told it can't be entered before they spend time uploading it.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "project-submission-form",
    type: "form",
    category: "file-upload",
    goals: [],
    roles: ["education", "operations", "freelancers-agencies"],
    searchName: "Project submission form",
    title: "Project submission",
    icon: "FileUp",
    metaDescription:
      "Receive project proposals and finished work in one place: title, summary, team, files and links. Proposals give a start date and budget, finished work its results.",
    description: "Take proposals and finished projects in one consistent format for review.",
    blurb:
      "Works for course projects, grant rounds, hackathons and internal pitches. Solo and team submissions are handled separately, proposals are asked for a start date and budget, and completed work is asked what it achieved, so reviewers get what they need for each without one long form.",
    tags: ["project submission", "proposal form", "assignment submission", "hackathon submission", "file upload"],
    greeting: "Ready to submit your project? This takes about five minutes. Have your files and links to hand.",
    questions: [
      {
        ref: "submitter",
        type: "contact_info",
        title: "Who's submitting?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      { ref: "project_title", type: "short_text", title: "What's the project called?", required: true, maxLength: 150 },
      {
        ref: "is_team",
        type: "yes_no",
        title: "Is this a team project?",
        required: true,
        yesLabel: "Yes, a team",
        noLabel: "No, just me",
      },
      {
        ref: "team_members",
        type: "long_text",
        title: "Who else is on the team, and what did each person do?",
        description: "One person per line, with their email.",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "summary",
        type: "long_text",
        title: "Summarise the project in a few sentences.",
        description: "What problem it tackles, what you did or plan to do, and who it's for.",
        required: true,
        maxLength: 2000,
      },

      {
        ref: "submission_type",
        type: "single_select",
        title: "What are you submitting?",
        required: true,
        options: [{ label: "A proposal for new work" }, { label: "Finished work for review" }],
      },
      // Proposals
      {
        ref: "start_date",
        type: "date",
        title: "When would you want to start?",
        required: true,
        disablePast: true,
      },
      {
        ref: "budget",
        type: "number",
        title: "What budget would you need, if any?",
        required: false,
        min: 0,
        currency: "USD",
      },

      // Finished work
      {
        ref: "results",
        type: "long_text",
        title: "What did the project achieve, and what would you do differently?",
        required: true,
        maxLength: 1500,
      },

      // Everyone
      {
        ref: "files",
        type: "file_upload",
        title: "Upload your project files",
        description: "Documents, slides, images or a zip. Up to five files.",
        required: true,
        accept: ["application/pdf", "application/zip", "image/*", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],
        maxFiles: 5,
        maxSizeMB: 25,
      },
      {
        ref: "project_link",
        type: "url",
        title: "Is there a link we should see, like a demo, repository or video?",
        required: false,
      },
      {
        ref: "anything_else",
        type: "long_text",
        title: "Anything else reviewers should know?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "originality",
        type: "legal_consent",
        title: "Your confirmation",
        required: true,
        consentText:
          "This submission is my own work, or my team's, and anything taken from others is credited. I understand it will be shared with the people reviewing it.",
        agreeLabel: "I confirm",
      },
    ],
    branches: [
      { when: "is_team", is: false, then: "summary" },
      { when: "is_team", is: true, then: "team_members" },
      { when: "submission_type", is: "A proposal for new work", then: "start_date" },
      { when: "submission_type", is: "Finished work for review", then: "results" },
      { when: "budget", always: true, then: "files" },
    ],
    ending: {
      title: "Submitted, thank you 🚀",
      body: "Your project is with the reviewers. We'll email you about next steps.",
    },
    guide: {
      questionsToConsider: [
        "Is this for proposals, finished work or both, and do you need the choice question at all?",
        "Which file types can your reviewers open, and how large are typical submissions?",
        "Do reviewers need to know who did what on a team project?",
        "Is there a deadline, and should the greeting say it?",
      ],
      howToUseResponses:
        "Export the submissions to CSV and share the list with reviewers, split into proposals and finished work since they are judged differently. Give each reviewer the same criteria and a column to score against. For team projects, the breakdown of who did what helps when marks or credit are shared out. Reply to every submitter once a decision is made.",
      customizeSteps: [
        "Change the submission types, or remove the question if you only take one kind.",
        "Adjust the accepted file types and size limit to what your reviewers can open.",
        "Share the link with your class, applicants or team, or embed it on the brief page.",
      ],
      faqs: [
        {
          q: "What should a project submission form include?",
          a: "Contact details, the project title, a short summary, the team, the files and any links such as a demo or repository. A confirmation that the work is original is common for courses and competitions.",
        },
        {
          q: "Can people upload several files?",
          a: "Yes. This form accepts up to five files, including PDFs, documents, slides, images and zip archives. You can change the types and limits when you edit the question.",
        },
        {
          q: "How do I handle team project submissions?",
          a: "Ask one person to submit for the team and list the others. This form asks for each team member and what they contributed only when it's a team project.",
        },
        {
          q: "Can I use this for student assignments?",
          a: "Yes. Remove the budget question, rename the submission types to your assignment stages, and share the link with the class.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "art-submission-form",
    type: "form",
    category: "file-upload",
    goals: ["run-events"],
    roles: ["marketing", "operations"],
    searchName: "Art submission form",
    title: "Art submission",
    icon: "Palette",
    metaDescription:
      "Collect artwork for a show, open call or publication: images of the work, medium, size, year and statement, with a price asked only when the piece is for sale.",
    description: "Receive artwork and the context a curator or editor needs to review it.",
    blurb:
      "An open call form for galleries, exhibitions and publications. Artists upload images of the work and give the details a curator needs to picture it in the room: medium, size, year and an artist statement. The asking price is only asked when the work is for sale, and three-dimensional work gets a question about handling.",
    tags: ["art submission", "open call", "artist application", "exhibition submission", "artwork upload"],
    greeting: "Thanks for submitting your work. This takes about five minutes. Have images of the piece ready.",
    questions: [
      {
        ref: "artist",
        type: "contact_info",
        title: "Who's the artist?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "portfolio",
        type: "url",
        title: "Your website or online portfolio, if you have one",
        required: false,
      },
      { ref: "work_title", type: "short_text", title: "What's the title of the work?", required: true, maxLength: 150 },
      {
        ref: "medium",
        type: "dropdown",
        title: "What medium is it?",
        required: true,
        options: [
          { label: "Painting" },
          { label: "Drawing" },
          { label: "Printmaking" },
          { label: "Photography" },
          { label: "Digital" },
          { label: "Mixed media" },
          { label: "Textile or fibre" },
          { label: "Sculpture" },
          { label: "Ceramics" },
          { label: "Installation" },
        ],
      },
      {
        ref: "handling",
        type: "long_text",
        title: "Anything we should know about installing or handling it?",
        description: "Weight, how it stands or hangs, power, or anything fragile.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "dimensions",
        type: "short_text",
        title: "What are its dimensions?",
        required: true,
        maxLength: 80,
        description: "For digital work, give the pixel size or the size you'd print it.",
        placeholder: "Height x width x depth, in cm or inches",
      },
      {
        ref: "year",
        type: "number",
        title: "What year was it made?",
        required: true,
        integerOnly: true,
        min: 1900,
        max: 2100,
      },
      {
        ref: "images",
        type: "file_upload",
        title: "Upload images of the work",
        description: "The full piece first, then details or other angles. JPEG or PNG.",
        required: true,
        accept: ["image/jpeg", "image/png"],
        maxFiles: 5,
        maxSizeMB: 20,
      },
      {
        ref: "statement",
        type: "long_text",
        title: "Tell us about this piece.",
        description: "What it's about and how you made it, in your own words.",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "for_sale",
        type: "yes_no",
        title: "Is the work for sale?",
        required: true,
      },
      {
        ref: "price",
        type: "number",
        title: "What's the asking price?",
        required: true,
        min: 0,
        currency: "USD",
      },
      {
        ref: "bio",
        type: "long_text",
        title: "A short bio we could print alongside the work",
        required: false,
        maxLength: 800,
      },
      {
        ref: "image_permission",
        type: "legal_consent",
        title: "Use of images",
        required: true,
        consentText:
          "I made this work and own the rights to it. If it is selected, the organisers may reproduce these images, credited to me, to present and promote the show or publication. I keep the copyright.",
        agreeLabel: "I agree",
      },
    ],
    branches: [
      { when: "medium", is: "Sculpture", then: "handling" },
      { when: "medium", is: "Ceramics", then: "handling" },
      { when: "medium", is: "Installation", then: "handling" },
      { when: "medium", is: "Textile or fibre", then: "handling" },
      { when: "medium", is: "Painting", then: "dimensions" },
      { when: "medium", is: "Drawing", then: "dimensions" },
      { when: "medium", is: "Printmaking", then: "dimensions" },
      { when: "medium", is: "Photography", then: "dimensions" },
      { when: "medium", is: "Digital", then: "dimensions" },
      { when: "medium", is: "Mixed media", then: "dimensions" },
      { when: "for_sale", is: false, then: "bio" },
      { when: "for_sale", is: true, then: "price" },
    ],
    ending: {
      title: "Your work has been submitted 🎨",
      body: "Thank you for sharing it. We'll email you once the selection has been made.",
    },
    guide: {
      questionsToConsider: [
        "Is this for one show, an ongoing open call or a publication, and does the greeting say which?",
        "Are there limits on size, medium or year that artists should know before they start?",
        "Will you take a commission on sales, and should the price question say so?",
        "How many works may each artist submit, and should they fill in the form once per piece?",
      ],
      howToUseResponses:
        "Export the submissions to CSV and review the images alongside the medium, size and year, so the selection panel can picture each piece in the space. Pass the handling notes for sculpture and installation to whoever plans the hang early. Keep the bios and prices together for the wall labels and price list once the selection is made.",
      customizeSteps: [
        "Add the deadline, theme and any size limits to the greeting.",
        "Edit the medium list to match what your show accepts.",
        "Share the link in your open call announcement, or embed it on the call page.",
      ],
      faqs: [
        {
          q: "What should an art submission form ask for?",
          a: "Images of the work, the title, medium, dimensions and year, an artist statement, contact details, and whether the work is for sale. Permission to reproduce the images is worth asking for up front.",
        },
        {
          q: "What image files should artists submit?",
          a: "High resolution JPEG or PNG files that show the whole piece clearly, plus a few detail shots. This form accepts up to five images per work.",
        },
        {
          q: "How long should an artist statement be for a submission?",
          a: "A short paragraph is usually enough: what the work is about and how it was made. Curators read many of them, so clear beats long.",
        },
        {
          q: "Can artists submit more than one piece?",
          a: "Yes. The simplest way is to fill in the form once per piece, which keeps each work's details and images together in your responses.",
        },
      ],
    },
  }),
];
