import { defineTemplate, type TemplateSeed } from "../define.js";

export const FORM_REQUEST: TemplateSeed[] = [
  defineTemplate({
    slug: "marketing-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["marketing", "operations"],
    searchName: "Marketing request form",
    title: "Marketing request",
    icon: "Megaphone",
    metaDescription:
      "Take campaign, content and design requests in one place. Each request type gets its own follow-ups, and every brief covers audience, success measure and deadline.",
    description: "One intake for campaigns, content and design, so every brief arrives complete.",
    blurb:
      "Requesters pick what they need first, and the form asks the questions that fit: goals and channels for a campaign, formats for a piece of content or design. Everyone then covers the audience, what success looks like and whether the date is fixed, which is what a marketing team needs before it can say yes.",
    tags: ["marketing request", "creative brief", "content request", "campaign intake", "design request"],
    greeting: "Need something from marketing? Tell us what it is and we'll take it from here.",
    questions: [
      {
        ref: "requester",
        type: "contact_info",
        title: "Who is asking?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "team",
        type: "dropdown",
        title: "Which team are you on?",
        required: true,
        options: [
          { label: "Sales" },
          { label: "Product" },
          { label: "Customer success" },
          { label: "Leadership" },
          { label: "People and HR" },
          { label: "Finance" },
          { label: "Other" },
        ],
      },
      {
        ref: "request_type",
        type: "single_select",
        title: "What do you need?",
        required: true,
        options: [
          { label: "A full campaign" },
          { label: "A single piece of content" },
          { label: "Design work" },
          { label: "Event or sponsorship support" },
          { label: "Something else" },
        ],
      },

      // Campaigns
      {
        ref: "campaign_goal",
        type: "single_select",
        title: "What should the campaign achieve above all?",
        required: true,
        options: [
          { label: "Awareness of something new" },
          { label: "Leads or sign-ups" },
          { label: "A product or feature launch" },
          { label: "Keeping existing customers engaged" },
        ],
      },
      {
        ref: "channels",
        type: "multi_select",
        title: "Which channels do you have in mind?",
        description: "Pick any you already know you want. We'll suggest others.",
        required: false,
        minSelections: 0,
        maxSelections: 8,
        options: [
          { label: "Email" },
          { label: "Social media" },
          { label: "Paid ads" },
          { label: "Website or landing page" },
          { label: "Blog" },
          { label: "Events or webinars" },
          { label: "Not sure yet" },
        ],
      },

      // Content and design
      {
        ref: "formats",
        type: "multi_select",
        title: "Where will it be used?",
        required: true,
        minSelections: 1,
        maxSelections: 8,
        allowOther: true,
        options: [
          { label: "Website" },
          { label: "Social posts" },
          { label: "Email" },
          { label: "Slides or a sales deck" },
          { label: "Print" },
          { label: "Video" },
        ],
      },

      // Everyone
      {
        ref: "summary",
        type: "long_text",
        title: "Describe the request in a few sentences. What is it, and why now?",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "audience",
        type: "short_text",
        title: "Who is it for?",
        description: "For example, trial users, customers in one region, or partners.",
        required: true,
        maxLength: 200,
      },
      {
        ref: "success",
        type: "long_text",
        title: "How will you know it worked?",
        required: false,
        maxLength: 600,
      },
      { ref: "due_date", type: "date", title: "When do you need it by?", required: true, disablePast: true },
      {
        ref: "date_fixed",
        type: "yes_no",
        title: "Is that date fixed, for example by a launch or an event?",
        required: true,
      },
      {
        ref: "date_reason",
        type: "short_text",
        title: "What is the date tied to?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "references",
        type: "file_upload",
        title: "Any drafts, examples or brand files that would help?",
        required: false,
        accept: ["image/*", "application/pdf", "video/*"],
        maxFiles: 5,
        maxSizeMB: 25,
      },
      {
        ref: "approver",
        type: "short_text",
        title: "Who gives final sign-off on your side?",
        required: false,
        maxLength: 120,
      },
    ],
    branches: [
      { when: "request_type", is: "A full campaign", then: "campaign_goal" },
      { when: "request_type", is: "A single piece of content", then: "formats" },
      { when: "request_type", is: "Design work", then: "formats" },
      { when: "request_type", is: "Event or sponsorship support", then: "summary" },
      { when: "request_type", is: "Something else", then: "summary" },
      { when: "channels", always: true, then: "summary" },
      { when: "date_fixed", is: true, then: "date_reason" },
      { when: "date_fixed", is: false, then: "references" },
    ],
    ending: {
      title: "Request received",
      body: "We'll review it at our next planning session and reply with a yes, a question or a suggested date.",
    },
    guide: {
      questionsToConsider: [
        "Which request types does your team actually take on, and which should go somewhere else?",
        "How much notice do you need for a campaign compared with a single social post?",
        "Do you want a budget question, or is budget decided elsewhere?",
        "Who on your team triages new requests, and how often?",
      ],
      howToUseResponses:
        "Review new requests on a fixed day each week rather than as they arrive, so priorities are set together instead of by whoever asked loudest. Sort by due date and by whether the date is fixed: a launch-tied deadline outranks a preferred one. Reply to every requester with a decision, and export the responses to CSV each quarter to see which teams ask most and which request types take longest.",
      customizeSteps: [
        "Edit the request types and channels to match what your team actually produces.",
        "Add a line to the greeting saying how much notice you need, so people know before they start.",
        "Share the link in your team's wiki or intranet, and point every ad hoc request in chat back to it.",
      ],
      faqs: [
        {
          q: "What should a marketing request form include?",
          a: "Who is asking, what they need, the audience, the goal and the deadline. Asking whether the deadline is fixed saves a lot of back and forth when two requests clash.",
        },
        {
          q: "How far in advance should people submit marketing requests?",
          a: "It depends on the work. Many teams ask for a few days for a social post and several weeks for a full campaign; say your own lead times in the greeting.",
        },
        {
          q: "Can different request types ask different questions?",
          a: "Yes. This form already branches: a campaign request is asked about goals and channels, while a content or design request is asked where the work will be used.",
        },
        {
          q: "Can I add a budget question?",
          a: "Yes. Use this template copies it into your account, where you can add a number question for budget and edit or remove any other question.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "media-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["marketing"],
    searchName: "Media request form",
    title: "Media request",
    icon: "Newspaper",
    metaDescription:
      "Handle press enquiries with a form that asks for the outlet, topic, format and deadline, then follows up on interviews, media assets and filming requests.",
    description: "Collect press enquiries with everything your communications team needs to respond.",
    blurb:
      "Journalists get a short, clear route to your press team instead of a generic inbox. The form asks what kind of request it is and follows up to match: preferred format and spokesperson for an interview, which assets for a media kit request, and location details for filming.",
    tags: ["media request", "press enquiry", "press office", "interview request", "PR"],
    greeting: "Hello. Tell us about your story and we'll get back to you before your deadline where we can.",
    questions: [
      {
        ref: "journalist",
        type: "contact_info",
        title: "Your name and how to reach you",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      { ref: "outlet", type: "short_text", title: "Which outlet or publication are you with?", required: true, maxLength: 150 },
      {
        ref: "outlet_type",
        type: "single_select",
        title: "What kind of outlet is it?",
        required: true,
        allowOther: true,
        options: [
          { label: "Newspaper" },
          { label: "Magazine" },
          { label: "TV" },
          { label: "Radio" },
          { label: "Podcast" },
          { label: "Online publication" },
          { label: "Newsletter or blog" },
        ],
      },
      {
        ref: "outlet_link",
        type: "url",
        title: "A link to the outlet or to your recent work",
        required: false,
      },
      {
        ref: "request_kind",
        type: "single_select",
        title: "What are you asking for?",
        required: true,
        options: [
          { label: "An interview" },
          { label: "A comment or quote" },
          { label: "Background information" },
          { label: "Images, logos or a media kit" },
          { label: "Filming or photography on site" },
        ],
      },

      // Interviews
      {
        ref: "interview_format",
        type: "single_select",
        title: "How would you like to do the interview?",
        required: true,
        options: [{ label: "In person" }, { label: "Phone" }, { label: "Video call" }, { label: "Written answers" }],
      },
      {
        ref: "spokesperson",
        type: "short_text",
        title: "Is there someone in particular you'd like to speak to?",
        description: "A name or a role is fine. Leave blank and we'll suggest the right person.",
        required: false,
        maxLength: 150,
      },

      // Assets
      {
        ref: "assets",
        type: "multi_select",
        title: "Which assets do you need?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        allowOther: true,
        options: [
          { label: "Logo files" },
          { label: "Product or service photos" },
          { label: "Headshots of leadership" },
          { label: "Fact sheet or company background" },
          { label: "Video footage" },
        ],
      },

      // Filming
      {
        ref: "filming_details",
        type: "long_text",
        title: "Where would you like to film or photograph, and roughly how big is the crew?",
        required: true,
        maxLength: 800,
      },

      // Everyone
      {
        ref: "topic",
        type: "long_text",
        title: "What is the story about, and what angle are you taking?",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "deadline",
        type: "date",
        title: "What is your deadline?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 30,
        timeMin: "06:00",
        timeMax: "23:30",
      },
      {
        ref: "publish_date",
        type: "date",
        title: "When do you expect it to publish or air?",
        required: false,
        disablePast: true,
      },
      {
        ref: "anything_else",
        type: "long_text",
        title: "Anything else we should know, such as other people you're speaking to?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "request_kind", is: "An interview", then: "interview_format" },
      { when: "request_kind", is: "A comment or quote", then: "topic" },
      { when: "request_kind", is: "Background information", then: "topic" },
      { when: "request_kind", is: "Images, logos or a media kit", then: "assets" },
      { when: "request_kind", is: "Filming or photography on site", then: "filming_details" },
      { when: "spokesperson", always: true, then: "topic" },
      { when: "assets", always: true, then: "topic" },
    ],
    ending: {
      title: "Thanks, your request is with our press team",
      body: "We'll reply by email, and we'll tell you early if we can't meet your deadline.",
    },
    guide: {
      questionsToConsider: [
        "Who answers media requests, and do they need the phone number as well as the email?",
        "Which spokespeople are available, and should the form list them by name?",
        "Do you have a media kit you can link to in the ending, so asset requests answer themselves?",
        "What is your policy on filming at your premises?",
      ],
      howToUseResponses:
        "Sort new requests by deadline, since a same-day quote needs a reply within hours while a feature can wait a few days. Tell the journalist early if you can't help, because a clear no lets them move on. Keep a record of outlets and topics in an exported CSV, which becomes your press list for future announcements.",
      customizeSteps: [
        "List your actual spokespeople or press contacts in the interview follow-up if you want to steer requests.",
        "Add a link to your media kit in the ending so asset requests can be served straight away.",
        "Link the form from the press or newsroom page on your site, or embed it there directly.",
      ],
      faqs: [
        {
          q: "What should a media request form ask?",
          a: "The journalist's contact details, the outlet, what they want, the story angle and the deadline. The deadline matters most, because press requests are time-sensitive.",
        },
        {
          q: "Where should I put a media request form?",
          a: "On your press or newsroom page, and in the signature of whoever handles press. Journalists look there first for a direct route.",
        },
        {
          q: "Should I ask for the journalist's phone number?",
          a: "Yes, if you can call back. Tight deadlines are often resolved faster by phone than by email.",
        },
        {
          q: "Can I use this for event press passes too?",
          a: "Yes. Copy the template with Use this template, add a request type for press passes and a follow-up asking which event and date.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "new-user-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["operations", "hr-people"],
    searchName: "New user request form",
    title: "New user request",
    icon: "UserPlus",
    metaDescription:
      "Request accounts and access for a new starter: who they are, when they start, which systems they need, and why if they need admin rights. Built for IT and ops.",
    description: "Ask for accounts, access and equipment for a new starter in one go.",
    blurb:
      "Everything IT needs to set someone up before their first morning: start date, role, systems and equipment. Contractors and temporary staff are asked for an end date so access doesn't outlive the contract, and any request for admin rights has to say why and whether a manager has approved it.",
    tags: ["new user request", "access request", "IT onboarding", "new starter", "account request"],
    greeting: "Setting up access for someone new? This takes about three minutes.",
    questions: [
      {
        ref: "requester",
        type: "contact_info",
        title: "First, who is making the request?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      { ref: "new_user_name", type: "short_text", title: "What is the new user's full name?", required: true, maxLength: 150 },
      { ref: "job_title", type: "short_text", title: "What is their job title?", required: true, maxLength: 150 },
      {
        ref: "department",
        type: "dropdown",
        title: "Which department will they be in?",
        required: true,
        options: [
          { label: "Sales" },
          { label: "Marketing" },
          { label: "Engineering" },
          { label: "Product" },
          { label: "Customer support" },
          { label: "Finance" },
          { label: "People and HR" },
          { label: "Operations" },
          { label: "Other" },
        ],
      },
      { ref: "start_date", type: "date", title: "When is their first day?", required: true, disablePast: true },
      {
        ref: "employment_type",
        type: "single_select",
        title: "What kind of role is it?",
        required: true,
        options: [{ label: "Employee" }, { label: "Contractor" }, { label: "Intern" }, { label: "Temporary staff" }],
      },
      {
        ref: "end_date",
        type: "date",
        title: "When should their access end?",
        description: "We'll switch accounts off on this date unless you tell us otherwise.",
        required: true,
        disablePast: true,
      },
      {
        ref: "systems",
        type: "multi_select",
        title: "Which systems will they need?",
        required: true,
        minSelections: 1,
        maxSelections: 10,
        allowOther: true,
        options: [
          { label: "Email and calendar" },
          { label: "Team chat" },
          { label: "Shared drives and documents" },
          { label: "CRM" },
          { label: "Finance or accounting system" },
          { label: "Code repositories" },
          { label: "HR system" },
          { label: "VPN or remote access" },
        ],
      },
      {
        ref: "access_level",
        type: "single_select",
        title: "What level of access do they need?",
        required: true,
        options: [{ label: "Standard user access" }, { label: "Admin or elevated access" }],
      },

      // Admin access
      {
        ref: "admin_reason",
        type: "long_text",
        title: "Which systems need admin access, and why does the role need it?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "manager_approved",
        type: "yes_no",
        title: "Has their manager approved the admin access?",
        required: true,
      },

      // Everyone
      {
        ref: "mirror_user",
        type: "short_text",
        title: "Is there a colleague whose access they should match?",
        description: "Often the quickest way to get it right. Leave blank if not.",
        required: false,
        maxLength: 150,
      },
      {
        ref: "equipment",
        type: "multi_select",
        title: "What equipment will they need?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        options: [
          { label: "Laptop" },
          { label: "Monitor" },
          { label: "Phone" },
          { label: "Headset" },
          { label: "Building access card" },
          { label: "Nothing, they have their own" },
        ],
      },
      {
        ref: "notes",
        type: "long_text",
        title: "Anything else IT should know?",
        description: "For example, they work remotely and need equipment posted.",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "employment_type", is: "Employee", then: "systems" },
      { when: "employment_type", is: "Contractor", then: "end_date" },
      { when: "employment_type", is: "Intern", then: "end_date" },
      { when: "employment_type", is: "Temporary staff", then: "end_date" },
      { when: "access_level", is: "Standard user access", then: "mirror_user" },
      { when: "access_level", is: "Admin or elevated access", then: "admin_reason" },
    ],
    ending: {
      title: "Request logged",
      body: "IT will confirm by email once the accounts are ready. If you asked for admin access, that part waits until the manager has approved it.",
    },
    guide: {
      questionsToConsider: [
        "Which systems does everyone get by default, and which need a specific request?",
        "Who can approve admin access, and does the form need to name them?",
        "How much notice does IT need before a start date?",
        "Should HR or the hiring manager be the one filling this in?",
      ],
      howToUseResponses:
        "Sort requests by start date so the earliest starters are set up first, and aim to finish a few days before day one. Hold any admin request where the manager hasn't approved yet and follow up with the requester. Keep the end dates for contractors and temporary staff in a calendar, since the most common access mistake is an account nobody switched off.",
      customizeSteps: [
        "Replace the system list with the tools your company actually runs, grouped the way IT provisions them.",
        "Edit the department list to match your organisation chart.",
        "Share the link with HR and hiring managers, and add it to your hiring checklist so it goes out when an offer is signed.",
      ],
      faqs: [
        {
          q: "What should a new user request form include?",
          a: "The new person's name, role, department and start date, the systems and access level they need, and their equipment. For contractors, add an end date so access can be removed on time.",
        },
        {
          q: "Who should fill in a new user access request?",
          a: "Usually the hiring manager or HR, since the new person has no accounts yet. The form asks for the requester's details separately from the new user's.",
        },
        {
          q: "How do I handle admin access requests?",
          a: "Ask for a reason and a manager's approval before granting it. This form only asks those questions when admin access is selected, so standard requests stay short.",
        },
        {
          q: "Can I use this for access changes, not just new starters?",
          a: "Yes. Copy it with Use this template and change the greeting and first questions; the systems and access questions work the same for someone changing roles.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "information-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["customer-success", "operations"],
    searchName: "Information request form",
    title: "Information request",
    icon: "FileSearch",
    metaDescription:
      "Collect requests for documents, records or details: what is needed, why, and how to send it. Requests about personal records include an identity check.",
    description: "Take requests for documents or details, and know where and how to send the reply.",
    blurb:
      "Asks what the person needs, what it is for and how they want to receive it. Anyone asking for records about themselves is asked for a reference and proof of identity before the rest, and a request for a printed copy asks for a postal address, so nobody is chased for details afterwards.",
    tags: ["information request", "document request", "records request", "request for information", "proof of identity"],
    greeting: "Looking for some information from us? Tell us what you need and we'll get it to you.",
    questions: [
      {
        ref: "requester",
        type: "contact_info",
        title: "Who should we reply to?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "requester_type",
        type: "single_select",
        title: "Which best describes you?",
        required: true,
        allowOther: true,
        options: [
          { label: "Customer or client" },
          { label: "Partner or supplier" },
          { label: "Student or researcher" },
          { label: "Member of the public" },
        ],
      },
      {
        ref: "about",
        type: "single_select",
        title: "What is the information about?",
        required: true,
        options: [
          { label: "Records about me or my account" },
          { label: "Our policies or procedures" },
          { label: "Our products or services" },
          { label: "Reports or published data" },
          { label: "Something else" },
        ],
      },

      // Personal records
      {
        ref: "account_ref",
        type: "short_text",
        title: "Do you have an account, customer or case number?",
        description: "It helps us find your records quickly. Leave blank if you don't know it.",
        required: false,
        maxLength: 80,
      },
      {
        ref: "id_proof",
        type: "file_upload",
        title: "Please upload proof of identity",
        description: "We only release personal records to the person they belong to. A photo of an ID document is enough.",
        required: true,
        accept: ["image/*", "application/pdf"],
        maxFiles: 2,
        maxSizeMB: 10,
      },

      // Everyone
      {
        ref: "details",
        type: "long_text",
        title: "What exactly would you like to receive?",
        description: "Name the document, time period or topic if you can.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "purpose",
        type: "long_text",
        title: "What do you need it for?",
        description: "Optional, but it helps us send the most useful version.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "delivery",
        type: "single_select",
        title: "How would you like to receive it?",
        required: true,
        options: [{ label: "By email" }, { label: "As a printed copy by post" }, { label: "A phone call to talk it through" }],
      },
      {
        ref: "postal_address",
        type: "address",
        title: "Where should we post it?",
        required: true,
        fields: ["street", "city", "state", "postal", "country"],
      },
      {
        ref: "phone",
        type: "phone",
        title: "What number should we call?",
        required: true,
      },
      {
        ref: "needed_by",
        type: "date",
        title: "Is there a date you need it by?",
        required: false,
        disablePast: true,
      },
    ],
    branches: [
      { when: "about", is: "Records about me or my account", then: "account_ref" },
      { when: "about", is: "Our policies or procedures", then: "details" },
      { when: "about", is: "Our products or services", then: "details" },
      { when: "about", is: "Reports or published data", then: "details" },
      { when: "about", is: "Something else", then: "details" },
      { when: "delivery", is: "By email", then: "needed_by" },
      { when: "delivery", is: "As a printed copy by post", then: "postal_address" },
      { when: "delivery", is: "A phone call to talk it through", then: "phone" },
      { when: "postal_address", always: true, then: "needed_by" },
    ],
    ending: {
      title: "Request received",
      body: "We'll confirm we have it and tell you when to expect a reply. If we need anything else, we'll ask by email.",
    },
    guide: {
      questionsToConsider: [
        "Which kinds of information can you share, and which should the form say you can't?",
        "Do personal record requests need an identity check in your setting, and what counts as proof?",
        "Are you bound by a response deadline for some requests, and should the ending mention it?",
        "Which delivery methods can your team really offer?",
      ],
      howToUseResponses:
        "Log each request with the date it arrived, because many information requests carry a response deadline set by law or policy. Check the identity proof before releasing any personal records, and delete uploaded ID once it has been checked if you don't need to keep it. Group requests by topic every few months: questions that keep coming back are usually a sign the answer should be published on your website.",
      customizeSteps: [
        "Edit the topic list to the kinds of information people actually ask your organisation for.",
        "Change the identity check wording to match what your organisation accepts as proof.",
        "Link the form from your contact, privacy or help page so requests arrive in one place.",
      ],
      faqs: [
        {
          q: "What is an information request form?",
          a: "A form someone uses to ask an organisation for documents, records or details. It records who asked, what they need and how to send it, so nothing gets lost in an inbox.",
        },
        {
          q: "Should I verify identity before sharing information?",
          a: "Yes, whenever the information is about a specific person. This form only asks for proof of identity when someone requests their own records.",
        },
        {
          q: "Can I use this for subject access or freedom of information requests?",
          a: "It can be a starting point, but those requests follow specific legal rules where you are. Check what your law requires and edit the questions and ending to match.",
        },
        {
          q: "Can I change how people receive the information?",
          a: "Yes. Copy it with Use this template and edit the delivery options; each one can lead to its own follow-up question.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "logo-design-request-form",
    type: "form",
    category: "request",
    goals: ["onboard-clients"],
    roles: ["freelancers-agencies", "marketing"],
    searchName: "Logo design request form",
    title: "Logo design brief",
    icon: "PenTool",
    metaDescription:
      "Brief a logo designer properly: the business, its audience, the style it wants, references and where the logo will appear. Rebrands also share the current logo.",
    description: "Collect a logo brief that a designer can start from on day one.",
    blurb:
      "Written from the designer's side of the table: what the business does, who it serves, the personality it wants and every place the logo has to work. Clients refreshing or replacing a logo are asked to upload the current one and say what should survive, while brand-new businesses skip straight to style.",
    tags: ["logo design brief", "logo request", "design brief", "branding questionnaire", "logo questionnaire"],
    greeting: "Let's start on your logo. The more you tell us here, the closer the first drafts will be.",
    questions: [
      {
        ref: "client",
        type: "contact_info",
        title: "Your name and email",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "business_name",
        type: "short_text",
        title: "What name should appear in the logo, exactly as written?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "business",
        type: "long_text",
        title: "What does the business do, in a sentence or two?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "audience",
        type: "long_text",
        title: "Who are your customers, and what do they care about?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "stage",
        type: "single_select",
        title: "Where are you starting from?",
        required: true,
        options: [
          { label: "A new business with no logo yet" },
          { label: "A refresh of our current logo" },
          { label: "A complete rebrand" },
        ],
      },

      // Existing logo
      {
        ref: "current_logo",
        type: "file_upload",
        title: "Please upload your current logo",
        required: true,
        accept: ["image/*", "application/pdf"],
        maxFiles: 3,
        maxSizeMB: 20,
      },
      {
        ref: "keep_change",
        type: "long_text",
        title: "What should stay, and what isn't working any more?",
        required: true,
        maxLength: 800,
      },

      // Everyone
      {
        ref: "personality",
        type: "multi_select",
        title: "Pick up to three words the logo should feel like",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "Friendly" },
          { label: "Premium" },
          { label: "Playful" },
          { label: "Trustworthy" },
          { label: "Bold" },
          { label: "Calm" },
          { label: "Traditional" },
          { label: "Technical" },
        ],
      },
      {
        ref: "logo_style",
        type: "single_select",
        title: "Which kind of logo do you picture?",
        required: true,
        options: [
          { label: "Name only, in a distinctive typeface", description: "A wordmark" },
          { label: "A symbol alongside the name" },
          { label: "A badge or emblem with the name inside" },
          { label: "Not sure, show me options" },
        ],
      },
      {
        ref: "colours",
        type: "short_text",
        title: "Any colours you want, or want to avoid?",
        required: false,
        maxLength: 200,
      },
      {
        ref: "references",
        type: "file_upload",
        title: "Logos or brands you admire",
        description: "Optional. Screenshots are fine, from any industry.",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 5,
        maxSizeMB: 10,
      },
      {
        ref: "reference_notes",
        type: "long_text",
        title: "What do you like about those, and is there anything you dislike in your industry's logos?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "usage",
        type: "multi_select",
        title: "Where will the logo need to work?",
        required: true,
        minSelections: 1,
        maxSelections: 8,
        options: [
          { label: "Website" },
          { label: "Social media profile pictures" },
          { label: "App icon" },
          { label: "Signage or shopfront" },
          { label: "Packaging" },
          { label: "Printed materials" },
          { label: "Clothing or merchandise" },
        ],
      },
      { ref: "deadline", type: "date", title: "When do you need final files by?", required: false, disablePast: true },
    ],
    branches: [
      { when: "stage", is: "A new business with no logo yet", then: "personality" },
      { when: "stage", is: "A refresh of our current logo", then: "current_logo" },
      { when: "stage", is: "A complete rebrand", then: "current_logo" },
    ],
    ending: {
      title: "Brief received ✏️",
      body: "Thanks. We'll read it through and come back with any questions before we start sketching.",
    },
    guide: {
      questionsToConsider: [
        "How many initial concepts will you present, and should the ending say so?",
        "Do you want a budget question, or do you quote after reading the brief?",
        "Which file formats will you deliver, and does the client need to know now?",
        "Should the personality words be your own vocabulary rather than these?",
      ],
      howToUseResponses:
        "Read the brief before the kickoff call and list anything that conflicts, such as premium and playful together, so you can ask about it directly. Build a moodboard from the uploaded references and the notes on what the client likes. Keep the usage answers in front of you while designing, because a logo that must work as an app icon or embroidered on a shirt needs to survive at small sizes and in one colour.",
      customizeSteps: [
        "Swap the personality words for the vocabulary you already use with clients.",
        "Add your process to the ending, such as how many rounds of revisions are included.",
        "Send the link as soon as a client signs, or embed it on your enquiry page so the brief arrives with the lead.",
      ],
      faqs: [
        {
          q: "What should a logo design brief include?",
          a: "The business name, what it does, who its customers are, the feel it wants, examples it likes and every place the logo will be used. Deadlines and existing brand colours help too.",
        },
        {
          q: "Why ask where the logo will be used?",
          a: "A logo that works on a website may fail as a tiny app icon or in one colour on packaging. Knowing the uses early shapes the design.",
        },
        {
          q: "Should I ask clients for reference logos?",
          a: "Yes. References are faster than descriptions, and asking what they like about each one tells you more than the images alone.",
        },
        {
          q: "Can I use this form for a full brand identity project?",
          a: "Yes. Copy it with Use this template and add questions about typography, tone of voice or brand guidelines.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "taxi-booking-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["operations"],
    searchName: "Taxi booking form",
    title: "Taxi booking",
    icon: "Car",
    metaDescription:
      "Take taxi bookings with pickup, destination, time and passenger details. Airport runs ask for the flight number, and return trips get their own pickup time.",
    description: "Take a trip request with everything a dispatcher needs to send the right car.",
    blurb:
      "Pickup and drop-off first, with an option to share the passenger's current location, then when, how many and what kind of vehicle. Airport pickups are asked for the flight number so the driver can track delays, and anyone booking a return trip gives the return time in the same conversation.",
    tags: ["taxi booking", "cab booking", "ride booking", "airport transfer", "car service booking"],
    greeting: "Where are you headed? Let's get your ride booked.",
    questions: [
      {
        ref: "passenger",
        type: "contact_info",
        title: "Your name and a number the driver can call",
        required: true,
        fields: ["first_name", "last_name", "phone", "email"],
      },
      {
        ref: "pickup",
        type: "address",
        title: "Where should we pick you up?",
        required: true,
        fields: ["street", "city", "postal"],
        location: "optional",
      },
      { ref: "airport", type: "yes_no", title: "Is the pickup at an airport?", required: true },
      {
        ref: "flight",
        type: "short_text",
        title: "What is your flight number?",
        description: "The driver will check arrival times, so a delay won't cost you the ride.",
        required: true,
        maxLength: 20,
      },
      {
        ref: "destination",
        type: "address",
        title: "Where are you going?",
        required: true,
        fields: ["street", "city", "postal"],
      },
      {
        ref: "timing",
        type: "single_select",
        title: "When do you need the car?",
        required: true,
        options: [{ label: "As soon as possible" }, { label: "At a later time" }],
      },
      {
        ref: "pickup_time",
        type: "date",
        title: "What date and time should the driver arrive?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 15,
        timeMin: "00:00",
        timeMax: "23:45",
      },
      {
        ref: "passengers",
        type: "number",
        title: "How many passengers?",
        required: true,
        min: 1,
        max: 16,
        integerOnly: true,
      },
      {
        ref: "luggage",
        type: "single_select",
        title: "How much luggage?",
        required: true,
        options: [
          { label: "None or hand luggage only" },
          { label: "One or two suitcases" },
          { label: "Three or more suitcases" },
          { label: "Bulky items, like a bike or skis" },
        ],
      },
      {
        ref: "vehicle_needs",
        type: "multi_select",
        title: "Do you need any of these?",
        required: false,
        minSelections: 0,
        maxSelections: 5,
        options: [
          { label: "Wheelchair accessible vehicle" },
          { label: "Child or booster seat" },
          { label: "Space for a pet" },
          { label: "A larger car or van" },
        ],
      },
      { ref: "return_trip", type: "yes_no", title: "Would you like to book a return trip too?", required: true },
      {
        ref: "return_time",
        type: "date",
        title: "When should we pick you up for the return?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 15,
        timeMin: "00:00",
        timeMax: "23:45",
      },
      {
        ref: "pay_method",
        type: "single_select",
        title: "How will you pay the driver?",
        required: true,
        options: [{ label: "Card" }, { label: "Cash" }, { label: "Company account" }],
      },
      {
        ref: "driver_notes",
        type: "long_text",
        title: "Anything the driver should know?",
        description: "Gate codes, which entrance, or where you'll be waiting.",
        required: false,
        maxLength: 500,
      },
    ],
    branches: [
      { when: "airport", is: true, then: "flight" },
      { when: "airport", is: false, then: "destination" },
      { when: "timing", is: "As soon as possible", then: "passengers" },
      { when: "timing", is: "At a later time", then: "pickup_time" },
      { when: "return_trip", is: true, then: "return_time" },
      { when: "return_trip", is: false, then: "pay_method" },
    ],
    ending: {
      title: "Booking request received 🚕",
      body: "We'll confirm your driver and fare by text or email. For a pickup in the next hour, please also call us.",
    },
    guide: {
      questionsToConsider: [
        "How far ahead do you accept bookings, and do you take same-day requests through the form?",
        "Which vehicle types can you actually send?",
        "How do you confirm a booking back to the passenger, and how fast?",
        "Do you serve airports often enough to keep the flight question?",
      ],
      howToUseResponses:
        "Check new bookings often, and treat as-soon-as-possible requests as urgent: a form is slower than a phone call, so call the passenger back to confirm. For scheduled trips, confirm the driver and fare well before the pickup time. Look at the flight numbers on airport runs on the day, and export the bookings to CSV at the end of each week to see your busiest routes and times.",
      customizeSteps: [
        "Edit the vehicle options and payment methods to match your fleet and how you take payment.",
        "Put your phone number in the ending, so urgent passengers know to call as well.",
        "Share the link on your website, business listing and social profiles, or embed it on your booking page.",
      ],
      faqs: [
        {
          q: "What information does a taxi booking form need?",
          a: "The passenger's name and phone number, pickup and drop-off addresses, the pickup time, how many people and how much luggage. Airport pickups also need a flight number.",
        },
        {
          q: "Is a form confirmation the same as a confirmed booking?",
          a: "No. Submitting the form sends a request; you still confirm the driver and fare. Say this in the ending so passengers wait for your confirmation.",
        },
        {
          q: "Why ask for the flight number?",
          a: "It lets the driver check the arrival time and adjust for delays, so the passenger isn't left waiting and the driver isn't sent too early.",
        },
        {
          q: "Can passengers share their current location?",
          a: "Yes. The pickup question offers a button to share their location, which helps when they don't know the exact address.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "transportation-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["operations"],
    searchName: "Transportation request form",
    title: "Transportation request",
    icon: "Truck",
    metaDescription:
      "Collect transport requests for people or goods: route, schedule, load and site access. Passenger trips and deliveries each get the follow-ups they need.",
    description: "Request transport for a group or a load, with the details a coordinator needs to plan it.",
    blurb:
      "The form first asks whether people or goods are moving. Passenger trips cover group size, accessibility and luggage; goods cover what the load is, its size and weight and any special handling. Both then share the route, timing, return trip and site access, so the coordinator can book the right vehicle first time.",
    tags: ["transportation request", "transport booking", "vehicle request", "delivery request", "logistics"],
    greeting: "Need transport arranged? Tell us what's moving and we'll plan the rest.",
    questions: [
      {
        ref: "requester",
        type: "contact_info",
        title: "Who is making the request?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "department",
        type: "short_text",
        title: "Which team, department or organisation is it for?",
        required: true,
        maxLength: 150,
      },
      {
        ref: "moving",
        type: "single_select",
        title: "What needs moving?",
        required: true,
        options: [{ label: "People" }, { label: "Goods or equipment" }],
      },

      // People
      {
        ref: "passengers",
        type: "number",
        title: "How many people are travelling?",
        required: true,
        min: 1,
        max: 500,
        integerOnly: true,
      },
      {
        ref: "accessibility",
        type: "yes_no",
        title: "Does anyone need step-free access or help getting on board?",
        required: true,
      },
      {
        ref: "passenger_luggage",
        type: "short_text",
        title: "Will they bring luggage or equipment? If so, roughly how much?",
        required: false,
        maxLength: 200,
      },

      // Goods
      {
        ref: "goods",
        type: "long_text",
        title: "What is being moved?",
        description: "For example, 20 boxes of printed materials, or two display stands.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "load_size",
        type: "single_select",
        title: "How big is the load?",
        required: true,
        options: [
          { label: "Fits in a car" },
          { label: "Needs a van" },
          { label: "Needs a truck or pallet transport" },
          { label: "Not sure" },
        ],
      },
      {
        ref: "weight",
        type: "number",
        title: "Roughly how much does it weigh, in kilograms?",
        required: false,
        min: 0,
      },
      {
        ref: "handling",
        type: "multi_select",
        title: "Does any of it need special handling?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        options: [
          { label: "Fragile" },
          { label: "Temperature controlled" },
          { label: "Hazardous materials" },
          { label: "Oversized or awkward shape" },
          { label: "None of these" },
        ],
      },

      // Everyone
      {
        ref: "from",
        type: "address",
        title: "Where does the trip start?",
        required: true,
        fields: ["street", "city", "postal"],
      },
      {
        ref: "to",
        type: "address",
        title: "Where does it end?",
        required: true,
        fields: ["street", "city", "postal"],
      },
      {
        ref: "departure",
        type: "date",
        title: "When should it leave?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 15,
        timeMin: "00:00",
        timeMax: "23:45",
      },
      { ref: "return_needed", type: "yes_no", title: "Is a return trip needed?", required: true },
      {
        ref: "return_time",
        type: "date",
        title: "When should the return trip leave?",
        required: true,
        disablePast: true,
        includeTime: true,
        timeStepMinutes: 15,
        timeMin: "00:00",
        timeMax: "23:45",
      },
      {
        ref: "site_access",
        type: "long_text",
        title: "Anything the driver should know about parking, loading or access?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "cost_code",
        type: "short_text",
        title: "Which budget or cost code should this be charged to?",
        required: false,
        maxLength: 60,
      },
    ],
    branches: [
      { when: "moving", is: "People", then: "passengers" },
      { when: "moving", is: "Goods or equipment", then: "goods" },
      { when: "passenger_luggage", always: true, then: "from" },
      { when: "return_needed", is: true, then: "return_time" },
      { when: "return_needed", is: false, then: "site_access" },
    ],
    ending: {
      title: "Request received",
      body: "The transport coordinator will confirm the vehicle and times, or come back to you with questions.",
    },
    guide: {
      questionsToConsider: [
        "How much notice do you need for a van or a truck compared with a car?",
        "Do you move hazardous or temperature-sensitive goods at all, or should the form rule them out?",
        "Does every request need a cost code, or only some departments?",
        "Who approves transport spending, and should the form ask for their name?",
      ],
      howToUseResponses:
        "Sort requests by departure time and check the load size and handling answers first, since they decide which vehicle or supplier you need. Call the requester when the load size is marked not sure or hazardous materials are involved. Grouping requests by route in an exported CSV shows trips that could share a vehicle, which is often the easiest saving.",
      customizeSteps: [
        "Edit the load sizes and handling options to match the vehicles and suppliers you use.",
        "Make the cost code question required if finance needs it on every trip.",
        "Share the link on your intranet or operations page, and ask teams to use it instead of emailing the coordinator.",
      ],
      faqs: [
        {
          q: "What should a transportation request form include?",
          a: "Who is asking, what or who is moving, the pickup and drop-off points, the date and time, and anything that affects the vehicle choice, such as group size, load size or accessibility.",
        },
        {
          q: "Can one form handle both passengers and goods?",
          a: "Yes. This one asks which it is first and then shows only the questions that apply, so a group booking never sees questions about pallets.",
        },
        {
          q: "How far ahead should transport be requested?",
          a: "It depends on your vehicles and suppliers. State your own lead time in the greeting so people plan accordingly.",
        },
        {
          q: "Can I add an approval step?",
          a: "You can add a question naming the approver, and read or export requests from the dashboard to pass on. Copy the form with Use this template to add it.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "work-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["operations"],
    searchName: "Work request form",
    title: "Work request",
    icon: "Wrench",
    metaDescription:
      "Receive work requests in one place: what needs doing, why it matters and when. Broken things get a follow-up, and requests stopping work get an urgent ending.",
    description: "A single intake for jobs, fixes and changes, with enough detail to prioritise them.",
    blurb:
      "After a one-line summary and the details, it asks whether something is broken, needs changing or is new, and anyone reporting a fault is asked when it started and whether there's a workaround. The last question asks whether anyone is unable to work until it's done, and those requests get their own ending so the requester knows it is being treated as urgent.",
    tags: ["work request", "job request", "work order", "task request", "maintenance request"],
    greeting: "Need something done? Tell us what and why, and we'll pick it up.",
    questions: [
      {
        ref: "requester",
        type: "contact_info",
        title: "Who is making the request?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "team",
        type: "short_text",
        title: "Which team or location are you in?",
        required: true,
        maxLength: 150,
      },
      { ref: "summary", type: "short_text", title: "In one line, what needs doing?", required: true, maxLength: 200 },
      {
        ref: "details",
        type: "long_text",
        title: "Give us the details",
        description: "Where it is, what you expected, and anything you've already tried.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "kind",
        type: "single_select",
        title: "What kind of request is it?",
        required: true,
        options: [
          { label: "Something is broken or not working" },
          { label: "A change to something that exists" },
          { label: "Something new" },
          { label: "A question or advice" },
        ],
      },

      // Faults
      {
        ref: "broken_since",
        type: "date",
        title: "When did you first notice it?",
        required: false,
      },
      {
        ref: "workaround",
        type: "yes_no",
        title: "Is there a workaround in the meantime?",
        required: true,
      },

      // Everyone
      {
        ref: "why",
        type: "long_text",
        title: "What happens if this isn't done?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "impact",
        type: "single_select",
        title: "Who does it affect?",
        required: true,
        options: [{ label: "Just me" }, { label: "My team" }, { label: "Several teams" }, { label: "Customers" }],
      },
      { ref: "needed_by", type: "date", title: "When do you need it done by?", required: false, disablePast: true },
      {
        ref: "files",
        type: "file_upload",
        title: "Photos, screenshots or documents that help explain it",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 5,
        maxSizeMB: 10,
      },
      {
        ref: "work_stopped",
        type: "yes_no",
        title: "Is anyone unable to work until this is done?",
        required: true,
      },
    ],
    branches: [
      { when: "kind", is: "Something is broken or not working", then: "broken_since" },
      { when: "kind", is: "A change to something that exists", then: "why" },
      { when: "kind", is: "Something new", then: "why" },
      { when: "kind", is: "A question or advice", then: "why" },
      { when: "work_stopped", is: true, then: "end_urgent" },
      { when: "work_stopped", is: false, then: "end_thanks" },
    ],
    endings: [
      {
        ref: "end_urgent",
        title: "Marked urgent",
        body: "We'll look at this first and get in touch today. If it gets worse in the meantime, contact the team directly.",
      },
    ],
    ending: {
      title: "Request received",
      body: "We'll review it, set a priority and let you know who's picking it up.",
    },
    guide: {
      questionsToConsider: [
        "Which kinds of work does your team take on, and where should other requests go?",
        "What counts as urgent for you, and who is on hand to respond to it?",
        "Do requests need a manager's approval before work starts?",
        "Would a location or asset question help your team find the problem faster?",
      ],
      howToUseResponses:
        "Check the urgent requests first and reply the same day, even if only to say who has it. Triage the rest weekly using the impact and deadline answers: a fault affecting customers outranks a new idea for one person. Export the responses to CSV each month and count requests by kind, since a steady stream of the same fault is a sign to fix the cause rather than the symptom.",
      customizeSteps: [
        "Change the team question to a dropdown of your departments or sites if you want cleaner reporting.",
        "Put how to reach the team directly in the urgent ending, so people know what to do if things get worse.",
        "Share the link wherever requests used to arrive, such as your intranet or team chat, and reply to ad hoc asks with it.",
      ],
      faqs: [
        {
          q: "What should a work request form include?",
          a: "Who is asking, what needs doing, why it matters, who it affects and when it is needed. A photo or screenshot often saves a follow-up question.",
        },
        {
          q: "Is a work request the same as a work order?",
          a: "Not quite. A work request is someone asking for a job; a work order is the job once it has been approved and assigned. Many teams turn requests into work orders after triage.",
        },
        {
          q: "How do I handle urgent work requests?",
          a: "This form asks whether anyone is unable to work, and sends those requests to a separate ending that says they will be handled first. Make sure someone checks for them daily.",
        },
        {
          q: "Can I add different questions for maintenance or IT work?",
          a: "Yes. Copy it with Use this template and add request types, each with its own follow-up questions through branching.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "software-development-request-form",
    type: "form",
    category: "request",
    goals: [],
    roles: ["product-research", "operations"],
    searchName: "Software development request form",
    title: "Software development request",
    icon: "Code",
    metaDescription:
      "Collect software requests that start with the problem: who it is for, what it must do, constraints and deadlines. Gives developers enough to estimate the work.",
    description: "Take requests for new tools and features, starting from the problem rather than the solution.",
    blurb:
      "Asks the questions a developer would ask before estimating: what problem this solves, for whom, how it is handled today and what the finished thing must do. Changes to existing systems name the system, and only requests with a real deadline are asked for the date and what it depends on.",
    tags: ["software development request", "development request", "app development request", "IT project request", "requirements gathering"],
    greeting: "Have something you'd like built or changed? Start with the problem and we'll work out the solution together.",
    questions: [
      {
        ref: "requester",
        type: "contact_info",
        title: "Who is making the request?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      { ref: "team", type: "short_text", title: "Which team or department are you in?", required: true, maxLength: 150 },
      {
        ref: "kind",
        type: "single_select",
        title: "What kind of request is this?",
        required: true,
        options: [
          { label: "A new tool or app" },
          { label: "A new feature in an existing system" },
          { label: "A change to how something works" },
          { label: "Connecting two systems" },
          { label: "A report or data export" },
        ],
      },
      {
        ref: "existing_system",
        type: "short_text",
        title: "Which existing system or systems does it involve?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "problem",
        type: "long_text",
        title: "What problem are you trying to solve?",
        description: "Describe the problem, not the solution. We may find an easier way to fix it.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "today",
        type: "long_text",
        title: "How is it handled today?",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "users",
        type: "multi_select",
        title: "Who will use it?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        options: [{ label: "People on my team" }, { label: "Other staff" }, { label: "Customers" }, { label: "Partners or suppliers" }],
      },
      {
        ref: "user_count",
        type: "dropdown",
        title: "Roughly how many people will use it?",
        required: true,
        options: [{ label: "Fewer than 10" }, { label: "10 to 100" }, { label: "100 to 1,000" }, { label: "More than 1,000" }],
      },
      {
        ref: "must_do",
        type: "long_text",
        title: "What must it do for you to call it done?",
        description: "List the essentials. Nice-to-haves come next.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "nice_to_have",
        type: "long_text",
        title: "Anything that would be nice but isn't essential?",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "constraints",
        type: "multi_select",
        title: "Do any of these apply?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        options: [
          { label: "It handles personal or sensitive data" },
          { label: "It must work on phones" },
          { label: "It has to meet regulatory or compliance rules" },
          { label: "It must connect to an outside system" },
          { label: "None of these" },
        ],
      },
      {
        ref: "value",
        type: "opinion_scale",
        title: "How much difference would this make to your team's work?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "A small convenience",
        labelHigh: "It changes how we work",
      },
      { ref: "has_deadline", type: "yes_no", title: "Is there a date it has to be live by?", required: true },
      {
        ref: "deadline",
        type: "date",
        title: "What is the date?",
        required: true,
        disablePast: true,
      },
      {
        ref: "deadline_reason",
        type: "short_text",
        title: "What depends on that date?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "attachments",
        type: "file_upload",
        title: "Sketches, screenshots or example files",
        description: "Optional, but a rough drawing of a screen is worth a page of description.",
        required: false,
        accept: ["image/*", "application/pdf", ".csv", ".xlsx"],
        maxFiles: 5,
        maxSizeMB: 10,
      },
    ],
    branches: [
      { when: "kind", is: "A new tool or app", then: "problem" },
      { when: "kind", is: "A new feature in an existing system", then: "existing_system" },
      { when: "kind", is: "A change to how something works", then: "existing_system" },
      { when: "kind", is: "Connecting two systems", then: "existing_system" },
      { when: "kind", is: "A report or data export", then: "existing_system" },
      { when: "has_deadline", is: true, then: "deadline" },
      { when: "has_deadline", is: false, then: "attachments" },
    ],
    ending: {
      title: "Request received",
      body: "We'll read it, ask any questions we have and come back with an estimate or a next step.",
    },
    guide: {
      questionsToConsider: [
        "What size of request should go through this form, and what is small enough to just ask for?",
        "Which constraints matter most in your organisation, such as data protection or accessibility?",
        "Who decides which requests are built, and how often do they meet?",
        "Should the form ask for a budget holder or sponsor?",
      ],
      howToUseResponses:
        "Read the problem and the current workaround before the proposed solution, because the right fix is often smaller than the request. Follow up with the requester to turn the must-have list into acceptance criteria before estimating. Score requests by the difference they would make against the number of users and any fixed deadline, and export the list to CSV to review it with whoever sets priorities.",
      customizeSteps: [
        "Replace the constraints list with the checks your team has to make, such as security review or accessibility.",
        "Name your internal systems in a dropdown if requests always touch the same few.",
        "Share the link where requests currently arrive, and add your review cadence to the ending so requesters know when to expect an answer.",
      ],
      faqs: [
        {
          q: "What should a software development request include?",
          a: "The problem, who has it, how it is handled today, what the solution must do and any constraints or deadlines. That is enough for a developer to ask sensible questions and give a rough estimate.",
        },
        {
          q: "Why ask for the problem instead of the solution?",
          a: "People often ask for the first fix they thought of. Knowing the underlying problem lets the team suggest something simpler, or something that already exists.",
        },
        {
          q: "Is this the same as a feature request form?",
          a: "It overlaps. A feature request usually comes from customers about a product; this form is for internal teams asking for tools, changes or integrations, and gathers more detail for estimating.",
        },
        {
          q: "Can I add technical questions?",
          a: "Yes. Copy it with Use this template and add questions about platforms, data sources or hosting. You can also branch so only technical requesters see them.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "feature-request",
    type: "form",
    category: "request",
    goals: ["collect-feedback"],
    roles: ["product-research", "customer-success"],
    searchName: "Feature request form",
    title: "Feature request",
    icon: "Lightbulb",
    metaDescription:
      "Capture the problem behind each feature request, not just the idea. Users who are blocked right now are routed to a priority follow-up and a same-day reply.",
    description: "Capture the problem behind the request, not just the request.",
    blurb:
      "People ask for solutions; roadmaps need problems. This asks what they are trying to do and how they work around it today, and when someone says they are blocked right now, it takes that seriously: it asks what they can't do and where to reach them, and ends by promising a reply that day.",
    tags: ["feature request", "product feedback", "roadmap", "user ideas", "feature request form"],
    greeting: "Got an idea? Tell us what you're trying to do and we'll take it from there.",
    questions: [
      {
        ref: "request",
        type: "short_text",
        title: "In one line, what would you like to be able to do?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "problem",
        type: "long_text",
        title: "What are you trying to accomplish when you need it?",
        description: "The goal behind the request helps us more than a specific design.",
        required: true,
        maxLength: 1200,
      },
      { ref: "workaround", type: "long_text", title: "How do you handle it today?", required: false, maxLength: 800 },
      {
        ref: "area",
        type: "single_select",
        title: "Which part of the product is this about?",
        required: true,
        allowOther: true,
        options: [
          { label: "Building and editing" },
          { label: "Sharing and publishing" },
          { label: "Results and reporting" },
          { label: "Connecting to other tools" },
          { label: "Billing and admin" },
        ],
      },
      {
        ref: "mockup",
        type: "file_upload",
        title: "A screenshot or sketch, if it helps explain",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 3,
        maxSizeMB: 10,
      },
      {
        ref: "importance",
        type: "single_select",
        title: "How much would this change your day?",
        required: true,
        options: [
          { label: "It's blocking me right now" },
          { label: "It would save me real time" },
          { label: "It would be nice to have" },
        ],
      },

      // Blocked right now
      { ref: "blocking_since", type: "date", title: "When did it start blocking you?", required: false },
      {
        ref: "blocking_impact",
        type: "long_text",
        title: "What can't you do until this exists?",
        required: true,
        maxLength: 800,
      },
      { ref: "blocking_email", type: "email", title: "Where can we reach you today?", required: true },

      // Everyone else
      {
        ref: "how_often",
        type: "single_select",
        title: "How often would you use it?",
        required: false,
        options: [{ label: "Daily" }, { label: "Weekly" }, { label: "Monthly" }, { label: "Now and then" }],
      },
      {
        ref: "who_else",
        type: "single_select",
        title: "Who else on your side would use it?",
        required: false,
        options: [{ label: "Just me" }, { label: "A few people on my team" }, { label: "Most of my team or company" }],
      },
      { ref: "email", type: "email", title: "Where can we reach you if we build it?", required: false },
    ],
    branches: [
      { when: "importance", is: "It's blocking me right now", then: "blocking_since" },
      { when: "importance", is: "It would save me real time", then: "how_often" },
      { when: "importance", is: "It would be nice to have", then: "how_often" },
      { when: "blocking_email", always: true, then: "end_urgent" },
    ],
    endings: [
      {
        ref: "end_urgent",
        title: "Flagged as blocking 🚧",
        body: "Someone will reply today, often with a workaround before the fix exists.",
      },
    ],
    ending: { title: "Logged 💡", body: "We read every one of these. If you left an email, we'll tell you when it ships." },
    guide: {
      questionsToConsider: [
        "Which product areas should people choose from, and do they match how your team is organised?",
        "Who replies to blocked users, and can they really do it the same day?",
        "Do you want to hear from everyone, or only from signed-in customers?",
        "Will you tell people when their request ships, and how?",
      ],
      howToUseResponses:
        "Answer the blocked requests first, since a workaround often keeps a customer who was about to leave. For everything else, group requests by the problem they describe rather than the feature they name: five different asks can share one cause. Export the responses to CSV and count requests by area and how often people would use them, then email the people who left an address when something ships.",
      customizeSteps: [
        "Rename the product areas to the parts of your product people actually talk about.",
        "Edit the urgent ending to say who will reply and through which channel.",
        "Link the form from your help menu, changelog or in-app feedback button, or embed it on your roadmap page.",
      ],
      faqs: [
        {
          q: "What should a feature request form ask?",
          a: "What the person wants to do, the problem behind it, how they manage today and how much it matters. The problem is the most useful part, because it lets you design the right solution.",
        },
        {
          q: "How do I prioritise feature requests?",
          a: "Weigh how many people share the underlying problem, how often they hit it and how badly it blocks them. This form asks for each of those, so you can sort by them after exporting.",
        },
        {
          q: "Should I reply to every feature request?",
          a: "Reply quickly to anyone who is blocked, and let everyone else know when something they asked for ships. A short acknowledgement is better than silence.",
        },
        {
          q: "Can I embed a feature request form in my app?",
          a: "Yes. Share it as a link from your help menu or embed it on a page on your site after copying it with Use this template.",
        },
      ],
    },
  }),
];
