/**
 * Every named type resolves to something.
 *
 * The aliases in `src/types` read the generated spec by path and method, and a
 * renamed path or a response that lost its schema turns one into `never`
 * silently. `tsc` (run by `pnpm typecheck`) fails here instead. Imported by nothing, so it never ships.
 */
import type * as T from "./index.js";

type NotNever<X> = [X] extends [never] ? never : true;

export const resolved = {
  FormDocument: true satisfies NotNever<T.FormDocument>,
  ChatformResponse: true satisfies NotNever<T.ChatformResponse>,
  ResponseStatus: true satisfies NotNever<T.ResponseStatus>,
  ResponseSource: true satisfies NotNever<T.ResponseSource>,
  Mode: true satisfies NotNever<T.Mode>,
  Progress: true satisfies NotNever<T.Progress>,
  ResponseMetadata: true satisfies NotNever<T.ResponseMetadata>,
  NextStep: true satisfies NotNever<T.NextStep>,
  PublicBlock: true satisfies NotNever<T.PublicBlock>,
  PublicEnding: true satisfies NotNever<T.PublicEnding>,
  FormSummary: true satisfies NotNever<T.FormSummary>,
  CreatedForm: true satisfies NotNever<T.CreatedForm>,
  FormRead: true satisfies NotNever<T.FormRead>,
  FormDocumentRead: true satisfies NotNever<T.FormDocumentRead>,
  PublicFormConfig: true satisfies NotNever<T.PublicFormConfig>,
  DocSaved: true satisfies NotNever<T.DocSaved>,
  LintIssue: true satisfies NotNever<T.LintIssue>,
  Published: true satisfies NotNever<T.Published>,
  Analytics: true satisfies NotNever<T.Analytics>,
  FollowUpStats: true satisfies NotNever<T.FollowUpStats>,
  FormSettings: true satisfies NotNever<T.FormSettings>,
  FormSetting: true satisfies NotNever<T.FormSetting>,
  SettingsPatch: true satisfies NotNever<T.SettingsPatch>,
  SettingsPatched: true satisfies NotNever<T.SettingsPatched>,
  SettingChange: true satisfies NotNever<T.SettingChange>,
  Imported: true satisfies NotNever<T.Imported>,
  ImportInput: true satisfies NotNever<T.ImportInput>,
  BlockCatalogue: true satisfies NotNever<T.BlockCatalogue>,
  BlockDefinition: true satisfies NotNever<T.BlockDefinition>,
  EventCatalogue: true satisfies NotNever<T.EventCatalogue>,
  KeyIdentity: true satisfies NotNever<T.KeyIdentity>,
  SessionCreated: true satisfies NotNever<T.SessionCreated>,
  TurnResult: true satisfies NotNever<T.TurnResult>,
  TurnProcessing: true satisfies NotNever<T.TurnProcessing>,
  SessionEvent: true satisfies NotNever<T.SessionEvent>,
  SessionEvents: true satisfies NotNever<T.SessionEvents>,
  SessionState: true satisfies NotNever<T.SessionState>,
  SessionAction: true satisfies NotNever<T.SessionAction>,
  PendingVerification: true satisfies NotNever<T.PendingVerification>,
  PendingPayment: true satisfies NotNever<T.PendingPayment>,
  CheckoutLaunch: true satisfies NotNever<T.CheckoutLaunch>,
  PaymentStarted: true satisfies NotNever<T.PaymentStarted>,
  PaymentConfirmed: true satisfies NotNever<T.PaymentConfirmed>,
  RotatedToken: true satisfies NotNever<T.RotatedToken>,
  RespondentAuthResult: true satisfies NotNever<T.RespondentAuthResult>,
  EmailCodeSent: true satisfies NotNever<T.EmailCodeSent>,
  TemplateSummary: true satisfies NotNever<T.TemplateSummary>,
  TemplateDetail: true satisfies NotNever<T.TemplateDetail>,
  FormVersionSummary: true satisfies NotNever<T.FormVersionSummary>,
  FormVersion: true satisfies NotNever<T.FormVersion>,
  RestoredVersion: true satisfies NotNever<T.RestoredVersion>,
  KnowledgeIndex: true satisfies NotNever<T.KnowledgeIndex>,
  KnowledgeSource: true satisfies NotNever<T.KnowledgeSource>,
  Integration: true satisfies NotNever<T.Integration>,
  SpreadsheetIntegration: true satisfies NotNever<T.SpreadsheetIntegration>,
  AiGenerateInput: true satisfies NotNever<T.AiGenerateInput>,
  AiGenerateResult: true satisfies NotNever<T.AiGenerateResult>,
  AiEditInput: true satisfies NotNever<T.AiEditInput>,
  AiEditResult: true satisfies NotNever<T.AiEditResult>,
  AiClarifyInput: true satisfies NotNever<T.AiClarifyInput>,
  ClarifyQuestion: true satisfies NotNever<T.ClarifyQuestion>,
  WebhookEndpoint: true satisfies NotNever<T.WebhookEndpoint>,
  WebhookCreated: true satisfies NotNever<T.WebhookCreated>,
  WebhookDelivery: true satisfies NotNever<T.WebhookDelivery>,
  WebhookAttempt: true satisfies NotNever<T.WebhookAttempt>,
  WebhookQueueStats: true satisfies NotNever<T.WebhookQueueStats>,
  WebhookQueueCounts: true satisfies NotNever<T.WebhookQueueCounts>,
  PaymentAccounts: true satisfies NotNever<T.PaymentAccounts>,
  PaymentAccount: true satisfies NotNever<T.PaymentAccount>,
  FormPayments: true satisfies NotNever<T.FormPayments>,
  ExportJob: true satisfies NotNever<T.ExportJob>,
  StoredFileView: true satisfies NotNever<T.StoredFileView>,
};
