/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
export type GetHealth200 = {
  ok: boolean;
  env: string;
  db: string;
  ts: number;
};

export type PostPFormsBySlugSessionsBodyHiddenFields = {[key: string]: string};

export type PostPFormsBySlugSessionsBodyEmbed = {
  origin?: string;
};

export type PostPFormsBySlugSessionsBody = {
  turnstileToken?: string;
  hiddenFields?: PostPFormsBySlugSessionsBodyHiddenFields;
  embed?: PostPFormsBySlugSessionsBodyEmbed;
};

export type PostPFormsBySlugSessions200 = {
  sessionId: string;
  sseUrl: string;
  respondentToken: string;
};

export type PostPFormsBySlugSessions403Error = {
  code: string;
  message: string;
};

export type PostPFormsBySlugSessions403 = {
  error: PostPFormsBySlugSessions403Error;
};

export type PostPFormsBySlugSessions404Error = {
  code: string;
  message: string;
};

export type PostPFormsBySlugSessions404 = {
  error: PostPFormsBySlugSessions404Error;
};

export type PostPSessionsByIdUploadsIntentBody = {
  ref: string;
  /**
     * @minLength 1
     * @maxLength 300
     */
  filename: string;
  /**
     * @minLength 3
     * @maxLength 120
     */
  mime: string;
  /**
     * @minimum 1
     * @maximum 26214400
     */
  size: number;
};

export type PostPSessionsByIdUploadsIntent200 = {
  fileId: string;
  uploadUrl: string;
};

export type PostPSessionsByIdUploadsByFileIdConfirm200 = {
  ok: boolean;
};

export type GetApiAuthOk200 = {
  ok: boolean;
};

export type GetApiForms200Item = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
};

export type PostApiFormsBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  workspaceId?: string;
  doc?: unknown;
};

export type PostApiForms200 = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  workingSchema: unknown;
  activeVersion: number | null;
};

export type PostApiForms403Error = {
  code: string;
  message: string;
};

export type PostApiForms403 = {
  error: PostApiForms403Error;
};

export type DeleteApiFormsById200 = {
  ok: boolean;
};

export type GetApiFormsById200 = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  workingSchema: unknown;
  activeVersion: number | null;
};

export type GetApiFormsById404Error = {
  code: string;
  message: string;
};

export type GetApiFormsById404 = {
  error: GetApiFormsById404Error;
};

export type PutApiFormsByIdDocBody = {
  doc: unknown;
  theme?: unknown;
  settings?: unknown;
};

export type PutApiFormsByIdDoc200 = {
  ok: boolean;
  issues: unknown[];
};

export type PostApiFormsByIdPublish200 = {
  ok: boolean;
  version: number;
};

export type PostApiFormsByIdPublish422Error = {
  code: string;
  message: string;
};

export type PostApiFormsByIdPublish422 = {
  error: PostApiFormsByIdPublish422Error;
};

export type PostApiAiGenerateFormBody = {
  /**
     * @minLength 5
     * @maxLength 2000
     */
  prompt: string;
  /**
     * @minimum 2
     * @maximum 20
     */
  questionCount?: number;
};

export type PostApiAiGenerateForm200 = {
  doc: unknown;
  issues: unknown[];
  tokens: number;
};

export type GetApiFormsByIdSubmissionsParams = {
status?: GetApiFormsByIdSubmissionsStatus;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GetApiFormsByIdSubmissionsStatus = typeof GetApiFormsByIdSubmissionsStatus[keyof typeof GetApiFormsByIdSubmissionsStatus];


export const GetApiFormsByIdSubmissionsStatus = {
  all: 'all',
  completed: 'completed',
  abandoned: 'abandoned',
  in_progress: 'in_progress',
} as const;

export type GetApiFormsByIdSubmissions200ItemAnswersItem = {
  blockRef: string;
  blockType: string;
  value: unknown;
};

export type GetApiFormsByIdSubmissions200ItemTranscriptItem = {
  role: string;
  content: string;
  createdAt: number;
};

export type GetApiFormsByIdSubmissions200Item = {
  id: string;
  status: string;
  startedAt: number;
  completedAt: number | null;
  durationMs: number | null;
  answers: GetApiFormsByIdSubmissions200ItemAnswersItem[];
  transcript: GetApiFormsByIdSubmissions200ItemTranscriptItem[];
};

export type GetApiFormsByIdAnalytics200PerBlockItem = {
  blockRef: string;
  blockType: string;
  title: string;
  answered: number;
  answerRate: number;
};

export type GetApiFormsByIdAnalytics200 = {
  views: number;
  starts: number;
  completed: number;
  abandoned: number;
  completionRate: number;
  avgDurationMs: number | null;
  perBlock: GetApiFormsByIdAnalytics200PerBlockItem[];
};

export type GetV1Forms200Item = {
  id: string;
  title: string;
  slug: string;
};

export type GetV1FormsById404Error = {
  code: string;
  message: string;
};

export type GetV1FormsById404 = {
  error: GetV1FormsById404Error;
};

export type PostV1FormsByIdChatSessionsBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdChatSessionsBody = {
  externalId?: string;
  hiddenFields?: PostV1FormsByIdChatSessionsBodyHiddenFields;
};

export type PostV1FormsByIdChatSessions200 = {
  sessionId: string;
  greeting: string | null;
  firstQuestion: unknown | null;
};

export type PostV1ChatSessionsBySidMessagesBody = {
  type: 'text';
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
} | {
  type: 'structured';
  ref: string;
  value: unknown;
};

export type GetApiKeys200Item = {
  id: string;
  name: string | null;
  start: string | null;
  enabled: boolean;
  lastUsedAt: number | null;
  createdAt: number;
};

export type PostApiKeysBody = {
  /**
     * @minLength 1
     * @maxLength 100
     */
  name?: string;
};

export type PostApiKeys200 = {
  id: string;
  name: string | null;
  start: string | null;
  enabled: boolean;
  lastUsedAt: number | null;
  createdAt: number;
  key: string;
};

export type DeleteApiKeysById200 = {
  ok: boolean;
};

export type GetApiWebhooks200Item = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  createdAt: number;
};

export type PostApiWebhooksBodyEventsItem = typeof PostApiWebhooksBodyEventsItem[keyof typeof PostApiWebhooksBodyEventsItem];


export const PostApiWebhooksBodyEventsItem = {
  submissioncompleted: 'submission.completed',
  submissionabandoned: 'submission.abandoned',
  sessionstarted: 'session.started',
  formpublished: 'form.published',
} as const;

export type PostApiWebhooksBody = {
  url: string;
  /** @minItems 1 */
  events: PostApiWebhooksBodyEventsItem[];
  formId?: string | null;
};

export type PostApiWebhooks200 = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  createdAt: number;
  secret: string;
};

export type DeleteApiWebhooksById200 = {
  ok: boolean;
};

export type PostApiWebhooksByIdTest200 = {
  ok: boolean;
  signature: string;
};

export type GetApiBillingUsage200Limits = {[key: string]: number};

export type GetApiBillingUsage200Usage = {[key: string]: number};

export type GetApiBillingUsage200 = {
  plan: string;
  planId: string;
  status: string;
  limits: GetApiBillingUsage200Limits;
  usage: GetApiBillingUsage200Usage;
};

export type PostApiBillingCheckoutBodyPlanId = typeof PostApiBillingCheckoutBodyPlanId[keyof typeof PostApiBillingCheckoutBodyPlanId];


export const PostApiBillingCheckoutBodyPlanId = {
  pro: 'pro',
  team: 'team',
} as const;

export type PostApiBillingCheckoutBodyCycle = typeof PostApiBillingCheckoutBodyCycle[keyof typeof PostApiBillingCheckoutBodyCycle];


export const PostApiBillingCheckoutBodyCycle = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type PostApiBillingCheckoutBody = {
  planId: PostApiBillingCheckoutBodyPlanId;
  cycle?: PostApiBillingCheckoutBodyCycle;
};

export type PostApiBillingCheckout200 = {
  url: string;
};

