/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
export type GetApiBillingPlans200PlansItemLimits = {[key: string]: number | null};

export type GetApiBillingPlans200PlansItem = {
  id: string;
  name: string;
  tagline: string;
  priceMonthlyCents: number;
  priceYearlyCents: number;
  priceYearlyPerMonthCents: number;
  yearlySavingPercent: number;
  seatPriceCents: number;
  currency: string;
  features: string[];
  limits: GetApiBillingPlans200PlansItemLimits;
  checkoutReady: boolean;
};

export type GetApiBillingPlans200Features = {[key: string]: {
  label: string;
  blurb: string;
  minPlan: string;
  soon: boolean;
}};

export type GetApiBillingPlans200Limits = {[key: string]: {
  label: string;
  unit: string;
  mode: string;
}};

export type GetApiBillingPlans200 = {
  plans: GetApiBillingPlans200PlansItem[];
  features: GetApiBillingPlans200Features;
  limits: GetApiBillingPlans200Limits;
};

export type GetHealth200 = {
  ok: boolean;
  env: string;
  db: string;
  ts: number;
};

export type GetPFormsBySlugConfig404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetPFormsBySlugConfig404Error = {
  code: string;
  message: string;
  issues?: GetPFormsBySlugConfig404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetPFormsBySlugConfig404 = {
  error: GetPFormsBySlugConfig404Error;
};

export type PostPFormsBySlugSessionsBodyHiddenFields = {[key: string]: string};

export type PostPFormsBySlugSessionsBodyEmbed = {
  origin?: string;
};

export type PostPFormsBySlugSessionsBody = {
  turnstileToken?: string;
  /** @maxLength 200 */
  password?: string;
  hiddenFields?: PostPFormsBySlugSessionsBodyHiddenFields;
  embed?: PostPFormsBySlugSessionsBodyEmbed;
};

export type PostPFormsBySlugSessions200 = {
  sessionId: string;
  sseUrl: string;
  respondentToken: string;
};

export type PostPFormsBySlugSessions403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostPFormsBySlugSessions403Error = {
  code: string;
  message: string;
  issues?: PostPFormsBySlugSessions403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostPFormsBySlugSessions403 = {
  error: PostPFormsBySlugSessions403Error;
};

export type PostPFormsBySlugSessions404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostPFormsBySlugSessions404Error = {
  code: string;
  message: string;
  issues?: PostPFormsBySlugSessions404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostPFormsBySlugSessions404 = {
  error: PostPFormsBySlugSessions404Error;
};

export type PostPSessionsByIdUploadsIntentBody = {
  ref: string;
  /**
     * @minLength 1
     * @maxLength 300
     */
  filename: string;
  /**
     * @minLength 3
     * @maxLength 120
     */
  mime: string;
  /**
     * @minimum 1
     * @maximum 26214400
     */
  size: number;
};

export type PostPSessionsByIdUploadsIntent200 = {
  fileId: string;
  uploadUrl: string;
};

export type PutPSessionsByIdUploadsByFileId200 = {
  ok: boolean;
};

export type PostPSessionsByIdUploadsByFileIdConfirm200 = {
  ok: boolean;
};

export type GetApiAuthProviders200 = {
  emailPassword: boolean;
  google: boolean;
};

export type GetApiAuthOk200 = {
  ok: boolean;
};

export type GetApiForms200Item = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  questionCount: number;
  preview: string[];
};

export type PostApiFormsBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  workspaceId?: string;
  doc?: unknown;
};

export type PostApiForms200 = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  workingSchema: unknown;
  activeVersion: number | null;
};

export type PostApiForms403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiForms403Error = {
  code: string;
  message: string;
  issues?: PostApiForms403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiForms403 = {
  error: PostApiForms403Error;
};

export type DeleteApiFormsById200 = {
  ok: boolean;
};

export type GetApiFormsById200 = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  workingSchema: unknown;
  activeVersion: number | null;
};

export type GetApiFormsById404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetApiFormsById404Error = {
  code: string;
  message: string;
  issues?: GetApiFormsById404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetApiFormsById404 = {
  error: GetApiFormsById404Error;
};

export type PutApiFormsByIdDocBody = {
  doc: unknown;
  theme?: unknown;
  settings?: unknown;
};

export type PutApiFormsByIdDoc200 = {
  ok: boolean;
  issues: unknown[];
};

export type PostApiFormsByIdPublish200StrippedItem = {
  path: string;
  feature: string;
  label: string;
  requiredPlan: string;
};

export type PostApiFormsByIdPublish200 = {
  ok: boolean;
  version: number;
  stripped: PostApiFormsByIdPublish200StrippedItem[];
};

export type PostApiFormsByIdPublish402ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiFormsByIdPublish402Error = {
  code: string;
  message: string;
  issues?: PostApiFormsByIdPublish402ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiFormsByIdPublish402 = {
  error: PostApiFormsByIdPublish402Error;
};

export type PostApiFormsByIdPublish422ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiFormsByIdPublish422Error = {
  code: string;
  message: string;
  issues?: PostApiFormsByIdPublish422ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiFormsByIdPublish422 = {
  error: PostApiFormsByIdPublish422Error;
};

export type PostApiAiGenerateFormBody = {
  /**
     * @minLength 5
     * @maxLength 2000
     */
  prompt: string;
  /**
     * @minimum 2
     * @maximum 20
     */
  questionCount?: number;
};

export type PostApiAiGenerateForm200 = {
  doc: unknown;
  issues: unknown[];
  tokens: number;
};

export type PostApiAiGenerateFormStreamBody = {
  /**
     * @minLength 5
     * @maxLength 2000
     */
  prompt: string;
  /**
     * @minimum 2
     * @maximum 20
     */
  questionCount?: number;
};

export type PostApiAiEditFormBodyHistoryItemRole = typeof PostApiAiEditFormBodyHistoryItemRole[keyof typeof PostApiAiEditFormBodyHistoryItemRole];


export const PostApiAiEditFormBodyHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type PostApiAiEditFormBodyHistoryItem = {
  role: PostApiAiEditFormBodyHistoryItemRole;
  /** @maxLength 2000 */
  text: string;
};

export type PostApiAiEditFormBody = {
  formId: string;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  prompt: string;
  /** @maxItems 20 */
  history?: PostApiAiEditFormBodyHistoryItem[];
  /**
     * @minimum 1
     * @maximum 10
     */
  count?: number;
};

export type PostApiAiEditForm200 = {
  doc: unknown;
  added: number;
  removed: number;
  rules: number;
  rewired: number;
  summary: string;
  tokens: number;
};

export type PostApiAiAddBlocksBodyHistoryItemRole = typeof PostApiAiAddBlocksBodyHistoryItemRole[keyof typeof PostApiAiAddBlocksBodyHistoryItemRole];


export const PostApiAiAddBlocksBodyHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type PostApiAiAddBlocksBodyHistoryItem = {
  role: PostApiAiAddBlocksBodyHistoryItemRole;
  /** @maxLength 2000 */
  text: string;
};

export type PostApiAiAddBlocksBody = {
  formId: string;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  prompt: string;
  /** @maxItems 20 */
  history?: PostApiAiAddBlocksBodyHistoryItem[];
  /**
     * @minimum 1
     * @maximum 10
     */
  count?: number;
};

export type PostApiAiAddBlocks200 = {
  doc: unknown;
  added: number;
  removed: number;
  rules: number;
  rewired: number;
  summary: string;
  tokens: number;
};

export type GetApiFormsByIdSubmissionsParams = {
status?: GetApiFormsByIdSubmissionsStatus;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GetApiFormsByIdSubmissionsStatus = typeof GetApiFormsByIdSubmissionsStatus[keyof typeof GetApiFormsByIdSubmissionsStatus];


export const GetApiFormsByIdSubmissionsStatus = {
  all: 'all',
  completed: 'completed',
  abandoned: 'abandoned',
  in_progress: 'in_progress',
} as const;

export type GetApiFormsByIdSubmissions200ItemAnswersItem = {
  blockRef: string;
  blockType: string;
  value: unknown;
};

export type GetApiFormsByIdSubmissions200ItemTranscriptItem = {
  role: string;
  content: string;
  createdAt: number;
};

export type GetApiFormsByIdSubmissions200Item = {
  id: string;
  status: string;
  startedAt: number;
  completedAt: number | null;
  durationMs: number | null;
  answers: GetApiFormsByIdSubmissions200ItemAnswersItem[];
  transcript: GetApiFormsByIdSubmissions200ItemTranscriptItem[];
};

export type GetApiFormsByIdAnalytics200PerBlockItem = {
  blockRef: string;
  blockType: string;
  title: string;
  answered: number;
  answerRate: number;
};

export type GetApiFormsByIdAnalytics200LockedContext = {
  feature: string;
  requiredPlan: string;
  questionCount: number;
  worstBlockTitle: string | null;
  worstBlockIndex: number | null;
} | null;

export type GetApiFormsByIdAnalytics200 = {
  views: number;
  starts: number;
  completed: number;
  abandoned: number;
  completionRate: number;
  avgDurationMs: number | null;
  perBlock: GetApiFormsByIdAnalytics200PerBlockItem[];
  locked: string[];
  lockedContext: GetApiFormsByIdAnalytics200LockedContext;
};

export type PostV1FormsByIdResponsesBodyAnswers = {[key: string]: unknown};

export type PostV1FormsByIdResponsesBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdResponsesBodyMode = typeof PostV1FormsByIdResponsesBodyMode[keyof typeof PostV1FormsByIdResponsesBodyMode];


export const PostV1FormsByIdResponsesBodyMode = {
  flow: 'flow',
  free: 'free',
} as const;

export type PostV1FormsByIdResponsesBodyRespondent = {
  /** @maxLength 128 */
  ipHash?: string;
  /** @maxLength 8 */
  country?: string;
  /** @maxLength 300 */
  userAgent?: string;
};

export type PostV1FormsByIdResponsesBody = {
  answers?: PostV1FormsByIdResponsesBodyAnswers;
  hiddenFields?: PostV1FormsByIdResponsesBodyHiddenFields;
  complete?: boolean;
  mode?: PostV1FormsByIdResponsesBodyMode;
  /**
     * @minimum 300
     * @maximum 2592000
     */
  expiresIn?: number;
  respondent?: PostV1FormsByIdResponsesBodyRespondent;
};

export type GetV1FormsByIdResponsesParams = {
status?: string;
source?: string;
mode?: GetV1FormsByIdResponsesMode;
created_after?: number;
created_before?: number;
updated_since?: number;
ending_ref?: string;
/**
 * @maxLength 200
 */
q?: string;
order?: GetV1FormsByIdResponsesOrder;
include?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string;
};

export type GetV1FormsByIdResponsesMode = typeof GetV1FormsByIdResponsesMode[keyof typeof GetV1FormsByIdResponsesMode];


export const GetV1FormsByIdResponsesMode = {
  live: 'live',
  test: 'test',
  all: 'all',
} as const;

export type GetV1FormsByIdResponsesOrder = typeof GetV1FormsByIdResponsesOrder[keyof typeof GetV1FormsByIdResponsesOrder];


export const GetV1FormsByIdResponsesOrder = {
  created: 'created',
  updated: 'updated',
} as const;

export type PostV1ResponsesByIdAnswersBody = {
  /**
     * @minItems 1
     * @maxItems 200
     */
  answers: {
  ref: string;
  value: unknown;
}[];
} | {
  ref: string;
  value: unknown;
};

export type PostV1ResponsesByIdCompleteBody = {
  endingRef?: string;
};

export type PostV1ResponsesByIdAbandonBody = {
  /** @maxLength 100 */
  reason?: string;
};

export type GetV1FormsParams = {
status?: GetV1FormsStatus;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string;
};

export type GetV1FormsStatus = typeof GetV1FormsStatus[keyof typeof GetV1FormsStatus];


export const GetV1FormsStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
  all: 'all',
} as const;

export type PostV1FormsBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  doc?: unknown;
};

export type PutV1FormsByIdDocBody = {
  doc: unknown;
};

export type GetV1Webhooks200Item = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  consecutiveFailures: number;
  createdAt: number;
  secretPreview: string;
};

export type PostV1WebhooksBody = {
  /** @maxLength 2000 */
  url: string;
  /**
     * @minItems 1
     * @maxItems 20
     */
  events: string[];
  /** @maxLength 64 */
  formId?: string;
};

export type PostV1FormsByIdExportsBodyFormat = typeof PostV1FormsByIdExportsBodyFormat[keyof typeof PostV1FormsByIdExportsBodyFormat];


export const PostV1FormsByIdExportsBodyFormat = {
  csv: 'csv',
  json: 'json',
} as const;

export type PostV1FormsByIdExportsBodyMode = typeof PostV1FormsByIdExportsBodyMode[keyof typeof PostV1FormsByIdExportsBodyMode];


export const PostV1FormsByIdExportsBodyMode = {
  live: 'live',
  test: 'test',
  all: 'all',
} as const;

export type PostV1FormsByIdExportsBody = {
  format?: PostV1FormsByIdExportsBodyFormat;
  /** @maxItems 6 */
  status?: string[];
  /** @maxLength 20 */
  source?: string;
  mode?: PostV1FormsByIdExportsBodyMode;
  created_after?: number;
  created_before?: number;
};

export type PostV1FormsByIdExports202Status = typeof PostV1FormsByIdExports202Status[keyof typeof PostV1FormsByIdExports202Status];


export const PostV1FormsByIdExports202Status = {
  queued: 'queued',
  running: 'running',
  ready: 'ready',
  failed: 'failed',
} as const;

export type PostV1FormsByIdExports202Format = typeof PostV1FormsByIdExports202Format[keyof typeof PostV1FormsByIdExports202Format];


export const PostV1FormsByIdExports202Format = {
  csv: 'csv',
  json: 'json',
} as const;

export type PostV1FormsByIdExports202 = {
  id: string;
  object: 'export';
  form_id: string;
  status: PostV1FormsByIdExports202Status;
  format: PostV1FormsByIdExports202Format;
  row_count: number | null;
  bytes: number | null;
  error: string | null;
  created_at: number;
  completed_at: number | null;
  expires_at: number | null;
  download_url: string | null;
  download_expires_at: number | null;
};

export type GetV1ExportsById200Status = typeof GetV1ExportsById200Status[keyof typeof GetV1ExportsById200Status];


export const GetV1ExportsById200Status = {
  queued: 'queued',
  running: 'running',
  ready: 'ready',
  failed: 'failed',
} as const;

export type GetV1ExportsById200Format = typeof GetV1ExportsById200Format[keyof typeof GetV1ExportsById200Format];


export const GetV1ExportsById200Format = {
  csv: 'csv',
  json: 'json',
} as const;

export type GetV1ExportsById200 = {
  id: string;
  object: 'export';
  form_id: string;
  status: GetV1ExportsById200Status;
  format: GetV1ExportsById200Format;
  row_count: number | null;
  bytes: number | null;
  error: string | null;
  created_at: number;
  completed_at: number | null;
  expires_at: number | null;
  download_url: string | null;
  download_expires_at: number | null;
};

export type GetV1ExportsParams = {
form_id?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type GetV1FilesById200 = {
  id: string;
  object: 'file';
  form_id: string | null;
  response_id: string | null;
  filename: string;
  mime: string;
  size_bytes: number;
  created_at: number;
  download_url: string;
  download_expires_at: number;
};

export type PostV1SessionsBySidUploadsIntentBody = {
  ref: string;
  /**
     * @minLength 1
     * @maxLength 300
     */
  filename: string;
  /**
     * @minLength 3
     * @maxLength 120
     */
  mime: string;
  /**
     * @minimum 1
     * @maximum 26214400
     */
  size: number;
};

export type PostV1SessionsBySidUploadsIntent200 = {
  fileId: string;
  uploadUrl: string;
};

export type PutV1SessionsBySidUploadsByFileId200 = {
  ok: boolean;
};

export type PostV1SessionsBySidUploadsByFileIdConfirm200 = {
  ok: boolean;
};

export type PostV1FormsByIdSessionsBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdSessionsBodyRespondent = {
  /** @maxLength 128 */
  ipHash?: string;
  /** @maxLength 8 */
  country?: string;
  /** @maxLength 300 */
  userAgent?: string;
};

export type PostV1FormsByIdSessionsBody = {
  hiddenFields?: PostV1FormsByIdSessionsBodyHiddenFields;
  /** @maxLength 200 */
  externalId?: string;
  /**
     * @minimum 300
     * @maximum 2592000
     */
  expiresIn?: number;
  respondent?: PostV1FormsByIdSessionsBodyRespondent;
};

export type PostV1FormsByIdSessions200 = {
  sessionId: string;
  respondentToken: string;
  expiresAt: number;
  streamUrl: string;
  greeting: string | null;
  question: unknown | null;
};

export type PostV1FormsByIdChatSessionsBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdChatSessionsBodyRespondent = {
  /** @maxLength 128 */
  ipHash?: string;
  /** @maxLength 8 */
  country?: string;
  /** @maxLength 300 */
  userAgent?: string;
};

export type PostV1FormsByIdChatSessionsBody = {
  hiddenFields?: PostV1FormsByIdChatSessionsBodyHiddenFields;
  /** @maxLength 200 */
  externalId?: string;
  /**
     * @minimum 300
     * @maximum 2592000
     */
  expiresIn?: number;
  respondent?: PostV1FormsByIdChatSessionsBodyRespondent;
};

export type PostV1FormsByIdChatSessions200 = {
  sessionId: string;
  respondentToken: string;
  expiresAt: number;
  streamUrl: string;
  greeting: string | null;
  question: unknown | null;
};

export type PostV1SessionsBySidMessagesBody = {
  type: 'text';
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
} | {
  type: 'structured';
  ref: string;
  value: unknown;
};

export type PostV1SessionsBySidActionsBodyAction = typeof PostV1SessionsBySidActionsBodyAction[keyof typeof PostV1SessionsBySidActionsBodyAction];


export const PostV1SessionsBySidActionsBodyAction = {
  skip: 'skip',
  stop: 'stop',
  restart: 'restart',
  edit: 'edit',
  submit: 'submit',
} as const;

export type PostV1SessionsBySidActionsBody = {
  action: PostV1SessionsBySidActionsBodyAction;
  ref?: string;
};

export type PostV1ChatSessionsBySidMessagesBody = {
  type: 'text';
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
} | {
  type: 'structured';
  ref: string;
  value: unknown;
};

export type PostV1ChatSessionsBySidActionsBodyAction = typeof PostV1ChatSessionsBySidActionsBodyAction[keyof typeof PostV1ChatSessionsBySidActionsBodyAction];


export const PostV1ChatSessionsBySidActionsBodyAction = {
  skip: 'skip',
  stop: 'stop',
  restart: 'restart',
  edit: 'edit',
  submit: 'submit',
} as const;

export type PostV1ChatSessionsBySidActionsBody = {
  action: PostV1ChatSessionsBySidActionsBodyAction;
  ref?: string;
};

export type GetApiKeys200ItemKeyType = typeof GetApiKeys200ItemKeyType[keyof typeof GetApiKeys200ItemKeyType];


export const GetApiKeys200ItemKeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type GetApiKeys200ItemEnvironment = typeof GetApiKeys200ItemEnvironment[keyof typeof GetApiKeys200ItemEnvironment];


export const GetApiKeys200ItemEnvironment = {
  live: 'live',
  test: 'test',
} as const;

export type GetApiKeys200ItemScopes = {[key: string]: string[]};

export type GetApiKeys200Item = {
  id: string;
  name: string | null;
  keyType: GetApiKeys200ItemKeyType;
  environment: GetApiKeys200ItemEnvironment;
  start: string | null;
  enabled: boolean;
  scopes: GetApiKeys200ItemScopes;
  origins: string[];
  formIds: string[];
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  requestCount: number;
  lastUsedAt: number | null;
  expiresAt: number | null;
  createdBy: string | null;
  createdAt: number;
};

export type PostApiKeysBodyKeyType = typeof PostApiKeysBodyKeyType[keyof typeof PostApiKeysBodyKeyType];


export const PostApiKeysBodyKeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type PostApiKeysBodyScopes = {[key: string]: string[]};

export type PostApiKeysBody = {
  /**
     * @minLength 1
     * @maxLength 64
     */
  name?: string;
  keyType?: PostApiKeysBodyKeyType;
  scopes?: PostApiKeysBodyScopes;
  /**
     * @maxItems 20
     * @items.maxLength 200
     */
  origins?: string[];
  /**
     * @maxItems 50
     * @items.maxLength 64
     */
  formIds?: string[];
  /**
     * @minimum 1
     * @maximum 365
     */
  expiresInDays?: number;
  /**
     * @minimum 1
     * @maximum 10000
     */
  rateLimitMax?: number;
};

export type PostApiKeys200KeyType = typeof PostApiKeys200KeyType[keyof typeof PostApiKeys200KeyType];


export const PostApiKeys200KeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type PostApiKeys200Environment = typeof PostApiKeys200Environment[keyof typeof PostApiKeys200Environment];


export const PostApiKeys200Environment = {
  live: 'live',
  test: 'test',
} as const;

export type PostApiKeys200Scopes = {[key: string]: string[]};

export type PostApiKeys200 = {
  id: string;
  name: string | null;
  keyType: PostApiKeys200KeyType;
  environment: PostApiKeys200Environment;
  start: string | null;
  enabled: boolean;
  scopes: PostApiKeys200Scopes;
  origins: string[];
  formIds: string[];
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  requestCount: number;
  lastUsedAt: number | null;
  expiresAt: number | null;
  createdBy: string | null;
  createdAt: number;
  key: string;
};

export type PostApiKeysByIdRotateBody = {
  /**
     * @minimum 0
     * @maximum 168
     */
  graceHours?: number;
};

export type PostApiKeysByIdRotate200KeyType = typeof PostApiKeysByIdRotate200KeyType[keyof typeof PostApiKeysByIdRotate200KeyType];


export const PostApiKeysByIdRotate200KeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type PostApiKeysByIdRotate200Environment = typeof PostApiKeysByIdRotate200Environment[keyof typeof PostApiKeysByIdRotate200Environment];


export const PostApiKeysByIdRotate200Environment = {
  live: 'live',
  test: 'test',
} as const;

export type PostApiKeysByIdRotate200Scopes = {[key: string]: string[]};

export type PostApiKeysByIdRotate200 = {
  id: string;
  name: string | null;
  keyType: PostApiKeysByIdRotate200KeyType;
  environment: PostApiKeysByIdRotate200Environment;
  start: string | null;
  enabled: boolean;
  scopes: PostApiKeysByIdRotate200Scopes;
  origins: string[];
  formIds: string[];
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  requestCount: number;
  lastUsedAt: number | null;
  expiresAt: number | null;
  createdBy: string | null;
  createdAt: number;
  key: string;
  replacedKeyId: string;
  oldKeyExpiresAt: number | null;
};

export type DeleteApiKeysById200 = {
  ok: boolean;
};

export type GetApiWebhooks200Item = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  createdAt: number;
  secretPreview?: string;
};

export type PostApiWebhooksBodyEventsItem = typeof PostApiWebhooksBodyEventsItem[keyof typeof PostApiWebhooksBodyEventsItem];


export const PostApiWebhooksBodyEventsItem = {
  submissioncompleted: 'submission.completed',
  submissionabandoned: 'submission.abandoned',
  sessionstarted: 'session.started',
  formpublished: 'form.published',
} as const;

export type PostApiWebhooksBody = {
  url: string;
  /** @minItems 1 */
  events: PostApiWebhooksBodyEventsItem[];
  formId?: string | null;
};

export type PostApiWebhooks200 = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  createdAt: number;
  secretPreview?: string;
  secret: string;
};

export type DeleteApiWebhooksById200 = {
  ok: boolean;
};

export type PostApiWebhooksByIdTest200 = {
  ok: boolean;
  signature: string;
};

export type GetApiBillingEntitlements200Features = {[key: string]: boolean};

export type GetApiBillingEntitlements200Limits = {[key: string]: number | null};

export type GetApiBillingEntitlements200Usage = {[key: string]: number};

export type GetApiBillingEntitlements200Gauges = {[key: string]: number};

export type GetApiBillingEntitlements200Permissions = {[key: string]: string[]};

export type GetApiBillingEntitlements200 = {
  planId: string;
  planName: string;
  status: string;
  cycle: string | null;
  periodStart: number | null;
  periodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  inGrace: boolean;
  seats: number;
  features: GetApiBillingEntitlements200Features;
  limits: GetApiBillingEntitlements200Limits;
  usage: GetApiBillingEntitlements200Usage;
  gauges: GetApiBillingEntitlements200Gauges;
  periodResetsAt: number;
  role: string;
  roleLabel: string;
  permissions: GetApiBillingEntitlements200Permissions;
};

export type GetApiBillingUsage200Limits = {[key: string]: number | null};

export type GetApiBillingUsage200Usage = {[key: string]: number};

export type GetApiBillingUsage200 = {
  plan: string;
  planId: string;
  status: string;
  periodEnd: number | null;
  limits: GetApiBillingUsage200Limits;
  usage: GetApiBillingUsage200Usage;
};

export type PostApiBillingCheckoutBodyPlanId = typeof PostApiBillingCheckoutBodyPlanId[keyof typeof PostApiBillingCheckoutBodyPlanId];


export const PostApiBillingCheckoutBodyPlanId = {
  pro: 'pro',
  business: 'business',
} as const;

export type PostApiBillingCheckoutBodyCycle = typeof PostApiBillingCheckoutBodyCycle[keyof typeof PostApiBillingCheckoutBodyCycle];


export const PostApiBillingCheckoutBodyCycle = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type PostApiBillingCheckoutBody = {
  planId: PostApiBillingCheckoutBodyPlanId;
  cycle?: PostApiBillingCheckoutBodyCycle;
  /** @maxLength 64 */
  discountCode?: string;
};

export type PostApiBillingCheckout200 = {
  url: string;
};

export type PostApiBillingPortal200 = {
  url: string;
};

export type PostApiBillingPreviewChangeBodyPlanId = typeof PostApiBillingPreviewChangeBodyPlanId[keyof typeof PostApiBillingPreviewChangeBodyPlanId];


export const PostApiBillingPreviewChangeBodyPlanId = {
  free: 'free',
  pro: 'pro',
  business: 'business',
} as const;

export type PostApiBillingPreviewChangeBodyCycle = typeof PostApiBillingPreviewChangeBodyCycle[keyof typeof PostApiBillingPreviewChangeBodyCycle];


export const PostApiBillingPreviewChangeBodyCycle = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type PostApiBillingPreviewChangeBody = {
  planId: PostApiBillingPreviewChangeBodyPlanId;
  cycle?: PostApiBillingPreviewChangeBodyCycle;
};

export type PostApiBillingChangePlanBodyPlanId = typeof PostApiBillingChangePlanBodyPlanId[keyof typeof PostApiBillingChangePlanBodyPlanId];


export const PostApiBillingChangePlanBodyPlanId = {
  free: 'free',
  pro: 'pro',
  business: 'business',
} as const;

export type PostApiBillingChangePlanBodyCycle = typeof PostApiBillingChangePlanBodyCycle[keyof typeof PostApiBillingChangePlanBodyCycle];


export const PostApiBillingChangePlanBodyCycle = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type PostApiBillingChangePlanBody = {
  planId: PostApiBillingChangePlanBodyPlanId;
  cycle?: PostApiBillingChangePlanBodyCycle;
};

export type PostApiFormsByIdPreviewSessions200 = {
  sessionId: string;
  sseUrl: string;
  respondentToken: string;
};

export type GetApiTemplates200Item = {
  slug: string;
  title: string;
  category: string;
  description: string;
  blurb: string;
  tags: string[];
  icon: string;
  accent: string;
  blockCount: number;
  estMinutes: number;
  usageCount: number;
};

export type GetApiTemplatesBySlug200 = {
  slug: string;
  title: string;
  category: string;
  description: string;
  blurb: string;
  tags: string[];
  icon: string;
  accent: string;
  blockCount: number;
  estMinutes: number;
  usageCount: number;
  doc: unknown;
};

export type GetApiTemplatesBySlug404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetApiTemplatesBySlug404Error = {
  code: string;
  message: string;
  issues?: GetApiTemplatesBySlug404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetApiTemplatesBySlug404 = {
  error: GetApiTemplatesBySlug404Error;
};

export type PostApiTemplatesBySlugUse403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiTemplatesBySlugUse403Error = {
  code: string;
  message: string;
  issues?: PostApiTemplatesBySlugUse403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiTemplatesBySlugUse403 = {
  error: PostApiTemplatesBySlugUse403Error;
};

export type PostApiTemplatesBySlugUse404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiTemplatesBySlugUse404Error = {
  code: string;
  message: string;
  issues?: PostApiTemplatesBySlugUse404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiTemplatesBySlugUse404 = {
  error: PostApiTemplatesBySlugUse404Error;
};

export type GetApiAuditLogsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum -9007199254740991
 * @maximum 9007199254740991
 */
before?: number;
/**
 * @maxLength 80
 */
action?: string;
};

export type GetApiAuditLogs200EntriesItem = {
  id: string;
  action: string;
  actorType: string;
  actorLabel: string | null;
  resourceType: string | null;
  resourceId: string | null;
  meta: unknown | null;
  createdAt: number;
};

export type GetApiAuditLogs200 = {
  entries: GetApiAuditLogs200EntriesItem[];
  nextBefore: number | null;
};

