/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
export type GetApiBillingPlans200PlansItemLimits = {[key: string]: number | null};

export type GetApiBillingPlans200PlansItem = {
  id: string;
  name: string;
  tagline: string;
  priceMonthlyCents: number;
  priceYearlyCents: number;
  priceYearlyPerMonthCents: number;
  yearlySavingPercent: number;
  seatPriceCents: number;
  currency: string;
  features: string[];
  limits: GetApiBillingPlans200PlansItemLimits;
  checkoutReady: boolean;
};

export type GetApiBillingPlans200Features = {[key: string]: {
  label: string;
  blurb: string;
  minPlan: string;
  soon: boolean;
}};

export type GetApiBillingPlans200Limits = {[key: string]: {
  label: string;
  unit: string;
  mode: string;
}};

export type GetApiBillingPlans200 = {
  plans: GetApiBillingPlans200PlansItem[];
  features: GetApiBillingPlans200Features;
  limits: GetApiBillingPlans200Limits;
};

export type GetApiAdminMe200 = {
  email: string;
  userId: string;
};

export type GetApiAdminOverviewParams = {
range?: GetApiAdminOverviewRange;
};

export type GetApiAdminOverviewRange = typeof GetApiAdminOverviewRange[keyof typeof GetApiAdminOverviewRange];


export const GetApiAdminOverviewRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '365d': '365d',
} as const;

export type GetApiAdminOverview200Kpis = {[key: string]: {
  value: number;
  previous: number;
}};

export type GetApiAdminOverview200Series = {[key: string]: number[]};

export type GetApiAdminOverview200FunnelItem = {
  key: string;
  label: string;
  count: number;
  rate: number;
};

export type GetApiAdminOverview200PlanMixItem = {
  plan: string;
  orgs: number;
};

export type GetApiAdminOverview200CohortsItem = {
  cohort: string;
  size: number;
  retention: (number | null)[];
};

export type GetApiAdminOverview200ActionCounts = {[key: string]: number};

export type GetApiAdminOverview200 = {
  range: string;
  days: string[];
  kpis: GetApiAdminOverview200Kpis;
  series: GetApiAdminOverview200Series;
  funnel: GetApiAdminOverview200FunnelItem[];
  planMix: GetApiAdminOverview200PlanMixItem[];
  mrrSeries: number[];
  cohorts: GetApiAdminOverview200CohortsItem[];
  actionCounts: GetApiAdminOverview200ActionCounts;
  formStatsAsOf: number | null;
};

export type GetApiAdminActions200DunningItem = {[key: string]: unknown};

export type GetApiAdminActions200FailedPaymentsItem = {[key: string]: unknown};

export type GetApiAdminActions200FailingWebhooksItem = {[key: string]: unknown};

export type GetApiAdminActions200StuckBillingEventsItem = {[key: string]: unknown};

export type GetApiAdminActions200AtLimitItem = {[key: string]: unknown};

export type GetApiAdminActions200 = {
  dunning: GetApiAdminActions200DunningItem[];
  failedPayments: GetApiAdminActions200FailedPaymentsItem[];
  failingWebhooks: GetApiAdminActions200FailingWebhooksItem[];
  stuckBillingEvents: GetApiAdminActions200StuckBillingEventsItem[];
  atLimit: GetApiAdminActions200AtLimitItem[];
};

export type GetApiAdminAccountsParams = {
/**
 * @maxLength 120
 */
q?: string;
plan?: GetApiAdminAccountsPlan;
cohort?: GetApiAdminAccountsCohort;
sort?: GetApiAdminAccountsSort;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
offset?: number;
};

export type GetApiAdminAccountsPlan = typeof GetApiAdminAccountsPlan[keyof typeof GetApiAdminAccountsPlan];


export const GetApiAdminAccountsPlan = {
  free: 'free',
  pro: 'pro',
  business: 'business',
} as const;

export type GetApiAdminAccountsCohort = typeof GetApiAdminAccountsCohort[keyof typeof GetApiAdminAccountsCohort];


export const GetApiAdminAccountsCohort = {
  created_form: 'created_form',
  published: 'published',
  first_response: 'first_response',
  ten_responses: 'ten_responses',
  paid: 'paid',
  no_form: 'no_form',
  stalled: 'stalled',
} as const;

export type GetApiAdminAccountsSort = typeof GetApiAdminAccountsSort[keyof typeof GetApiAdminAccountsSort];


export const GetApiAdminAccountsSort = {
  created: 'created',
  responses: 'responses',
  forms: 'forms',
  ai: 'ai',
  active: 'active',
  mrr: 'mrr',
} as const;

export type GetApiAdminAccounts200AccountsItem = {
  id: string;
  name: string;
  slug: string;
  created_at: number;
  owner_email: string | null;
  plan: string;
  seats: number;
  forms: number;
  responses_30d: number;
  ai_tokens_30d: number;
  ai_cost_micro_30d: number;
  last_active_at: number | null;
  mrr_cents: number;
};

export type GetApiAdminAccounts200 = {
  accounts: GetApiAdminAccounts200AccountsItem[];
  total: number;
  limit: number;
  offset: number;
};

export type GetApiAdminAccountsByOrgId200Org = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200Plan = {
  id: string;
  name: string;
} | null;

export type GetApiAdminAccountsByOrgId200Limits = {[key: string]: number | null};

export type GetApiAdminAccountsByOrgId200MembersItem = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200Subscription = {[key: string]: unknown} | null;

export type GetApiAdminAccountsByOrgId200FormsItem = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200UsageItem = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200OverridesItem = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200AuditItem = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200DenialsItem = {[key: string]: unknown};

export type GetApiAdminAccountsByOrgId200 = {
  org: GetApiAdminAccountsByOrgId200Org;
  plan: GetApiAdminAccountsByOrgId200Plan;
  limits: GetApiAdminAccountsByOrgId200Limits;
  members: GetApiAdminAccountsByOrgId200MembersItem[];
  subscription: GetApiAdminAccountsByOrgId200Subscription;
  forms: GetApiAdminAccountsByOrgId200FormsItem[];
  usage: GetApiAdminAccountsByOrgId200UsageItem[];
  overrides: GetApiAdminAccountsByOrgId200OverridesItem[];
  audit: GetApiAdminAccountsByOrgId200AuditItem[];
  denials: GetApiAdminAccountsByOrgId200DenialsItem[];
};

export type GetApiAdminProductParams = {
range?: GetApiAdminProductRange;
};

export type GetApiAdminProductRange = typeof GetApiAdminProductRange[keyof typeof GetApiAdminProductRange];


export const GetApiAdminProductRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '365d': '365d',
} as const;

export type GetApiAdminProduct200BlockTypesItem = {
  key: string;
  value: number;
};

export type GetApiAdminProduct200FormSizesItem = {
  key: string;
  value: number;
};

export type GetApiAdminProduct200FormLogicItem = {
  key: string;
  value: number;
};

export type GetApiAdminProduct200CreationSourceItem = {
  key: string;
  value: number;
};

export type GetApiAdminProduct200ResponseSourceItem = {
  key: string;
  value: number;
};

export type GetApiAdminProduct200TemplatesItem = {[key: string]: unknown};

export type GetApiAdminProduct200AdoptionItem = {
  feature: string;
  orgs: number;
  share: number;
};

export type GetApiAdminProduct200TopQuestionsItem = {[key: string]: unknown};

export type GetApiAdminProduct200Totals = {
  orgs: number;
  forms: number;
  published: number;
  avgBlocks: number;
};

export type GetApiAdminProduct200 = {
  blockTypes: GetApiAdminProduct200BlockTypesItem[];
  formSizes: GetApiAdminProduct200FormSizesItem[];
  formLogic: GetApiAdminProduct200FormLogicItem[];
  creationSource: GetApiAdminProduct200CreationSourceItem[];
  responseSource: GetApiAdminProduct200ResponseSourceItem[];
  templates: GetApiAdminProduct200TemplatesItem[];
  adoption: GetApiAdminProduct200AdoptionItem[];
  topQuestions: GetApiAdminProduct200TopQuestionsItem[];
  totals: GetApiAdminProduct200Totals;
  statsAsOf: number | null;
};

export type GetApiAdminFormsParams = {
/**
 * @maxLength 120
 */
q?: string;
status?: GetApiAdminFormsStatus;
sort?: GetApiAdminFormsSort;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
offset?: number;
};

export type GetApiAdminFormsStatus = typeof GetApiAdminFormsStatus[keyof typeof GetApiAdminFormsStatus];


export const GetApiAdminFormsStatus = {
  draft: 'draft',
  published: 'published',
  closed: 'closed',
} as const;

export type GetApiAdminFormsSort = typeof GetApiAdminFormsSort[keyof typeof GetApiAdminFormsSort];


export const GetApiAdminFormsSort = {
  recent: 'recent',
  responses: 'responses',
  starts: 'starts',
  drop_off: 'drop_off',
  size: 'size',
} as const;

export type GetApiAdminForms200FormsItem = {[key: string]: unknown};

export type GetApiAdminForms200 = {
  forms: GetApiAdminForms200FormsItem[];
  total: number;
  limit: number;
  offset: number;
};

export type GetApiAdminRevenueParams = {
range?: GetApiAdminRevenueRange;
};

export type GetApiAdminRevenueRange = typeof GetApiAdminRevenueRange[keyof typeof GetApiAdminRevenueRange];


export const GetApiAdminRevenueRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '365d': '365d',
} as const;

export type GetApiAdminRevenue200MrrByPlanItem = {
  plan: string;
  orgs: number;
  mrrCents: number;
};

export type GetApiAdminRevenue200Totals = {
  mrrCents: number;
  arrCents: number;
  payingOrgs: number;
  arpaCents: number;
  trialing: number;
  atRiskCents: number;
  collectedCents: number;
  failedCents: number;
  refundedCents: number;
};

export type GetApiAdminRevenue200PaymentsSeriesItem = {
  date: string;
  succeeded: number;
  failed: number;
};

export type GetApiAdminRevenue200StatusBoardItem = {
  status: string;
  orgs: number;
  mrrCents: number;
};

export type GetApiAdminRevenue200UpgradeFunnelItem = {
  feature: string;
  orgs: number;
  denials: number;
  converted: number;
  conversion: number;
  topSurface: string | null;
};

export type GetApiAdminRevenue200CancellationsItem = {[key: string]: unknown};

export type GetApiAdminRevenue200CompedItem = {[key: string]: unknown};

export type GetApiAdminRevenue200RecentPaymentsItem = {[key: string]: unknown};

export type GetApiAdminRevenue200 = {
  days: string[];
  mrrSeries: number[];
  payingSeries: number[];
  mrrByPlan: GetApiAdminRevenue200MrrByPlanItem[];
  totals: GetApiAdminRevenue200Totals;
  paymentsSeries: GetApiAdminRevenue200PaymentsSeriesItem[];
  statusBoard: GetApiAdminRevenue200StatusBoardItem[];
  upgradeFunnel: GetApiAdminRevenue200UpgradeFunnelItem[];
  cancellations: GetApiAdminRevenue200CancellationsItem[];
  comped: GetApiAdminRevenue200CompedItem[];
  recentPayments: GetApiAdminRevenue200RecentPaymentsItem[];
};

export type GetApiAdminAiParams = {
range?: GetApiAdminAiRange;
};

export type GetApiAdminAiRange = typeof GetApiAdminAiRange[keyof typeof GetApiAdminAiRange];


export const GetApiAdminAiRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '365d': '365d',
} as const;

export type GetApiAdminAi200ByModelItem = {
  key: string;
  value: number;
};

export type GetApiAdminAi200ByKindItem = {
  key: string;
  value: number;
};

export type GetApiAdminAi200Totals = {
  costMicro: number;
  tokens: number;
  calls: number;
  errors: number;
  errorRate: number;
  costPerConversationMicro: number;
  conversations: number;
};

export type GetApiAdminAi200LatencyItem = {
  model: string;
  calls: number;
  p50: number;
  p90: number;
  errorRate: number;
};

export type GetApiAdminAi200TopSpendersItem = {[key: string]: unknown};

export type GetApiAdminAi200LossMakersItem = {[key: string]: unknown};

export type GetApiAdminAi200 = {
  days: string[];
  costSeries: number[];
  tokenSeries: number[];
  callSeries: number[];
  byModel: GetApiAdminAi200ByModelItem[];
  byKind: GetApiAdminAi200ByKindItem[];
  totals: GetApiAdminAi200Totals;
  latency: GetApiAdminAi200LatencyItem[];
  topSpenders: GetApiAdminAi200TopSpendersItem[];
  lossMakers: GetApiAdminAi200LossMakersItem[];
};

export type GetApiAdminHealthParams = {
range?: GetApiAdminHealthRange;
};

export type GetApiAdminHealthRange = typeof GetApiAdminHealthRange[keyof typeof GetApiAdminHealthRange];


export const GetApiAdminHealthRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '365d': '365d',
} as const;

export type GetApiAdminHealth200WebhooksByStatusCodeItem = {
  key: string;
  value: number;
};

export type GetApiAdminHealth200WebhooksWorstItem = {[key: string]: unknown};

export type GetApiAdminHealth200Webhooks = {
  delivered: number;
  failed: number;
  pending: number;
  successRate: number;
  endpointsFailing: number;
  byStatusCode: GetApiAdminHealth200WebhooksByStatusCodeItem[];
  worst: GetApiAdminHealth200WebhooksWorstItem[];
};

export type GetApiAdminHealth200BillingByStatusItem = {
  key: string;
  value: number;
};

export type GetApiAdminHealth200BillingStuckItem = {[key: string]: unknown};

export type GetApiAdminHealth200Billing = {
  byStatus: GetApiAdminHealth200BillingByStatusItem[];
  stuck: GetApiAdminHealth200BillingStuckItem[];
};

export type GetApiAdminHealth200IntegrationsByStatusItem = {[key: string]: unknown};

export type GetApiAdminHealth200IntegrationsFailingItem = {[key: string]: unknown};

export type GetApiAdminHealth200Integrations = {
  byStatus: GetApiAdminHealth200IntegrationsByStatusItem[];
  failing: GetApiAdminHealth200IntegrationsFailingItem[];
};

export type GetApiAdminHealth200EmailFollowupsByStatusItem = {
  key: string;
  value: number;
};

export type GetApiAdminHealth200EmailSuppressionsByReasonItem = {
  key: string;
  value: number;
};

export type GetApiAdminHealth200Email = {
  followupsByStatus: GetApiAdminHealth200EmailFollowupsByStatusItem[];
  suppressionsByReason: GetApiAdminHealth200EmailSuppressionsByReasonItem[];
  sent: number;
  complaintRate: number;
};

export type GetApiAdminHealth200ExportsItem = {
  key: string;
  value: number;
};

export type GetApiAdminHealth200SessionsByStatusItem = {
  key: string;
  value: number;
};

export type GetApiAdminHealth200Sessions = {
  byStatus: GetApiAdminHealth200SessionsByStatusItem[];
  stale: number;
};

export type GetApiAdminHealth200Storage = {
  files: number;
  bytes: number;
  rejected: number;
};

export type GetApiAdminHealth200 = {
  webhooks: GetApiAdminHealth200Webhooks;
  billing: GetApiAdminHealth200Billing;
  integrations: GetApiAdminHealth200Integrations;
  email: GetApiAdminHealth200Email;
  exports: GetApiAdminHealth200ExportsItem[];
  sessions: GetApiAdminHealth200Sessions;
  storage: GetApiAdminHealth200Storage;
};

export type GetApiAdminUsersParams = {
/**
 * @maxLength 120
 */
q?: string;
sort?: GetApiAdminUsersSort;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
offset?: number;
};

export type GetApiAdminUsersSort = typeof GetApiAdminUsersSort[keyof typeof GetApiAdminUsersSort];


export const GetApiAdminUsersSort = {
  created: 'created',
  last_seen: 'last_seen',
  orgs: 'orgs',
} as const;

export type GetApiAdminUsers200UsersItem = {[key: string]: unknown};

export type GetApiAdminUsers200 = {
  users: GetApiAdminUsers200UsersItem[];
  total: number;
  limit: number;
  offset: number;
};

export type PostApiAdminBillingEventsByIdReprocess200 = {
  ok: boolean;
  outcome: string;
};

export type PostApiAdminSubscriptionsByIdGraceBody = {
  /**
     * @minimum 1
     * @maximum 90
     */
  days: number;
  /** @maxLength 300 */
  reason?: string;
};

export type PostApiAdminSubscriptionsByIdGrace200 = {
  ok: boolean;
  graceUntil: number;
};

export type PostApiAdminAccountsByOrgIdOverridesBodyKind = typeof PostApiAdminAccountsByOrgIdOverridesBodyKind[keyof typeof PostApiAdminAccountsByOrgIdOverridesBodyKind];


export const PostApiAdminAccountsByOrgIdOverridesBodyKind = {
  feature: 'feature',
  limit: 'limit',
} as const;

export type PostApiAdminAccountsByOrgIdOverridesBody = {
  kind: PostApiAdminAccountsByOrgIdOverridesBodyKind;
  /**
     * @minLength 1
     * @maxLength 60
     */
  key: string;
  /** @maxLength 40 */
  value: string;
  /**
     * @minLength 1
     * @maxLength 300
     */
  reason: string;
  expiresInDays?: number | null;
};

export type PostApiAdminAccountsByOrgIdOverrides200 = {
  ok: boolean;
};

export type DeleteApiAdminAccountsByOrgIdOverridesByKey200 = {
  ok: boolean;
};

export type PostApiAdminAccountsByOrgIdRefreshEntitlements200 = {
  ok: boolean;
};

export type PostApiAdminImpersonateBody = {
  /**
     * @minLength 1
     * @maxLength 80
     */
  userId: string;
  /**
     * @minLength 1
     * @maxLength 80
     */
  orgId?: string;
  /** @maxLength 300 */
  reason?: string;
};

export type PostApiAdminImpersonate200User = {
  id: string;
  name: string;
  email: string;
};

export type PostApiAdminImpersonate200 = {
  token: string;
  expiresAt: number;
  user: PostApiAdminImpersonate200User;
};

export type GetHealth200 = {
  ok: boolean;
  env: string;
  db: string;
  ts: number;
};

export type GetPFormsBySlugConfig404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetPFormsBySlugConfig404Error = {
  code: string;
  message: string;
  issues?: GetPFormsBySlugConfig404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetPFormsBySlugConfig404 = {
  error: GetPFormsBySlugConfig404Error;
};

export type PostPFormsBySlugSessionsBodyHiddenFields = {[key: string]: string};

export type PostPFormsBySlugSessionsBodyEmbed = {
  origin?: string;
};

export type PostPFormsBySlugSessionsBody = {
  turnstileToken?: string;
  /** @maxLength 200 */
  password?: string;
  hiddenFields?: PostPFormsBySlugSessionsBodyHiddenFields;
  embed?: PostPFormsBySlugSessionsBodyEmbed;
  /** @maxLength 300 */
  resumeToken?: string;
};

export type PostPFormsBySlugSessions200 = {
  sessionId: string;
  sseUrl: string;
  respondentToken: string;
};

export type PostPFormsBySlugSessions403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostPFormsBySlugSessions403Error = {
  code: string;
  message: string;
  issues?: PostPFormsBySlugSessions403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostPFormsBySlugSessions403 = {
  error: PostPFormsBySlugSessions403Error;
};

export type PostPFormsBySlugSessions404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostPFormsBySlugSessions404Error = {
  code: string;
  message: string;
  issues?: PostPFormsBySlugSessions404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostPFormsBySlugSessions404 = {
  error: PostPFormsBySlugSessions404Error;
};

export type PostPSessionsByIdUploadsIntentBody = {
  ref: string;
  /**
     * @minLength 1
     * @maxLength 300
     */
  filename: string;
  /**
     * @minLength 3
     * @maxLength 120
     */
  mime: string;
  /**
     * @minimum 1
     * @maximum 26214400
     */
  size: number;
};

export type PostPSessionsByIdUploadsIntent200 = {
  fileId: string;
  uploadUrl: string;
};

export type PutPSessionsByIdUploadsByFileId200 = {
  ok: boolean;
};

export type PostPSessionsByIdUploadsByFileIdConfirm200 = {
  ok: boolean;
};

export type GetApiAuthProviders200 = {
  emailPassword: boolean;
  google: boolean;
};

export type GetApiInvitationPreview200State = typeof GetApiInvitationPreview200State[keyof typeof GetApiInvitationPreview200State];


export const GetApiInvitationPreview200State = {
  pending: 'pending',
  expired: 'expired',
  accepted: 'accepted',
  rejected: 'rejected',
  canceled: 'canceled',
  not_found: 'not_found',
} as const;

export type GetApiInvitationPreview200 = {
  state: GetApiInvitationPreview200State;
  email: string | null;
  role: string | null;
  organizationName: string | null;
  inviterName: string | null;
  inviterEmail: string | null;
  expiresAt: number | null;
  recipientHasAccount: boolean;
};

export type GetApiAuthOk200 = {
  ok: boolean;
};

export type GetApiFormsParams = {
ws?: string;
};

export type GetApiForms200ItemTheme = {
  background: string;
  botBubble: string;
  userBubble: string;
  userBubbleText: string;
  accent: string;
  logoUrl: string | null;
} | null;

export type GetApiForms200Item = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  questionCount: number;
  preview: string[];
  theme: GetApiForms200ItemTheme;
};

export type PostApiFormsBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  workspaceId?: string;
  doc?: unknown;
};

export type PostApiForms200 = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  workingSchema: unknown;
  activeVersion: number | null;
  publishedAt: number | null;
  hasUnpublishedChanges: boolean;
};

export type PostApiForms403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiForms403Error = {
  code: string;
  message: string;
  issues?: PostApiForms403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiForms403 = {
  error: PostApiForms403Error;
};

export type DeleteApiFormsById200 = {
  ok: boolean;
};

export type GetApiFormsById200 = {
  id: string;
  title: string;
  slug: string;
  status: string;
  responses: number;
  updatedAt: number;
  workingSchema: unknown;
  activeVersion: number | null;
  publishedAt: number | null;
  hasUnpublishedChanges: boolean;
};

export type GetApiFormsById404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetApiFormsById404Error = {
  code: string;
  message: string;
  issues?: GetApiFormsById404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetApiFormsById404 = {
  error: GetApiFormsById404Error;
};

export type PatchApiFormsByIdWorkspaceBody = {
  workspaceId: string;
};

export type PatchApiFormsByIdWorkspace200 = {
  ok: boolean;
};

export type PatchApiFormsByIdWorkspace404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PatchApiFormsByIdWorkspace404Error = {
  code: string;
  message: string;
  issues?: PatchApiFormsByIdWorkspace404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PatchApiFormsByIdWorkspace404 = {
  error: PatchApiFormsByIdWorkspace404Error;
};

export type PutApiFormsByIdDocBody = {
  doc: unknown;
  theme?: unknown;
  settings?: unknown;
};

export type PutApiFormsByIdDoc200 = {
  ok: boolean;
  issues: unknown[];
};

export type PostApiFormsByIdPublish200StrippedItem = {
  path: string;
  feature: string;
  label: string;
  requiredPlan: string;
};

export type PostApiFormsByIdPublish200 = {
  ok: boolean;
  version: number;
  stripped: PostApiFormsByIdPublish200StrippedItem[];
};

export type PostApiFormsByIdPublish402ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiFormsByIdPublish402Error = {
  code: string;
  message: string;
  issues?: PostApiFormsByIdPublish402ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiFormsByIdPublish402 = {
  error: PostApiFormsByIdPublish402Error;
};

export type PostApiFormsByIdPublish422ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiFormsByIdPublish422Error = {
  code: string;
  message: string;
  issues?: PostApiFormsByIdPublish422ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiFormsByIdPublish422 = {
  error: PostApiFormsByIdPublish422Error;
};

export type GetApiWorkspaces200Item = {
  id: string;
  name: string;
  slug: string;
  formCount: number;
  createdAt: number;
};

export type PostApiWorkspacesBody = {
  /**
     * @minLength 1
     * @maxLength 60
     */
  name: string;
};

export type PostApiWorkspaces200 = {
  id: string;
  name: string;
  slug: string;
  formCount: number;
  createdAt: number;
};

export type PatchApiWorkspacesByIdBody = {
  /**
     * @minLength 1
     * @maxLength 60
     */
  name: string;
};

export type PatchApiWorkspacesById200 = {
  id: string;
  name: string;
  slug: string;
  formCount: number;
  createdAt: number;
};

export type PostApiAiGenerateFormBody = {
  /**
     * @minLength 5
     * @maxLength 2000
     */
  prompt: string;
  /**
     * @minimum 2
     * @maximum 19
     */
  questionCount?: number;
  workspaceId?: string;
};

export type PostApiAiGenerateForm200 = {
  doc: unknown;
  issues: unknown[];
  tokens: number;
};

export type PostApiAiGenerateFormStreamBody = {
  /**
     * @minLength 5
     * @maxLength 2000
     */
  prompt: string;
  /**
     * @minimum 2
     * @maximum 19
     */
  questionCount?: number;
  workspaceId?: string;
};

export type PostApiAiEditFormBodyHistoryItemRole = typeof PostApiAiEditFormBodyHistoryItemRole[keyof typeof PostApiAiEditFormBodyHistoryItemRole];


export const PostApiAiEditFormBodyHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type PostApiAiEditFormBodyHistoryItem = {
  role: PostApiAiEditFormBodyHistoryItemRole;
  /** @maxLength 2000 */
  text: string;
};

export type PostApiAiEditFormBody = {
  formId: string;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  prompt: string;
  /** @maxItems 20 */
  history?: PostApiAiEditFormBodyHistoryItem[];
  /**
     * @minimum 1
     * @maximum 10
     */
  count?: number;
};

export type PostApiAiEditForm200 = {
  doc: unknown;
  added: number;
  updated: number;
  removed: number;
  rules: number;
  rewired: number;
  summary: string;
  tokens: number;
};

export type PostApiAiAddBlocksBodyHistoryItemRole = typeof PostApiAiAddBlocksBodyHistoryItemRole[keyof typeof PostApiAiAddBlocksBodyHistoryItemRole];


export const PostApiAiAddBlocksBodyHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type PostApiAiAddBlocksBodyHistoryItem = {
  role: PostApiAiAddBlocksBodyHistoryItemRole;
  /** @maxLength 2000 */
  text: string;
};

export type PostApiAiAddBlocksBody = {
  formId: string;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  prompt: string;
  /** @maxItems 20 */
  history?: PostApiAiAddBlocksBodyHistoryItem[];
  /**
     * @minimum 1
     * @maximum 10
     */
  count?: number;
};

export type PostApiAiAddBlocks200 = {
  doc: unknown;
  added: number;
  updated: number;
  removed: number;
  rules: number;
  rewired: number;
  summary: string;
  tokens: number;
};

export type GetApiFormsByIdSubmissionsParams = {
status?: GetApiFormsByIdSubmissionsStatus;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GetApiFormsByIdSubmissionsStatus = typeof GetApiFormsByIdSubmissionsStatus[keyof typeof GetApiFormsByIdSubmissionsStatus];


export const GetApiFormsByIdSubmissionsStatus = {
  all: 'all',
  completed: 'completed',
  disqualified: 'disqualified',
  abandoned: 'abandoned',
  in_progress: 'in_progress',
} as const;

export type GetApiFormsByIdSubmissions200ItemAnswersItem = {
  blockRef: string;
  blockType: string;
  value: unknown;
};

export type GetApiFormsByIdSubmissions200ItemTranscriptItem = {
  role: string;
  content: string;
  createdAt: number;
};

export type GetApiFormsByIdSubmissions200Item = {
  id: string;
  status: string;
  startedAt: number;
  completedAt: number | null;
  durationMs: number | null;
  answers: GetApiFormsByIdSubmissions200ItemAnswersItem[];
  transcript: GetApiFormsByIdSubmissions200ItemTranscriptItem[];
};

export type DeleteApiFormsByIdSubmissionsBody = {
  /**
     * @minItems 1
     * @maxItems 200
     */
  ids: string[];
};

export type DeleteApiFormsByIdSubmissions200 = {
  deleted: number;
};

export type GetApiFormsByIdAnalytics200PerBlockItem = {
  blockRef: string;
  blockType: string;
  title: string;
  answered: number;
  answerRate: number;
  dropOff: number;
};

export type GetApiFormsByIdAnalytics200DistributionsItemOptionsItem = {
  label: string;
  count: number;
};

export type GetApiFormsByIdAnalytics200DistributionsItemValuesItem = {
  value: number;
  count: number;
};

export type GetApiFormsByIdAnalytics200DistributionsItemNumericSummary = {
  avg: number;
  min: number;
  max: number;
  median: number;
} | null;

export type GetApiFormsByIdAnalytics200DistributionsItemRankingItem = {
  label: string;
  avgRank: number;
};

export type GetApiFormsByIdAnalytics200DistributionsItemMatrix = {
  rows: string[];
  cols: string[];
  counts: number[][];
} | null;

export type GetApiFormsByIdAnalytics200DistributionsItemTimelineItem = {
  label: string;
  count: number;
};

export type GetApiFormsByIdAnalytics200DistributionsItem = {
  blockRef: string;
  title: string;
  type: string;
  answered: number;
  options: GetApiFormsByIdAnalytics200DistributionsItemOptionsItem[];
  multi: boolean;
  values: GetApiFormsByIdAnalytics200DistributionsItemValuesItem[];
  numericSummary: GetApiFormsByIdAnalytics200DistributionsItemNumericSummary;
  samples: string[];
  ranking: GetApiFormsByIdAnalytics200DistributionsItemRankingItem[];
  matrix: GetApiFormsByIdAnalytics200DistributionsItemMatrix;
  timeline: GetApiFormsByIdAnalytics200DistributionsItemTimelineItem[];
};

export type GetApiFormsByIdAnalytics200DailyItem = {
  date: string;
  views: number;
  starts: number;
  completed: number;
};

export type GetApiFormsByIdAnalytics200BySourceItem = {
  source: string;
  count: number;
};

export type GetApiFormsByIdAnalytics200ByCountryItem = {
  country: string;
  count: number;
};

export type GetApiFormsByIdAnalytics200ByDevice = {
  mobile: number;
  desktop: number;
} | null;

export type GetApiFormsByIdAnalytics200DurationBucketsItem = {
  label: string;
  count: number;
};

export type GetApiFormsByIdAnalytics200LockedContext = {
  feature: string;
  requiredPlan: string;
  questionCount: number;
  worstBlockTitle: string | null;
  worstBlockIndex: number | null;
} | null;

export type GetApiFormsByIdAnalytics200 = {
  views: number;
  starts: number;
  completed: number;
  abandoned: number;
  completionRate: number;
  avgDurationMs: number | null;
  medianDurationMs: number | null;
  perBlock: GetApiFormsByIdAnalytics200PerBlockItem[];
  distributions: GetApiFormsByIdAnalytics200DistributionsItem[];
  daily: GetApiFormsByIdAnalytics200DailyItem[];
  bySource: GetApiFormsByIdAnalytics200BySourceItem[];
  byCountry: GetApiFormsByIdAnalytics200ByCountryItem[];
  byDevice: GetApiFormsByIdAnalytics200ByDevice;
  durationBuckets: GetApiFormsByIdAnalytics200DurationBucketsItem[];
  locked: string[];
  lockedContext: GetApiFormsByIdAnalytics200LockedContext;
};

export type PostV1FormsByIdResponsesBodyAnswers = {[key: string]: unknown};

export type PostV1FormsByIdResponsesBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdResponsesBodyMode = typeof PostV1FormsByIdResponsesBodyMode[keyof typeof PostV1FormsByIdResponsesBodyMode];


export const PostV1FormsByIdResponsesBodyMode = {
  flow: 'flow',
  free: 'free',
} as const;

export type PostV1FormsByIdResponsesBodyRespondent = {
  /** @maxLength 128 */
  ipHash?: string;
  /** @maxLength 8 */
  country?: string;
  /** @maxLength 300 */
  userAgent?: string;
};

export type PostV1FormsByIdResponsesBody = {
  answers?: PostV1FormsByIdResponsesBodyAnswers;
  hiddenFields?: PostV1FormsByIdResponsesBodyHiddenFields;
  complete?: boolean;
  mode?: PostV1FormsByIdResponsesBodyMode;
  /**
     * @minimum 300
     * @maximum 2592000
     */
  expiresIn?: number;
  respondent?: PostV1FormsByIdResponsesBodyRespondent;
};

export type GetV1FormsByIdResponsesParams = {
status?: string;
source?: string;
mode?: GetV1FormsByIdResponsesMode;
created_after?: number;
created_before?: number;
updated_since?: number;
ending_ref?: string;
/**
 * @maxLength 200
 */
q?: string;
order?: GetV1FormsByIdResponsesOrder;
include?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string;
};

export type GetV1FormsByIdResponsesMode = typeof GetV1FormsByIdResponsesMode[keyof typeof GetV1FormsByIdResponsesMode];


export const GetV1FormsByIdResponsesMode = {
  live: 'live',
  test: 'test',
  all: 'all',
} as const;

export type GetV1FormsByIdResponsesOrder = typeof GetV1FormsByIdResponsesOrder[keyof typeof GetV1FormsByIdResponsesOrder];


export const GetV1FormsByIdResponsesOrder = {
  created: 'created',
  updated: 'updated',
} as const;

export type PostV1ResponsesByIdAnswersBody = {
  /**
     * @minItems 1
     * @maxItems 200
     */
  answers: {
  ref: string;
  value: unknown;
}[];
} | {
  ref: string;
  value: unknown;
};

export type PostV1ResponsesByIdCompleteBody = {
  endingRef?: string;
};

export type PostV1ResponsesByIdAbandonBody = {
  /** @maxLength 100 */
  reason?: string;
};

export type GetV1FormsParams = {
status?: GetV1FormsStatus;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string;
};

export type GetV1FormsStatus = typeof GetV1FormsStatus[keyof typeof GetV1FormsStatus];


export const GetV1FormsStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
  all: 'all',
} as const;

export type PostV1FormsBody = {
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
  doc?: unknown;
};

export type PutV1FormsByIdDocBody = {
  doc: unknown;
};

export type GetV1Templates200Item = {
  slug: string;
  title: string;
  category: string;
  description: string;
  blurb: string;
  tags: string[];
  icon: string;
  accent: string;
  blockCount: number;
  estMinutes: number;
  usageCount: number;
};

export type GetV1TemplatesBySlug200 = {
  slug: string;
  title: string;
  category: string;
  description: string;
  blurb: string;
  tags: string[];
  icon: string;
  accent: string;
  blockCount: number;
  estMinutes: number;
  usageCount: number;
  doc: unknown;
};

export type GetV1TemplatesBySlug404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetV1TemplatesBySlug404Error = {
  code: string;
  message: string;
  issues?: GetV1TemplatesBySlug404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetV1TemplatesBySlug404 = {
  error: GetV1TemplatesBySlug404Error;
};

export type PostV1TemplatesBySlugUseParams = {
workspace?: string;
};

export type GetV1FormsByIdVersions200Item = {
  version: number;
  versionId: string;
  note: string | null;
  publishedAt: number;
  authorLabel: string | null;
  changeCount: number;
  isActive: boolean;
  responses: number;
};

export type GetV1FormsByIdVersions404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetV1FormsByIdVersions404Error = {
  code: string;
  message: string;
  issues?: GetV1FormsByIdVersions404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetV1FormsByIdVersions404 = {
  error: GetV1FormsByIdVersions404Error;
};

export type GetV1FormsByIdVersionsByVersionParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
compare?: number;
};

export type GetV1FormsByIdVersionsByVersion404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetV1FormsByIdVersionsByVersion404Error = {
  code: string;
  message: string;
  issues?: GetV1FormsByIdVersionsByVersion404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetV1FormsByIdVersionsByVersion404 = {
  error: GetV1FormsByIdVersionsByVersion404Error;
};

export type PostV1FormsByIdVersionsByVersionRestore404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1FormsByIdVersionsByVersionRestore404Error = {
  code: string;
  message: string;
  issues?: PostV1FormsByIdVersionsByVersionRestore404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1FormsByIdVersionsByVersionRestore404 = {
  error: PostV1FormsByIdVersionsByVersionRestore404Error;
};

export type PostV1FormsByIdVersionsByVersionRestore422ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1FormsByIdVersionsByVersionRestore422Error = {
  code: string;
  message: string;
  issues?: PostV1FormsByIdVersionsByVersionRestore422ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1FormsByIdVersionsByVersionRestore422 = {
  error: PostV1FormsByIdVersionsByVersionRestore422Error;
};

export type PostV1AiGenerateFormBody = {
  /**
     * @minLength 5
     * @maxLength 2000
     */
  prompt: string;
  /**
     * @minimum 2
     * @maximum 19
     */
  questionCount?: number;
  workspaceId?: string;
};

export type PostV1AiGenerateForm200 = {
  doc: unknown;
  issues: unknown[];
  tokens: number;
};

export type PostV1AiGenerateForm402ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1AiGenerateForm402Error = {
  code: string;
  message: string;
  issues?: PostV1AiGenerateForm402ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1AiGenerateForm402 = {
  error: PostV1AiGenerateForm402Error;
};

export type PostV1AiGenerateForm403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1AiGenerateForm403Error = {
  code: string;
  message: string;
  issues?: PostV1AiGenerateForm403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1AiGenerateForm403 = {
  error: PostV1AiGenerateForm403Error;
};

export type PostV1AiEditFormBodyHistoryItemRole = typeof PostV1AiEditFormBodyHistoryItemRole[keyof typeof PostV1AiEditFormBodyHistoryItemRole];


export const PostV1AiEditFormBodyHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type PostV1AiEditFormBodyHistoryItem = {
  role: PostV1AiEditFormBodyHistoryItemRole;
  /** @maxLength 2000 */
  text: string;
};

export type PostV1AiEditFormBody = {
  formId: string;
  /**
     * @minLength 3
     * @maxLength 1000
     */
  prompt: string;
  /** @maxItems 20 */
  history?: PostV1AiEditFormBodyHistoryItem[];
  /**
     * @minimum 1
     * @maximum 10
     */
  count?: number;
};

export type PostV1AiEditForm402ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1AiEditForm402Error = {
  code: string;
  message: string;
  issues?: PostV1AiEditForm402ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1AiEditForm402 = {
  error: PostV1AiEditForm402Error;
};

export type PostV1AiEditForm403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1AiEditForm403Error = {
  code: string;
  message: string;
  issues?: PostV1AiEditForm403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1AiEditForm403 = {
  error: PostV1AiEditForm403Error;
};

export type PostV1AiEditForm404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostV1AiEditForm404Error = {
  code: string;
  message: string;
  issues?: PostV1AiEditForm404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostV1AiEditForm404 = {
  error: PostV1AiEditForm404Error;
};

export type GetV1FormsByIdIntegrations200Item = {
  id: string;
  provider: string;
  status: string;
  createdAt: number;
  feedUrl?: string;
  includePartials?: boolean;
};

export type GetV1FormsByIdIntegrations404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetV1FormsByIdIntegrations404Error = {
  code: string;
  message: string;
  issues?: GetV1FormsByIdIntegrations404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetV1FormsByIdIntegrations404 = {
  error: GetV1FormsByIdIntegrations404Error;
};

export type PutV1FormsByIdIntegrationsSpreadsheetBody = {
  includePartials?: boolean;
  rotate?: boolean;
};

export type PutV1FormsByIdIntegrationsSpreadsheet200 = {
  id: string;
  provider: string;
  status: string;
  createdAt: number;
  feedUrl?: string;
  includePartials?: boolean;
};

export type PutV1FormsByIdIntegrationsSpreadsheet402ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PutV1FormsByIdIntegrationsSpreadsheet402Error = {
  code: string;
  message: string;
  issues?: PutV1FormsByIdIntegrationsSpreadsheet402ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PutV1FormsByIdIntegrationsSpreadsheet402 = {
  error: PutV1FormsByIdIntegrationsSpreadsheet402Error;
};

export type PutV1FormsByIdIntegrationsSpreadsheet404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PutV1FormsByIdIntegrationsSpreadsheet404Error = {
  code: string;
  message: string;
  issues?: PutV1FormsByIdIntegrationsSpreadsheet404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PutV1FormsByIdIntegrationsSpreadsheet404 = {
  error: PutV1FormsByIdIntegrationsSpreadsheet404Error;
};

export type DeleteV1FormsByIdIntegrationsSpreadsheet404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type DeleteV1FormsByIdIntegrationsSpreadsheet404Error = {
  code: string;
  message: string;
  issues?: DeleteV1FormsByIdIntegrationsSpreadsheet404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type DeleteV1FormsByIdIntegrationsSpreadsheet404 = {
  error: DeleteV1FormsByIdIntegrationsSpreadsheet404Error;
};

export type GetV1Webhooks200Item = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  consecutiveFailures: number;
  createdAt: number;
  secretPreview: string;
};

export type PostV1WebhooksBody = {
  /** @maxLength 2000 */
  url: string;
  /**
     * @minItems 1
     * @maxItems 20
     */
  events: string[];
  /** @maxLength 64 */
  formId?: string;
};

export type PostV1FormsByIdExportsBodyFormat = typeof PostV1FormsByIdExportsBodyFormat[keyof typeof PostV1FormsByIdExportsBodyFormat];


export const PostV1FormsByIdExportsBodyFormat = {
  csv: 'csv',
  json: 'json',
} as const;

export type PostV1FormsByIdExportsBodyMode = typeof PostV1FormsByIdExportsBodyMode[keyof typeof PostV1FormsByIdExportsBodyMode];


export const PostV1FormsByIdExportsBodyMode = {
  live: 'live',
  test: 'test',
  all: 'all',
} as const;

export type PostV1FormsByIdExportsBody = {
  format?: PostV1FormsByIdExportsBodyFormat;
  /** @maxItems 6 */
  status?: string[];
  /** @maxLength 20 */
  source?: string;
  mode?: PostV1FormsByIdExportsBodyMode;
  created_after?: number;
  created_before?: number;
};

export type PostV1FormsByIdExports202Status = typeof PostV1FormsByIdExports202Status[keyof typeof PostV1FormsByIdExports202Status];


export const PostV1FormsByIdExports202Status = {
  queued: 'queued',
  running: 'running',
  ready: 'ready',
  failed: 'failed',
} as const;

export type PostV1FormsByIdExports202Format = typeof PostV1FormsByIdExports202Format[keyof typeof PostV1FormsByIdExports202Format];


export const PostV1FormsByIdExports202Format = {
  csv: 'csv',
  json: 'json',
} as const;

export type PostV1FormsByIdExports202 = {
  id: string;
  object: 'export';
  form_id: string;
  status: PostV1FormsByIdExports202Status;
  format: PostV1FormsByIdExports202Format;
  row_count: number | null;
  bytes: number | null;
  error: string | null;
  created_at: number;
  completed_at: number | null;
  expires_at: number | null;
  download_url: string | null;
  download_expires_at: number | null;
};

export type GetV1ExportsById200Status = typeof GetV1ExportsById200Status[keyof typeof GetV1ExportsById200Status];


export const GetV1ExportsById200Status = {
  queued: 'queued',
  running: 'running',
  ready: 'ready',
  failed: 'failed',
} as const;

export type GetV1ExportsById200Format = typeof GetV1ExportsById200Format[keyof typeof GetV1ExportsById200Format];


export const GetV1ExportsById200Format = {
  csv: 'csv',
  json: 'json',
} as const;

export type GetV1ExportsById200 = {
  id: string;
  object: 'export';
  form_id: string;
  status: GetV1ExportsById200Status;
  format: GetV1ExportsById200Format;
  row_count: number | null;
  bytes: number | null;
  error: string | null;
  created_at: number;
  completed_at: number | null;
  expires_at: number | null;
  download_url: string | null;
  download_expires_at: number | null;
};

export type GetV1ExportsParams = {
form_id?: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type GetV1FilesById200 = {
  id: string;
  object: 'file';
  form_id: string | null;
  response_id: string | null;
  filename: string;
  mime: string;
  size_bytes: number;
  created_at: number;
  download_url: string;
  download_expires_at: number;
};

export type PostV1SessionsBySidUploadsIntentBody = {
  ref: string;
  /**
     * @minLength 1
     * @maxLength 300
     */
  filename: string;
  /**
     * @minLength 3
     * @maxLength 120
     */
  mime: string;
  /**
     * @minimum 1
     * @maximum 26214400
     */
  size: number;
};

export type PostV1SessionsBySidUploadsIntent200 = {
  fileId: string;
  uploadUrl: string;
};

export type PutV1SessionsBySidUploadsByFileId200 = {
  ok: boolean;
};

export type PostV1SessionsBySidUploadsByFileIdConfirm200 = {
  ok: boolean;
};

export type PostV1FormsByIdSessionsBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdSessionsBodyRespondent = {
  /** @maxLength 128 */
  ipHash?: string;
  /** @maxLength 8 */
  country?: string;
  /** @maxLength 300 */
  userAgent?: string;
};

export type PostV1FormsByIdSessionsBody = {
  hiddenFields?: PostV1FormsByIdSessionsBodyHiddenFields;
  /** @maxLength 200 */
  externalId?: string;
  /**
     * @minimum 300
     * @maximum 2592000
     */
  expiresIn?: number;
  respondent?: PostV1FormsByIdSessionsBodyRespondent;
};

export type PostV1FormsByIdSessions200 = {
  sessionId: string;
  respondentToken: string;
  expiresAt: number;
  streamUrl: string;
  greeting: string | null;
  question: unknown | null;
};

export type PostV1FormsByIdChatSessionsBodyHiddenFields = {[key: string]: string};

export type PostV1FormsByIdChatSessionsBodyRespondent = {
  /** @maxLength 128 */
  ipHash?: string;
  /** @maxLength 8 */
  country?: string;
  /** @maxLength 300 */
  userAgent?: string;
};

export type PostV1FormsByIdChatSessionsBody = {
  hiddenFields?: PostV1FormsByIdChatSessionsBodyHiddenFields;
  /** @maxLength 200 */
  externalId?: string;
  /**
     * @minimum 300
     * @maximum 2592000
     */
  expiresIn?: number;
  respondent?: PostV1FormsByIdChatSessionsBodyRespondent;
};

export type PostV1FormsByIdChatSessions200 = {
  sessionId: string;
  respondentToken: string;
  expiresAt: number;
  streamUrl: string;
  greeting: string | null;
  question: unknown | null;
};

export type PostV1SessionsBySidMessagesBody = {
  type: 'text';
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
} | {
  type: 'structured';
  ref: string;
  value: unknown;
};

export type PostV1SessionsBySidActionsBodyAction = typeof PostV1SessionsBySidActionsBodyAction[keyof typeof PostV1SessionsBySidActionsBodyAction];


export const PostV1SessionsBySidActionsBodyAction = {
  skip: 'skip',
  stop: 'stop',
  restart: 'restart',
  edit: 'edit',
  submit: 'submit',
} as const;

export type PostV1SessionsBySidActionsBody = {
  action: PostV1SessionsBySidActionsBodyAction;
  ref?: string;
};

export type PostV1ChatSessionsBySidMessagesBody = {
  type: 'text';
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
} | {
  type: 'structured';
  ref: string;
  value: unknown;
};

export type PostV1ChatSessionsBySidActionsBodyAction = typeof PostV1ChatSessionsBySidActionsBodyAction[keyof typeof PostV1ChatSessionsBySidActionsBodyAction];


export const PostV1ChatSessionsBySidActionsBodyAction = {
  skip: 'skip',
  stop: 'stop',
  restart: 'restart',
  edit: 'edit',
  submit: 'submit',
} as const;

export type PostV1ChatSessionsBySidActionsBody = {
  action: PostV1ChatSessionsBySidActionsBodyAction;
  ref?: string;
};

export type GetApiKeys200ItemKeyType = typeof GetApiKeys200ItemKeyType[keyof typeof GetApiKeys200ItemKeyType];


export const GetApiKeys200ItemKeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type GetApiKeys200ItemEnvironment = typeof GetApiKeys200ItemEnvironment[keyof typeof GetApiKeys200ItemEnvironment];


export const GetApiKeys200ItemEnvironment = {
  live: 'live',
  test: 'test',
} as const;

export type GetApiKeys200ItemScopes = {[key: string]: string[]};

export type GetApiKeys200Item = {
  id: string;
  name: string | null;
  keyType: GetApiKeys200ItemKeyType;
  environment: GetApiKeys200ItemEnvironment;
  start: string | null;
  enabled: boolean;
  scopes: GetApiKeys200ItemScopes;
  origins: string[];
  formIds: string[];
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  requestCount: number;
  lastUsedAt: number | null;
  expiresAt: number | null;
  createdBy: string | null;
  createdAt: number;
};

export type PostApiKeysBodyKeyType = typeof PostApiKeysBodyKeyType[keyof typeof PostApiKeysBodyKeyType];


export const PostApiKeysBodyKeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type PostApiKeysBodyScopes = {[key: string]: string[]};

export type PostApiKeysBody = {
  /**
     * @minLength 1
     * @maxLength 64
     */
  name?: string;
  keyType?: PostApiKeysBodyKeyType;
  scopes?: PostApiKeysBodyScopes;
  /**
     * @maxItems 20
     * @items.maxLength 200
     */
  origins?: string[];
  /**
     * @maxItems 50
     * @items.maxLength 64
     */
  formIds?: string[];
  /**
     * @minimum 1
     * @maximum 365
     */
  expiresInDays?: number;
  /**
     * @minimum 1
     * @maximum 10000
     */
  rateLimitMax?: number;
};

export type PostApiKeys200KeyType = typeof PostApiKeys200KeyType[keyof typeof PostApiKeys200KeyType];


export const PostApiKeys200KeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type PostApiKeys200Environment = typeof PostApiKeys200Environment[keyof typeof PostApiKeys200Environment];


export const PostApiKeys200Environment = {
  live: 'live',
  test: 'test',
} as const;

export type PostApiKeys200Scopes = {[key: string]: string[]};

export type PostApiKeys200 = {
  id: string;
  name: string | null;
  keyType: PostApiKeys200KeyType;
  environment: PostApiKeys200Environment;
  start: string | null;
  enabled: boolean;
  scopes: PostApiKeys200Scopes;
  origins: string[];
  formIds: string[];
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  requestCount: number;
  lastUsedAt: number | null;
  expiresAt: number | null;
  createdBy: string | null;
  createdAt: number;
  key: string;
};

export type PostApiKeysByIdRotateBody = {
  /**
     * @minimum 0
     * @maximum 168
     */
  graceHours?: number;
};

export type PostApiKeysByIdRotate200KeyType = typeof PostApiKeysByIdRotate200KeyType[keyof typeof PostApiKeysByIdRotate200KeyType];


export const PostApiKeysByIdRotate200KeyType = {
  sk_live: 'sk_live',
  sk_test: 'sk_test',
  pk_live: 'pk_live',
  pk_test: 'pk_test',
} as const;

export type PostApiKeysByIdRotate200Environment = typeof PostApiKeysByIdRotate200Environment[keyof typeof PostApiKeysByIdRotate200Environment];


export const PostApiKeysByIdRotate200Environment = {
  live: 'live',
  test: 'test',
} as const;

export type PostApiKeysByIdRotate200Scopes = {[key: string]: string[]};

export type PostApiKeysByIdRotate200 = {
  id: string;
  name: string | null;
  keyType: PostApiKeysByIdRotate200KeyType;
  environment: PostApiKeysByIdRotate200Environment;
  start: string | null;
  enabled: boolean;
  scopes: PostApiKeysByIdRotate200Scopes;
  origins: string[];
  formIds: string[];
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  requestCount: number;
  lastUsedAt: number | null;
  expiresAt: number | null;
  createdBy: string | null;
  createdAt: number;
  key: string;
  replacedKeyId: string;
  oldKeyExpiresAt: number | null;
};

export type DeleteApiKeysById200 = {
  ok: boolean;
};

export type GetApiWebhooks200Item = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  createdAt: number;
  secretPreview?: string;
};

export type PostApiWebhooksBodyEventsItem = typeof PostApiWebhooksBodyEventsItem[keyof typeof PostApiWebhooksBodyEventsItem];


export const PostApiWebhooksBodyEventsItem = {
  responsecompleted: 'response.completed',
  submissioncompleted: 'submission.completed',
  responseabandoned: 'response.abandoned',
  submissionabandoned: 'submission.abandoned',
  responsedisqualified: 'response.disqualified',
  responsepartial: 'response.partial',
  responseanswer_recorded: 'response.answer_recorded',
  sessionstarted: 'session.started',
  responseresumed: 'response.resumed',
  followupsent: 'followup.sent',
  formpublished: 'form.published',
} as const;

export type PostApiWebhooksBody = {
  url: string;
  /** @minItems 1 */
  events: PostApiWebhooksBodyEventsItem[];
  formId?: string | null;
};

export type PostApiWebhooks200 = {
  id: string;
  url: string;
  events: string[];
  formId: string | null;
  active: boolean;
  createdAt: number;
  secretPreview?: string;
  secret: string;
};

export type DeleteApiWebhooksById200 = {
  ok: boolean;
};

export type PostApiWebhooksByIdTest200 = {
  ok: boolean;
  signature: string;
};

export type GetApiFormsByIdIntegrations200Item = {
  id: string;
  provider: string;
  status: string;
  createdAt: number;
  feedUrl?: string;
  includePartials?: boolean;
};

export type PostApiFormsByIdIntegrationsSpreadsheetBody = {
  includePartials?: boolean;
  rotate?: boolean;
};

export type PostApiFormsByIdIntegrationsSpreadsheet200 = {
  id: string;
  provider: string;
  status: string;
  createdAt: number;
  feedUrl?: string;
  includePartials?: boolean;
};

export type GetApiBillingEntitlements200Features = {[key: string]: boolean};

export type GetApiBillingEntitlements200Limits = {[key: string]: number | null};

export type GetApiBillingEntitlements200Usage = {[key: string]: number};

export type GetApiBillingEntitlements200PreviousUsage = {[key: string]: number} | null;

export type GetApiBillingEntitlements200Gauges = {[key: string]: number};

export type GetApiBillingEntitlements200Permissions = {[key: string]: string[]};

export type GetApiBillingEntitlements200 = {
  planId: string;
  planName: string;
  status: string;
  cycle: string | null;
  periodStart: number | null;
  periodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  inGrace: boolean;
  seats: number;
  features: GetApiBillingEntitlements200Features;
  limits: GetApiBillingEntitlements200Limits;
  usage: GetApiBillingEntitlements200Usage;
  previousUsage: GetApiBillingEntitlements200PreviousUsage;
  gauges: GetApiBillingEntitlements200Gauges;
  periodResetsAt: number;
  role: string;
  roleLabel: string;
  permissions: GetApiBillingEntitlements200Permissions;
};

export type GetApiBillingUsage200Limits = {[key: string]: number | null};

export type GetApiBillingUsage200Usage = {[key: string]: number};

export type GetApiBillingUsage200 = {
  plan: string;
  planId: string;
  status: string;
  periodEnd: number | null;
  limits: GetApiBillingUsage200Limits;
  usage: GetApiBillingUsage200Usage;
};

export type PostApiBillingCheckoutBodyPlanId = typeof PostApiBillingCheckoutBodyPlanId[keyof typeof PostApiBillingCheckoutBodyPlanId];


export const PostApiBillingCheckoutBodyPlanId = {
  pro: 'pro',
  business: 'business',
} as const;

export type PostApiBillingCheckoutBodyCycle = typeof PostApiBillingCheckoutBodyCycle[keyof typeof PostApiBillingCheckoutBodyCycle];


export const PostApiBillingCheckoutBodyCycle = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type PostApiBillingCheckoutBody = {
  planId: PostApiBillingCheckoutBodyPlanId;
  cycle?: PostApiBillingCheckoutBodyCycle;
  /** @maxLength 64 */
  discountCode?: string;
};

export type PostApiBillingCheckout200 = {
  url: string;
};

export type PostApiBillingPortal200 = {
  url: string;
};

export type PostApiFormsByIdPreviewSessions200 = {
  sessionId: string;
  sseUrl: string;
  respondentToken: string;
};

export type GetApiTemplates200Item = {
  slug: string;
  title: string;
  category: string;
  description: string;
  blurb: string;
  tags: string[];
  icon: string;
  accent: string;
  blockCount: number;
  estMinutes: number;
  usageCount: number;
};

export type GetApiTemplatesBySlug200 = {
  slug: string;
  title: string;
  category: string;
  description: string;
  blurb: string;
  tags: string[];
  icon: string;
  accent: string;
  blockCount: number;
  estMinutes: number;
  usageCount: number;
  doc: unknown;
};

export type GetApiTemplatesBySlug404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetApiTemplatesBySlug404Error = {
  code: string;
  message: string;
  issues?: GetApiTemplatesBySlug404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetApiTemplatesBySlug404 = {
  error: GetApiTemplatesBySlug404Error;
};

export type PostApiTemplatesBySlugUseParams = {
ws?: string;
};

export type PostApiTemplatesBySlugUse403ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiTemplatesBySlugUse403Error = {
  code: string;
  message: string;
  issues?: PostApiTemplatesBySlugUse403ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiTemplatesBySlugUse403 = {
  error: PostApiTemplatesBySlugUse403Error;
};

export type PostApiTemplatesBySlugUse404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiTemplatesBySlugUse404Error = {
  code: string;
  message: string;
  issues?: PostApiTemplatesBySlugUse404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiTemplatesBySlugUse404 = {
  error: PostApiTemplatesBySlugUse404Error;
};

export type GetApiAuditLogsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum -9007199254740991
 * @maximum 9007199254740991
 */
before?: number;
/**
 * @maxLength 80
 */
action?: string;
};

export type GetApiAuditLogs200EntriesItem = {
  id: string;
  action: string;
  actorType: string;
  actorLabel: string | null;
  resourceType: string | null;
  resourceId: string | null;
  meta: unknown | null;
  createdAt: number;
};

export type GetApiAuditLogs200 = {
  entries: GetApiAuditLogs200EntriesItem[];
  nextBefore: number | null;
};

export type GetApiFormsByIdHistoryParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum -9007199254740991
 * @maximum 9007199254740991
 */
before?: number;
};

export type GetApiFormsByIdHistory200GroupsItemEntriesItemChangesItem = {
  op: string;
  target: string;
  label: string;
  from?: string;
  to?: string;
};

export type GetApiFormsByIdHistory200GroupsItemEntriesItem = {
  id: string;
  kind: string;
  summary: string;
  changes: GetApiFormsByIdHistory200GroupsItemEntriesItemChangesItem[];
  changeCount: number;
  actorType: string;
  actorLabel: string | null;
  source: string;
  createdAt: number;
  updatedAt: number;
};

export type GetApiFormsByIdHistory200GroupsItem = {
  version: number | null;
  versionId: string | null;
  publishedAt: number | null;
  note: string | null;
  isActive: boolean;
  entries: GetApiFormsByIdHistory200GroupsItemEntriesItem[];
};

export type GetApiFormsByIdHistory200 = {
  groups: GetApiFormsByIdHistory200GroupsItem[];
  nextBefore: number | null;
};

export type GetApiFormsByIdVersions200Item = {
  version: number;
  versionId: string;
  note: string | null;
  publishedAt: number;
  authorLabel: string | null;
  changeCount: number;
  isActive: boolean;
  responses: number;
};

export type GetApiFormsByIdVersionsByVersionParams = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
compare?: number;
};

export type GetApiFormsByIdVersionsByVersion200ChangesItem = {
  op: string;
  target: string;
  label: string;
  from?: string;
  to?: string;
};

export type GetApiFormsByIdVersionsByVersion200 = {
  version: number;
  versionId: string;
  note: string | null;
  publishedAt: number;
  doc: unknown;
  comparedTo: number | null;
  changes: GetApiFormsByIdVersionsByVersion200ChangesItem[];
  summary: string | null;
};

export type GetApiFormsByIdVersionsByVersion404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type GetApiFormsByIdVersionsByVersion404Error = {
  code: string;
  message: string;
  issues?: GetApiFormsByIdVersionsByVersion404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type GetApiFormsByIdVersionsByVersion404 = {
  error: GetApiFormsByIdVersionsByVersion404Error;
};

export type PostApiFormsByIdVersionsByVersionRestore200ChangesItem = {
  op: string;
  target: string;
  label: string;
  from?: string;
  to?: string;
};

export type PostApiFormsByIdVersionsByVersionRestore200 = {
  ok: boolean;
  version: number;
  summary: string;
  changes: PostApiFormsByIdVersionsByVersionRestore200ChangesItem[];
  doc: unknown;
};

export type PostApiFormsByIdVersionsByVersionRestore404ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiFormsByIdVersionsByVersionRestore404Error = {
  code: string;
  message: string;
  issues?: PostApiFormsByIdVersionsByVersionRestore404ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiFormsByIdVersionsByVersionRestore404 = {
  error: PostApiFormsByIdVersionsByVersionRestore404Error;
};

export type PostApiFormsByIdVersionsByVersionRestore422ErrorIssuesItem = {
  ref?: string;
  path?: string;
  code: string;
  message: string;
};

export type PostApiFormsByIdVersionsByVersionRestore422Error = {
  code: string;
  message: string;
  issues?: PostApiFormsByIdVersionsByVersionRestore422ErrorIssuesItem[];
  request_id?: string;
  doc_url?: string;
  [key: string]: unknown;
};

export type PostApiFormsByIdVersionsByVersionRestore422 = {
  error: PostApiFormsByIdVersionsByVersionRestore422Error;
};

