/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiAdminAccountsByOrgIdOverridesByKey200,
  DeleteApiAdminAccountsByOrgIdPlan200,
  GetApiAdminAccounts200,
  GetApiAdminAccountsByOrgId200,
  GetApiAdminAccountsParams,
  GetApiAdminActions200,
  GetApiAdminAi200,
  GetApiAdminAiParams,
  GetApiAdminForms200,
  GetApiAdminFormsParams,
  GetApiAdminHealth200,
  GetApiAdminHealthParams,
  GetApiAdminLive200,
  GetApiAdminMe200,
  GetApiAdminOverview200,
  GetApiAdminOverviewParams,
  GetApiAdminProduct200,
  GetApiAdminProductParams,
  GetApiAdminRevenue200,
  GetApiAdminRevenueParams,
  GetApiAdminUsers200,
  GetApiAdminUsersParams,
  PostApiAdminAccountsByOrgIdOverrides200,
  PostApiAdminAccountsByOrgIdOverridesBody,
  PostApiAdminAccountsByOrgIdPlan200,
  PostApiAdminAccountsByOrgIdPlanBody,
  PostApiAdminAccountsByOrgIdRefreshEntitlements200,
  PostApiAdminBillingEventsByIdReprocess200,
  PostApiAdminImpersonate200,
  PostApiAdminImpersonateBody,
  PostApiAdminSubscriptionsByIdGrace200,
  PostApiAdminSubscriptionsByIdGraceBody
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiAdminMeResponse200 = {
  data: GetApiAdminMe200
  status: 200
}

export type getApiAdminMeResponse404 = {
  data: void
  status: 404
}

export type getApiAdminMeResponseSuccess = (getApiAdminMeResponse200) & {
  headers: Headers;
};
export type getApiAdminMeResponseError = (getApiAdminMeResponse404) & {
  headers: Headers;
};

export type getApiAdminMeResponse = (getApiAdminMeResponseSuccess | getApiAdminMeResponseError)

export const getGetApiAdminMeUrl = () => {




  return `/api/admin/me`
}

/**
 * @summary Confirm the caller is a platform admin
 */
export const getApiAdminMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminMeResponse> => {

  return customFetch<getApiAdminMeResponse>(getGetApiAdminMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminMeQueryKey = () => {
    return [
    `/api/admin/me`
    ] as const;
    }


export const getGetApiAdminMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminMe>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminMe>>> = ({ signal }) => getApiAdminMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminMe>>>
export type GetApiAdminMeQueryError = void


/**
 * @summary Confirm the caller is a platform admin
 */

export function useGetApiAdminMe<TData = Awaited<ReturnType<typeof getApiAdminMe>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminOverviewResponse200 = {
  data: GetApiAdminOverview200
  status: 200
}

export type getApiAdminOverviewResponse404 = {
  data: void
  status: 404
}

export type getApiAdminOverviewResponseSuccess = (getApiAdminOverviewResponse200) & {
  headers: Headers;
};
export type getApiAdminOverviewResponseError = (getApiAdminOverviewResponse404) & {
  headers: Headers;
};

export type getApiAdminOverviewResponse = (getApiAdminOverviewResponseSuccess | getApiAdminOverviewResponseError)

export const getGetApiAdminOverviewUrl = (params?: GetApiAdminOverviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/overview?${stringifiedParams}` : `/api/admin/overview`
}

/**
 * @summary Platform-wide growth, funnel, retention and revenue
 */
export const getApiAdminOverview = async (params?: GetApiAdminOverviewParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminOverviewResponse> => {

  return customFetch<getApiAdminOverviewResponse>(getGetApiAdminOverviewUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminOverviewQueryKey = (params?: GetApiAdminOverviewParams,) => {
    return [
    `/api/admin/overview`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminOverview>>, TError = void>(params?: GetApiAdminOverviewParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminOverview>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminOverviewQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminOverview>>> = ({ signal }) => getApiAdminOverview(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminOverview>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminOverview>>>
export type GetApiAdminOverviewQueryError = void


/**
 * @summary Platform-wide growth, funnel, retention and revenue
 */

export function useGetApiAdminOverview<TData = Awaited<ReturnType<typeof getApiAdminOverview>>, TError = void>(
 params?: GetApiAdminOverviewParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminOverview>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminOverviewQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminLiveResponse200 = {
  data: GetApiAdminLive200
  status: 200
}

export type getApiAdminLiveResponse404 = {
  data: void
  status: 404
}

export type getApiAdminLiveResponseSuccess = (getApiAdminLiveResponse200) & {
  headers: Headers;
};
export type getApiAdminLiveResponseError = (getApiAdminLiveResponse404) & {
  headers: Headers;
};

export type getApiAdminLiveResponse = (getApiAdminLiveResponseSuccess | getApiAdminLiveResponseError)

export const getGetApiAdminLiveUrl = () => {




  return `/api/admin/live`
}

/**
 * @summary Per-minute event counts for the last half hour
 */
export const getApiAdminLive = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminLiveResponse> => {

  return customFetch<getApiAdminLiveResponse>(getGetApiAdminLiveUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminLiveQueryKey = () => {
    return [
    `/api/admin/live`
    ] as const;
    }


export const getGetApiAdminLiveQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminLive>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminLive>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminLiveQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminLive>>> = ({ signal }) => getApiAdminLive({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminLive>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminLiveQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminLive>>>
export type GetApiAdminLiveQueryError = void


/**
 * @summary Per-minute event counts for the last half hour
 */

export function useGetApiAdminLive<TData = Awaited<ReturnType<typeof getApiAdminLive>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminLive>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminLiveQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminActionsResponse200 = {
  data: GetApiAdminActions200
  status: 200
}

export type getApiAdminActionsResponse404 = {
  data: void
  status: 404
}

export type getApiAdminActionsResponseSuccess = (getApiAdminActionsResponse200) & {
  headers: Headers;
};
export type getApiAdminActionsResponseError = (getApiAdminActionsResponse404) & {
  headers: Headers;
};

export type getApiAdminActionsResponse = (getApiAdminActionsResponseSuccess | getApiAdminActionsResponseError)

export const getGetApiAdminActionsUrl = () => {




  return `/api/admin/actions`
}

/**
 * @summary Accounts and systems that need attention today
 */
export const getApiAdminActions = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminActionsResponse> => {

  return customFetch<getApiAdminActionsResponse>(getGetApiAdminActionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminActionsQueryKey = () => {
    return [
    `/api/admin/actions`
    ] as const;
    }


export const getGetApiAdminActionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminActions>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminActions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminActionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminActions>>> = ({ signal }) => getApiAdminActions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminActions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminActionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminActions>>>
export type GetApiAdminActionsQueryError = void


/**
 * @summary Accounts and systems that need attention today
 */

export function useGetApiAdminActions<TData = Awaited<ReturnType<typeof getApiAdminActions>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminActions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminActionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminAccountsResponse200 = {
  data: GetApiAdminAccounts200
  status: 200
}

export type getApiAdminAccountsResponse404 = {
  data: void
  status: 404
}

export type getApiAdminAccountsResponseSuccess = (getApiAdminAccountsResponse200) & {
  headers: Headers;
};
export type getApiAdminAccountsResponseError = (getApiAdminAccountsResponse404) & {
  headers: Headers;
};

export type getApiAdminAccountsResponse = (getApiAdminAccountsResponseSuccess | getApiAdminAccountsResponseError)

export const getGetApiAdminAccountsUrl = (params?: GetApiAdminAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/accounts?${stringifiedParams}` : `/api/admin/accounts`
}

/**
 * @summary Every organization, with the numbers that decide what to do about it
 */
export const getApiAdminAccounts = async (params?: GetApiAdminAccountsParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminAccountsResponse> => {

  return customFetch<getApiAdminAccountsResponse>(getGetApiAdminAccountsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminAccountsQueryKey = (params?: GetApiAdminAccountsParams,) => {
    return [
    `/api/admin/accounts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminAccounts>>, TError = void>(params?: GetApiAdminAccountsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAccounts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminAccountsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminAccounts>>> = ({ signal }) => getApiAdminAccounts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAccounts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAccounts>>>
export type GetApiAdminAccountsQueryError = void


/**
 * @summary Every organization, with the numbers that decide what to do about it
 */

export function useGetApiAdminAccounts<TData = Awaited<ReturnType<typeof getApiAdminAccounts>>, TError = void>(
 params?: GetApiAdminAccountsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAccounts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminAccountsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminAccountsByOrgIdResponse200 = {
  data: GetApiAdminAccountsByOrgId200
  status: 200
}

export type getApiAdminAccountsByOrgIdResponse404 = {
  data: void
  status: 404
}

export type getApiAdminAccountsByOrgIdResponseSuccess = (getApiAdminAccountsByOrgIdResponse200) & {
  headers: Headers;
};
export type getApiAdminAccountsByOrgIdResponseError = (getApiAdminAccountsByOrgIdResponse404) & {
  headers: Headers;
};

export type getApiAdminAccountsByOrgIdResponse = (getApiAdminAccountsByOrgIdResponseSuccess | getApiAdminAccountsByOrgIdResponseError)

export const getGetApiAdminAccountsByOrgIdUrl = (orgId: string,) => {




  return `/api/admin/accounts/${orgId}`
}

/**
 * @summary One organization, in full
 */
export const getApiAdminAccountsByOrgId = async (orgId: string, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminAccountsByOrgIdResponse> => {

  return customFetch<getApiAdminAccountsByOrgIdResponse>(getGetApiAdminAccountsByOrgIdUrl(orgId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminAccountsByOrgIdQueryKey = (orgId: string,) => {
    return [
    `/api/admin/accounts/${orgId}`
    ] as const;
    }


export const getGetApiAdminAccountsByOrgIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>, TError = void>(orgId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminAccountsByOrgIdQueryKey(orgId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>> = ({ signal }) => getApiAdminAccountsByOrgId(orgId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: orgId !== null && orgId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminAccountsByOrgIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>>
export type GetApiAdminAccountsByOrgIdQueryError = void


/**
 * @summary One organization, in full
 */

export function useGetApiAdminAccountsByOrgId<TData = Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>, TError = void>(
 orgId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAccountsByOrgId>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminAccountsByOrgIdQueryOptions(orgId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminProductResponse200 = {
  data: GetApiAdminProduct200
  status: 200
}

export type getApiAdminProductResponse404 = {
  data: void
  status: 404
}

export type getApiAdminProductResponseSuccess = (getApiAdminProductResponse200) & {
  headers: Headers;
};
export type getApiAdminProductResponseError = (getApiAdminProductResponse404) & {
  headers: Headers;
};

export type getApiAdminProductResponse = (getApiAdminProductResponseSuccess | getApiAdminProductResponseError)

export const getGetApiAdminProductUrl = (params?: GetApiAdminProductParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/product?${stringifiedParams}` : `/api/admin/product`
}

/**
 * @summary What people build: block types, form shapes, templates, feature adoption
 */
export const getApiAdminProduct = async (params?: GetApiAdminProductParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminProductResponse> => {

  return customFetch<getApiAdminProductResponse>(getGetApiAdminProductUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminProductQueryKey = (params?: GetApiAdminProductParams,) => {
    return [
    `/api/admin/product`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminProductQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminProduct>>, TError = void>(params?: GetApiAdminProductParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminProduct>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminProductQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminProduct>>> = ({ signal }) => getApiAdminProduct(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminProduct>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminProductQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminProduct>>>
export type GetApiAdminProductQueryError = void


/**
 * @summary What people build: block types, form shapes, templates, feature adoption
 */

export function useGetApiAdminProduct<TData = Awaited<ReturnType<typeof getApiAdminProduct>>, TError = void>(
 params?: GetApiAdminProductParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminProduct>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminProductQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminFormsResponse200 = {
  data: GetApiAdminForms200
  status: 200
}

export type getApiAdminFormsResponse404 = {
  data: void
  status: 404
}

export type getApiAdminFormsResponseSuccess = (getApiAdminFormsResponse200) & {
  headers: Headers;
};
export type getApiAdminFormsResponseError = (getApiAdminFormsResponse404) & {
  headers: Headers;
};

export type getApiAdminFormsResponse = (getApiAdminFormsResponseSuccess | getApiAdminFormsResponseError)

export const getGetApiAdminFormsUrl = (params?: GetApiAdminFormsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/forms?${stringifiedParams}` : `/api/admin/forms`
}

/**
 * @summary Every form, by title and performance — never its content
 */
export const getApiAdminForms = async (params?: GetApiAdminFormsParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminFormsResponse> => {

  return customFetch<getApiAdminFormsResponse>(getGetApiAdminFormsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminFormsQueryKey = (params?: GetApiAdminFormsParams,) => {
    return [
    `/api/admin/forms`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminFormsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminForms>>, TError = void>(params?: GetApiAdminFormsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminForms>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminFormsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminForms>>> = ({ signal }) => getApiAdminForms(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminForms>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminFormsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminForms>>>
export type GetApiAdminFormsQueryError = void


/**
 * @summary Every form, by title and performance — never its content
 */

export function useGetApiAdminForms<TData = Awaited<ReturnType<typeof getApiAdminForms>>, TError = void>(
 params?: GetApiAdminFormsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminForms>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminFormsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminRevenueResponse200 = {
  data: GetApiAdminRevenue200
  status: 200
}

export type getApiAdminRevenueResponse404 = {
  data: void
  status: 404
}

export type getApiAdminRevenueResponseSuccess = (getApiAdminRevenueResponse200) & {
  headers: Headers;
};
export type getApiAdminRevenueResponseError = (getApiAdminRevenueResponse404) & {
  headers: Headers;
};

export type getApiAdminRevenueResponse = (getApiAdminRevenueResponseSuccess | getApiAdminRevenueResponseError)

export const getGetApiAdminRevenueUrl = (params?: GetApiAdminRevenueParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/revenue?${stringifiedParams}` : `/api/admin/revenue`
}

/**
 * @summary MRR, payments, churn risk, and which paywall converts
 */
export const getApiAdminRevenue = async (params?: GetApiAdminRevenueParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminRevenueResponse> => {

  return customFetch<getApiAdminRevenueResponse>(getGetApiAdminRevenueUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminRevenueQueryKey = (params?: GetApiAdminRevenueParams,) => {
    return [
    `/api/admin/revenue`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminRevenueQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminRevenue>>, TError = void>(params?: GetApiAdminRevenueParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminRevenue>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminRevenueQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminRevenue>>> = ({ signal }) => getApiAdminRevenue(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminRevenue>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminRevenueQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminRevenue>>>
export type GetApiAdminRevenueQueryError = void


/**
 * @summary MRR, payments, churn risk, and which paywall converts
 */

export function useGetApiAdminRevenue<TData = Awaited<ReturnType<typeof getApiAdminRevenue>>, TError = void>(
 params?: GetApiAdminRevenueParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminRevenue>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminRevenueQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminAiResponse200 = {
  data: GetApiAdminAi200
  status: 200
}

export type getApiAdminAiResponse404 = {
  data: void
  status: 404
}

export type getApiAdminAiResponseSuccess = (getApiAdminAiResponse200) & {
  headers: Headers;
};
export type getApiAdminAiResponseError = (getApiAdminAiResponse404) & {
  headers: Headers;
};

export type getApiAdminAiResponse = (getApiAdminAiResponseSuccess | getApiAdminAiResponseError)

export const getGetApiAdminAiUrl = (params?: GetApiAdminAiParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/ai?${stringifiedParams}` : `/api/admin/ai`
}

/**
 * @summary AI spend, latency, and which accounts cost more than they pay
 */
export const getApiAdminAi = async (params?: GetApiAdminAiParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminAiResponse> => {

  return customFetch<getApiAdminAiResponse>(getGetApiAdminAiUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminAiQueryKey = (params?: GetApiAdminAiParams,) => {
    return [
    `/api/admin/ai`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminAiQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminAi>>, TError = void>(params?: GetApiAdminAiParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAi>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminAiQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminAi>>> = ({ signal }) => getApiAdminAi(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAi>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminAiQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAi>>>
export type GetApiAdminAiQueryError = void


/**
 * @summary AI spend, latency, and which accounts cost more than they pay
 */

export function useGetApiAdminAi<TData = Awaited<ReturnType<typeof getApiAdminAi>>, TError = void>(
 params?: GetApiAdminAiParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminAi>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminAiQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminHealthResponse200 = {
  data: GetApiAdminHealth200
  status: 200
}

export type getApiAdminHealthResponse404 = {
  data: void
  status: 404
}

export type getApiAdminHealthResponseSuccess = (getApiAdminHealthResponse200) & {
  headers: Headers;
};
export type getApiAdminHealthResponseError = (getApiAdminHealthResponse404) & {
  headers: Headers;
};

export type getApiAdminHealthResponse = (getApiAdminHealthResponseSuccess | getApiAdminHealthResponseError)

export const getGetApiAdminHealthUrl = (params?: GetApiAdminHealthParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/health?${stringifiedParams}` : `/api/admin/health`
}

/**
 * @summary Webhooks, billing events, integrations, email deliverability, storage
 */
export const getApiAdminHealth = async (params?: GetApiAdminHealthParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminHealthResponse> => {

  return customFetch<getApiAdminHealthResponse>(getGetApiAdminHealthUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminHealthQueryKey = (params?: GetApiAdminHealthParams,) => {
    return [
    `/api/admin/health`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminHealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminHealth>>, TError = void>(params?: GetApiAdminHealthParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminHealth>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminHealthQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminHealth>>> = ({ signal }) => getApiAdminHealth(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminHealth>>>
export type GetApiAdminHealthQueryError = void


/**
 * @summary Webhooks, billing events, integrations, email deliverability, storage
 */

export function useGetApiAdminHealth<TData = Awaited<ReturnType<typeof getApiAdminHealth>>, TError = void>(
 params?: GetApiAdminHealthParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminHealth>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminHealthQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiAdminUsersResponse200 = {
  data: GetApiAdminUsers200
  status: 200
}

export type getApiAdminUsersResponse404 = {
  data: void
  status: 404
}

export type getApiAdminUsersResponseSuccess = (getApiAdminUsersResponse200) & {
  headers: Headers;
};
export type getApiAdminUsersResponseError = (getApiAdminUsersResponse404) & {
  headers: Headers;
};

export type getApiAdminUsersResponse = (getApiAdminUsersResponseSuccess | getApiAdminUsersResponseError)

export const getGetApiAdminUsersUrl = (params?: GetApiAdminUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/users?${stringifiedParams}` : `/api/admin/users`
}

/**
 * @summary Every person, their organizations and their last sign-in
 */
export const getApiAdminUsers = async (params?: GetApiAdminUsersParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiAdminUsersResponse> => {

  return customFetch<getApiAdminUsersResponse>(getGetApiAdminUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAdminUsersQueryKey = (params?: GetApiAdminUsersParams,) => {
    return [
    `/api/admin/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(params?: GetApiAdminUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminUsers>>> = ({ signal }) => getApiAdminUsers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminUsers>>>
export type GetApiAdminUsersQueryError = void


/**
 * @summary Every person, their organizations and their last sign-in
 */

export function useGetApiAdminUsers<TData = Awaited<ReturnType<typeof getApiAdminUsers>>, TError = void>(
 params?: GetApiAdminUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAdminUsersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiAdminBillingEventsByIdReprocessResponse200 = {
  data: PostApiAdminBillingEventsByIdReprocess200
  status: 200
}

export type postApiAdminBillingEventsByIdReprocessResponse404 = {
  data: void
  status: 404
}

export type postApiAdminBillingEventsByIdReprocessResponseSuccess = (postApiAdminBillingEventsByIdReprocessResponse200) & {
  headers: Headers;
};
export type postApiAdminBillingEventsByIdReprocessResponseError = (postApiAdminBillingEventsByIdReprocessResponse404) & {
  headers: Headers;
};

export type postApiAdminBillingEventsByIdReprocessResponse = (postApiAdminBillingEventsByIdReprocessResponseSuccess | postApiAdminBillingEventsByIdReprocessResponseError)

export const getPostApiAdminBillingEventsByIdReprocessUrl = (id: string,) => {




  return `/api/admin/billing-events/${id}/reprocess`
}

/**
 * @summary Re-run a stored Dodo webhook event through the handler
 */
export const postApiAdminBillingEventsByIdReprocess = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiAdminBillingEventsByIdReprocessResponse> => {

  return customFetch<postApiAdminBillingEventsByIdReprocessResponse>(getPostApiAdminBillingEventsByIdReprocessUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiAdminBillingEventsByIdReprocessMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminBillingEventsByIdReprocess>>, TError,PostApiAdminBillingEventsByIdReprocessMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminBillingEventsByIdReprocess>>, TError,PostApiAdminBillingEventsByIdReprocessMutationVariables, TContext> => {

const mutationKey = ['postApiAdminBillingEventsByIdReprocess'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminBillingEventsByIdReprocess>>, PostApiAdminBillingEventsByIdReprocessMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminBillingEventsByIdReprocess(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminBillingEventsByIdReprocessMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminBillingEventsByIdReprocess>>>

    export type PostApiAdminBillingEventsByIdReprocessMutationError = void
    export type PostApiAdminBillingEventsByIdReprocessMutationVariables = {id: string}

    /**
 * @summary Re-run a stored Dodo webhook event through the handler
 */
export const usePostApiAdminBillingEventsByIdReprocess = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminBillingEventsByIdReprocess>>, TError,PostApiAdminBillingEventsByIdReprocessMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminBillingEventsByIdReprocess>>,
        TError,
        PostApiAdminBillingEventsByIdReprocessMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAdminBillingEventsByIdReprocessMutationOptions(options));
    }
    export type postApiAdminSubscriptionsByIdGraceResponse200 = {
  data: PostApiAdminSubscriptionsByIdGrace200
  status: 200
}

export type postApiAdminSubscriptionsByIdGraceResponse404 = {
  data: void
  status: 404
}

export type postApiAdminSubscriptionsByIdGraceResponseSuccess = (postApiAdminSubscriptionsByIdGraceResponse200) & {
  headers: Headers;
};
export type postApiAdminSubscriptionsByIdGraceResponseError = (postApiAdminSubscriptionsByIdGraceResponse404) & {
  headers: Headers;
};

export type postApiAdminSubscriptionsByIdGraceResponse = (postApiAdminSubscriptionsByIdGraceResponseSuccess | postApiAdminSubscriptionsByIdGraceResponseError)

export const getPostApiAdminSubscriptionsByIdGraceUrl = (id: string,) => {




  return `/api/admin/subscriptions/${id}/grace`
}

/**
 * @summary Extend the dunning grace period on a subscription
 */
export const postApiAdminSubscriptionsByIdGrace = async (id: string,
    postApiAdminSubscriptionsByIdGraceBody: PostApiAdminSubscriptionsByIdGraceBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiAdminSubscriptionsByIdGraceResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiAdminSubscriptionsByIdGraceResponse>(getPostApiAdminSubscriptionsByIdGraceUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAdminSubscriptionsByIdGraceBody)
  }
);}





export const getPostApiAdminSubscriptionsByIdGraceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubscriptionsByIdGrace>>, TError,PostApiAdminSubscriptionsByIdGraceMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubscriptionsByIdGrace>>, TError,PostApiAdminSubscriptionsByIdGraceMutationVariables, TContext> => {

const mutationKey = ['postApiAdminSubscriptionsByIdGrace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSubscriptionsByIdGrace>>, PostApiAdminSubscriptionsByIdGraceMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAdminSubscriptionsByIdGrace(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSubscriptionsByIdGraceMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSubscriptionsByIdGrace>>>
    export type PostApiAdminSubscriptionsByIdGraceMutationBody = PostApiAdminSubscriptionsByIdGraceBody
    export type PostApiAdminSubscriptionsByIdGraceMutationError = void
    export type PostApiAdminSubscriptionsByIdGraceMutationVariables = {id: string;data: PostApiAdminSubscriptionsByIdGraceBody}

    /**
 * @summary Extend the dunning grace period on a subscription
 */
export const usePostApiAdminSubscriptionsByIdGrace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubscriptionsByIdGrace>>, TError,PostApiAdminSubscriptionsByIdGraceMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSubscriptionsByIdGrace>>,
        TError,
        PostApiAdminSubscriptionsByIdGraceMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAdminSubscriptionsByIdGraceMutationOptions(options));
    }
    export type postApiAdminAccountsByOrgIdOverridesResponse200 = {
  data: PostApiAdminAccountsByOrgIdOverrides200
  status: 200
}

export type postApiAdminAccountsByOrgIdOverridesResponse404 = {
  data: void
  status: 404
}

export type postApiAdminAccountsByOrgIdOverridesResponseSuccess = (postApiAdminAccountsByOrgIdOverridesResponse200) & {
  headers: Headers;
};
export type postApiAdminAccountsByOrgIdOverridesResponseError = (postApiAdminAccountsByOrgIdOverridesResponse404) & {
  headers: Headers;
};

export type postApiAdminAccountsByOrgIdOverridesResponse = (postApiAdminAccountsByOrgIdOverridesResponseSuccess | postApiAdminAccountsByOrgIdOverridesResponseError)

export const getPostApiAdminAccountsByOrgIdOverridesUrl = (orgId: string,) => {




  return `/api/admin/accounts/${orgId}/overrides`
}

/**
 * @summary Grant a feature or raise a limit for one organization
 */
export const postApiAdminAccountsByOrgIdOverrides = async (orgId: string,
    postApiAdminAccountsByOrgIdOverridesBody: PostApiAdminAccountsByOrgIdOverridesBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiAdminAccountsByOrgIdOverridesResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiAdminAccountsByOrgIdOverridesResponse>(getPostApiAdminAccountsByOrgIdOverridesUrl(orgId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAdminAccountsByOrgIdOverridesBody)
  }
);}





export const getPostApiAdminAccountsByOrgIdOverridesMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdOverrides>>, TError,PostApiAdminAccountsByOrgIdOverridesMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdOverrides>>, TError,PostApiAdminAccountsByOrgIdOverridesMutationVariables, TContext> => {

const mutationKey = ['postApiAdminAccountsByOrgIdOverrides'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdOverrides>>, PostApiAdminAccountsByOrgIdOverridesMutationVariables> = (props) => {
          const {orgId,data} = props ?? {};

          return  postApiAdminAccountsByOrgIdOverrides(orgId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminAccountsByOrgIdOverridesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdOverrides>>>
    export type PostApiAdminAccountsByOrgIdOverridesMutationBody = PostApiAdminAccountsByOrgIdOverridesBody
    export type PostApiAdminAccountsByOrgIdOverridesMutationError = void
    export type PostApiAdminAccountsByOrgIdOverridesMutationVariables = {orgId: string;data: PostApiAdminAccountsByOrgIdOverridesBody}

    /**
 * @summary Grant a feature or raise a limit for one organization
 */
export const usePostApiAdminAccountsByOrgIdOverrides = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdOverrides>>, TError,PostApiAdminAccountsByOrgIdOverridesMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdOverrides>>,
        TError,
        PostApiAdminAccountsByOrgIdOverridesMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAdminAccountsByOrgIdOverridesMutationOptions(options));
    }
    export type deleteApiAdminAccountsByOrgIdOverridesByKeyResponse200 = {
  data: DeleteApiAdminAccountsByOrgIdOverridesByKey200
  status: 200
}

export type deleteApiAdminAccountsByOrgIdOverridesByKeyResponse404 = {
  data: void
  status: 404
}

export type deleteApiAdminAccountsByOrgIdOverridesByKeyResponseSuccess = (deleteApiAdminAccountsByOrgIdOverridesByKeyResponse200) & {
  headers: Headers;
};
export type deleteApiAdminAccountsByOrgIdOverridesByKeyResponseError = (deleteApiAdminAccountsByOrgIdOverridesByKeyResponse404) & {
  headers: Headers;
};

export type deleteApiAdminAccountsByOrgIdOverridesByKeyResponse = (deleteApiAdminAccountsByOrgIdOverridesByKeyResponseSuccess | deleteApiAdminAccountsByOrgIdOverridesByKeyResponseError)

export const getDeleteApiAdminAccountsByOrgIdOverridesByKeyUrl = (orgId: string,
    key: string,) => {




  return `/api/admin/accounts/${orgId}/overrides/${key}`
}

/**
 * @summary Revoke an entitlement override
 */
export const deleteApiAdminAccountsByOrgIdOverridesByKey = async (orgId: string,
    key: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteApiAdminAccountsByOrgIdOverridesByKeyResponse> => {

  return customFetch<deleteApiAdminAccountsByOrgIdOverridesByKeyResponse>(getDeleteApiAdminAccountsByOrgIdOverridesByKeyUrl(orgId,key),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiAdminAccountsByOrgIdOverridesByKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdOverridesByKey>>, TError,DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdOverridesByKey>>, TError,DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationVariables, TContext> => {

const mutationKey = ['deleteApiAdminAccountsByOrgIdOverridesByKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdOverridesByKey>>, DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationVariables> = (props) => {
          const {orgId,key} = props ?? {};

          return  deleteApiAdminAccountsByOrgIdOverridesByKey(orgId,key,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdOverridesByKey>>>

    export type DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationError = void
    export type DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationVariables = {orgId: string;key: string}

    /**
 * @summary Revoke an entitlement override
 */
export const useDeleteApiAdminAccountsByOrgIdOverridesByKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdOverridesByKey>>, TError,DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdOverridesByKey>>,
        TError,
        DeleteApiAdminAccountsByOrgIdOverridesByKeyMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiAdminAccountsByOrgIdOverridesByKeyMutationOptions(options));
    }
    export type postApiAdminAccountsByOrgIdRefreshEntitlementsResponse200 = {
  data: PostApiAdminAccountsByOrgIdRefreshEntitlements200
  status: 200
}

export type postApiAdminAccountsByOrgIdRefreshEntitlementsResponse404 = {
  data: void
  status: 404
}

export type postApiAdminAccountsByOrgIdRefreshEntitlementsResponseSuccess = (postApiAdminAccountsByOrgIdRefreshEntitlementsResponse200) & {
  headers: Headers;
};
export type postApiAdminAccountsByOrgIdRefreshEntitlementsResponseError = (postApiAdminAccountsByOrgIdRefreshEntitlementsResponse404) & {
  headers: Headers;
};

export type postApiAdminAccountsByOrgIdRefreshEntitlementsResponse = (postApiAdminAccountsByOrgIdRefreshEntitlementsResponseSuccess | postApiAdminAccountsByOrgIdRefreshEntitlementsResponseError)

export const getPostApiAdminAccountsByOrgIdRefreshEntitlementsUrl = (orgId: string,) => {




  return `/api/admin/accounts/${orgId}/refresh-entitlements`
}

/**
 * @summary Drop the cached entitlements for one organization
 */
export const postApiAdminAccountsByOrgIdRefreshEntitlements = async (orgId: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiAdminAccountsByOrgIdRefreshEntitlementsResponse> => {

  return customFetch<postApiAdminAccountsByOrgIdRefreshEntitlementsResponse>(getPostApiAdminAccountsByOrgIdRefreshEntitlementsUrl(orgId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiAdminAccountsByOrgIdRefreshEntitlementsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdRefreshEntitlements>>, TError,PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdRefreshEntitlements>>, TError,PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationVariables, TContext> => {

const mutationKey = ['postApiAdminAccountsByOrgIdRefreshEntitlements'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdRefreshEntitlements>>, PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationVariables> = (props) => {
          const {orgId} = props ?? {};

          return  postApiAdminAccountsByOrgIdRefreshEntitlements(orgId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdRefreshEntitlements>>>

    export type PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationError = void
    export type PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationVariables = {orgId: string}

    /**
 * @summary Drop the cached entitlements for one organization
 */
export const usePostApiAdminAccountsByOrgIdRefreshEntitlements = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdRefreshEntitlements>>, TError,PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdRefreshEntitlements>>,
        TError,
        PostApiAdminAccountsByOrgIdRefreshEntitlementsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAdminAccountsByOrgIdRefreshEntitlementsMutationOptions(options));
    }
    export type postApiAdminAccountsByOrgIdPlanResponse200 = {
  data: PostApiAdminAccountsByOrgIdPlan200
  status: 200
}

export type postApiAdminAccountsByOrgIdPlanResponse404 = {
  data: void
  status: 404
}

export type postApiAdminAccountsByOrgIdPlanResponse409 = {
  data: void
  status: 409
}

export type postApiAdminAccountsByOrgIdPlanResponseSuccess = (postApiAdminAccountsByOrgIdPlanResponse200) & {
  headers: Headers;
};
export type postApiAdminAccountsByOrgIdPlanResponseError = (postApiAdminAccountsByOrgIdPlanResponse404 | postApiAdminAccountsByOrgIdPlanResponse409) & {
  headers: Headers;
};

export type postApiAdminAccountsByOrgIdPlanResponse = (postApiAdminAccountsByOrgIdPlanResponseSuccess | postApiAdminAccountsByOrgIdPlanResponseError)

export const getPostApiAdminAccountsByOrgIdPlanUrl = (orgId: string,) => {




  return `/api/admin/accounts/${orgId}/plan`
}

/**
 * @summary Put one organization on a paid plan at no charge
 */
export const postApiAdminAccountsByOrgIdPlan = async (orgId: string,
    postApiAdminAccountsByOrgIdPlanBody: PostApiAdminAccountsByOrgIdPlanBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiAdminAccountsByOrgIdPlanResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiAdminAccountsByOrgIdPlanResponse>(getPostApiAdminAccountsByOrgIdPlanUrl(orgId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAdminAccountsByOrgIdPlanBody)
  }
);}





export const getPostApiAdminAccountsByOrgIdPlanMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdPlan>>, TError,PostApiAdminAccountsByOrgIdPlanMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdPlan>>, TError,PostApiAdminAccountsByOrgIdPlanMutationVariables, TContext> => {

const mutationKey = ['postApiAdminAccountsByOrgIdPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdPlan>>, PostApiAdminAccountsByOrgIdPlanMutationVariables> = (props) => {
          const {orgId,data} = props ?? {};

          return  postApiAdminAccountsByOrgIdPlan(orgId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminAccountsByOrgIdPlanMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdPlan>>>
    export type PostApiAdminAccountsByOrgIdPlanMutationBody = PostApiAdminAccountsByOrgIdPlanBody
    export type PostApiAdminAccountsByOrgIdPlanMutationError = void
    export type PostApiAdminAccountsByOrgIdPlanMutationVariables = {orgId: string;data: PostApiAdminAccountsByOrgIdPlanBody}

    /**
 * @summary Put one organization on a paid plan at no charge
 */
export const usePostApiAdminAccountsByOrgIdPlan = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdPlan>>, TError,PostApiAdminAccountsByOrgIdPlanMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminAccountsByOrgIdPlan>>,
        TError,
        PostApiAdminAccountsByOrgIdPlanMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAdminAccountsByOrgIdPlanMutationOptions(options));
    }
    export type deleteApiAdminAccountsByOrgIdPlanResponse200 = {
  data: DeleteApiAdminAccountsByOrgIdPlan200
  status: 200
}

export type deleteApiAdminAccountsByOrgIdPlanResponse404 = {
  data: void
  status: 404
}

export type deleteApiAdminAccountsByOrgIdPlanResponseSuccess = (deleteApiAdminAccountsByOrgIdPlanResponse200) & {
  headers: Headers;
};
export type deleteApiAdminAccountsByOrgIdPlanResponseError = (deleteApiAdminAccountsByOrgIdPlanResponse404) & {
  headers: Headers;
};

export type deleteApiAdminAccountsByOrgIdPlanResponse = (deleteApiAdminAccountsByOrgIdPlanResponseSuccess | deleteApiAdminAccountsByOrgIdPlanResponseError)

export const getDeleteApiAdminAccountsByOrgIdPlanUrl = (orgId: string,) => {




  return `/api/admin/accounts/${orgId}/plan`
}

/**
 * @summary Remove a comped plan from one organization
 */
export const deleteApiAdminAccountsByOrgIdPlan = async (orgId: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteApiAdminAccountsByOrgIdPlanResponse> => {

  return customFetch<deleteApiAdminAccountsByOrgIdPlanResponse>(getDeleteApiAdminAccountsByOrgIdPlanUrl(orgId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiAdminAccountsByOrgIdPlanMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdPlan>>, TError,DeleteApiAdminAccountsByOrgIdPlanMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdPlan>>, TError,DeleteApiAdminAccountsByOrgIdPlanMutationVariables, TContext> => {

const mutationKey = ['deleteApiAdminAccountsByOrgIdPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdPlan>>, DeleteApiAdminAccountsByOrgIdPlanMutationVariables> = (props) => {
          const {orgId} = props ?? {};

          return  deleteApiAdminAccountsByOrgIdPlan(orgId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAdminAccountsByOrgIdPlanMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdPlan>>>

    export type DeleteApiAdminAccountsByOrgIdPlanMutationError = void
    export type DeleteApiAdminAccountsByOrgIdPlanMutationVariables = {orgId: string}

    /**
 * @summary Remove a comped plan from one organization
 */
export const useDeleteApiAdminAccountsByOrgIdPlan = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdPlan>>, TError,DeleteApiAdminAccountsByOrgIdPlanMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAdminAccountsByOrgIdPlan>>,
        TError,
        DeleteApiAdminAccountsByOrgIdPlanMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiAdminAccountsByOrgIdPlanMutationOptions(options));
    }
    export type postApiAdminImpersonateResponse200 = {
  data: PostApiAdminImpersonate200
  status: 200
}

export type postApiAdminImpersonateResponse404 = {
  data: void
  status: 404
}

export type postApiAdminImpersonateResponseSuccess = (postApiAdminImpersonateResponse200) & {
  headers: Headers;
};
export type postApiAdminImpersonateResponseError = (postApiAdminImpersonateResponse404) & {
  headers: Headers;
};

export type postApiAdminImpersonateResponse = (postApiAdminImpersonateResponseSuccess | postApiAdminImpersonateResponseError)

export const getPostApiAdminImpersonateUrl = () => {




  return `/api/admin/impersonate`
}

/**
 * @summary Mint a short-lived token to act as a customer
 */
export const postApiAdminImpersonate = async (postApiAdminImpersonateBody: PostApiAdminImpersonateBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiAdminImpersonateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiAdminImpersonateResponse>(getPostApiAdminImpersonateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAdminImpersonateBody)
  }
);}





export const getPostApiAdminImpersonateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminImpersonate>>, TError,PostApiAdminImpersonateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminImpersonate>>, TError,PostApiAdminImpersonateMutationVariables, TContext> => {

const mutationKey = ['postApiAdminImpersonate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminImpersonate>>, PostApiAdminImpersonateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAdminImpersonate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminImpersonateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminImpersonate>>>
    export type PostApiAdminImpersonateMutationBody = PostApiAdminImpersonateBody
    export type PostApiAdminImpersonateMutationError = void
    export type PostApiAdminImpersonateMutationVariables = {data: PostApiAdminImpersonateBody}

    /**
 * @summary Mint a short-lived token to act as a customer
 */
export const usePostApiAdminImpersonate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminImpersonate>>, TError,PostApiAdminImpersonateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminImpersonate>>,
        TError,
        PostApiAdminImpersonateMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAdminImpersonateMutationOptions(options));
    }
