import { defineTemplate, type TemplateSeed } from "./define.js";

export const HR: TemplateSeed[] = [
  defineTemplate({
    slug: "job-application",
    title: "Job application",
    category: "HR",
    icon: "Briefcase",
    description: "Screen candidates with experience, links and a cover note.",
    blurb:
      "Everything a first-pass review needs and nothing it doesn't: who they are, what they've built, how much notice they have, and why this role. The CV upload is there, but the answers stand on their own.",
    tags: ["hiring", "recruiting", "candidates"],
    greeting: "Glad you're interested in joining us. Let's start.",
    questions: [
      { ref: "name", type: "short_text", title: "Your full name?", required: true },
      { ref: "email", type: "email", title: "Email address?", required: true },
      {
        ref: "role",
        type: "single_select",
        title: "Which role are you applying for?",
        required: true,
        options: [
          { label: "Engineering" },
          { label: "Design" },
          { label: "Product" },
          { label: "Sales" },
          { label: "Operations" },
        ],
      },
      { ref: "experience_years", type: "number", title: "How many years of relevant experience?", required: true, integerOnly: true, min: 0, max: 60 },
      { ref: "portfolio", type: "url", title: "Portfolio, GitHub or LinkedIn", required: false },
      { ref: "cv", type: "file_upload", title: "Attach your CV", required: false, accept: ["application/pdf", "application/msword"], maxFiles: 1, maxSizeMB: 10 },
      { ref: "motivation", type: "long_text", title: "Why do you want to work with us?", required: true, maxLength: 1500 },
      {
        ref: "notice_period",
        type: "single_select",
        title: "When could you start?",
        required: true,
        options: [
          { label: "Immediately" },
          { label: "Within a month" },
          { label: "One to three months" },
          { label: "Longer than three months" },
        ],
      },
    ],
    ending: { title: "Application received 🚀", body: "We review every application within a week." },
  }),

  defineTemplate({
    slug: "employee-onboarding",
    title: "Employee onboarding",
    category: "HR",
    icon: "UserCheck",
    description: "Collect what a new starter needs before day one.",
    blurb:
      "The details that otherwise arrive as five separate emails in the first week: legal name, address, start date, equipment preference, and a signature on the handbook.",
    tags: ["onboarding", "people ops", "new hire"],
    greeting: "Welcome aboard! A few details so everything's ready on your first day.",
    questions: [
      { ref: "legal_name", type: "short_text", title: "Your full legal name?", required: true },
      { ref: "personal_email", type: "email", title: "A personal email we can reach you on", required: true },
      { ref: "phone", type: "phone", title: "Mobile number?", required: true },
      { ref: "address", type: "address", title: "Where should we ship your kit?", required: true, fields: ["street", "city", "state", "postal", "country"] },
      { ref: "start_date", type: "date", title: "Confirm your start date", required: true, disablePast: true },
      {
        ref: "equipment",
        type: "single_select",
        title: "Which laptop would you like?",
        required: true,
        options: [{ label: "MacBook Pro" }, { label: "MacBook Air" }, { label: "Windows laptop" }, { label: "Linux laptop" }],
      },
      { ref: "dietary", type: "short_text", title: "Any dietary requirements for team lunches?", required: false },
      { ref: "handbook", type: "signature", title: "Sign to confirm you've read the employee handbook", required: true, drawnNameRequired: true },
    ],
    ending: { title: "All set 🎊", body: "See you on day one — we'll email the schedule shortly." },
  }),

  defineTemplate({
    slug: "exit-interview",
    title: "Exit interview",
    category: "HR",
    icon: "LogOut",
    description: "Ask why someone is leaving in a way they can answer honestly.",
    blurb:
      "Leaving is when people say what they meant. Keep it structured enough to count across a year of departures, open enough to catch the thing no option covers, and make clear it's confidential.",
    tags: ["retention", "people ops", "offboarding"],
    greeting: "Before you go — your honest answers help the people staying. This is confidential.",
    questions: [
      {
        ref: "primary_reason",
        type: "single_select",
        title: "What's the main reason you're leaving?",
        required: true,
        options: [
          { label: "Compensation" },
          { label: "Career growth" },
          { label: "Manager or team" },
          { label: "Work-life balance" },
          { label: "Company direction" },
          { label: "Personal reasons" },
        ],
      },
      {
        ref: "ratings",
        type: "matrix",
        title: "How would you rate each of these?",
        required: true,
        rows: ["Your manager", "Your team", "Compensation", "Growth opportunities", "Work-life balance"],
        columns: ["Poor", "Fair", "Good", "Excellent"],
      },
      { ref: "what_worked", type: "long_text", title: "What worked well here?", required: false, maxLength: 1000 },
      { ref: "what_to_change", type: "long_text", title: "What would you change?", required: false, maxLength: 1200 },
      { ref: "recommend", type: "nps", title: "How likely are you to recommend us as a place to work?", required: false },
      { ref: "boomerang", type: "yes_no", title: "Would you consider working here again one day?", required: false },
    ],
    ending: { title: "Thank you — genuinely 🙏", body: "All the best for what's next." },
  }),

  defineTemplate({
    slug: "engagement-pulse",
    title: "Engagement pulse",
    category: "HR",
    icon: "HeartPulse",
    description: "A short, repeatable check on how the team is doing.",
    blurb:
      "Short enough to send monthly and consistent enough to trend. Five scaled questions that stay identical every round, and one open box for whatever this month happens to be about.",
    tags: ["culture", "pulse", "people ops"],
    greeting: "Quick pulse check — anonymous, and under two minutes.",
    questions: [
      { ref: "workload", type: "opinion_scale", title: "My workload is manageable.", required: true, steps: 5, labelLow: "Strongly disagree", labelHigh: "Strongly agree" },
      { ref: "clarity", type: "opinion_scale", title: "I'm clear on what's expected of me.", required: true, steps: 5, labelLow: "Strongly disagree", labelHigh: "Strongly agree" },
      { ref: "support", type: "opinion_scale", title: "I get the support I need from my manager.", required: true, steps: 5, labelLow: "Strongly disagree", labelHigh: "Strongly agree" },
      { ref: "growth", type: "opinion_scale", title: "I'm learning and growing here.", required: true, steps: 5, labelLow: "Strongly disagree", labelHigh: "Strongly agree" },
      { ref: "enps", type: "nps", title: "How likely are you to recommend us as a place to work?", required: true },
      { ref: "anything_else", type: "long_text", title: "Anything on your mind?", required: false, maxLength: 1000 },
    ],
    ending: { title: "Thanks 💬", body: "Results are shared with the whole team." },
  }),

  defineTemplate({
    slug: "referral-submission",
    title: "Employee referral",
    category: "HR",
    icon: "Users",
    description: "Make referring someone take a minute, not an afternoon.",
    blurb:
      "Referral schemes die on friction. Name, contact, role, and one honest line about why they'd be good — enough for a recruiter to act on and short enough that people actually submit.",
    tags: ["referral", "hiring", "internal"],
    greeting: "Know someone great? Put them forward.",
    questions: [
      { ref: "referrer", type: "short_text", title: "Your name?", required: true },
      { ref: "candidate_name", type: "short_text", title: "Who are you referring?", required: true },
      { ref: "candidate_contact", type: "short_text", title: "How can we reach them? Email or LinkedIn.", required: true },
      {
        ref: "role",
        type: "dropdown",
        title: "Which role?",
        required: true,
        options: [
          { label: "Engineering" },
          { label: "Design" },
          { label: "Product" },
          { label: "Sales" },
          { label: "Operations" },
          { label: "Open application" },
        ],
      },
      { ref: "why", type: "long_text", title: "Why would they be good here?", required: true, maxLength: 1000 },
      { ref: "has_consent", type: "yes_no", title: "Do they know you're referring them?", required: true },
    ],
    ending: { title: "Thanks for the referral 🙌", body: "We'll take it from here and keep you posted." },
  }),
];
