"use client";

import { useEffect } from "react";

/**
 * The frame's half of the embed protocol.
 *
 * `?embed=1` has been generated by both snippet writers since embedding shipped
 * and read by nobody, and `embed.js` listened for a close message nothing ever
 * sent. This is the other end of both.
 *
 * Mounted next to the chat rather than inside it, so what a host page can
 * observe is a deliberate, small surface rather than whatever the runtime
 * happens to expose.
 */

export interface ToParent {
  source: "chatform";
  v: 1;
  type: "ready" | "resize" | "question" | "answer" | "complete" | "close" | "error";
  [key: string]: unknown;
}

let post: ((message: Omit<ToParent, "source" | "v">) => void) | null = null;

/**
 * Tell the host page something happened.
 *
 * A module-level function rather than context, because the callers are inside a
 * component tree this one does not own, and a no-op when not embedded is exactly
 * the right behaviour for all of them.
 */
export function emitEmbedEvent(message: Omit<ToParent, "source" | "v">): void {
  post?.(message);
}

/**
 * Ask the host page to close the panel.
 *
 * `embed.js` has always handled an inbound `close`, and this end has always
 * been able to send one — what was missing was anything in the form that
 * *would*. So a framed form had no exit of its own: the launcher was the only
 * way out, and in side-tab and on a phone the launcher is underneath the sheet
 * it would be closing.
 *
 * Returns whether the message went anywhere, because the caller needs to know
 * whether to render a control at all. Untrusted parent, no frame, standalone
 * page — all three are `false`, and all three mean "do not offer a close".
 */
export function requestEmbedClose(): boolean {
  if (!post) return false;
  post({ type: "close" });
  return true;
}

/**
 * Whether this form is framed by a host page that accepted our handshake.
 *
 * Subscribable, because the answer is not known at first render — the handshake
 * runs in an effect — and a close button that appears a tick late is correct
 * where one rendered eagerly and wired to nothing is a lie.
 */
const bridgeListeners = new Set<() => void>();

export function embedBridgeReady(): boolean {
  return post !== null;
}

export function subscribeEmbedBridge(onChange: () => void): () => void {
  bridgeListeners.add(onChange);
  return () => {
    bridgeListeners.delete(onChange);
  };
}

function setPost(next: typeof post): void {
  if (post === next) return;
  post = next;
  for (const listener of bridgeListeners) listener();
}

export function EmbedBridge({
  parentOrigin,
  allowedOrigins,
}: {
  parentOrigin: string | null;
  /** From the form's settings. Empty means embeddable anywhere. */
  allowedOrigins: string[];
}) {
  useEffect(() => {
    if (window.parent === window || !parentOrigin) return;

    /**
     * The parent's origin arrives as a query parameter, so it is
     * attacker-controlled and used for exactly one thing: the `targetOrigin` of
     * postMessage. It is checked against the form's allowlist first, and `"*"`
     * is never used — that is what would leak the question stream to any page
     * that framed us.
     *
     * This is not the security boundary. Opening a session checks the `Origin`
     * header the browser sets, which a page cannot forge.
     */
    const trusted =
      allowedOrigins.length === 0 ||
      allowedOrigins.some((entry) => {
        if (entry === parentOrigin) return true;
        const star = entry.indexOf("://*.");
        if (star === -1) return false;
        try {
          const url = new URL(parentOrigin);
          const suffix = entry.slice(star + 4);
          return `${entry.slice(0, star)}:` === url.protocol && url.host.endsWith(suffix);
        } catch {
          return false;
        }
      });
    if (!trusted) return;

    const send = (message: Omit<ToParent, "source" | "v">) => {
      window.parent.postMessage({ source: "chatform", v: 1, ...message }, parentOrigin);
    };
    setPost(send);
    send({ type: "ready" });

    /**
     * Height, coalesced.
     *
     * An uncoalesced ResizeObserver on a view that grows by a token at a time
     * fires roughly sixty times a second, and every one of those is a
     * cross-origin message plus a layout in the host page.
     */
    let frame = 0;
    let lastHeight = 0;
    const observer = new ResizeObserver(() => {
      cancelAnimationFrame(frame);
      frame = requestAnimationFrame(() => {
        const height = Math.ceil(document.documentElement.scrollHeight);
        if (Math.abs(height - lastHeight) < 2) return;
        lastHeight = height;
        send({ type: "resize", height });
      });
    });
    observer.observe(document.documentElement);

    const onMessage = (event: MessageEvent) => {
      if (event.origin !== parentOrigin) return;
      const message = event.data as { source?: string; type?: string; fields?: Record<string, string> };
      if (message?.source !== "chatform") return;
      if (message.type === "close") send({ type: "close" });
    };
    window.addEventListener("message", onMessage);

    return () => {
      observer.disconnect();
      cancelAnimationFrame(frame);
      window.removeEventListener("message", onMessage);
      setPost(null);
    };
  }, [parentOrigin, allowedOrigins]);

  return null;
}
