/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPFormsBySlugConfig404,
  PostPFormsBySlugSessions200,
  PostPFormsBySlugSessions403,
  PostPFormsBySlugSessions404,
  PostPFormsBySlugSessionsBody,
  PostPSessionsByIdUploadsByFileIdConfirm200,
  PostPSessionsByIdUploadsIntent200,
  PostPSessionsByIdUploadsIntentBody,
  PutPSessionsByIdUploadsByFileId200
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPFormsBySlugConfigResponse200 = {
  data: void
  status: 200
}

export type getPFormsBySlugConfigResponse404 = {
  data: GetPFormsBySlugConfig404
  status: 404
}

export type getPFormsBySlugConfigResponseSuccess = (getPFormsBySlugConfigResponse200) & {
  headers: Headers;
};
export type getPFormsBySlugConfigResponseError = (getPFormsBySlugConfigResponse404) & {
  headers: Headers;
};

export type getPFormsBySlugConfigResponse = (getPFormsBySlugConfigResponseSuccess | getPFormsBySlugConfigResponseError)

export const getGetPFormsBySlugConfigUrl = (slug: string,) => {




  return `/p/forms/${slug}/config`
}

/**
 * @summary Public rendering config for a published form
 */
export const getPFormsBySlugConfig = async (slug: string, options?: Parameters<typeof customFetch>[1]): Promise<getPFormsBySlugConfigResponse> => {

  return customFetch<getPFormsBySlugConfigResponse>(getGetPFormsBySlugConfigUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPFormsBySlugConfigQueryKey = (slug: string,) => {
    return [
    `/p/forms/${slug}/config`
    ] as const;
    }


export const getGetPFormsBySlugConfigQueryOptions = <TData = Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError = GetPFormsBySlugConfig404>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPFormsBySlugConfigQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPFormsBySlugConfig>>> = ({ signal }) => getPFormsBySlugConfig(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPFormsBySlugConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getPFormsBySlugConfig>>>
export type GetPFormsBySlugConfigQueryError = GetPFormsBySlugConfig404


/**
 * @summary Public rendering config for a published form
 */

export function useGetPFormsBySlugConfig<TData = Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError = GetPFormsBySlugConfig404>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPFormsBySlugConfigQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postPFormsBySlugSessionsResponse200 = {
  data: PostPFormsBySlugSessions200
  status: 200
}

export type postPFormsBySlugSessionsResponse403 = {
  data: PostPFormsBySlugSessions403
  status: 403
}

export type postPFormsBySlugSessionsResponse404 = {
  data: PostPFormsBySlugSessions404
  status: 404
}

export type postPFormsBySlugSessionsResponseSuccess = (postPFormsBySlugSessionsResponse200) & {
  headers: Headers;
};
export type postPFormsBySlugSessionsResponseError = (postPFormsBySlugSessionsResponse403 | postPFormsBySlugSessionsResponse404) & {
  headers: Headers;
};

export type postPFormsBySlugSessionsResponse = (postPFormsBySlugSessionsResponseSuccess | postPFormsBySlugSessionsResponseError)

export const getPostPFormsBySlugSessionsUrl = (slug: string,) => {




  return `/p/forms/${slug}/sessions`
}

/**
 * @summary Create a chat session for a published form
 */
export const postPFormsBySlugSessions = async (slug: string,
    postPFormsBySlugSessionsBody: PostPFormsBySlugSessionsBody, options?: Parameters<typeof customFetch>[1]): Promise<postPFormsBySlugSessionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postPFormsBySlugSessionsResponse>(getPostPFormsBySlugSessionsUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postPFormsBySlugSessionsBody)
  }
);}





export const getPostPFormsBySlugSessionsMutationOptions = <TError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext> => {

const mutationKey = ['postPFormsBySlugSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, PostPFormsBySlugSessionsMutationVariables> = (props) => {
          const {slug,data} = props ?? {};

          return  postPFormsBySlugSessions(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPFormsBySlugSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postPFormsBySlugSessions>>>
    export type PostPFormsBySlugSessionsMutationBody = PostPFormsBySlugSessionsBody
    export type PostPFormsBySlugSessionsMutationError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404
    export type PostPFormsBySlugSessionsMutationVariables = {slug: string;data: PostPFormsBySlugSessionsBody}

    /**
 * @summary Create a chat session for a published form
 */
export const usePostPFormsBySlugSessions = <TError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPFormsBySlugSessions>>,
        TError,
        PostPFormsBySlugSessionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostPFormsBySlugSessionsMutationOptions(options));
    }
    export type postPSessionsByIdUploadsIntentResponse200 = {
  data: PostPSessionsByIdUploadsIntent200
  status: 200
}

export type postPSessionsByIdUploadsIntentResponse413 = {
  data: void
  status: 413
}

export type postPSessionsByIdUploadsIntentResponse415 = {
  data: void
  status: 415
}

export type postPSessionsByIdUploadsIntentResponseSuccess = (postPSessionsByIdUploadsIntentResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdUploadsIntentResponseError = (postPSessionsByIdUploadsIntentResponse413 | postPSessionsByIdUploadsIntentResponse415) & {
  headers: Headers;
};

export type postPSessionsByIdUploadsIntentResponse = (postPSessionsByIdUploadsIntentResponseSuccess | postPSessionsByIdUploadsIntentResponseError)

export const getPostPSessionsByIdUploadsIntentUrl = (id: string,) => {




  return `/p/sessions/${id}/uploads/intent`
}

/**
 * @summary Register an upload — returns a fileId to PUT against
 */
export const postPSessionsByIdUploadsIntent = async (id: string,
    postPSessionsByIdUploadsIntentBody: PostPSessionsByIdUploadsIntentBody, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdUploadsIntentResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postPSessionsByIdUploadsIntentResponse>(getPostPSessionsByIdUploadsIntentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postPSessionsByIdUploadsIntentBody)
  }
);}





export const getPostPSessionsByIdUploadsIntentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdUploadsIntent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, PostPSessionsByIdUploadsIntentMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  postPSessionsByIdUploadsIntent(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdUploadsIntentMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>>
    export type PostPSessionsByIdUploadsIntentMutationBody = PostPSessionsByIdUploadsIntentBody
    export type PostPSessionsByIdUploadsIntentMutationError = void
    export type PostPSessionsByIdUploadsIntentMutationVariables = {id: string;data: PostPSessionsByIdUploadsIntentBody}

    /**
 * @summary Register an upload — returns a fileId to PUT against
 */
export const usePostPSessionsByIdUploadsIntent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>,
        TError,
        PostPSessionsByIdUploadsIntentMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdUploadsIntentMutationOptions(options));
    }
    export type putPSessionsByIdUploadsByFileIdResponse200 = {
  data: PutPSessionsByIdUploadsByFileId200
  status: 200
}

export type putPSessionsByIdUploadsByFileIdResponse400 = {
  data: void
  status: 400
}

export type putPSessionsByIdUploadsByFileIdResponse404 = {
  data: void
  status: 404
}

export type putPSessionsByIdUploadsByFileIdResponse413 = {
  data: void
  status: 413
}

export type putPSessionsByIdUploadsByFileIdResponseSuccess = (putPSessionsByIdUploadsByFileIdResponse200) & {
  headers: Headers;
};
export type putPSessionsByIdUploadsByFileIdResponseError = (putPSessionsByIdUploadsByFileIdResponse400 | putPSessionsByIdUploadsByFileIdResponse404 | putPSessionsByIdUploadsByFileIdResponse413) & {
  headers: Headers;
};

export type putPSessionsByIdUploadsByFileIdResponse = (putPSessionsByIdUploadsByFileIdResponseSuccess | putPSessionsByIdUploadsByFileIdResponseError)

export const getPutPSessionsByIdUploadsByFileIdUrl = (id: string,
    fileId: string,) => {




  return `/p/sessions/${id}/uploads/${fileId}`
}

/**
 * PUT the raw file body — not multipart, not base64 — to the `uploadUrl` returned by the intent step. The declared size must match within 1KB, and the object is not visible to the form until `confirm`.
 * @summary Upload the bytes for a registered intent
 */
export const putPSessionsByIdUploadsByFileId = async (id: string,
    fileId: string,
    putPSessionsByIdUploadsByFileIdBody: Blob, options?: Parameters<typeof customFetch>[1]): Promise<putPSessionsByIdUploadsByFileIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<putPSessionsByIdUploadsByFileIdResponse>(getPutPSessionsByIdUploadsByFileIdUrl(id,fileId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/octet-stream', ...getHeaders(options?.headers) },
    body: putPSessionsByIdUploadsByFileIdBody
  }
);}





export const getPutPSessionsByIdUploadsByFileIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, TError,PutPSessionsByIdUploadsByFileIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, TError,PutPSessionsByIdUploadsByFileIdMutationVariables, TContext> => {

const mutationKey = ['putPSessionsByIdUploadsByFileId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, PutPSessionsByIdUploadsByFileIdMutationVariables> = (props) => {
          const {id,fileId,data} = props ?? {};

          return  putPSessionsByIdUploadsByFileId(id,fileId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutPSessionsByIdUploadsByFileIdMutationResult = NonNullable<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>>
    export type PutPSessionsByIdUploadsByFileIdMutationBody = Blob
    export type PutPSessionsByIdUploadsByFileIdMutationError = void
    export type PutPSessionsByIdUploadsByFileIdMutationVariables = {id: string;fileId: string;data: Blob}

    /**
 * @summary Upload the bytes for a registered intent
 */
export const usePutPSessionsByIdUploadsByFileId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, TError,PutPSessionsByIdUploadsByFileIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>,
        TError,
        PutPSessionsByIdUploadsByFileIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutPSessionsByIdUploadsByFileIdMutationOptions(options));
    }
    export type postPSessionsByIdUploadsByFileIdConfirmResponse200 = {
  data: PostPSessionsByIdUploadsByFileIdConfirm200
  status: 200
}

export type postPSessionsByIdUploadsByFileIdConfirmResponse400 = {
  data: void
  status: 400
}

export type postPSessionsByIdUploadsByFileIdConfirmResponse404 = {
  data: void
  status: 404
}

export type postPSessionsByIdUploadsByFileIdConfirmResponseSuccess = (postPSessionsByIdUploadsByFileIdConfirmResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdUploadsByFileIdConfirmResponseError = (postPSessionsByIdUploadsByFileIdConfirmResponse400 | postPSessionsByIdUploadsByFileIdConfirmResponse404) & {
  headers: Headers;
};

export type postPSessionsByIdUploadsByFileIdConfirmResponse = (postPSessionsByIdUploadsByFileIdConfirmResponseSuccess | postPSessionsByIdUploadsByFileIdConfirmResponseError)

export const getPostPSessionsByIdUploadsByFileIdConfirmUrl = (id: string,
    fileId: string,) => {




  return `/p/sessions/${id}/uploads/${fileId}/confirm`
}

/**
 * @summary Confirm an upload — flips pending → confirmed and notifies the session
 */
export const postPSessionsByIdUploadsByFileIdConfirm = async (id: string,
    fileId: string, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdUploadsByFileIdConfirmResponse> => {

  return customFetch<postPSessionsByIdUploadsByFileIdConfirmResponse>(getPostPSessionsByIdUploadsByFileIdConfirmUrl(id,fileId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPSessionsByIdUploadsByFileIdConfirmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdUploadsByFileIdConfirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, PostPSessionsByIdUploadsByFileIdConfirmMutationVariables> = (props) => {
          const {id,fileId} = props ?? {};

          return  postPSessionsByIdUploadsByFileIdConfirm(id,fileId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdUploadsByFileIdConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>>

    export type PostPSessionsByIdUploadsByFileIdConfirmMutationError = void
    export type PostPSessionsByIdUploadsByFileIdConfirmMutationVariables = {id: string;fileId: string}

    /**
 * @summary Confirm an upload — flips pending → confirmed and notifies the session
 */
export const usePostPSessionsByIdUploadsByFileIdConfirm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>,
        TError,
        PostPSessionsByIdUploadsByFileIdConfirmMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdUploadsByFileIdConfirmMutationOptions(options));
    }
    export type getDByKindByIdResponse200 = {
  data: void
  status: 200
}

export type getDByKindByIdResponse404 = {
  data: void
  status: 404
}

export type getDByKindByIdResponseSuccess = (getDByKindByIdResponse200) & {
  headers: Headers;
};
export type getDByKindByIdResponseError = (getDByKindByIdResponse404) & {
  headers: Headers;
};

export type getDByKindByIdResponse = (getDByKindByIdResponseSuccess | getDByKindByIdResponseError)

export const getGetDByKindByIdUrl = (kind: string,
    id: string,) => {




  return `/d/${kind}/${id}`
}

/**
 * You never build this URL yourself — `GET /v1/exports/{id}` and `GET /v1/files/{id}` return it complete. It carries no API key, expires within minutes, and answers 404 for anything it cannot serve, including a link that has expired.
 * @summary Follow a signed download link
 */
export const getDByKindById = async (kind: string,
    id: string, options?: Parameters<typeof customFetch>[1]): Promise<getDByKindByIdResponse> => {

  return customFetch<getDByKindByIdResponse>(getGetDByKindByIdUrl(kind,id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDByKindByIdQueryKey = (kind: string,
    id: string,) => {
    return [
    `/d/${kind}/${id}`
    ] as const;
    }


export const getGetDByKindByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDByKindById>>, TError = void>(kind: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDByKindById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDByKindByIdQueryKey(kind,id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDByKindById>>> = ({ signal }) => getDByKindById(kind,id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: kind !== null && kind !== undefined && id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDByKindById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDByKindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDByKindById>>>
export type GetDByKindByIdQueryError = void


/**
 * @summary Follow a signed download link
 */

export function useGetDByKindById<TData = Awaited<ReturnType<typeof getDByKindById>>, TError = void>(
 kind: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDByKindById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDByKindByIdQueryOptions(kind,id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






