/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostPFormsBySlugSessions200,
  PostPFormsBySlugSessions403,
  PostPFormsBySlugSessions404,
  PostPFormsBySlugSessionsBody,
  PostPSessionsByIdUploadsByFileIdConfirm200,
  PostPSessionsByIdUploadsIntent200,
  PostPSessionsByIdUploadsIntentBody
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postPFormsBySlugSessionsResponse200 = {
  data: PostPFormsBySlugSessions200
  status: 200
}

export type postPFormsBySlugSessionsResponse403 = {
  data: PostPFormsBySlugSessions403
  status: 403
}

export type postPFormsBySlugSessionsResponse404 = {
  data: PostPFormsBySlugSessions404
  status: 404
}

export type postPFormsBySlugSessionsResponseSuccess = (postPFormsBySlugSessionsResponse200) & {
  headers: Headers;
};
export type postPFormsBySlugSessionsResponseError = (postPFormsBySlugSessionsResponse403 | postPFormsBySlugSessionsResponse404) & {
  headers: Headers;
};

export type postPFormsBySlugSessionsResponse = (postPFormsBySlugSessionsResponseSuccess | postPFormsBySlugSessionsResponseError)

export const getPostPFormsBySlugSessionsUrl = (slug: string,) => {




  return `http://localhost:8787/p/forms/${slug}/sessions`
}

/**
 * @summary Create a chat session for a published form
 */
export const postPFormsBySlugSessions = async (slug: string,
    postPFormsBySlugSessionsBody: PostPFormsBySlugSessionsBody, options?: Parameters<typeof customFetch>[1]): Promise<postPFormsBySlugSessionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postPFormsBySlugSessionsResponse>(getPostPFormsBySlugSessionsUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postPFormsBySlugSessionsBody)
  }
);}





export const getPostPFormsBySlugSessionsMutationOptions = <TError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext> => {

const mutationKey = ['postPFormsBySlugSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, PostPFormsBySlugSessionsMutationVariables> = (props) => {
          const {slug,data} = props ?? {};

          return  postPFormsBySlugSessions(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPFormsBySlugSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postPFormsBySlugSessions>>>
    export type PostPFormsBySlugSessionsMutationBody = PostPFormsBySlugSessionsBody
    export type PostPFormsBySlugSessionsMutationError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404
    export type PostPFormsBySlugSessionsMutationVariables = {slug: string;data: PostPFormsBySlugSessionsBody}

    /**
 * @summary Create a chat session for a published form
 */
export const usePostPFormsBySlugSessions = <TError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPFormsBySlugSessions>>,
        TError,
        PostPFormsBySlugSessionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostPFormsBySlugSessionsMutationOptions(options));
    }
    export type postPSessionsByIdUploadsIntentResponse200 = {
  data: PostPSessionsByIdUploadsIntent200
  status: 200
}

export type postPSessionsByIdUploadsIntentResponse413 = {
  data: void
  status: 413
}

export type postPSessionsByIdUploadsIntentResponse415 = {
  data: void
  status: 415
}

export type postPSessionsByIdUploadsIntentResponseSuccess = (postPSessionsByIdUploadsIntentResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdUploadsIntentResponseError = (postPSessionsByIdUploadsIntentResponse413 | postPSessionsByIdUploadsIntentResponse415) & {
  headers: Headers;
};

export type postPSessionsByIdUploadsIntentResponse = (postPSessionsByIdUploadsIntentResponseSuccess | postPSessionsByIdUploadsIntentResponseError)

export const getPostPSessionsByIdUploadsIntentUrl = (id: string,) => {




  return `http://localhost:8787/p/sessions/${id}/uploads/intent`
}

/**
 * @summary Register an upload — returns a fileId to PUT against
 */
export const postPSessionsByIdUploadsIntent = async (id: string,
    postPSessionsByIdUploadsIntentBody: PostPSessionsByIdUploadsIntentBody, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdUploadsIntentResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postPSessionsByIdUploadsIntentResponse>(getPostPSessionsByIdUploadsIntentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postPSessionsByIdUploadsIntentBody)
  }
);}





export const getPostPSessionsByIdUploadsIntentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdUploadsIntent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, PostPSessionsByIdUploadsIntentMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  postPSessionsByIdUploadsIntent(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdUploadsIntentMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>>
    export type PostPSessionsByIdUploadsIntentMutationBody = PostPSessionsByIdUploadsIntentBody
    export type PostPSessionsByIdUploadsIntentMutationError = void
    export type PostPSessionsByIdUploadsIntentMutationVariables = {id: string;data: PostPSessionsByIdUploadsIntentBody}

    /**
 * @summary Register an upload — returns a fileId to PUT against
 */
export const usePostPSessionsByIdUploadsIntent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>,
        TError,
        PostPSessionsByIdUploadsIntentMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdUploadsIntentMutationOptions(options));
    }
    export type postPSessionsByIdUploadsByFileIdConfirmResponse200 = {
  data: PostPSessionsByIdUploadsByFileIdConfirm200
  status: 200
}

export type postPSessionsByIdUploadsByFileIdConfirmResponse400 = {
  data: void
  status: 400
}

export type postPSessionsByIdUploadsByFileIdConfirmResponse404 = {
  data: void
  status: 404
}

export type postPSessionsByIdUploadsByFileIdConfirmResponseSuccess = (postPSessionsByIdUploadsByFileIdConfirmResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdUploadsByFileIdConfirmResponseError = (postPSessionsByIdUploadsByFileIdConfirmResponse400 | postPSessionsByIdUploadsByFileIdConfirmResponse404) & {
  headers: Headers;
};

export type postPSessionsByIdUploadsByFileIdConfirmResponse = (postPSessionsByIdUploadsByFileIdConfirmResponseSuccess | postPSessionsByIdUploadsByFileIdConfirmResponseError)

export const getPostPSessionsByIdUploadsByFileIdConfirmUrl = (id: string,
    fileId: string,) => {




  return `http://localhost:8787/p/sessions/${id}/uploads/${fileId}/confirm`
}

/**
 * @summary Confirm an upload — flips pending → confirmed and notifies the session
 */
export const postPSessionsByIdUploadsByFileIdConfirm = async (id: string,
    fileId: string, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdUploadsByFileIdConfirmResponse> => {

  return customFetch<postPSessionsByIdUploadsByFileIdConfirmResponse>(getPostPSessionsByIdUploadsByFileIdConfirmUrl(id,fileId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPSessionsByIdUploadsByFileIdConfirmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdUploadsByFileIdConfirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, PostPSessionsByIdUploadsByFileIdConfirmMutationVariables> = (props) => {
          const {id,fileId} = props ?? {};

          return  postPSessionsByIdUploadsByFileIdConfirm(id,fileId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdUploadsByFileIdConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>>

    export type PostPSessionsByIdUploadsByFileIdConfirmMutationError = void
    export type PostPSessionsByIdUploadsByFileIdConfirmMutationVariables = {id: string;fileId: string}

    /**
 * @summary Confirm an upload — flips pending → confirmed and notifies the session
 */
export const usePostPSessionsByIdUploadsByFileIdConfirm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>,
        TError,
        PostPSessionsByIdUploadsByFileIdConfirmMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdUploadsByFileIdConfirmMutationOptions(options));
    }
