/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPFormsBySlugConfig404,
  PostPFormsBySlugSessions200,
  PostPFormsBySlugSessions403,
  PostPFormsBySlugSessions404,
  PostPFormsBySlugSessionsBody,
  PostPSessionsByIdPayments200,
  PostPSessionsByIdPayments402,
  PostPSessionsByIdPayments403,
  PostPSessionsByIdPayments409,
  PostPSessionsByIdPayments422,
  PostPSessionsByIdPayments429,
  PostPSessionsByIdPaymentsByRecordIdConfirm200,
  PostPSessionsByIdUploadsByFileIdConfirm200,
  PostPSessionsByIdUploadsIntent200,
  PostPSessionsByIdUploadsIntentBody,
  PutPSessionsByIdUploadsByFileId200
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type postPPaymentsWebhooksCashfreeResponse200 = {
  data: void
  status: 200
}

export type postPPaymentsWebhooksCashfreeResponse400 = {
  data: void
  status: 400
}

export type postPPaymentsWebhooksCashfreeResponse401 = {
  data: void
  status: 401
}

export type postPPaymentsWebhooksCashfreeResponse500 = {
  data: void
  status: 500
}

export type postPPaymentsWebhooksCashfreeResponseSuccess = (postPPaymentsWebhooksCashfreeResponse200) & {
  headers: Headers;
};
export type postPPaymentsWebhooksCashfreeResponseError = (postPPaymentsWebhooksCashfreeResponse400 | postPPaymentsWebhooksCashfreeResponse401 | postPPaymentsWebhooksCashfreeResponse500) & {
  headers: Headers;
};

export type postPPaymentsWebhooksCashfreeResponse = (postPPaymentsWebhooksCashfreeResponseSuccess | postPPaymentsWebhooksCashfreeResponseError)

export const getPostPPaymentsWebhooksCashfreeUrl = () => {




  return `/p/payments/webhooks/cashfree`
}

/**
 * @summary Cashfree payment webhook
 */
export const postPPaymentsWebhooksCashfree = async ( options?: Parameters<typeof customFetch>[1]): Promise<postPPaymentsWebhooksCashfreeResponse> => {

  return customFetch<postPPaymentsWebhooksCashfreeResponse>(getPostPPaymentsWebhooksCashfreeUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPPaymentsWebhooksCashfreeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksCashfree>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksCashfree>>, TError,void, TContext> => {

const mutationKey = ['postPPaymentsWebhooksCashfree'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPPaymentsWebhooksCashfree>>, void> = () => {


          return  postPPaymentsWebhooksCashfree(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPPaymentsWebhooksCashfreeMutationResult = NonNullable<Awaited<ReturnType<typeof postPPaymentsWebhooksCashfree>>>

    export type PostPPaymentsWebhooksCashfreeMutationError = void


    /**
 * @summary Cashfree payment webhook
 */
export const usePostPPaymentsWebhooksCashfree = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksCashfree>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPPaymentsWebhooksCashfree>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostPPaymentsWebhooksCashfreeMutationOptions(options));
    }
    export type postPPaymentsWebhooksRazorpayResponse200 = {
  data: void
  status: 200
}

export type postPPaymentsWebhooksRazorpayResponse400 = {
  data: void
  status: 400
}

export type postPPaymentsWebhooksRazorpayResponse401 = {
  data: void
  status: 401
}

export type postPPaymentsWebhooksRazorpayResponse500 = {
  data: void
  status: 500
}

export type postPPaymentsWebhooksRazorpayResponseSuccess = (postPPaymentsWebhooksRazorpayResponse200) & {
  headers: Headers;
};
export type postPPaymentsWebhooksRazorpayResponseError = (postPPaymentsWebhooksRazorpayResponse400 | postPPaymentsWebhooksRazorpayResponse401 | postPPaymentsWebhooksRazorpayResponse500) & {
  headers: Headers;
};

export type postPPaymentsWebhooksRazorpayResponse = (postPPaymentsWebhooksRazorpayResponseSuccess | postPPaymentsWebhooksRazorpayResponseError)

export const getPostPPaymentsWebhooksRazorpayUrl = () => {




  return `/p/payments/webhooks/razorpay`
}

/**
 * @summary Razorpay payment webhook
 */
export const postPPaymentsWebhooksRazorpay = async ( options?: Parameters<typeof customFetch>[1]): Promise<postPPaymentsWebhooksRazorpayResponse> => {

  return customFetch<postPPaymentsWebhooksRazorpayResponse>(getPostPPaymentsWebhooksRazorpayUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPPaymentsWebhooksRazorpayMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksRazorpay>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksRazorpay>>, TError,void, TContext> => {

const mutationKey = ['postPPaymentsWebhooksRazorpay'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPPaymentsWebhooksRazorpay>>, void> = () => {


          return  postPPaymentsWebhooksRazorpay(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPPaymentsWebhooksRazorpayMutationResult = NonNullable<Awaited<ReturnType<typeof postPPaymentsWebhooksRazorpay>>>

    export type PostPPaymentsWebhooksRazorpayMutationError = void


    /**
 * @summary Razorpay payment webhook
 */
export const usePostPPaymentsWebhooksRazorpay = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksRazorpay>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPPaymentsWebhooksRazorpay>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostPPaymentsWebhooksRazorpayMutationOptions(options));
    }
    export type postPPaymentsWebhooksStripeByAccountIdResponse200 = {
  data: void
  status: 200
}

export type postPPaymentsWebhooksStripeByAccountIdResponse400 = {
  data: void
  status: 400
}

export type postPPaymentsWebhooksStripeByAccountIdResponse401 = {
  data: void
  status: 401
}

export type postPPaymentsWebhooksStripeByAccountIdResponse500 = {
  data: void
  status: 500
}

export type postPPaymentsWebhooksStripeByAccountIdResponseSuccess = (postPPaymentsWebhooksStripeByAccountIdResponse200) & {
  headers: Headers;
};
export type postPPaymentsWebhooksStripeByAccountIdResponseError = (postPPaymentsWebhooksStripeByAccountIdResponse400 | postPPaymentsWebhooksStripeByAccountIdResponse401 | postPPaymentsWebhooksStripeByAccountIdResponse500) & {
  headers: Headers;
};

export type postPPaymentsWebhooksStripeByAccountIdResponse = (postPPaymentsWebhooksStripeByAccountIdResponseSuccess | postPPaymentsWebhooksStripeByAccountIdResponseError)

export const getPostPPaymentsWebhooksStripeByAccountIdUrl = (accountId: string,) => {




  return `/p/payments/webhooks/stripe/${accountId}`
}

/**
 * @summary Stripe payment webhook
 */
export const postPPaymentsWebhooksStripeByAccountId = async (accountId: string, options?: Parameters<typeof customFetch>[1]): Promise<postPPaymentsWebhooksStripeByAccountIdResponse> => {

  return customFetch<postPPaymentsWebhooksStripeByAccountIdResponse>(getPostPPaymentsWebhooksStripeByAccountIdUrl(accountId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPPaymentsWebhooksStripeByAccountIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksStripeByAccountId>>, TError,PostPPaymentsWebhooksStripeByAccountIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksStripeByAccountId>>, TError,PostPPaymentsWebhooksStripeByAccountIdMutationVariables, TContext> => {

const mutationKey = ['postPPaymentsWebhooksStripeByAccountId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPPaymentsWebhooksStripeByAccountId>>, PostPPaymentsWebhooksStripeByAccountIdMutationVariables> = (props) => {
          const {accountId} = props ?? {};

          return  postPPaymentsWebhooksStripeByAccountId(accountId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPPaymentsWebhooksStripeByAccountIdMutationResult = NonNullable<Awaited<ReturnType<typeof postPPaymentsWebhooksStripeByAccountId>>>

    export type PostPPaymentsWebhooksStripeByAccountIdMutationError = void
    export type PostPPaymentsWebhooksStripeByAccountIdMutationVariables = {accountId: string}

    /**
 * @summary Stripe payment webhook
 */
export const usePostPPaymentsWebhooksStripeByAccountId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPPaymentsWebhooksStripeByAccountId>>, TError,PostPPaymentsWebhooksStripeByAccountIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPPaymentsWebhooksStripeByAccountId>>,
        TError,
        PostPPaymentsWebhooksStripeByAccountIdMutationVariables,
        TContext
      > => {
      return useMutation(getPostPPaymentsWebhooksStripeByAccountIdMutationOptions(options));
    }
    export type getPFeedByTokenResponse200 = {
  data: string
  status: 200
}

export type getPFeedByTokenResponse404 = {
  data: void
  status: 404
}

export type getPFeedByTokenResponseSuccess = (getPFeedByTokenResponse200) & {
  headers: Headers;
};
export type getPFeedByTokenResponseError = (getPFeedByTokenResponse404) & {
  headers: Headers;
};

export type getPFeedByTokenResponse = (getPFeedByTokenResponseSuccess | getPFeedByTokenResponseError)

export const getGetPFeedByTokenUrl = (token: string,) => {




  return `/p/feed/${token}`
}

/**
 * Built for you by the dashboard — paste it into Google Sheets as `=IMPORTDATA("…")` or into Excel via Data → From Web. The URL is the credential; rotate it if it leaks.
 * @summary A form's responses as CSV, for a spreadsheet to pull
 */
export const getPFeedByToken = async (token: string, options?: Parameters<typeof customFetch>[1]): Promise<getPFeedByTokenResponse> => {

  return customFetch<getPFeedByTokenResponse>(getGetPFeedByTokenUrl(token),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPFeedByTokenQueryKey = (token: string,) => {
    return [
    `/p/feed/${token}`
    ] as const;
    }


export const getGetPFeedByTokenQueryOptions = <TData = Awaited<ReturnType<typeof getPFeedByToken>>, TError = void>(token: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPFeedByToken>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPFeedByTokenQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPFeedByToken>>> = ({ signal }) => getPFeedByToken(token, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPFeedByToken>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPFeedByTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getPFeedByToken>>>
export type GetPFeedByTokenQueryError = void


/**
 * @summary A form's responses as CSV, for a spreadsheet to pull
 */

export function useGetPFeedByToken<TData = Awaited<ReturnType<typeof getPFeedByToken>>, TError = void>(
 token: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPFeedByToken>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPFeedByTokenQueryOptions(token,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getPFormsBySlugConfigResponse200 = {
  data: void
  status: 200
}

export type getPFormsBySlugConfigResponse404 = {
  data: GetPFormsBySlugConfig404
  status: 404
}

export type getPFormsBySlugConfigResponseSuccess = (getPFormsBySlugConfigResponse200) & {
  headers: Headers;
};
export type getPFormsBySlugConfigResponseError = (getPFormsBySlugConfigResponse404) & {
  headers: Headers;
};

export type getPFormsBySlugConfigResponse = (getPFormsBySlugConfigResponseSuccess | getPFormsBySlugConfigResponseError)

export const getGetPFormsBySlugConfigUrl = (slug: string,) => {




  return `/p/forms/${slug}/config`
}

/**
 * @summary Public rendering config for a published form
 */
export const getPFormsBySlugConfig = async (slug: string, options?: Parameters<typeof customFetch>[1]): Promise<getPFormsBySlugConfigResponse> => {

  return customFetch<getPFormsBySlugConfigResponse>(getGetPFormsBySlugConfigUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPFormsBySlugConfigQueryKey = (slug: string,) => {
    return [
    `/p/forms/${slug}/config`
    ] as const;
    }


export const getGetPFormsBySlugConfigQueryOptions = <TData = Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError = GetPFormsBySlugConfig404>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPFormsBySlugConfigQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPFormsBySlugConfig>>> = ({ signal }) => getPFormsBySlugConfig(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPFormsBySlugConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getPFormsBySlugConfig>>>
export type GetPFormsBySlugConfigQueryError = GetPFormsBySlugConfig404


/**
 * @summary Public rendering config for a published form
 */

export function useGetPFormsBySlugConfig<TData = Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError = GetPFormsBySlugConfig404>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPFormsBySlugConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPFormsBySlugConfigQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postPFormsBySlugSessionsResponse200 = {
  data: PostPFormsBySlugSessions200
  status: 200
}

export type postPFormsBySlugSessionsResponse403 = {
  data: PostPFormsBySlugSessions403
  status: 403
}

export type postPFormsBySlugSessionsResponse404 = {
  data: PostPFormsBySlugSessions404
  status: 404
}

export type postPFormsBySlugSessionsResponseSuccess = (postPFormsBySlugSessionsResponse200) & {
  headers: Headers;
};
export type postPFormsBySlugSessionsResponseError = (postPFormsBySlugSessionsResponse403 | postPFormsBySlugSessionsResponse404) & {
  headers: Headers;
};

export type postPFormsBySlugSessionsResponse = (postPFormsBySlugSessionsResponseSuccess | postPFormsBySlugSessionsResponseError)

export const getPostPFormsBySlugSessionsUrl = (slug: string,) => {




  return `/p/forms/${slug}/sessions`
}

/**
 * @summary Create a chat session for a published form
 */
export const postPFormsBySlugSessions = async (slug: string,
    postPFormsBySlugSessionsBody: PostPFormsBySlugSessionsBody, options?: Parameters<typeof customFetch>[1]): Promise<postPFormsBySlugSessionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postPFormsBySlugSessionsResponse>(getPostPFormsBySlugSessionsUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postPFormsBySlugSessionsBody)
  }
);}





export const getPostPFormsBySlugSessionsMutationOptions = <TError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext> => {

const mutationKey = ['postPFormsBySlugSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, PostPFormsBySlugSessionsMutationVariables> = (props) => {
          const {slug,data} = props ?? {};

          return  postPFormsBySlugSessions(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPFormsBySlugSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postPFormsBySlugSessions>>>
    export type PostPFormsBySlugSessionsMutationBody = PostPFormsBySlugSessionsBody
    export type PostPFormsBySlugSessionsMutationError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404
    export type PostPFormsBySlugSessionsMutationVariables = {slug: string;data: PostPFormsBySlugSessionsBody}

    /**
 * @summary Create a chat session for a published form
 */
export const usePostPFormsBySlugSessions = <TError = PostPFormsBySlugSessions403 | PostPFormsBySlugSessions404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPFormsBySlugSessions>>, TError,PostPFormsBySlugSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPFormsBySlugSessions>>,
        TError,
        PostPFormsBySlugSessionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostPFormsBySlugSessionsMutationOptions(options));
    }
    export type postPSessionsByIdPaymentsResponse200 = {
  data: PostPSessionsByIdPayments200
  status: 200
}

export type postPSessionsByIdPaymentsResponse402 = {
  data: PostPSessionsByIdPayments402
  status: 402
}

export type postPSessionsByIdPaymentsResponse403 = {
  data: PostPSessionsByIdPayments403
  status: 403
}

export type postPSessionsByIdPaymentsResponse409 = {
  data: PostPSessionsByIdPayments409
  status: 409
}

export type postPSessionsByIdPaymentsResponse422 = {
  data: PostPSessionsByIdPayments422
  status: 422
}

export type postPSessionsByIdPaymentsResponse429 = {
  data: PostPSessionsByIdPayments429
  status: 429
}

export type postPSessionsByIdPaymentsResponseSuccess = (postPSessionsByIdPaymentsResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdPaymentsResponseError = (postPSessionsByIdPaymentsResponse402 | postPSessionsByIdPaymentsResponse403 | postPSessionsByIdPaymentsResponse409 | postPSessionsByIdPaymentsResponse422 | postPSessionsByIdPaymentsResponse429) & {
  headers: Headers;
};

export type postPSessionsByIdPaymentsResponse = (postPSessionsByIdPaymentsResponseSuccess | postPSessionsByIdPaymentsResponseError)

export const getPostPSessionsByIdPaymentsUrl = (id: string,) => {




  return `/p/sessions/${id}/payments`
}

/**
 * @summary Open a verified checkout for the current payment question
 */
export const postPSessionsByIdPayments = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdPaymentsResponse> => {

  return customFetch<postPSessionsByIdPaymentsResponse>(getPostPSessionsByIdPaymentsUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPSessionsByIdPaymentsMutationOptions = <TError = PostPSessionsByIdPayments402 | PostPSessionsByIdPayments403 | PostPSessionsByIdPayments409 | PostPSessionsByIdPayments422 | PostPSessionsByIdPayments429,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdPayments>>, TError,PostPSessionsByIdPaymentsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdPayments>>, TError,PostPSessionsByIdPaymentsMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdPayments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdPayments>>, PostPSessionsByIdPaymentsMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  postPSessionsByIdPayments(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdPaymentsMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdPayments>>>

    export type PostPSessionsByIdPaymentsMutationError = PostPSessionsByIdPayments402 | PostPSessionsByIdPayments403 | PostPSessionsByIdPayments409 | PostPSessionsByIdPayments422 | PostPSessionsByIdPayments429
    export type PostPSessionsByIdPaymentsMutationVariables = {id: string}

    /**
 * @summary Open a verified checkout for the current payment question
 */
export const usePostPSessionsByIdPayments = <TError = PostPSessionsByIdPayments402 | PostPSessionsByIdPayments403 | PostPSessionsByIdPayments409 | PostPSessionsByIdPayments422 | PostPSessionsByIdPayments429,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdPayments>>, TError,PostPSessionsByIdPaymentsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdPayments>>,
        TError,
        PostPSessionsByIdPaymentsMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdPaymentsMutationOptions(options));
    }
    export type postPSessionsByIdPaymentsByRecordIdConfirmResponse200 = {
  data: PostPSessionsByIdPaymentsByRecordIdConfirm200
  status: 200
}

export type postPSessionsByIdPaymentsByRecordIdConfirmResponse404 = {
  data: void
  status: 404
}

export type postPSessionsByIdPaymentsByRecordIdConfirmResponse502 = {
  data: void
  status: 502
}

export type postPSessionsByIdPaymentsByRecordIdConfirmResponseSuccess = (postPSessionsByIdPaymentsByRecordIdConfirmResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdPaymentsByRecordIdConfirmResponseError = (postPSessionsByIdPaymentsByRecordIdConfirmResponse404 | postPSessionsByIdPaymentsByRecordIdConfirmResponse502) & {
  headers: Headers;
};

export type postPSessionsByIdPaymentsByRecordIdConfirmResponse = (postPSessionsByIdPaymentsByRecordIdConfirmResponseSuccess | postPSessionsByIdPaymentsByRecordIdConfirmResponseError)

export const getPostPSessionsByIdPaymentsByRecordIdConfirmUrl = (id: string,
    recordId: string,) => {




  return `/p/sessions/${id}/payments/${recordId}/confirm`
}

/**
 * @summary Re-check a checkout with the gateway and settle it if paid
 */
export const postPSessionsByIdPaymentsByRecordIdConfirm = async (id: string,
    recordId: string, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdPaymentsByRecordIdConfirmResponse> => {

  return customFetch<postPSessionsByIdPaymentsByRecordIdConfirmResponse>(getPostPSessionsByIdPaymentsByRecordIdConfirmUrl(id,recordId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPSessionsByIdPaymentsByRecordIdConfirmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdPaymentsByRecordIdConfirm>>, TError,PostPSessionsByIdPaymentsByRecordIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdPaymentsByRecordIdConfirm>>, TError,PostPSessionsByIdPaymentsByRecordIdConfirmMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdPaymentsByRecordIdConfirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdPaymentsByRecordIdConfirm>>, PostPSessionsByIdPaymentsByRecordIdConfirmMutationVariables> = (props) => {
          const {id,recordId} = props ?? {};

          return  postPSessionsByIdPaymentsByRecordIdConfirm(id,recordId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdPaymentsByRecordIdConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdPaymentsByRecordIdConfirm>>>

    export type PostPSessionsByIdPaymentsByRecordIdConfirmMutationError = void
    export type PostPSessionsByIdPaymentsByRecordIdConfirmMutationVariables = {id: string;recordId: string}

    /**
 * @summary Re-check a checkout with the gateway and settle it if paid
 */
export const usePostPSessionsByIdPaymentsByRecordIdConfirm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdPaymentsByRecordIdConfirm>>, TError,PostPSessionsByIdPaymentsByRecordIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdPaymentsByRecordIdConfirm>>,
        TError,
        PostPSessionsByIdPaymentsByRecordIdConfirmMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdPaymentsByRecordIdConfirmMutationOptions(options));
    }
    export type postPSessionsByIdUploadsIntentResponse200 = {
  data: PostPSessionsByIdUploadsIntent200
  status: 200
}

export type postPSessionsByIdUploadsIntentResponse413 = {
  data: void
  status: 413
}

export type postPSessionsByIdUploadsIntentResponse415 = {
  data: void
  status: 415
}

export type postPSessionsByIdUploadsIntentResponseSuccess = (postPSessionsByIdUploadsIntentResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdUploadsIntentResponseError = (postPSessionsByIdUploadsIntentResponse413 | postPSessionsByIdUploadsIntentResponse415) & {
  headers: Headers;
};

export type postPSessionsByIdUploadsIntentResponse = (postPSessionsByIdUploadsIntentResponseSuccess | postPSessionsByIdUploadsIntentResponseError)

export const getPostPSessionsByIdUploadsIntentUrl = (id: string,) => {




  return `/p/sessions/${id}/uploads/intent`
}

/**
 * @summary Register an upload, returning a fileId to PUT against
 */
export const postPSessionsByIdUploadsIntent = async (id: string,
    postPSessionsByIdUploadsIntentBody: PostPSessionsByIdUploadsIntentBody, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdUploadsIntentResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postPSessionsByIdUploadsIntentResponse>(getPostPSessionsByIdUploadsIntentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postPSessionsByIdUploadsIntentBody)
  }
);}





export const getPostPSessionsByIdUploadsIntentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdUploadsIntent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, PostPSessionsByIdUploadsIntentMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  postPSessionsByIdUploadsIntent(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdUploadsIntentMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>>
    export type PostPSessionsByIdUploadsIntentMutationBody = PostPSessionsByIdUploadsIntentBody
    export type PostPSessionsByIdUploadsIntentMutationError = void
    export type PostPSessionsByIdUploadsIntentMutationVariables = {id: string;data: PostPSessionsByIdUploadsIntentBody}

    /**
 * @summary Register an upload, returning a fileId to PUT against
 */
export const usePostPSessionsByIdUploadsIntent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>, TError,PostPSessionsByIdUploadsIntentMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdUploadsIntent>>,
        TError,
        PostPSessionsByIdUploadsIntentMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdUploadsIntentMutationOptions(options));
    }
    export type putPSessionsByIdUploadsByFileIdResponse200 = {
  data: PutPSessionsByIdUploadsByFileId200
  status: 200
}

export type putPSessionsByIdUploadsByFileIdResponse400 = {
  data: void
  status: 400
}

export type putPSessionsByIdUploadsByFileIdResponse404 = {
  data: void
  status: 404
}

export type putPSessionsByIdUploadsByFileIdResponse413 = {
  data: void
  status: 413
}

export type putPSessionsByIdUploadsByFileIdResponseSuccess = (putPSessionsByIdUploadsByFileIdResponse200) & {
  headers: Headers;
};
export type putPSessionsByIdUploadsByFileIdResponseError = (putPSessionsByIdUploadsByFileIdResponse400 | putPSessionsByIdUploadsByFileIdResponse404 | putPSessionsByIdUploadsByFileIdResponse413) & {
  headers: Headers;
};

export type putPSessionsByIdUploadsByFileIdResponse = (putPSessionsByIdUploadsByFileIdResponseSuccess | putPSessionsByIdUploadsByFileIdResponseError)

export const getPutPSessionsByIdUploadsByFileIdUrl = (id: string,
    fileId: string,) => {




  return `/p/sessions/${id}/uploads/${fileId}`
}

/**
 * PUT the raw file body, not multipart and not base64, to the `uploadUrl` returned by the intent step. The declared size must match within 1KB, and the object is not visible to the form until `confirm`.
 * @summary Upload the bytes for a registered intent
 */
export const putPSessionsByIdUploadsByFileId = async (id: string,
    fileId: string,
    putPSessionsByIdUploadsByFileIdBody: Blob, options?: Parameters<typeof customFetch>[1]): Promise<putPSessionsByIdUploadsByFileIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<putPSessionsByIdUploadsByFileIdResponse>(getPutPSessionsByIdUploadsByFileIdUrl(id,fileId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/octet-stream', ...getHeaders(options?.headers) },
    body: putPSessionsByIdUploadsByFileIdBody
  }
);}





export const getPutPSessionsByIdUploadsByFileIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, TError,PutPSessionsByIdUploadsByFileIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, TError,PutPSessionsByIdUploadsByFileIdMutationVariables, TContext> => {

const mutationKey = ['putPSessionsByIdUploadsByFileId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, PutPSessionsByIdUploadsByFileIdMutationVariables> = (props) => {
          const {id,fileId,data} = props ?? {};

          return  putPSessionsByIdUploadsByFileId(id,fileId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutPSessionsByIdUploadsByFileIdMutationResult = NonNullable<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>>
    export type PutPSessionsByIdUploadsByFileIdMutationBody = Blob
    export type PutPSessionsByIdUploadsByFileIdMutationError = void
    export type PutPSessionsByIdUploadsByFileIdMutationVariables = {id: string;fileId: string;data: Blob}

    /**
 * @summary Upload the bytes for a registered intent
 */
export const usePutPSessionsByIdUploadsByFileId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>, TError,PutPSessionsByIdUploadsByFileIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putPSessionsByIdUploadsByFileId>>,
        TError,
        PutPSessionsByIdUploadsByFileIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutPSessionsByIdUploadsByFileIdMutationOptions(options));
    }
    export type postPSessionsByIdUploadsByFileIdConfirmResponse200 = {
  data: PostPSessionsByIdUploadsByFileIdConfirm200
  status: 200
}

export type postPSessionsByIdUploadsByFileIdConfirmResponse400 = {
  data: void
  status: 400
}

export type postPSessionsByIdUploadsByFileIdConfirmResponse404 = {
  data: void
  status: 404
}

export type postPSessionsByIdUploadsByFileIdConfirmResponseSuccess = (postPSessionsByIdUploadsByFileIdConfirmResponse200) & {
  headers: Headers;
};
export type postPSessionsByIdUploadsByFileIdConfirmResponseError = (postPSessionsByIdUploadsByFileIdConfirmResponse400 | postPSessionsByIdUploadsByFileIdConfirmResponse404) & {
  headers: Headers;
};

export type postPSessionsByIdUploadsByFileIdConfirmResponse = (postPSessionsByIdUploadsByFileIdConfirmResponseSuccess | postPSessionsByIdUploadsByFileIdConfirmResponseError)

export const getPostPSessionsByIdUploadsByFileIdConfirmUrl = (id: string,
    fileId: string,) => {




  return `/p/sessions/${id}/uploads/${fileId}/confirm`
}

/**
 * @summary Confirm an upload: flips pending to confirmed and notifies the session
 */
export const postPSessionsByIdUploadsByFileIdConfirm = async (id: string,
    fileId: string, options?: Parameters<typeof customFetch>[1]): Promise<postPSessionsByIdUploadsByFileIdConfirmResponse> => {

  return customFetch<postPSessionsByIdUploadsByFileIdConfirmResponse>(getPostPSessionsByIdUploadsByFileIdConfirmUrl(id,fileId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostPSessionsByIdUploadsByFileIdConfirmMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext> => {

const mutationKey = ['postPSessionsByIdUploadsByFileIdConfirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, PostPSessionsByIdUploadsByFileIdConfirmMutationVariables> = (props) => {
          const {id,fileId} = props ?? {};

          return  postPSessionsByIdUploadsByFileIdConfirm(id,fileId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPSessionsByIdUploadsByFileIdConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>>

    export type PostPSessionsByIdUploadsByFileIdConfirmMutationError = void
    export type PostPSessionsByIdUploadsByFileIdConfirmMutationVariables = {id: string;fileId: string}

    /**
 * @summary Confirm an upload: flips pending to confirmed and notifies the session
 */
export const usePostPSessionsByIdUploadsByFileIdConfirm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>, TError,PostPSessionsByIdUploadsByFileIdConfirmMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPSessionsByIdUploadsByFileIdConfirm>>,
        TError,
        PostPSessionsByIdUploadsByFileIdConfirmMutationVariables,
        TContext
      > => {
      return useMutation(getPostPSessionsByIdUploadsByFileIdConfirmMutationOptions(options));
    }
    export type getDByKindByIdResponse200 = {
  data: void
  status: 200
}

export type getDByKindByIdResponse404 = {
  data: void
  status: 404
}

export type getDByKindByIdResponseSuccess = (getDByKindByIdResponse200) & {
  headers: Headers;
};
export type getDByKindByIdResponseError = (getDByKindByIdResponse404) & {
  headers: Headers;
};

export type getDByKindByIdResponse = (getDByKindByIdResponseSuccess | getDByKindByIdResponseError)

export const getGetDByKindByIdUrl = (kind: string,
    id: string,) => {




  return `/d/${kind}/${id}`
}

/**
 * You never build this URL yourself — `GET /v1/exports/{id}` and `GET /v1/files/{id}` return it complete. It carries no API key, expires within minutes, and answers 404 for anything it cannot serve, including a link that has expired.
 * @summary Follow a signed download link
 */
export const getDByKindById = async (kind: string,
    id: string, options?: Parameters<typeof customFetch>[1]): Promise<getDByKindByIdResponse> => {

  return customFetch<getDByKindByIdResponse>(getGetDByKindByIdUrl(kind,id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDByKindByIdQueryKey = (kind: string,
    id: string,) => {
    return [
    `/d/${kind}/${id}`
    ] as const;
    }


export const getGetDByKindByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDByKindById>>, TError = void>(kind: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDByKindById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDByKindByIdQueryKey(kind,id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDByKindById>>> = ({ signal }) => getDByKindById(kind,id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: kind !== null && kind !== undefined && id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDByKindById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDByKindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDByKindById>>>
export type GetDByKindByIdQueryError = void


/**
 * @summary Follow a signed download link
 */

export function useGetDByKindById<TData = Awaited<ReturnType<typeof getDByKindById>>, TError = void>(
 kind: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDByKindById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDByKindByIdQueryOptions(kind,id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






