import { defineTemplate, type TemplateSeed } from "../define.js";

export const QUIZ_PRODUCT_RECOMMENDATION: TemplateSeed[] = [
  defineTemplate({
    slug: "3d-scanner-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes", "generate-leads"],
    roles: ["sales", "marketing"],
    searchName: "3D scanner recommendation quiz",
    title: "3D scanner finder",
    icon: "Camera",
    metaDescription:
      "Match buyers to the right kind of 3D scanner by asking about object size, detail, tricky surfaces, where they scan and budget, then route to one of four results.",
    description: "Ask what they scan, how precisely and where, then point them to one of four scanner types.",
    blurb:
      "Written the way a good sales engineer qualifies a scanner enquiry: object size, the detail the job needs, surfaces that defeat most scanners, and where the work happens. The last answer about what the scans are for routes each buyer to one of four results, and every earlier answer lands in your dashboard for the follow-up.",
    tags: ["3d scanner quiz", "product finder", "scanner buying guide", "reverse engineering", "3d printing"],
    greeting: "Not sure which 3D scanner fits your work? A few questions about what you scan, and we'll point you to the right kind.",
    questions: [
      {
        ref: "object_size",
        type: "single_select",
        title: "What size are the objects you'll scan most often?",
        required: true,
        options: [
          { label: "Small enough to hold in one hand", description: "Jewellery, dental models, small parts" },
          { label: "Shoebox to suitcase sized", description: "Tools, shoes, housings, busts" },
          { label: "Large items", description: "Car panels, furniture, sculptures" },
          { label: "Whole rooms, buildings or outdoor sites" },
        ],
      },
      {
        ref: "detail",
        type: "opinion_scale",
        title: "How fine does the detail need to be?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Rough shape is fine",
        labelHigh: "Every edge and texture",
      },
      {
        ref: "surfaces",
        type: "multi_select",
        title: "Will any of these surfaces come up? Pick all that apply.",
        description: "These are the ones that trip scanners up, so they change what we'd suggest.",
        required: false,
        minSelections: 0,
        maxSelections: 5,
        options: [
          { label: "Shiny or reflective metal" },
          { label: "Black or very dark" },
          { label: "Clear glass or plastic" },
          { label: "People, skin or hair" },
          { label: "None of these" },
        ],
      },
      {
        ref: "colour",
        type: "yes_no",
        title: "Do you need the scan to capture colour and texture, not just shape?",
        required: true,
      },
      {
        ref: "environment",
        type: "single_select",
        title: "Where will most of the scanning happen?",
        required: true,
        options: [
          { label: "On a desk or bench" },
          { label: "In a workshop or on a factory floor" },
          { label: "On site, carried from place to place" },
          { label: "Outdoors" },
        ],
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "Put these in order, most important first.",
        required: true,
        items: ["Accuracy", "Speed of scanning", "Ease of use", "Portability", "Price"],
      },
      {
        ref: "experience",
        type: "single_select",
        title: "Have you worked with 3D scan data before?",
        required: true,
        options: [
          { label: "No, this is my first scanner" },
          { label: "A little, mostly for 3D printing" },
          { label: "Yes, in CAD or inspection software every week" },
        ],
      },
      {
        ref: "budget",
        type: "dropdown",
        title: "Roughly what budget are you working with?",
        description: "Swap these ranges for the price points in your own range.",
        required: true,
        options: [
          { label: "Entry level" },
          { label: "Mid range" },
          { label: "Professional" },
          { label: "Industrial, if it's the right tool" },
          { label: "Not sure yet" },
        ],
      },
      {
        ref: "email",
        type: "email",
        title: "Where should we send the specs for your match?",
        description: "Optional. Leave it blank if you just want the answer on screen.",
        required: false,
      },
      {
        ref: "use",
        type: "single_select",
        title: "Last one: what will the scans mainly be used for?",
        required: true,
        options: [
          { label: "3D printing, hobby projects or personal use" },
          { label: "Product design or reverse engineering" },
          { label: "Quality inspection and measurement" },
          { label: "Recording buildings, rooms or heritage sites" },
        ],
      },
    ],
    branches: [
      { when: "use", is: "Product design or reverse engineering", then: "end_design" },
      { when: "use", is: "Quality inspection and measurement", then: "end_metrology" },
      { when: "use", is: "Recording buildings, rooms or heritage sites", then: "end_large" },
    ],
    endings: [
      {
        ref: "end_design",
        title: "A professional handheld scanner 🛠️",
        body: "For reverse engineering you need clean, accurate meshes that drop straight into CAD. A handheld laser or blue-light scanner copes with shiny and dark parts better than entry-level models, and it goes to the part instead of the part coming to the desk. We'll follow up with the models that fit the sizes you scan.",
      },
      {
        ref: "end_metrology",
        title: "A metrology-grade scanner 📐",
        body: "Inspection work needs measured, repeatable accuracy with a calibration certificate behind it, not just a nice-looking model. A metrology-grade blue-light or laser scanner, paired with inspection software, lets you compare every part to its CAD file. Our team will get in touch to talk through tolerances before you buy.",
      },
      {
        ref: "end_large",
        title: "A long-range scanner 🏛️",
        body: "Rooms, buildings and sites are a different job from objects on a bench. A long-range laser scanner captures whole spaces from a few set-ups and stitches them together, and works outdoors where handheld scanners struggle. We'll send the options that suit the size of the spaces you record.",
      },
    ],
    ending: {
      title: "An entry-level desktop or handheld scanner 🖨️",
      body: "For printing and personal projects, a desktop turntable scanner for small objects, or an entry-level handheld for anything bigger, is the easiest place to start. They give you print-ready models without a steep learning curve. If you scan shiny or dark objects, a light coat of scanning spray makes a big difference.",
    },
    guide: {
      questionsToConsider: [
        "Which scanners in your range do you actually want to recommend, and what separates them for a buyer?",
        "Do you want inspection and large-site enquiries to reach a person before any product page?",
        "Should the budget ranges show real prices from your catalogue, or stay as tiers?",
        "Is a demo or a sample scan something you can offer at the end of each result?",
      ],
      howToUseResponses:
        "Read the surfaces and environment answers before anyone calls a lead: a buyer scanning black, shiny parts on site needs a different demo from one scanning resin prints on a desk. Sort by the use answer to see which result your quiz sends most people to, and check that you stock enough of it. Export to CSV to hand inspection and site-scanning leads to your technical team.",
      customizeSteps: [
        "Rename each result after the real model or product family you sell, and adjust the budget ranges to match your prices.",
        "Change the options in the final question if your range splits differently, keeping one branch per result.",
        "Embed the quiz on your scanner category page or share the link in replies to enquiries.",
      ],
      faqs: [
        {
          q: "What should a 3D scanner buyer ask before choosing one?",
          a: "What they will scan, how big it is, how fine the detail must be, and what surfaces are involved. Where they scan and what they do with the data afterwards matters just as much as resolution.",
        },
        {
          q: "Why ask about shiny, dark or clear surfaces?",
          a: "Those surfaces reflect or absorb the light most scanners rely on, so they often need a different scanner type or a scanning spray. Knowing about them early avoids a disappointing first scan.",
        },
        {
          q: "How does this quiz decide which scanner to recommend?",
          a: "The final question about what the scans are for routes each person to one of four results. You can change the options and point each one at any result you write.",
        },
        {
          q: "Can I use this quiz to collect sales leads?",
          a: "Yes. The email question is optional, and every answer is saved to your dashboard so your team can follow up with the context already in hand.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "acrylic-nail-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes", "generate-leads"],
    roles: ["freelancers-agencies", "marketing"],
    searchName: "Acrylic nail quiz",
    title: "Acrylic nail style quiz",
    icon: "Sparkles",
    metaDescription:
      "Help clients pick an acrylic nail length and shape that suits their hands and routine. Scored answers suggest a style, and sensitivities get flagged before booking.",
    description: "Suggest a length and shape that suits how a client lives, and flag sensitivities before the appointment.",
    blurb:
      "Asks what a good nail tech asks at the start of a consultation: how hands-on their day is, the length and shape they like, how often they can come back for infills. Those answers are scored into one of three style results, and anyone who mentions a past reaction is asked for details your tech can read before the booking.",
    tags: ["acrylic nail quiz", "nail shape quiz", "nail salon", "nail consultation", "beauty quiz"],
    greeting: "Let's find your nail style. A few quick questions and we'll suggest a length and shape that suits you.",
    questions: [
      {
        ref: "experience",
        type: "single_select",
        title: "Have you had acrylics before?",
        required: true,
        options: [{ label: "Never, this would be my first set" }, { label: "A few times" }, { label: "I wear them most of the time" }],
      },
      {
        ref: "hands_on",
        type: "single_select",
        title: "How hands-on is your usual day?",
        description: "Typing, cooking, lifting, looking after little ones: it all counts.",
        required: true,
        options: [
          { label: "Very, my hands are busy all day", score: 0 },
          { label: "Somewhere in the middle", score: 1 },
          { label: "Not very, I can be careful with them", score: 2 },
        ],
      },
      {
        ref: "length",
        type: "single_select",
        title: "What length feels right?",
        required: true,
        options: [
          { label: "Short, just past the fingertip", score: 0 },
          { label: "Medium", score: 1 },
          { label: "Long", score: 2 },
          { label: "As long as possible", score: 3 },
        ],
      },
      {
        ref: "shape",
        type: "single_select",
        title: "Which shape do you like the look of?",
        required: true,
        options: [
          { label: "Round or oval", description: "Soft and natural", score: 0 },
          { label: "Squoval", description: "A square with softened corners", score: 0 },
          { label: "Almond", description: "Slim with a rounded point", score: 1 },
          { label: "Coffin or ballerina", description: "Tapered with a flat tip", score: 2 },
          { label: "Stiletto", description: "Long and pointed", score: 3 },
        ],
      },
      {
        ref: "colours",
        type: "multi_select",
        title: "What colours and finishes are you drawn to?",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        options: [
          { label: "Nudes and soft pinks" },
          { label: "French tips" },
          { label: "Bright, bold colours" },
          { label: "Dark and moody" },
          { label: "Chrome, glitter or shimmer" },
          { label: "Hand-painted nail art" },
        ],
      },
      {
        ref: "occasion",
        type: "single_select",
        title: "Are these for everyday or a special occasion?",
        required: true,
        options: [{ label: "Everyday" }, { label: "A holiday" }, { label: "A wedding, party or event" }],
      },
      {
        ref: "infills",
        type: "single_select",
        title: "How often could you come back for infills?",
        description: "Acrylics usually need filling as your natural nail grows out.",
        required: true,
        options: [{ label: "Every two to three weeks" }, { label: "About once a month" }, { label: "I'm not sure I can keep up with that" }],
      },
      {
        ref: "reaction",
        type: "yes_no",
        title: "Have you ever had a reaction or sore skin from nail products?",
        required: true,
      },
      {
        ref: "reaction_detail",
        type: "long_text",
        title: "Sorry to hear it. What happened, and roughly when?",
        description: "Your nail tech will read this before your appointment.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we send your result and booking link to?",
        required: false,
        fields: ["first_name", "email", "phone"],
      },
    ],
    branches: [
      { when: "reaction", is: true, then: "reaction_detail" },
      { when: "reaction", is: false, then: "contact" },
    ],
    scoreEndings: [
      { atLeast: 6, then: "end_statement" },
      { atLeast: 3, then: "end_everyday_glam" },
    ],
    endings: [
      {
        ref: "end_statement",
        title: "Long coffin or stiletto 💅",
        body: "You want nails people notice. A long coffin or stiletto set shows off colour, chrome and nail art best. Plan on regular infills to keep the length strong, and on a little extra care on busy days.",
      },
      {
        ref: "end_everyday_glam",
        title: "Medium almond ✨",
        body: "Almond at a medium length is the sweet spot: it lengthens your fingers and looks polished, but it's still easy to type and live in. It suits almost any colour, from nudes to French tips.",
      },
    ],
    ending: {
      title: "Short squoval or oval 🌸",
      body: "Your hands work hard, so a short squoval or oval set gives you a finished look without getting in the way. Short acrylics are also the easiest to wear for a first set, and they chip less on busy days.",
    },
    guide: {
      questionsToConsider: [
        "Do you want to ask about nail art in detail here, or save it for the appointment?",
        "Should a client who mentions a past reaction be booked for a patch test first?",
        "Would a photo upload of nails they love help your techs prepare?",
        "Do you offer gel or press-ons as an alternative for clients who can't keep up with infills?",
      ],
      howToUseResponses:
        "Check the reaction answers first and contact those clients before their appointment, so nobody finds out at the chair that a patch test was needed. The length, shape and colour answers tell your tech what to prepare and how long to book. If many people say they can't keep up with infills, that's a sign to promote a lower-maintenance service alongside acrylics.",
      customizeSteps: [
        "Rename the three results after the sets on your menu and add what each one costs to book.",
        "Adjust the scores on length and shape if your salon draws the lines differently, then move the bands to match.",
        "Share the link on your booking page or social profile so clients take it before they book.",
      ],
      faqs: [
        {
          q: "How do I choose an acrylic nail shape?",
          a: "Think about how you use your hands first. Short round, oval or squoval shapes are the most practical, almond suits most hands at medium length, and coffin or stiletto shapes need more length and care.",
        },
        {
          q: "How does this nail quiz pick a result?",
          a: "Each answer about daily routine, length and shape carries points. The total decides whether the quiz suggests a short, medium or long statement set, and you can change the points and bands.",
        },
        {
          q: "Why ask about reactions to nail products?",
          a: "Some people develop sensitivity to nail products, and a tech needs to know before starting. Anyone who answers yes is asked for details that you can review before the appointment.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "bedding-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes"],
    roles: ["marketing", "sales"],
    searchName: "Bedding quiz",
    title: "Bedding finder",
    icon: "Home",
    metaDescription:
      "Recommend bedding by how warm someone sleeps, the feel they like and their bedroom's climate. Scored answers pick cool, all-season or cosy bedding for their bed.",
    description: "Score how warm someone sleeps and the feel they like, then suggest cool, all-season or cosy bedding.",
    blurb:
      "The questions that actually decide bedding: whether they sleep hot or cold, how warm the room gets, and whether they like crisp or soft sheets. Each answer adds to a warmth score that picks one of three results, while bed size, mattress depth and allergy details go to your dashboard so the order fits first time.",
    tags: ["bedding quiz", "sheet finder", "duvet quiz", "home store", "sleep quiz"],
    greeting: "Let's find bedding you'll sleep well in. Tell us how you sleep and we'll suggest a set.",
    questions: [
      {
        ref: "bed_size",
        type: "dropdown",
        title: "What size is your bed?",
        required: true,
        options: [
          { label: "Single or twin" },
          { label: "Double or full" },
          { label: "Queen" },
          { label: "King" },
          { label: "Super king or California king" },
        ],
      },
      {
        ref: "mattress_depth",
        type: "number",
        title: "How deep is your mattress, including any topper?",
        description: "Optional, in centimetres. It tells us how deep a fitted sheet you need.",
        required: false,
        min: 5,
        max: 60,
        integerOnly: true,
      },
      {
        ref: "sleep_temp",
        type: "single_select",
        title: "How do you usually sleep?",
        required: true,
        options: [
          { label: "Hot, I kick the covers off", score: 0 },
          { label: "Somewhere in between", score: 1 },
          { label: "Cold, I'm the one stealing the duvet", score: 2 },
        ],
      },
      {
        ref: "room_temp",
        type: "single_select",
        title: "How warm is your bedroom at night?",
        required: true,
        options: [
          { label: "Warm, even in winter", score: 0 },
          { label: "Comfortable most of the year", score: 1 },
          { label: "Chilly, especially in winter", score: 2 },
        ],
      },
      {
        ref: "feel",
        type: "single_select",
        title: "Which feel do you like against your skin?",
        required: true,
        options: [
          { label: "Crisp and cool, like a fresh shirt", score: 0 },
          { label: "Smooth and silky", score: 1 },
          { label: "Soft and brushed, almost fuzzy", score: 2 },
        ],
      },
      {
        ref: "season",
        type: "single_select",
        title: "When will you use this bedding most?",
        required: true,
        options: [
          { label: "Mostly in summer", score: 0 },
          { label: "All year round", score: 1 },
          { label: "Mostly in winter", score: 2 },
        ],
      },
      {
        ref: "pieces",
        type: "multi_select",
        title: "What do you need?",
        required: true,
        minSelections: 1,
        maxSelections: 7,
        options: [
          { label: "Fitted sheet" },
          { label: "Flat sheet" },
          { label: "Duvet cover" },
          { label: "Pillowcases" },
          { label: "Duvet or comforter" },
          { label: "Pillows" },
          { label: "Mattress protector" },
        ],
      },
      {
        ref: "ironing",
        type: "opinion_scale",
        title: "How do you feel about ironing?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Never going to happen",
        labelHigh: "Happy to iron",
      },
      {
        ref: "allergies",
        type: "yes_no",
        title: "Does anyone sleeping here have allergies or sensitive skin?",
        required: true,
      },
      {
        ref: "allergy_detail",
        type: "multi_select",
        title: "Which of these should we avoid or look for?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        options: [
          { label: "Dust mite allergy" },
          { label: "Feather or down allergy" },
          { label: "Wool sensitivity" },
          { label: "Eczema or easily irritated skin" },
          { label: "Something else" },
        ],
      },
      {
        ref: "email",
        type: "email",
        title: "Want your picks sent over so you can shop later?",
        description: "Optional.",
        required: false,
      },
    ],
    branches: [
      { when: "allergies", is: true, then: "allergy_detail" },
      { when: "allergies", is: false, then: "email" },
    ],
    scoreEndings: [
      { atLeast: 6, then: "end_cosy" },
      { atLeast: 3, then: "end_all_season" },
    ],
    endings: [
      {
        ref: "end_cosy",
        title: "Warm and cosy 🧣",
        body: "Brushed cotton or flannel sheets with a heavier winter duvet. Brushed cotton traps a little warmth and feels soft from the first night, which is exactly what a cold sleeper in a chilly room wants.",
      },
      {
        ref: "end_all_season",
        title: "Cotton sateen, all season 🛏️",
        body: "Smooth cotton sateen sheets with a medium-weight duvet. Sateen feels silky and a touch warmer than crisp cotton, so it works across the year without swapping sets each season.",
      },
    ],
    ending: {
      title: "Cool and breathable ❄️",
      body: "Cotton percale or linen with a lightweight duvet. Percale is crisp and matte, and linen gets softer with every wash; both breathe well, which is what a hot sleeper needs. If you'd rather not iron, linen looks good a little rumpled.",
    },
    guide: {
      questionsToConsider: [
        "Which fabrics and duvet weights do you stock, and which result should each one sit under?",
        "Do you sell deep-pocket fitted sheets, and at what mattress depth should you suggest them?",
        "Should allergy answers lead to specific products, such as synthetic fillings instead of down?",
        "Would a colour or pattern question help, or is that better left to the product page?",
      ],
      howToUseResponses:
        "Use the bed size and mattress depth to check that the set you recommend actually fits before the customer orders, which saves a lot of returns. The allergy answers tell you when to steer someone away from feather and down fillings. Over time, the split between cool, all-season and cosy results is a useful guide for how much of each fabric to stock by season.",
      customizeSteps: [
        "Rename each result after the collection it matches in your store and describe what's in it.",
        "Check the scores on the four warmth questions and move the bands if your range has more than three warmth levels.",
        "Embed the quiz on your bedding category page or link to it from product pages where shoppers get stuck.",
      ],
      faqs: [
        {
          q: "How do I choose the right bedding for how I sleep?",
          a: "Start with temperature. Hot sleepers do best with breathable percale or linen and a light duvet, cold sleepers with brushed cotton or flannel and a heavier one.",
        },
        {
          q: "What is the difference between percale and sateen sheets?",
          a: "Percale has a crisp, matte, cool feel. Sateen has a smoother, silkier surface with a slight sheen and feels a little warmer.",
        },
        {
          q: "Why does the quiz ask about mattress depth?",
          a: "Fitted sheets come with different pocket depths, and a deep mattress or topper can pull a standard sheet off the corners. Knowing the depth lets you recommend a sheet that stays put.",
        },
        {
          q: "How are the bedding results worked out?",
          a: "Four questions about sleep temperature, room, feel and season each add points to a warmth score. The total picks cool, all-season or cosy bedding, and you can edit the points and bands.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "bike-wheel-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes", "generate-leads"],
    roles: ["sales", "customer-success"],
    searchName: "Bike wheel quiz",
    title: "Bike wheel finder",
    icon: "Bike",
    metaDescription:
      "Help riders pick wheels that fit their bike and riding. Checks size, brakes, axle and load, asks for a photo when unsure, and routes to one of four results.",
    description: "Check compatibility first, then match road, gravel, mountain or commuter riders to the right wheels.",
    blurb:
      "Compatibility comes first, because the wrong brake type or axle makes any wheel useless. Riders who don't know their brake type are asked for a photo so your shop can check, and the final question about where they ride sends them to a road, gravel, mountain or commuter result.",
    tags: ["bike wheel quiz", "wheelset finder", "bike shop", "cycling quiz", "wheel compatibility"],
    greeting: "Looking for new wheels? Let's check what fits your bike, then find what suits your riding.",
    questions: [
      {
        ref: "wheel_size",
        type: "dropdown",
        title: "What wheel size does your bike use?",
        description: "It's usually printed on the side of the tyre.",
        required: true,
        options: [
          { label: "700c" },
          { label: "650b" },
          { label: "29 inch" },
          { label: "27.5 inch" },
          { label: "26 inch" },
          { label: "20 inch or smaller" },
          { label: "Not sure" },
        ],
      },
      {
        ref: "brakes",
        type: "single_select",
        title: "What kind of brakes does your bike have?",
        required: true,
        options: [
          { label: "Rim brakes", description: "Pads squeeze the edge of the wheel" },
          { label: "Disc brakes", description: "A metal rotor sits at the centre of the wheel" },
          { label: "Not sure" },
        ],
      },
      {
        ref: "bike_photo",
        type: "file_upload",
        title: "No problem. Could you send a photo of the front wheel's centre and brake?",
        description: "We'll check the brake and axle type for you.",
        required: false,
        accept: ["image/*"],
        maxFiles: 2,
        maxSizeMB: 10,
      },
      {
        ref: "axle",
        type: "single_select",
        title: "How is the wheel held in the frame?",
        required: true,
        options: [
          { label: "Quick release lever" },
          { label: "Thru-axle", description: "A thick axle that screws through the frame" },
          { label: "Nuts on the axle" },
          { label: "Not sure" },
        ],
      },
      {
        ref: "tubeless",
        type: "single_select",
        title: "Do you want to run tubeless tyres?",
        required: true,
        options: [{ label: "Yes" }, { label: "No, I'll stick with tubes" }, { label: "Not sure what that means" }],
      },
      {
        ref: "load",
        type: "yes_no",
        title: "Will the wheels carry extra load, like panniers, a child seat or a heavier rider?",
        description: "Stronger builds with more spokes are worth it here.",
        required: true,
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "Rank what matters most in your new wheels.",
        required: true,
        items: ["Durability", "Low weight", "Speed and aerodynamics", "Comfort", "Price"],
      },
      {
        ref: "budget",
        type: "dropdown",
        title: "What budget do you have in mind for the pair?",
        description: "Replace these tiers with the price ranges you sell.",
        required: true,
        options: [{ label: "Budget friendly" }, { label: "Mid range" }, { label: "High end" }, { label: "Not sure yet" }],
      },
      {
        ref: "email",
        type: "email",
        title: "Where should we send the wheels that fit?",
        description: "Optional, but we need it to reply if you sent a photo.",
        required: false,
      },
      {
        ref: "riding",
        type: "single_select",
        title: "Last question: where do you ride most?",
        required: true,
        options: [
          { label: "Tarmac, training and fast group rides" },
          { label: "Gravel, towpaths and mixed surfaces" },
          { label: "Mountain bike trails" },
          { label: "Commuting and getting around town" },
        ],
      },
    ],
    branches: [
      { when: "brakes", is: "Rim brakes", then: "axle" },
      { when: "brakes", is: "Disc brakes", then: "axle" },
      { when: "brakes", is: "Not sure", then: "bike_photo" },
      { when: "riding", is: "Tarmac, training and fast group rides", then: "end_road" },
      { when: "riding", is: "Gravel, towpaths and mixed surfaces", then: "end_gravel" },
      { when: "riding", is: "Mountain bike trails", then: "end_mtb" },
    ],
    endings: [
      {
        ref: "end_road",
        title: "A lightweight road wheelset 🚴",
        body: "Lighter rims spin up faster and deeper profiles hold speed on flat roads, which is where road wheels earn their money. We'll match the brake type and axle you gave us, and suggest a stronger build if you're carrying extra load.",
      },
      {
        ref: "end_gravel",
        title: "A tough, wide gravel wheelset 🪨",
        body: "Wider rims support bigger tyres at lower pressure, which means more grip and comfort on rough surfaces. Tubeless-ready gravel wheels also shrug off the small punctures that come with it.",
      },
      {
        ref: "end_mtb",
        title: "A trail-ready mountain bike wheelset 🌲",
        body: "Trail wheels need to take hits more than save grams, so look for strong rims, a solid hub and tubeless compatibility. We'll check your wheel size and axle standard before suggesting a pair.",
      },
    ],
    ending: {
      title: "A durable commuter wheelset 🏙️",
      body: "For daily riding, a strong wheel with more spokes and reliable sealed bearings will outlast lighter options and needs less truing. Pair it with puncture-resistant tyres and it'll handle potholes and kerbs for years.",
    },
    guide: {
      questionsToConsider: [
        "Which wheel sizes, brake mounts and axle standards do you actually stock?",
        "Who in the shop will look at the photos riders send, and how quickly can they reply?",
        "Do you want an extra result for e-bikes or cargo bikes if you sell wheels for them?",
        "Should riders who pick high end see an offer to book a fitting or a test ride?",
      ],
      howToUseResponses:
        "Start with the rows that include a photo or a \"Not sure\" answer, since those riders need a person to confirm compatibility before they buy anything. For everyone else, the wheel size, brake and axle answers let you filter your stock to the wheels that fit. Export to CSV to see which riding result is most common and plan stock around it.",
      customizeSteps: [
        "Edit the wheel size, brake and axle options to match the standards in your range.",
        "Rename each result after the wheelsets you'd genuinely recommend and add their key specs.",
        "Put the quiz on your wheels page and share the link when riders ask what will fit.",
      ],
      faqs: [
        {
          q: "How do I know which bike wheels will fit my bike?",
          a: "You need the wheel size, the brake type (rim or disc) and the axle type, such as quick release or thru-axle. The tyre sidewall usually shows the size, and a bike shop can confirm the rest.",
        },
        {
          q: "What happens when a rider doesn't know their brake type?",
          a: "The quiz asks for a photo of the wheel's centre and brake, so someone at your shop can check it before recommending anything.",
        },
        {
          q: "How does the quiz choose between road, gravel, mountain and commuter wheels?",
          a: "The final question about where they ride routes each rider to one of four results. You can edit the options and rewrite each result for your own wheelsets.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "board-game-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes"],
    roles: ["marketing", "sales"],
    searchName: "Board game recommendation quiz",
    title: "Board game finder",
    icon: "Dices",
    metaDescription:
      "Find a group's next board game from player count, play time, experience and the kind of evening they want. Five results: party, co-op, gateway, heavy and duel games.",
    description: "Match a group to a party, co-op, gateway, strategy or two-player game.",
    blurb:
      "Asks the questions a good game shop assistant asks: how long you have, who's at the table, what puts them off and what they've enjoyed before. Pairs get their own question about competing or cooperating, so nobody playing as two is sent a party game, and larger groups pick the evening they want from four results, each with well-known games to try.",
    tags: ["board game quiz", "game recommendation", "game night", "board game shop", "gift finder"],
    greeting: "Looking for your next favourite game? Tell us about your table and we'll suggest where to start.",
    questions: [
      {
        ref: "time",
        type: "single_select",
        title: "How long do you want a game to last?",
        required: true,
        options: [
          { label: "Under 30 minutes" },
          { label: "30 minutes to an hour" },
          { label: "One to two hours" },
          { label: "As long as it takes" },
        ],
      },
      {
        ref: "ages",
        type: "multi_select",
        title: "Who's at the table? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        options: [{ label: "Children under 8" }, { label: "Children 8 to 12" }, { label: "Teenagers" }, { label: "Adults" }],
      },
      {
        ref: "experience",
        type: "opinion_scale",
        title: "How experienced is your group with board games?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Monopoly is about it",
        labelHigh: "We have a shelf full",
      },
      {
        ref: "avoid",
        type: "multi_select",
        title: "Anything that puts your group off?",
        required: false,
        minSelections: 0,
        maxSelections: 5,
        options: [
          { label: "Lots of rules to learn" },
          { label: "Taking things from other players" },
          { label: "Dice deciding who wins" },
          { label: "Lots of reading" },
          { label: "Long setup" },
        ],
      },
      {
        ref: "themes",
        type: "multi_select",
        title: "Which themes sound fun?",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        options: [
          { label: "Fantasy and adventure" },
          { label: "Space and science fiction" },
          { label: "Nature and animals" },
          { label: "Trains, trade and building" },
          { label: "Mystery and deduction" },
          { label: "No preference" },
        ],
      },
      {
        ref: "favourite",
        type: "short_text",
        title: "Name a game your group already loves, if you have one.",
        required: false,
        maxLength: 120,
      },
      {
        ref: "email",
        type: "email",
        title: "Want us to send your recommendations?",
        description: "Optional.",
        required: false,
      },
      {
        ref: "players",
        type: "single_select",
        title: "Nearly done. How many people usually play?",
        required: true,
        options: [{ label: "Just two" }, { label: "Three or four" }, { label: "Five or six" }, { label: "Seven or more" }],
      },
      {
        ref: "duo_style",
        type: "single_select",
        title: "Two players it is. How do you like to play?",
        required: true,
        options: [{ label: "Head to head, may the best player win" }, { label: "On the same side, against the game" }],
      },
      {
        ref: "evening",
        type: "single_select",
        title: "Finally, which game night sounds best?",
        required: true,
        options: [
          { label: "Loud, silly and full of laughs" },
          { label: "Working together to beat the game" },
          { label: "A friendly contest with easy rules" },
          { label: "A deep, thinky game with long-term plans" },
        ],
      },
    ],
    branches: [
      { when: "evening", is: "Loud, silly and full of laughs", then: "end_party" },
      { when: "evening", is: "Working together to beat the game", then: "end_coop" },
      { when: "evening", is: "A deep, thinky game with long-term plans", then: "end_heavy" },
      { when: "players", is: "Just two", then: "duo_style" },
      { when: "players", is: "Three or four", then: "evening" },
      { when: "players", is: "Five or six", then: "evening" },
      { when: "players", is: "Seven or more", then: "evening" },
      { when: "duo_style", is: "Head to head, may the best player win", then: "end_duo" },
      { when: "duo_style", is: "On the same side, against the game", then: "end_coop" },
    ],
    endings: [
      {
        ref: "end_party",
        title: "Party games 🎉",
        body: "Quick rules, big groups and plenty of shouting. Try Codenames, Just One or Wavelength: each one is taught in a couple of minutes and works with a crowd.",
      },
      {
        ref: "end_coop",
        title: "Cooperative games 🤝",
        body: "Everyone wins or loses together, so nobody goes home sore. Forbidden Island is a gentle start, Pandemic is the classic, and The Crew turns a card game into a team puzzle.",
      },
      {
        ref: "end_heavy",
        title: "Heavy strategy games 🧠",
        body: "Your group wants decisions that pay off an hour later. Terraforming Mars and Brass: Birmingham reward planning and repeat plays, so set aside a full evening for the first game.",
      },
      {
        ref: "end_duo",
        title: "Two-player games ⚔️",
        body: "Games designed for two are tighter than big games played with two. 7 Wonders Duel, Patchwork and Jaipur each play in under an hour and stay tense to the end.",
      },
    ],
    ending: {
      title: "Gateway strategy games 🚂",
      body: "Easy to learn, with enough choices to keep everyone interested. Ticket to Ride, Carcassonne and Azul are favourites for a reason: they suit mixed groups and new players pick them up in one game.",
    },
    guide: {
      questionsToConsider: [
        "Which games do you have in stock for each result, and how often will you update them?",
        "Should families with young children get their own result with games made for them?",
        "Would you like to invite people to a demo night or a games library if you run one?",
        "Is this a gift finder, where the person answering isn't the one who will play?",
      ],
      howToUseResponses:
        "Read the favourite game and avoid answers together: they tell you more than any single result. Someone who loves one game but hates taking things from other players is a clear hint for your next suggestion. Export to CSV to see which kinds of game night people want most, and use it to plan stock and events.",
      customizeSteps: [
        "Replace the example games in each result with titles you stock and want to recommend.",
        "Add or remove options in the last two questions, keeping one branch for each result.",
        "Embed the quiz on your shop's site or share the link before a game night.",
      ],
      faqs: [
        {
          q: "How do I pick a board game for my group?",
          a: "Start with player count and how long you want to play, then think about the mood: laughing, cooperating, a light contest or a long strategy game. What your group already enjoys is the best clue.",
        },
        {
          q: "What is a gateway board game?",
          a: "A game with simple rules and real decisions that works well for people new to modern board games. Ticket to Ride and Carcassonne are common examples.",
        },
        {
          q: "Can I change the games this quiz recommends?",
          a: "Yes. Each result is an ending you can rewrite, so swap in the games you stock and edit the final question to match.",
        },
        {
          q: "What are good board games for two players?",
          a: "Games designed for two, such as 7 Wonders Duel, Patchwork and Jaipur, stay tense in a way many bigger games don't at two. Pairs who prefer teaming up can try cooperative games like Pandemic.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "book-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes"],
    roles: ["marketing", "education"],
    searchName: "Book recommendation quiz",
    title: "What should I read next?",
    icon: "BookOpen",
    metaDescription:
      "Help readers find their next book by mood, length and recent favourites. Each mood opens its own follow-up question and leads to a result with titles to try and why.",
    description: "Ask about mood and reading habits, then suggest a genre with titles to try next.",
    blurb:
      "Starts with the reader rather than the genre shelf: a book they loved, how long they like a book to be and how they read. Their mood then opens a short follow-up of its own, such as how dark a thriller can get, before landing on one of six results with titles to try. Someone who wants a gripping read but nothing grim gets a cosy mystery, not a dark thriller.",
    tags: ["book recommendation quiz", "what to read next", "bookshop", "library", "reading quiz"],
    greeting: "Stuck on what to read next? Answer a few questions and we'll suggest a book to pick up.",
    questions: [
      {
        ref: "loved_book",
        type: "short_text",
        title: "What's a book you loved recently?",
        required: false,
        maxLength: 150,
      },
      {
        ref: "length",
        type: "single_select",
        title: "How long do you like a book to be?",
        required: true,
        options: [{ label: "Short, something I can finish in a weekend" }, { label: "Any length is fine" }, { label: "Long, I want to live in it" }],
      },
      {
        ref: "format",
        type: "multi_select",
        title: "How do you like to read?",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        options: [{ label: "Print" }, { label: "E-reader" }, { label: "Audiobook" }],
      },
      {
        ref: "pace",
        type: "opinion_scale",
        title: "Do you prefer a slow burn or a fast pace?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Slow and immersive",
        labelHigh: "Can't stop turning pages",
      },
      {
        ref: "email",
        type: "email",
        title: "Where should we send your reading list?",
        description: "Optional.",
        required: false,
      },
      {
        ref: "mood",
        type: "single_select",
        title: "What are you in the mood for right now?",
        required: true,
        options: [
          { label: "Something gripping I can't put down" },
          { label: "A story that takes me somewhere else entirely" },
          { label: "Something warm that makes me smile" },
          { label: "Real life: true stories and big ideas" },
          { label: "Beautiful writing that stays with me" },
        ],
      },

      // Gripping
      {
        ref: "darkness",
        type: "single_select",
        title: "How dark can it get?",
        required: true,
        options: [{ label: "Keep it cosy, nothing grim" }, { label: "Tense is good, but not too gory" }, { label: "Dark and twisty is fine" }],
      },

      // Somewhere else
      {
        ref: "world",
        type: "single_select",
        title: "Magic or science?",
        required: true,
        options: [{ label: "Magic and other worlds" }, { label: "Science and the future" }, { label: "Either works" }],
      },

      // Warm
      {
        ref: "warm_kind",
        type: "single_select",
        title: "Which sounds more like you?",
        required: true,
        options: [{ label: "Laugh-out-loud funny" }, { label: "Gentle and heartwarming" }, { label: "A love story" }],
      },

      // Real life
      {
        ref: "topics",
        type: "multi_select",
        title: "Which topics pull you in?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        options: [
          { label: "Memoir and life stories" },
          { label: "History" },
          { label: "Science and nature" },
          { label: "Psychology and how people think" },
          { label: "True crime" },
        ],
      },

      // Beautiful writing
      {
        ref: "literary_setting",
        type: "single_select",
        title: "Where would you like the story to be set?",
        required: false,
        options: [{ label: "The past" }, { label: "The present day" }, { label: "Somewhere slightly off from our world" }, { label: "Anywhere" }],
      },
    ],
    branches: [
      { when: "mood", is: "Something gripping I can't put down", then: "darkness" },
      { when: "mood", is: "A story that takes me somewhere else entirely", then: "world" },
      { when: "mood", is: "Something warm that makes me smile", then: "warm_kind" },
      { when: "mood", is: "Real life: true stories and big ideas", then: "topics" },
      { when: "mood", is: "Beautiful writing that stays with me", then: "literary_setting" },
      { when: "darkness", is: "Keep it cosy, nothing grim", then: "end_cosy_mystery" },
      { when: "darkness", is: "Tense is good, but not too gory", then: "end_thriller" },
      { when: "darkness", is: "Dark and twisty is fine", then: "end_thriller" },
      { when: "world", always: true, then: "end_speculative" },
      { when: "warm_kind", always: true, then: "end_feelgood" },
      { when: "topics", always: true, then: "end_nonfiction" },
    ],
    endings: [
      {
        ref: "end_thriller",
        title: "A page-turning thriller 🔪",
        body: "You want momentum and a twist you didn't see coming. Try Gone Girl by Gillian Flynn or The Silent Patient by Alex Michaelides: both are hard to put down once they get going.",
      },
      {
        ref: "end_cosy_mystery",
        title: "A cosy mystery 🫖",
        body: "All the fun of a whodunnit without the grim parts. Try The Thursday Murder Club by Richard Osman, where four friends in a retirement village take on a real murder case.",
      },
      {
        ref: "end_speculative",
        title: "Fantasy or science fiction 🚀",
        body: "You want a whole new world to get lost in. For science, Project Hail Mary by Andy Weir is clever and funny. For magic, The Name of the Wind by Patrick Rothfuss is a long, rich read.",
      },
      {
        ref: "end_feelgood",
        title: "A feel-good novel ☀️",
        body: "Warmth and humour it is. A Man Called Ove by Fredrik Backman and The House in the Cerulean Sea by TJ Klune are both funny, kind and quietly moving. If it's romance you're after, Beach Read by Emily Henry is a warm, witty place to start.",
      },
      {
        ref: "end_nonfiction",
        title: "Narrative nonfiction 🧭",
        body: "True stories told as well as any novel. Educated by Tara Westover is a gripping memoir, and Sapiens by Yuval Noah Harari is a big-picture read that sparks conversations.",
      },
    ],
    ending: {
      title: "Literary fiction 📖",
      body: "You read for the writing and the characters that stay with you. Try Never Let Me Go by Kazuo Ishiguro or Tomorrow, and Tomorrow, and Tomorrow by Gabrielle Zevin.",
    },
    guide: {
      questionsToConsider: [
        "Do you want the results to name specific titles, or point to a shelf or reading list you keep updated?",
        "Should the format answer change what you suggest, for example audiobook editions?",
        "Is this for a bookshop, a library, a book club or a classroom, and does the age range need its own question?",
        "Would an extra result for poetry, graphic novels or young adult books suit your readers?",
      ],
      howToUseResponses:
        "The loved book answer is the most useful thing here: read it alongside the mood to make a personal suggestion if someone asks for more. Export the responses to CSV to see which moods are most common and shape displays or reading lists around them. For a library or book club, the topics chosen by nonfiction readers are a good guide for the next themed event.",
      customizeSteps: [
        "Swap the example titles in each result for books you stock or have on your shelves.",
        "Edit the follow-up question in each mood's branch so it narrows toward the titles you want to suggest.",
        "Share the link on your website, newsletter or a QR code by the till.",
      ],
      faqs: [
        {
          q: "How do I find a book I'll actually like?",
          a: "Start with a book you loved and the mood you're in, rather than a genre. Pace and length matter too: a slow, immersive read and a fast thriller suit very different evenings.",
        },
        {
          q: "How does this book quiz decide what to recommend?",
          a: "The mood question opens a short follow-up for that mood and then leads to one of six results. You can rewrite every result and move the branches.",
        },
        {
          q: "Can a library or bookshop use this quiz?",
          a: "Yes. Replace the example titles with books on your shelves and share the link or embed the quiz on your website.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "boule-patanque-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes"],
    roles: ["sales", "marketing"],
    searchName: "Pétanque boules quiz",
    title: "Pétanque boule finder",
    icon: "Target",
    metaDescription:
      "Help players choose pétanque boules. Casual players get a garden or beach set, and club players are matched on hand size, grip and whether they point or shoot.",
    description: "Send leisure players to a garden set and match club players to boules for pointing or shooting.",
    blurb:
      "Splits early between people playing for fun and people playing in a club, because they need different boules. Leisure players are asked where and with whom they play, while club players answer about hand size, grip and weight before their playing position picks a pointer, shooter or all-round result.",
    tags: ["petanque boules quiz", "boules buying guide", "petanque shop", "competition boules", "garden games"],
    greeting: "Choosing pétanque boules? A few questions about how you play and we'll suggest the right set.",
    questions: [
      {
        ref: "experience",
        type: "single_select",
        title: "How long have you been playing?",
        required: true,
        options: [{ label: "I'm just starting out" }, { label: "A few seasons, casually" }, { label: "Years, I play in a club" }],
      },
      {
        ref: "for_whom",
        type: "single_select",
        title: "Who are the boules for?",
        required: true,
        options: [{ label: "Me" }, { label: "A gift for someone else" }, { label: "A club or group" }],
      },
      {
        ref: "email",
        type: "email",
        title: "Where should we send your suggestion?",
        description: "Optional.",
        required: false,
      },
      {
        ref: "competition",
        type: "single_select",
        title: "Will the boules be used in club matches or competitions?",
        required: true,
        options: [{ label: "Yes, club or competition play" }, { label: "No, just for fun" }],
      },

      // Club players
      {
        ref: "hand_size",
        type: "single_select",
        title: "How would you describe your hand size?",
        description: "Your boule should sit comfortably in your palm with your fingers wrapped around it.",
        required: true,
        options: [{ label: "Small" }, { label: "Medium" }, { label: "Large" }, { label: "Not sure" }],
      },
      {
        ref: "grip",
        type: "single_select",
        title: "Which surface do you prefer?",
        required: true,
        options: [{ label: "Smooth" }, { label: "Lightly grooved" }, { label: "Deeply grooved" }, { label: "No preference" }],
      },
      {
        ref: "weight_feel",
        type: "opinion_scale",
        title: "Do you like a boule that feels light or heavy in the hand?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Light",
        labelHigh: "Heavy",
      },
      {
        ref: "engraving",
        type: "yes_no",
        title: "Would you like your initials or a name engraved on the set?",
        required: false,
      },
      {
        ref: "position",
        type: "single_select",
        title: "Which role do you usually play on your team?",
        required: true,
        options: [
          { label: "Pointer", description: "I roll close to the jack" },
          { label: "Shooter", description: "I knock opponents' boules away" },
          { label: "A bit of both" },
        ],
      },

      // Leisure players
      {
        ref: "where",
        type: "single_select",
        title: "Where will you mostly play?",
        required: true,
        options: [{ label: "In the garden or on a lawn" }, { label: "On the beach" }, { label: "On gravel in a park" }, { label: "All over the place" }],
      },
      {
        ref: "who_plays",
        type: "multi_select",
        title: "Who will be playing?",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        options: [{ label: "Adults" }, { label: "Children" }, { label: "Older players" }],
      },
    ],
    branches: [
      { when: "competition", is: "Yes, club or competition play", then: "hand_size" },
      { when: "competition", is: "No, just for fun", then: "where" },
      { when: "position", is: "Pointer", then: "end_pointer" },
      { when: "position", is: "Shooter", then: "end_shooter" },
      { when: "position", is: "A bit of both", then: "end_allround" },
    ],
    endings: [
      {
        ref: "end_pointer",
        title: "Competition boules for pointing 🎯",
        body: "Pointers often choose a slightly smaller, heavier boule that stays where it lands, with grooves for a sure grip. We'll suggest competition-approved sets in the size that fits your hand.",
      },
      {
        ref: "end_shooter",
        title: "Competition boules for shooting 💥",
        body: "Shooters often prefer a slightly larger, lighter boule that is easier to throw hard and accurately. We'll suggest competition-approved sets that suit your hand and the grip you like.",
      },
      {
        ref: "end_allround",
        title: "An all-round competition set ⚖️",
        body: "If you point and shoot, a mid-weight boule in a size that fits your hand is the safe choice. It won't be the specialist's pick for either role, but it lets you play both without switching sets.",
      },
    ],
    ending: {
      title: "A leisure set for fun 🏖️",
      body: "For garden, beach and park games you don't need competition boules. A leisure set in a carry bag with a jack and a measuring tape is ideal, and lighter sets are easier for children and older players to throw.",
    },
    guide: {
      questionsToConsider: [
        "Which competition-approved and leisure sets do you sell, and which result should each one sit under?",
        "Would a hand measurement guide help players who answer not sure?",
        "Do you offer engraving, and should the quiz mention what it involves?",
        "Should gifts get their own result with a gift set or voucher?",
      ],
      howToUseResponses:
        "Club players' answers about hand size, grip and weight tell you exactly which sets to offer, so reply with two or three options rather than one. Anyone who wants engraving or is buying for a club is worth a personal follow-up. Export to CSV to see how many players are leisure versus competition, and balance your stock between the two.",
      customizeSteps: [
        "Rename each result after the sets you sell and add their sizes and weights.",
        "Check the grip and weight options match the choices your range actually offers.",
        "Share the link or embed the quiz on your boules page, and bring it up on a tablet at club events.",
      ],
      faqs: [
        {
          q: "How do I choose the right size pétanque boule?",
          a: "Pick a boule that sits comfortably in your palm with your fingers wrapped around it. Your hand size and whether you mostly point or shoot are the two main things to consider.",
        },
        {
          q: "Do I need competition boules to play pétanque?",
          a: "Only if you play in official competitions, which require approved boules. For the garden or the beach, a leisure set works fine.",
        },
        {
          q: "What's the difference between boules for pointing and shooting?",
          a: "Pointers often prefer smaller, heavier boules that stay put, while shooters often prefer larger, lighter boules that are easier to throw hard. Personal feel matters most, so try a few if you can.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "bridal-accessories-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes", "generate-leads"],
    roles: ["freelancers-agencies", "sales"],
    searchName: "Bridal accessories quiz",
    title: "Bridal accessories finder",
    icon: "Gem",
    metaDescription:
      "Help brides choose a veil, headpiece and jewellery that suit the dress, hair and wedding style. Their style leads to one of four coordinated looks.",
    description: "Match accessories to the dress, hair and wedding style, then suggest a coordinated look.",
    blurb:
      "Asks about the dress first, because neckline and detail decide most accessory choices, then hair, metals, comfort and what's still missing. The bride's overall style picks one of four coordinated looks, and her wedding date and budget go to your dashboard for the follow-up.",
    tags: ["bridal accessories quiz", "wedding veil quiz", "bridal jewellery", "bridal boutique", "wedding style"],
    greeting: "Congratulations! Let's find the finishing touches for your wedding look.",
    questions: [
      {
        ref: "wedding_date",
        type: "date",
        title: "When's the wedding?",
        required: true,
        disablePast: true,
      },
      {
        ref: "neckline",
        type: "dropdown",
        title: "What neckline does your dress have?",
        required: true,
        options: [
          { label: "Strapless or sweetheart" },
          { label: "V-neck" },
          { label: "Off the shoulder" },
          { label: "High neck or halter" },
          { label: "Square or straight" },
          { label: "Still choosing my dress" },
        ],
      },
      {
        ref: "dress_detail",
        type: "single_select",
        title: "How much detail does the dress have?",
        required: true,
        options: [{ label: "Lots of beading, lace or sparkle" }, { label: "Some detail" }, { label: "Clean and simple" }],
      },
      {
        ref: "hair",
        type: "single_select",
        title: "How are you planning to wear your hair?",
        required: true,
        options: [{ label: "Up" }, { label: "Half up" }, { label: "Down" }, { label: "Not decided" }],
      },
      {
        ref: "needs",
        type: "multi_select",
        title: "Which accessories are you still looking for?",
        required: true,
        minSelections: 1,
        maxSelections: 7,
        options: [
          { label: "Veil" },
          { label: "Headpiece or hair accessory" },
          { label: "Earrings" },
          { label: "Necklace" },
          { label: "Bracelet" },
          { label: "Belt or sash" },
          { label: "Cover-up or shawl" },
        ],
      },
      {
        ref: "metal",
        type: "single_select",
        title: "Which metal or finish do you wear most?",
        required: true,
        options: [{ label: "Silver or white gold" }, { label: "Gold" }, { label: "Rose gold" }, { label: "Pearls" }, { label: "A mix" }],
      },
      {
        ref: "comfort",
        type: "opinion_scale",
        title: "How much do you mind wearing something you can feel all day?",
        description: "Think heavy earrings, a long veil or a snug headpiece.",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "I want to forget it's there",
        labelHigh: "Worth it for the look",
      },
      {
        ref: "budget",
        type: "dropdown",
        title: "What budget do you have for accessories?",
        description: "Replace these with the ranges that fit your boutique.",
        required: true,
        options: [{ label: "Keeping it modest" }, { label: "Mid range" }, { label: "Happy to splurge on the right piece" }, { label: "Not sure yet" }],
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we send your look to?",
        required: false,
        fields: ["first_name", "email", "phone"],
      },
      {
        ref: "style",
        type: "single_select",
        title: "Last one: which word best describes your wedding style?",
        required: true,
        options: [
          { label: "Classic and timeless" },
          { label: "Boho and romantic" },
          { label: "Modern and minimal" },
          { label: "Glamorous" },
        ],
      },
    ],
    branches: [
      { when: "neckline", is: "Still choosing my dress", then: "hair" },
      { when: "style", is: "Boho and romantic", then: "end_boho" },
      { when: "style", is: "Modern and minimal", then: "end_modern" },
      { when: "style", is: "Glamorous", then: "end_glam" },
    ],
    endings: [
      {
        ref: "end_boho",
        title: "Soft and romantic 🌿",
        body: "A hair vine or floral comb, delicate gold drops and a soft, simple veil, or no veil at all. Loose, natural pieces suit flowing dresses and look lovely with hair worn down or half up.",
      },
      {
        ref: "end_modern",
        title: "Clean and modern 🤍",
        body: "One strong piece instead of many: sculptural earrings or a sleek bow, with a raw-edge or single-layer veil if you want one. A simple dress lets a single statement accessory stand out.",
      },
      {
        ref: "end_glam",
        title: "Full glamour ✨",
        body: "Crystal earrings, a sparkling headpiece and a long veil with a beaded or lace edge. If your dress already has a lot of sparkle, pick one of these to shine and keep the rest quiet.",
      },
    ],
    ending: {
      title: "Classic and timeless 🕊️",
      body: "Pearl or diamond-style studs, a fine necklace or none if your neckline is high, and a fingertip or cathedral veil. Classic pieces photograph well and still look right when you look back at the pictures years later.",
    },
    guide: {
      questionsToConsider: [
        "Which of your accessories belong under each of the four looks?",
        "Do you want brides still choosing a dress to get a different result, or an invitation to come back later?",
        "Should the wedding date change how you follow up, for example priority for weddings within two months?",
        "Would a photo of the dress help your stylists more than the neckline question?",
      ],
      howToUseResponses:
        "Sort by wedding date first so brides with close dates hear from you quickly. The neckline, hair and needs answers let a stylist put together a shortlist before the appointment, so the bride walks in to pieces already chosen for her. Export to CSV to see which looks are most popular and plan your stock by season.",
      customizeSteps: [
        "Rename each look after collections or pieces in your boutique and describe them in your own words.",
        "Edit the needs list to match what you sell, removing anything you don't stock.",
        "Share the link after a dress fitting or embed the quiz on your accessories page.",
      ],
      faqs: [
        {
          q: "How do I choose bridal accessories to match my dress?",
          a: "Start with the neckline and how detailed the dress is. A high or detailed neckline usually needs no necklace, while a simple strapless dress can carry a statement piece.",
        },
        {
          q: "Should I wear a veil or a headpiece?",
          a: "It depends on your hair and style. Hair worn up suits a comb or veil set at the back, while a hair vine or floral piece suits hair worn down or half up.",
        },
        {
          q: "How does this bridal accessories quiz choose a look?",
          a: "The final question about wedding style routes the bride to one of four coordinated looks, and the earlier answers help your stylist refine them.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "bridesmaid-dress-recommendation-quiz",
    type: "quiz",
    category: "product-recommendation",
    goals: ["engage-with-quizzes", "generate-leads"],
    roles: ["freelancers-agencies", "sales"],
    searchName: "Bridesmaid dress quiz",
    title: "Bridesmaid dress finder",
    icon: "Users",
    metaDescription:
      "Help a bridal party choose a bridesmaid dress approach from wedding style, colours, fit needs and budget, then suggest matching, same-colour or mixed dresses.",
    description: "Suggest matching, same-colour or mix-and-match dresses for the whole bridal party.",
    blurb:
      "Collects what a bridal stylist needs before an appointment: the date, how many bridesmaids, the wedding style, colours, length and fit needs across the group. The answer about how matched the party should look sends them to one of three approaches, with a clear suggestion for anyone still unsure.",
    tags: ["bridesmaid dress quiz", "bridal party", "bridesmaid colours", "bridal boutique", "wedding planning"],
    greeting: "Dressing the bridal party? Let's work out an approach that looks great and works for everyone.",
    questions: [
      {
        ref: "role",
        type: "single_select",
        title: "Who's taking the quiz?",
        required: true,
        options: [{ label: "The bride or couple" }, { label: "Maid of honour" }, { label: "A bridesmaid" }, { label: "A wedding planner" }],
      },
      {
        ref: "wedding_date",
        type: "date",
        title: "When's the wedding?",
        required: true,
        disablePast: true,
      },
      {
        ref: "party_size",
        type: "number",
        title: "How many bridesmaids need dresses?",
        required: true,
        min: 1,
        max: 20,
        integerOnly: true,
      },
      {
        ref: "wedding_style",
        type: "single_select",
        title: "What's the wedding like?",
        required: true,
        options: [
          { label: "Formal, black tie" },
          { label: "Rustic or outdoors" },
          { label: "Beach or destination" },
          { label: "City and modern" },
          { label: "Relaxed and boho" },
        ],
      },
      {
        ref: "colours",
        type: "short_text",
        title: "What colours are you thinking of?",
        description: "A colour, a palette, or even a flower you're matching.",
        required: false,
        maxLength: 150,
      },
      {
        ref: "length",
        type: "single_select",
        title: "Which length do you want?",
        required: true,
        options: [{ label: "Floor length" }, { label: "Midi" }, { label: "Short" }, { label: "Each bridesmaid can choose" }],
      },
      {
        ref: "fit_needs",
        type: "multi_select",
        title: "Any fit needs across the group? Pick all that apply.",
        required: false,
        minSelections: 0,
        maxSelections: 6,
        options: [
          { label: "A wide range of sizes" },
          { label: "Someone will be pregnant" },
          { label: "Sleeves or straps wanted" },
          { label: "Pockets, please" },
          { label: "Different heights" },
          { label: "None of these" },
        ],
      },
      {
        ref: "who_pays",
        type: "single_select",
        title: "Who's paying for the dresses?",
        required: true,
        options: [{ label: "The couple" }, { label: "Each bridesmaid" }, { label: "We're splitting it" }],
      },
      {
        ref: "budget",
        type: "dropdown",
        title: "What's the budget per dress?",
        description: "Replace these tiers with your own price ranges.",
        required: true,
        options: [{ label: "Budget friendly" }, { label: "Mid range" }, { label: "Designer" }, { label: "Not sure yet" }],
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we send the suggestions to?",
        required: false,
        fields: ["first_name", "email", "phone"],
      },
      {
        ref: "matching",
        type: "single_select",
        title: "Last question: how matched should the bridal party look?",
        required: true,
        options: [
          { label: "Identical dresses" },
          { label: "Same colour, each in her own style" },
          { label: "A palette of related colours" },
          { label: "I'm not sure yet" },
        ],
      },
    ],
    branches: [
      { when: "matching", is: "Identical dresses", then: "end_matching" },
      { when: "matching", is: "Same colour, each in her own style", then: "end_same_colour" },
      { when: "matching", is: "I'm not sure yet", then: "end_same_colour" },
    ],
    endings: [
      {
        ref: "end_matching",
        title: "Matching dresses 👗",
        body: "One style in one colour gives the neatest photos and suits formal weddings. Choose a forgiving cut, such as a wrap or A-line, in a fabric with a little stretch so every bridesmaid is comfortable. Order early so there's time for alterations.",
      },
      {
        ref: "end_same_colour",
        title: "Same colour, different styles 💐",
        body: "Everyone wears the same colour and fabric but picks the neckline and cut that suits her. It still looks planned in photos, and it's the easiest way to make a group of different shapes and sizes feel good. If you're unsure, this is the one we'd start with.",
      },
    ],
    ending: {
      title: "Mix and match a palette 🎨",
      body: "Choose three or four related shades and let each bridesmaid pick a dress within them. Keeping the length or fabric the same ties it together, and it suits relaxed, boho and outdoor weddings especially well.",
    },
    guide: {
      questionsToConsider: [
        "Which of your ranges come in many colours or styles, and which result should each sit under?",
        "Do you offer fabric swatches or group appointments you could mention in the results?",
        "Should weddings less than a few months away get a note about ordering and alteration times?",
        "Is it useful to know who is paying before you recommend a price range?",
      ],
      howToUseResponses:
        "Sort by wedding date so parties with the least time get a reply first, since ordering and alterations take time. The party size, fit needs and who is paying tell you which ranges to show: a large group paying for their own dresses needs options at a price everyone can manage. Export to CSV to plan group appointments and see which approach most parties choose.",
      customizeSteps: [
        "Rename the results after the ranges you'd suggest for each approach and describe them.",
        "Edit the wedding style, length and budget options to match what your boutique offers.",
        "Share the link with brides after their first appointment or embed it on your bridesmaid page.",
      ],
      faqs: [
        {
          q: "Should bridesmaid dresses match?",
          a: "They don't have to. Identical dresses look neat and formal, the same colour in different styles suits a mix of body shapes, and a palette of related shades feels relaxed.",
        },
        {
          q: "How far in advance should bridesmaid dresses be ordered?",
          a: "As early as you can, especially for a large group, because ordering and alterations both take time. Ask your boutique for their typical lead times.",
        },
        {
          q: "What should I ask bridesmaids before choosing dresses?",
          a: "Ask about sizes, any fit needs like pregnancy or preferring sleeves, and what they can afford if they're paying. A quiz like this collects it all in one place.",
        },
        {
          q: "How does this quiz pick a result?",
          a: "The final question about how matched the party should look leads to one of three approaches. Anyone unsure is pointed to same colour, different styles.",
        },
      ],
    },
  }),
];
