import { defineTemplate, type TemplateSeed } from "../define.js";

export const SURVEY_MARKETING: TemplateSeed[] = [
  defineTemplate({
    slug: "brand-perception-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["marketing", "product-research"],
    searchName: "Brand perception survey",
    title: "Brand perception",
    icon: "Sparkles",
    metaDescription:
      "Find out what people really think of your brand: the words they pick, how far they trust you and how you compare. Non-buyers skip the questions they can't answer.",
    description: "Learn the words people attach to your brand, and the experiences behind them.",
    blurb:
      "Asks how well someone knows you before asking what they think, so the answers can be split by customers, lapsed customers and people who have only heard of you. Anyone who has never bought skips the experience grid and goes straight to how you compare, and anyone whose view has shifted is asked what shifted it.",
    tags: ["brand perception", "brand image", "brand research", "customer perception", "marketing survey"],
    greeting: "We're trying to see ourselves the way you see us. Five minutes, and honest answers help most.",
    questions: [
      {
        ref: "familiarity",
        type: "single_select",
        title: "How well do you know us?",
        required: true,
        options: [
          { label: "I buy from you regularly" },
          { label: "I've bought once or twice" },
          { label: "I used to buy, but stopped" },
          { label: "I've heard of you, never bought" },
        ],
      },
      {
        ref: "first_heard",
        type: "single_select",
        title: "Where did you first come across us?",
        required: false,
        allowOther: true,
        options: [
          { label: "A friend or colleague mentioned you" },
          { label: "Searching online" },
          { label: "Social media" },
          { label: "An article, podcast or video" },
          { label: "In a shop or at an event" },
          { label: "I honestly can't remember" },
        ],
      },
      {
        ref: "qualities",
        type: "multi_select",
        title: "Which words fit us best? Pick up to three.",
        required: true,
        maxSelections: 3,
        options: [
          { label: "Trustworthy" },
          { label: "Good value" },
          { label: "Premium" },
          { label: "Innovative" },
          { label: "Friendly" },
          { label: "Reliable" },
          { label: "Expensive" },
          { label: "Old-fashioned" },
          { label: "Forgettable" },
          { label: "Confusing" },
        ],
      },
      {
        ref: "trust",
        type: "opinion_scale",
        title: "How much do you trust us to do what we say we'll do?",
        required: true,
        steps: 5,
        labelLow: "Not at all",
        labelHigh: "Completely",
      },
      {
        ref: "experience",
        type: "matrix",
        title: "From your own experience, how do we do on each of these?",
        required: false,
        rows: ["Quality of what we sell", "Fair pricing", "Customer service", "Keeping promises on delivery"],
        columns: ["Poor", "Fair", "Good", "Excellent", "Not sure"],
      },
      {
        ref: "compare",
        type: "single_select",
        title: "Compared with the alternatives you know, where do we sit?",
        required: true,
        options: [
          { label: "Clearly better" },
          { label: "A little better" },
          { label: "About the same" },
          { label: "A little worse" },
          { label: "Clearly worse" },
          { label: "I don't know the alternatives" },
        ],
      },
      {
        ref: "view_changed",
        type: "yes_no",
        title: "Has your opinion of us changed since you first came across us?",
        required: true,
      },
      {
        ref: "what_changed",
        type: "long_text",
        title: "What changed it, and in which direction?",
        description: "A specific moment, like an order, an ad or a conversation, is the most useful thing you can tell us.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "recommend",
        type: "nps",
        title: "How likely are you to recommend us to a friend or colleague?",
        required: true,
      },
      {
        ref: "one_sentence",
        type: "long_text",
        title: "How would you describe us to someone who has never heard of us?",
        required: false,
        maxLength: 400,
      },
    ],
    branches: [
      { when: "familiarity", is: "I've heard of you, never bought", then: "compare" },
      { when: "view_changed", is: false, then: "recommend" },
    ],
    ending: {
      title: "Thank you for being straight with us",
      body: "Your answers go to the people who decide how we present ourselves, and they read every one.",
    },
    guide: {
      questionsToConsider: [
        "Who do you most need to hear from: loyal customers, people who stopped buying, or people who only know your name?",
        "Which words do you hope people pick, and which ones would worry you if they came up often?",
        "Which competitors should respondents have in mind when they compare, and should you name them?",
        "What decision will this feed, such as a rebrand, a new campaign or a change to your service?",
      ],
      howToUseResponses:
        "Split every result by the first question before reading anything else, because a regular customer and someone who has only seen your ads are describing different brands. Count how often each word is picked in each group and compare that with the words you want to own. Then read the answers about what changed people's minds, since those name the specific moments that are building or damaging your reputation.",
      customizeSteps: [
        "Replace the word list with the qualities your brand is aiming for plus a few honest negatives, so the survey can tell you when you miss.",
        "Rename the rows in the experience grid to the parts of your business people actually touch, such as delivery, the app or the store.",
        "Send it to customers and share it more widely by link, then compare the groups in the dashboard or export the answers to CSV.",
      ],
      faqs: [
        {
          q: "What is a brand perception survey?",
          a: "It asks people what they think and feel about your brand: the qualities they associate with it, how much they trust it and how it compares with alternatives. It measures opinion, not just whether people recognise your name.",
        },
        {
          q: "What questions should a brand perception survey include?",
          a: "Ask how familiar the person is with you, which words describe you, how far they trust you, how you compare with alternatives and what experience shaped their view. Without the familiarity question, the rest is hard to interpret.",
        },
        {
          q: "Should I survey people who have never bought from us?",
          a: "Yes, they show you the impression your marketing creates on its own. This template lets them skip the questions about service and delivery that they could only guess at.",
        },
        {
          q: "How often should I run a brand perception survey?",
          a: "Once or twice a year works for most brands, plus before and after a rebrand or a big campaign. Keep the core questions the same so you can compare results over time.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "brand-personality-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["marketing"],
    searchName: "Brand personality survey",
    title: "Brand personality",
    icon: "Palette",
    metaDescription:
      "Ask customers what kind of person your brand would be: its traits, its tone and where it sits between serious and playful. Compare that with the voice you intended.",
    description: "See whether the personality people feel matches the one you meant to build.",
    blurb:
      "Uses sliders between opposite traits, like serious and playful or traditional and modern, so you get positions you can compare with your brand guidelines rather than a pile of adjectives. Anyone who feels your words and your actions don't match is asked where the gap shows up.",
    tags: ["brand personality", "brand voice", "tone of voice", "brand archetype", "brand research"],
    greeting: "Quick one: if our brand were a person, what would they be like? No right answers here.",
    questions: [
      {
        ref: "relationship",
        type: "single_select",
        title: "How do you know us?",
        required: true,
        options: [
          { label: "I'm a customer" },
          { label: "I follow you online" },
          { label: "I've only seen your ads or posts" },
          { label: "I work with you as a partner" },
        ],
      },
      {
        ref: "traits",
        type: "multi_select",
        title: "Which of these traits sound most like us? Pick up to three.",
        required: true,
        maxSelections: 3,
        options: [
          { label: "Warm" },
          { label: "Clever" },
          { label: "Playful" },
          { label: "Calm" },
          { label: "Bold" },
          { label: "Practical" },
          { label: "Elegant" },
          { label: "Down to earth" },
          { label: "Rebellious" },
          { label: "Serious" },
          { label: "Pushy" },
          { label: "Distant" },
        ],
      },
      {
        ref: "serious_playful",
        type: "opinion_scale",
        title: "Where do we sit between serious and playful?",
        required: true,
        steps: 7,
        labelLow: "Serious",
        labelHigh: "Playful",
      },
      {
        ref: "traditional_modern",
        type: "opinion_scale",
        title: "And between traditional and modern?",
        required: true,
        steps: 7,
        labelLow: "Traditional",
        labelHigh: "Modern",
      },
      {
        ref: "quiet_bold",
        type: "opinion_scale",
        title: "And between understated and bold?",
        required: true,
        steps: 7,
        labelLow: "Understated",
        labelHigh: "Bold",
      },
      {
        ref: "voice",
        type: "single_select",
        title: "When we write to you, who does it sound like?",
        required: true,
        options: [
          { label: "A friend who knows their stuff" },
          { label: "A patient expert" },
          { label: "An enthusiastic salesperson" },
          { label: "A big, formal company" },
          { label: "It changes a lot" },
        ],
      },
      {
        ref: "as_a_person",
        type: "long_text",
        title: "Imagine we walked into a room as a person. How would they come across?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "words_match",
        type: "yes_no",
        title: "Does the way we talk match the way we actually treat you?",
        required: true,
      },
      {
        ref: "mismatch",
        type: "long_text",
        title: "Where does the gap show up?",
        description: "For example, a friendly website but a stiff support email.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "similar_brand",
        type: "short_text",
        title: "Which other brand, in any industry, feels most like us?",
        required: false,
        maxLength: 120,
      },
    ],
    branches: [{ when: "words_match", is: true, then: "similar_brand" }],
    ending: {
      title: "Thanks, that's a great help",
      body: "We'll put your answers next to the personality we set out to have and see how close we got.",
    },
    guide: {
      questionsToConsider: [
        "Which three traits does your brand guide say you should have, and are they in the list?",
        "Which trait pairs matter most for your market, such as serious and playful for a finance brand?",
        "Do you want customers only, or also people who have just seen your marketing?",
        "Who on your team owns the tone of voice and will act on what comes back?",
      ],
      howToUseResponses:
        "Before you read a single answer, mark on each slider where you intend the brand to sit. Then compare the average position with your mark, and look separately at customers and people who have only seen your ads, since a gap between those two groups usually points at the product experience rather than the marketing. The answers about where words and actions don't match are your to-do list: each one names a touchpoint that is off-voice.",
      customizeSteps: [
        "Swap the trait list for your own intended traits, and keep two or three unflattering ones so people can be honest.",
        "Change the slider pairs to the tensions that matter for your brand, such as affordable and premium.",
        "Send it by email or embed it on your site, then review the slider averages in the dashboard or export them to CSV.",
      ],
      faqs: [
        {
          q: "What is a brand personality survey?",
          a: "It asks people to describe your brand as if it were a person: its traits, its tone and how it behaves. It is about the brand's character, not the respondent's personality.",
        },
        {
          q: "How is brand personality different from brand perception?",
          a: "Perception covers what people think of you overall, including trust, value and quality. Personality focuses on character and voice, which is what your writing, design and service all express.",
        },
        {
          q: "Why use sliders instead of a list of adjectives?",
          a: "A slider between two opposites gives you a position you can compare over time and against your brand guidelines. Adjective lists are still useful, which is why this template asks for both.",
        },
        {
          q: "Can I add my own traits and scales?",
          a: "Yes. Use this template copies it into your account, where you can edit every question, add more sliders or change the trait list.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "business-impact-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["operations", "hr-people"],
    searchName: "Business impact survey",
    title: "Business impact",
    icon: "Gauge",
    metaDescription:
      "Measure how a change is affecting daily work: workload, speed, quality and customers. People hit hardest describe the disruption and name the support they need.",
    description: "See how a change is really landing, team by team, and what support would help.",
    blurb:
      "Built for the weeks after a reorganisation, a new system, a price change or an outside event. A grid rates the effect on workload, speed, quality, customers and costs, and the overall verdict decides the follow-up: people seeing gains describe them, people struggling describe the disruption, and everyone picks the support that would help.",
    tags: ["business impact survey", "change impact", "impact assessment", "change management", "operations survey"],
    greeting: "We want to understand how the recent change is affecting your work. It takes about four minutes.",
    questions: [
      {
        ref: "change",
        type: "short_text",
        title: "Which change are you telling us about?",
        description: "For example, the new ordering system or the move to a hybrid schedule.",
        required: true,
        maxLength: 150,
      },
      {
        ref: "team",
        type: "dropdown",
        title: "Which team or area do you work in?",
        required: true,
        options: [
          { label: "Sales" },
          { label: "Marketing" },
          { label: "Customer support" },
          { label: "Operations or logistics" },
          { label: "Finance" },
          { label: "Product or engineering" },
          { label: "HR or people" },
          { label: "Leadership" },
          { label: "Other" },
        ],
      },
      {
        ref: "working_level",
        type: "opinion_scale",
        title: "Right now, how close to normal is your team working?",
        required: true,
        steps: 10,
        labelLow: "Badly disrupted",
        labelHigh: "Fully normal",
      },
      {
        ref: "effects",
        type: "matrix",
        title: "How has the change affected each of these for you?",
        required: true,
        rows: ["My workload", "How fast things get done", "Quality of our work", "Our customers or clients", "Costs"],
        columns: ["Much worse", "Worse", "No change", "Better", "Much better"],
      },
      {
        ref: "overall",
        type: "single_select",
        title: "Taking everything together, how has it gone so far?",
        required: true,
        options: [
          { label: "Mostly positive" },
          { label: "Mixed" },
          { label: "Mostly negative" },
          { label: "Too early to say" },
        ],
      },
      {
        ref: "gains",
        type: "long_text",
        title: "What has got better? An example helps us keep it.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "disruption",
        type: "long_text",
        title: "What has been hardest? Tell us about a moment when it got in the way.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "revenue",
        type: "single_select",
        title: "What do you expect it to do to revenue or results in your area?",
        required: true,
        options: [
          { label: "Increase them" },
          { label: "No real effect" },
          { label: "Reduce them" },
          { label: "I don't know" },
        ],
      },
      {
        ref: "support",
        type: "multi_select",
        title: "What would help you most from here?",
        required: true,
        options: [
          { label: "Clearer information about what's changing" },
          { label: "Training" },
          { label: "More people or time" },
          { label: "Better tools" },
          { label: "A chance to raise concerns with leadership" },
          { label: "Nothing, we're fine" },
        ],
      },
      {
        ref: "anything_else",
        type: "long_text",
        title: "Anything else leadership should know?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "overall", is: "Mostly positive", then: "gains" },
      { when: "gains", always: true, then: "revenue" },
      { when: "overall", is: "Mixed", then: "disruption" },
      { when: "overall", is: "Mostly negative", then: "disruption" },
      { when: "overall", is: "Too early to say", then: "revenue" },
    ],
    ending: {
      title: "Thanks, this helps us plan the next step",
      body: "We'll share what we heard, and what we're doing about it, with everyone who took part.",
    },
    guide: {
      questionsToConsider: [
        "Is this survey for your own staff, for customers affected by the change, or both?",
        "Which effects can you actually respond to, and which should you leave out of the grid?",
        "Should answers be anonymous so people feel safe describing problems?",
        "Will you run it again later to see whether things have settled?",
      ],
      howToUseResponses:
        "Sort the answers by team first, because a change that suits sales can swamp support. Look for rows in the grid where one team is mostly Worse or Much worse, and read that team's written answers about what has been hardest. Pick the most requested kind of support and act on it quickly, then run the same survey again after a month or two so you can see whether the working level has recovered.",
      customizeSteps: [
        "Write the change into the first question, or remove it and name the change in the greeting if the survey covers only one.",
        "Edit the team list and the grid rows so they match your organisation and the parts of work the change touches.",
        "Share the link with the affected teams, and compare results by team in the dashboard or export them to CSV.",
      ],
      faqs: [
        {
          q: "What is a business impact survey?",
          a: "It asks the people affected by a change how it is changing their work: workload, speed, quality, customers and costs. It shows where the change is working and where people need help.",
        },
        {
          q: "When should I send a business impact survey?",
          a: "A few weeks after the change, once people have lived with it but while the details are fresh. You can also send it before a planned change to collect expected effects, then again afterwards to compare.",
        },
        {
          q: "Should a business impact survey be anonymous?",
          a: "Usually yes, when it goes to staff. People are more candid about disruption when their name is not attached, and the team question still lets you see where problems cluster.",
        },
        {
          q: "Can I use it with customers instead of employees?",
          a: "Yes. Change the team question to ask about the customer's role or account, and reword the grid rows around what they experience, such as ordering or support.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "churn-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["customer-success", "product-research", "marketing"],
    searchName: "Churn survey",
    title: "Churn survey",
    icon: "LogOut",
    metaDescription:
      "Find out why customers stopped using your product, whether they cancelled or drifted away. Each reason gets its own follow-up, then ask what would win them back.",
    description: "Learn why customers left or went quiet, and when the product stopped being worth it.",
    blurb:
      "Works for people who cancelled and for people who simply stopped using you, and asks when the product stopped feeling worth it so you can see where value falls away. Every reason gets its own follow-up: a cheaper option, the missing feature, the competitor and why, what got in the way, what changed in their needs or what kept it out of their routine. Only people open to coming back are asked what it would take and for an email.",
    tags: ["churn survey", "customer churn", "why customers leave", "lost customer feedback", "customer retention"],
    greeting: "We noticed you've stepped away, and we'd like to understand why. It takes two minutes and shapes what we fix next.",
    questions: [
      {
        ref: "status",
        type: "single_select",
        title: "Which of these fits you best?",
        required: true,
        options: [
          { label: "I cancelled my account" },
          { label: "I still have an account but stopped using it" },
          { label: "I'm about to cancel" },
        ],
      },
      {
        ref: "used_for",
        type: "short_text",
        title: "What did you mainly use us for?",
        required: false,
        maxLength: 200,
      },
      {
        ref: "tenure",
        type: "single_select",
        title: "How long were you with us?",
        required: true,
        options: [
          { label: "Less than a month" },
          { label: "1–6 months" },
          { label: "6–12 months" },
          { label: "More than a year" },
        ],
      },
      {
        ref: "reason",
        type: "single_select",
        title: "What's the main reason you're leaving?",
        required: true,
        options: [
          { label: "It cost too much for what I got" },
          { label: "It was missing something I needed" },
          { label: "I switched to another product" },
          { label: "It was hard to use" },
          { label: "Too many bugs or problems" },
          { label: "I wasn't using it enough" },
          { label: "My needs changed" },
          { label: "Something else" },
        ],
      },
      {
        ref: "cheaper_plan",
        type: "yes_no",
        title: "Would a cheaper option with fewer features have kept you?",
        required: true,
      },
      {
        ref: "missing",
        type: "long_text",
        title: "What was missing? Tell us what you were trying to do.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "competitor",
        type: "short_text",
        title: "Which product did you move to?",
        required: false,
        maxLength: 120,
      },
      {
        ref: "competitor_why",
        type: "long_text",
        title: "What does it do better for you?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "friction",
        type: "long_text",
        title: "Tell us a bit more about what happened. A specific moment helps most.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "needs_changed",
        type: "long_text",
        title: "What changed for you?",
        description: "For example, a new job, a finished project or a smaller team.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "low_use",
        type: "long_text",
        title: "What got in the way of using it more often?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "when_value_dropped",
        type: "single_select",
        title: "When did it stop feeling worth it?",
        required: true,
        options: [
          { label: "Right from the start" },
          { label: "After the first few weeks" },
          { label: "After months of use" },
          { label: "Only recently" },
          { label: "It still felt worth it, my situation changed" },
        ],
      },
      {
        ref: "overall",
        type: "rating",
        title: "Overall, how would you rate your time with us?",
        required: true,
        scale: 5,
      },
      {
        ref: "come_back",
        type: "yes_no",
        title: "Is there anything that would bring you back?",
        required: true,
      },
      {
        ref: "bring_back",
        type: "long_text",
        title: "What would it take?",
        required: true,
        maxLength: 600,
      },
      {
        ref: "email",
        type: "email",
        title: "If we fix it, can we let you know? Leave your email, or skip this.",
        required: false,
      },
    ],
    branches: [
      { when: "reason", is: "It cost too much for what I got", then: "cheaper_plan" },
      { when: "cheaper_plan", always: true, then: "when_value_dropped" },
      { when: "reason", is: "It was missing something I needed", then: "missing" },
      { when: "missing", always: true, then: "when_value_dropped" },
      { when: "reason", is: "I switched to another product", then: "competitor" },
      { when: "competitor_why", always: true, then: "when_value_dropped" },
      { when: "reason", is: "It was hard to use", then: "friction" },
      { when: "reason", is: "Too many bugs or problems", then: "friction" },
      { when: "reason", is: "Something else", then: "friction" },
      { when: "friction", always: true, then: "when_value_dropped" },
      { when: "reason", is: "My needs changed", then: "needs_changed" },
      { when: "needs_changed", always: true, then: "when_value_dropped" },
      { when: "reason", is: "I wasn't using it enough", then: "low_use" },
      { when: "come_back", is: false, then: "end_thanks" },
    ],
    ending: {
      title: "Thank you, and good luck",
      body: "Your answer goes straight to the team deciding what we build and fix next. The door is always open.",
    },
    guide: {
      questionsToConsider: [
        "How long without a login or an order counts as churned for you, and when will this go out after that point?",
        "Which reasons can you act on, and are they all in the list?",
        "Who reads the answers from people who named a competitor, and what will they do with them?",
        "Will someone actually email people who said they'd come back, and when?",
      ],
      howToUseResponses:
        "Split the answers by the first question, because people who cancelled and people who quietly stopped often leave for different reasons. Count the main reasons each month and watch how the mix moves, because a rise in one reason after a price or product change tells you more than the total. Read the written follow-ups for your top reason in full, and group the missing features and competitor answers into themes. Put the people who left an email into a short list, and when you fix what they asked for, tell them.",
      customizeSteps: [
        "Edit the reason list to match why your customers really leave, and keep the follow-up for each one that stays.",
        "Send the link to customers who cancelled and to accounts that have gone quiet for the period you chose, in the same email.",
        "Read the answers weekly in the dashboard, or export them to CSV and tag each response by theme.",
      ],
      faqs: [
        {
          q: "What questions should a churn survey ask?",
          a: "Ask for the main reason first, then one follow-up specific to that reason, when the product stopped feeling worth it, and whether anything would bring them back. Keep it short, because people who are leaving owe you nothing.",
        },
        {
          q: "When is the best time to send a churn survey?",
          a: "At the moment of cancelling or within a day of it, while the reason is still clear. For customers who drift away without cancelling, send it after a set period of inactivity.",
        },
        {
          q: "What is the difference between a churn survey and a cancellation survey?",
          a: "A cancellation survey is shown during the act of cancelling. A churn survey can also reach people who stopped using the product without formally leaving.",
        },
        {
          q: "How do I get more people to answer a churn survey?",
          a: "Keep it to a couple of minutes, say plainly that the answers shape what gets fixed, and ask only the follow-ups that fit their reason. A conversational format helps because it feels like a quick exchange rather than a form.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "client-questionnaire",
    type: "survey",
    category: "marketing",
    goals: ["onboard-clients", "generate-leads"],
    roles: ["freelancers-agencies", "sales"],
    searchName: "Client questionnaire",
    title: "Client questionnaire",
    icon: "Briefcase",
    metaDescription:
      "Learn a new client's goals, challenges, budget and deadline before your first call. Ask who you'll work with day to day, and what success would look like to them.",
    description: "Understand a client's goals and context before you recommend anything.",
    blurb:
      "Covers what you need before a discovery call: who you'll work with, what the business does, what success looks like, what's in the way and what has been tried. If the person filling it in isn't the day-to-day contact, it asks who is, and a budget amount is only requested from clients who already have one in mind.",
    tags: ["client questionnaire", "new client questionnaire", "discovery questionnaire", "agency onboarding", "freelance clients"],
    greeting: "Looking forward to working together. A few questions first, so our first call can get straight to the useful part.",
    questions: [
      {
        ref: "contact",
        type: "contact_info",
        title: "Let's start with you. Who are we talking to?",
        required: true,
        fields: ["first_name", "last_name", "email", "phone"],
      },
      {
        ref: "company",
        type: "short_text",
        title: "What's the name of your business?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "primary_contact",
        type: "yes_no",
        title: "Will you be our main contact day to day?",
        required: true,
      },
      {
        ref: "day_to_day",
        type: "short_text",
        title: "Who should we work with, and how do we reach them?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "business",
        type: "long_text",
        title: "In a few sentences, what does your business do, and who are your customers?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "services",
        type: "multi_select",
        title: "Which kinds of help are you looking for?",
        required: true,
        allowOther: true,
        options: [
          { label: "Strategy and planning" },
          { label: "Brand and design" },
          { label: "Website" },
          { label: "Content and copywriting" },
          { label: "Social media" },
          { label: "Paid advertising" },
          { label: "Not sure yet" },
        ],
      },
      {
        ref: "success",
        type: "long_text",
        title: "Six months from now, what would make this a success for you?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "challenge",
        type: "long_text",
        title: "What's getting in the way at the moment?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "tried",
        type: "long_text",
        title: "What have you already tried, and how did it go?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "budget_status",
        type: "single_select",
        title: "Where are you with budget?",
        required: true,
        options: [
          { label: "We have a set budget" },
          { label: "We have a rough range" },
          { label: "We'd like your advice on it" },
        ],
      },
      {
        ref: "budget_amount",
        type: "number",
        title: "Roughly how much, in your currency?",
        required: false,
        min: 0,
      },
      {
        ref: "deadline",
        type: "date",
        title: "Is there a date this needs to be ready by?",
        description: "Skip this if there's no fixed deadline.",
        required: false,
        disablePast: true,
      },
      {
        ref: "decision",
        type: "single_select",
        title: "Who else is involved in decisions on this?",
        required: true,
        options: [
          { label: "Just me" },
          { label: "Me and a business partner" },
          { label: "A small team" },
          { label: "A board or senior leadership" },
        ],
      },
      {
        ref: "anything_else",
        type: "long_text",
        title: "Anything else we should know before we talk?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "primary_contact", is: true, then: "business" },
      { when: "budget_status", is: "We'd like your advice on it", then: "deadline" },
    ],
    ending: {
      title: "Thanks, we've got everything we need",
      body: "We'll read through this before we speak and come to the call with ideas, not a list of questions.",
    },
    guide: {
      questionsToConsider: [
        "Which services do you actually offer, and should the list stop at those?",
        "Do you need a budget figure before a call, or is knowing whether one exists enough?",
        "Should this go to every enquiry, or only to clients who have agreed to work with you?",
        "What do you usually wish you had known before a first meeting?",
      ],
      howToUseResponses:
        "Read the success and challenge answers side by side before the call and write down the one outcome the client cares about most. Use the tried-before answer to avoid pitching something that already failed for them. The decision question tells you who else needs to be in the room, so invite them early, and if the deadline is close, raise it in the first five minutes rather than the last.",
      customizeSteps: [
        "Replace the services list with what you offer, and delete any question you never use in a first call.",
        "Send the link in your reply to a new enquiry or embed it on your contact page so clients fill it in before booking.",
        "Open each response in the dashboard before the call, or export them to CSV to keep a record for every client.",
      ],
      faqs: [
        {
          q: "What should a client questionnaire include?",
          a: "Contact details, what the business does, the goal, the main obstacle, what has been tried, budget, deadline and who makes decisions. Those answers let you arrive at a first call already understanding the problem.",
        },
        {
          q: "What is the difference between a client questionnaire and a client intake form?",
          a: "An intake form collects the practical details needed to open a project. A questionnaire goes further into goals and context, so you can decide what to recommend.",
        },
        {
          q: "Should I ask clients about budget up front?",
          a: "It helps to know whether a budget exists. This template asks that first and only asks for an amount from clients who have one, so nobody is pushed to name a number they haven't worked out.",
        },
        {
          q: "When should I send a client questionnaire?",
          a: "Right after a new enquiry, or once a client has agreed to work with you but before the kickoff call. Sharing it as a link or embedding it on your contact page means answers arrive before you speak.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "conference-evaluation-survey",
    type: "survey",
    category: "marketing",
    goals: ["run-events", "collect-feedback"],
    roles: ["marketing", "operations"],
    searchName: "Conference evaluation survey",
    title: "Conference evaluation",
    icon: "Mic",
    metaDescription:
      "Rate your conference: sessions, networking, venue and value. Happy attendees name their highlight, unhappy ones say what went wrong, and everyone suggests topics.",
    description: "Hear what attendees valued and what to change before next year's conference.",
    blurb:
      "Asks for the overall verdict first, then follows it: attendees who loved it name their highlight, and those who didn't say what let them down. A grid rates keynotes, breakouts, networking, venue, food and scheduling, so you can separate a strong programme from a weak venue. It also asks what attendees will use at work and how many useful contacts they made, the two things most people go to a conference for, and closes with topics for next year.",
    tags: ["conference evaluation", "conference feedback survey", "post-event survey", "attendee feedback", "event evaluation"],
    greeting: "Thanks for coming to the conference. Tell us how it went for you, and help shape the next one.",
    questions: [
      {
        ref: "attended_as",
        type: "single_select",
        title: "How did you take part?",
        required: true,
        options: [
          { label: "Attendee" },
          { label: "Speaker" },
          { label: "Sponsor or exhibitor" },
          { label: "Volunteer" },
        ],
      },
      {
        ref: "overall",
        type: "rating",
        title: "Overall, how would you rate the conference?",
        required: true,
        scale: 5,
      },
      {
        ref: "highlight",
        type: "long_text",
        title: "What was the highlight for you?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "let_down",
        type: "long_text",
        title: "What let you down? Be as specific as you like.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "aspects",
        type: "matrix",
        title: "How did each part of the conference work for you?",
        required: true,
        rows: ["Keynotes", "Breakout sessions", "Networking", "Venue and facilities", "Food and drink", "Schedule and timing"],
        columns: ["Poor", "Fair", "Good", "Excellent", "Didn't use"],
      },
      {
        ref: "best_session",
        type: "short_text",
        title: "Which talk or speaker will you remember a month from now?",
        required: false,
        maxLength: 150,
      },
      {
        ref: "takeaway",
        type: "long_text",
        title: "What's one idea from the conference you'll put to use in your work?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "contacts",
        type: "number",
        title: "Roughly how many useful new contacts did you make?",
        required: false,
        min: 0,
      },
      {
        ref: "content_level",
        type: "single_select",
        title: "Was the content pitched at the right level for you?",
        required: true,
        options: [
          { label: "Too basic" },
          { label: "About right" },
          { label: "Too advanced" },
          { label: "It varied a lot between sessions" },
        ],
      },
      {
        ref: "worth_it",
        type: "opinion_scale",
        title: "Did what you took away justify the ticket and the time away from work?",
        required: true,
        steps: 5,
        labelLow: "Not at all",
        labelHigh: "Easily",
      },
      {
        ref: "recommend",
        type: "nps",
        title: "How likely are you to recommend this conference to a colleague?",
        required: true,
      },
      {
        ref: "return",
        type: "single_select",
        title: "Would you come back next year?",
        required: true,
        options: [{ label: "Yes" }, { label: "Maybe" }, { label: "No" }],
      },
      {
        ref: "next_topics",
        type: "long_text",
        title: "Which topics or speakers would you like to see next time?",
        required: false,
        maxLength: 600,
      },
    ],
    branches: [
      { when: "overall", op: "gte", is: 4, then: "highlight" },
      { when: "highlight", always: true, then: "aspects" },
      { when: "overall", op: "lte", is: 3, then: "let_down" },
    ],
    ending: {
      title: "Thank you, see you next time 👋",
      body: "The organising team reads every response while planning the next conference.",
    },
    guide: {
      questionsToConsider: [
        "Which parts of the event did you control, and which belonged to the venue or a partner?",
        "Do speakers and sponsors need their own questions, or is the shared version enough?",
        "Should the best-session question list your actual sessions so answers are easy to count?",
        "How soon after the closing session can you send this?",
      ],
      howToUseResponses:
        "Split the results by how people took part, because sponsors and attendees judge the same event by different things. Read the grid row by row to find the weakest part of the day, then read the let-down answers from people who rated it three or lower for the reasons behind it. Tally the best-session answers to decide who to invite back, and quote the takeaway answers when you pitch next year's event to attendees and their managers. Put the topic requests straight into next year's call for speakers.",
      customizeSteps: [
        "Rename the grid rows to match your programme, such as workshops, the expo hall or the evening reception.",
        "Send the link in your thank-you email within a day of the event, and add it to the event app or final slide.",
        "Compare scores by participant type in the dashboard, or export them to CSV to share with speakers and sponsors.",
      ],
      faqs: [
        {
          q: "What questions should a conference evaluation survey include?",
          a: "An overall rating, ratings for sessions, networking, venue and scheduling, the most useful session, whether it was worth the cost and topics for next time. Add one open question about what went wrong so problems are not hidden behind averages.",
        },
        {
          q: "When should I send a conference evaluation survey?",
          a: "Within a day of the event ending, while details are fresh. For a multi-day conference, you can also ask a short question at the end of each day.",
        },
        {
          q: "How do I get more attendees to fill it in?",
          a: "Keep it to a few minutes, send it quickly and mention it from the stage. A conversational survey that asks one question at a time also feels lighter on a phone.",
        },
        {
          q: "Can speakers and sponsors use the same survey?",
          a: "Yes. The first question records how each person took part, so you can filter their answers separately in the dashboard.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "consumer-behavior-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["product-research", "marketing"],
    searchName: "Consumer behavior survey",
    title: "Consumer behavior",
    icon: "ShoppingBag",
    metaDescription:
      "Study how people really shop by walking through a recent purchase: what set it off, where they looked, what decided it and how they feel about it now.",
    description: "Understand real buying decisions by asking about one recent purchase.",
    blurb:
      "Anchored on one real, recent purchase instead of general shopping habits, so answers describe what people did rather than what they think they do. It follows the purchase from trigger to research to the deciding factor, skips the comparison question for people who didn't shop around, and asks less happy buyers what they would do differently.",
    tags: ["consumer behavior survey", "buying behavior", "purchase decision", "shopper research", "market research"],
    greeting: "We're studying how people make buying decisions. Think of one recent purchase and we'll walk through it together.",
    questions: [
      {
        ref: "item",
        type: "short_text",
        title: "Think of the last thing you bought that took some thought, not an everyday top-up. What was it?",
        required: true,
        maxLength: 150,
      },
      {
        ref: "when",
        type: "single_select",
        title: "When did you buy it?",
        required: true,
        options: [
          { label: "In the last week" },
          { label: "In the last month" },
          { label: "1–3 months ago" },
          { label: "Longer ago" },
        ],
      },
      {
        ref: "trigger",
        type: "single_select",
        title: "What made you start looking?",
        required: true,
        allowOther: true,
        options: [
          { label: "Something broke or ran out" },
          { label: "A new need or a change in my life" },
          { label: "An ad or a post I saw" },
          { label: "Someone recommended it" },
          { label: "A sale or discount" },
          { label: "I just wanted to treat myself" },
        ],
      },
      {
        ref: "research",
        type: "multi_select",
        title: "Where did you look before deciding?",
        required: true,
        options: [
          { label: "Search engines" },
          { label: "Review sites or ratings" },
          { label: "Social media or videos" },
          { label: "Friends or family" },
          { label: "The brand's own website" },
          { label: "In a shop" },
          { label: "I didn't look around" },
        ],
      },
      {
        ref: "options_compared",
        type: "single_select",
        title: "How many options did you seriously consider?",
        required: true,
        options: [{ label: "Just the one I bought" }, { label: "2 or 3" }, { label: "4 or more" }],
      },
      {
        ref: "deciding_factors",
        type: "ranking",
        title: "Put these in order of how much they decided it for you.",
        required: true,
        items: ["Price", "Quality", "A brand I trust", "Reviews", "Delivery or availability", "A recommendation"],
      },
      {
        ref: "where_bought",
        type: "single_select",
        title: "Where did you buy it in the end?",
        required: true,
        options: [
          { label: "A large online marketplace" },
          { label: "The brand's own website" },
          { label: "A physical shop" },
          { label: "Through an app" },
          { label: "Somewhere else" },
        ],
      },
      {
        ref: "happy_now",
        type: "rating",
        title: "How happy are you with the purchase now?",
        required: true,
        scale: 5,
      },
      {
        ref: "do_differently",
        type: "long_text",
        title: "What would you do differently if you bought it again?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "buy_again",
        type: "yes_no",
        title: "Would you buy from the same place again?",
        required: true,
      },
      {
        ref: "age_range",
        type: "single_select",
        title: "Last one: which age group are you in?",
        required: false,
        options: [
          { label: "Under 25" },
          { label: "25–34" },
          { label: "35–44" },
          { label: "45–54" },
          { label: "55 or over" },
          { label: "Prefer not to say" },
        ],
      },
    ],
    branches: [
      { when: "research", op: "includes", is: "I didn't look around", then: "deciding_factors" },
      { when: "happy_now", op: "gte", is: 4, then: "buy_again" },
    ],
    ending: {
      title: "That's everything, thank you",
      body: "Your purchase story joins everyone else's and helps us see how real decisions get made.",
    },
    guide: {
      questionsToConsider: [
        "Should the survey focus on one product category, such as furniture or skincare, instead of any considered purchase?",
        "Which research channels matter to your marketing plan, and are they all in the list?",
        "Which deciding factors do you suspect matter most, and are you ready to be wrong?",
        "Which background details, like age or location, will you actually use to compare groups?",
      ],
      howToUseResponses:
        "Group the answers by trigger first, since people replacing something that broke shop very differently from people who were inspired by an ad. Within each group, look at which research channels were used and how the deciding factors were ranked. The answers about what people would do differently are often the best source of messaging, because they describe the doubt your marketing needs to answer.",
      customizeSteps: [
        "Narrow the first question to your category if you only care about one, for example the last piece of furniture someone bought.",
        "Edit the research channels and deciding factors to match the ways people shop in your market.",
        "Share the link with a panel or your audience, then filter by trigger in the dashboard or export to CSV for deeper analysis.",
      ],
      faqs: [
        {
          q: "What is a consumer behavior survey?",
          a: "It asks people how they actually find, compare, choose and buy products. The aim is to understand the steps and influences behind a purchase, not just what people say they prefer.",
        },
        {
          q: "Why ask about one recent purchase instead of shopping in general?",
          a: "A specific, recent purchase is easier to remember accurately. It gives you concrete steps and influences that broad questions about habits tend to blur.",
        },
        {
          q: "What questions should a consumer behavior survey ask?",
          a: "Ask what triggered the purchase, where the person researched, how many options they compared, what decided it, where they bought and how they feel about it now.",
        },
        {
          q: "Can I change it to focus on my product category?",
          a: "Yes. Edit the first question to name your category and adjust the channel and factor lists to fit. Every question can be edited after you copy the template.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "consumer-preference-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["product-research", "marketing"],
    searchName: "Consumer preference survey",
    title: "Consumer preferences",
    icon: "ListOrdered",
    metaDescription:
      "Learn what your audience values in a product and which trade-offs they'll accept. Rank features, find deal-breakers and see what would make people switch brands.",
    description: "Find out which features matter, which trade-offs people accept, and what makes them switch.",
    blurb:
      "Goes past 'what do you like' to the choices that shape a product: a ranking of priorities, a grid that separates nice-to-haves from deal-breakers, and direct trade-off questions on price and sustainability. People who wouldn't switch from their current brand are asked what keeps them loyal, and everyone else describes the product they'd switch for.",
    tags: ["consumer preference survey", "customer preferences", "product preferences", "feature priorities", "market research"],
    greeting: "We're designing something new and want it to fit how you actually choose. A few quick questions.",
    questions: [
      {
        ref: "frequency",
        type: "single_select",
        title: "How often do you buy or use this kind of product?",
        required: true,
        options: [
          { label: "Every week" },
          { label: "Every month or so" },
          { label: "A few times a year" },
          { label: "Rarely" },
        ],
      },
      {
        ref: "current_choice",
        type: "short_text",
        title: "Which brand or product do you use most at the moment?",
        required: false,
        maxLength: 120,
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "Rank these from most to least important when you choose.",
        required: true,
        items: ["Price", "Quality and durability", "Convenience", "Design", "Environmental impact", "Brand reputation"],
      },
      {
        ref: "importance",
        type: "matrix",
        title: "How much does each of these matter to you?",
        required: true,
        rows: ["A low price", "Lasting a long time", "Recyclable packaging", "Fast delivery", "A well-known brand", "Helpful customer service"],
        columns: ["Doesn't matter", "Nice to have", "Important", "Deal-breaker"],
      },
      {
        ref: "tradeoff",
        type: "single_select",
        title: "If you had to choose, which would you buy?",
        required: true,
        options: [
          { label: "A cheaper version that does the basics" },
          { label: "A pricier version that does more" },
          { label: "It depends on what it's for" },
        ],
      },
      {
        ref: "green_premium",
        type: "opinion_scale",
        title: "How willing are you to pay a little more for a version that's better for the environment?",
        required: true,
        steps: 5,
        labelLow: "Not willing",
        labelHigh: "Very willing",
      },
      {
        ref: "switch",
        type: "single_select",
        title: "What would make you switch from what you use now?",
        required: true,
        options: [
          { label: "A lower price" },
          { label: "Better quality" },
          { label: "Something more convenient" },
          { label: "A brand with values I share" },
          { label: "Nothing, I'm happy with what I use" },
        ],
      },
      {
        ref: "ideal",
        type: "long_text",
        title: "Describe the product you'd switch for. What would it do that yours doesn't?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "loyalty",
        type: "long_text",
        title: "What keeps you with your current choice?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "turn_off",
        type: "long_text",
        title: "Is there anything that would put you off a product like this straight away?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "age_range",
        type: "single_select",
        title: "Which age group are you in?",
        required: false,
        options: [
          { label: "Under 25" },
          { label: "25–34" },
          { label: "35–44" },
          { label: "45–54" },
          { label: "55 or over" },
          { label: "Prefer not to say" },
        ],
      },
    ],
    branches: [
      { when: "switch", is: "Nothing, I'm happy with what I use", then: "loyalty" },
      { when: "ideal", always: true, then: "turn_off" },
    ],
    ending: {
      title: "Thank you, that's really useful",
      body: "Your priorities go straight into how we shape the product.",
    },
    guide: {
      questionsToConsider: [
        "Which product or category is this about, and should the first question name it?",
        "Which features are you genuinely undecided about, and are they in the ranking?",
        "Which trade-off keeps coming up in your team's debates, such as price against durability?",
        "Do you need answers from current buyers only, or from people who use a competitor?",
      ],
      howToUseResponses:
        "Look at the ranking and the deal-breaker grid together: a feature ranked low but marked as a deal-breaker by a group of people is one you can't drop. Compare the trade-off answers by how often people buy, since frequent buyers often weigh price and quality differently. Read the switch-for answers as a brief for your product, and the loyalty answers as the bar you have to clear to win someone over.",
      customizeSteps: [
        "Name your product category in the greeting and the first question, and replace the ranking items with the features you're choosing between.",
        "Change the trade-off question to the real decision on your table, such as size against price.",
        "Share the link with your audience or a research panel, then compare groups in the dashboard or export the answers to CSV.",
      ],
      faqs: [
        {
          q: "What is a consumer preference survey?",
          a: "It asks your audience which features, qualities and trade-offs matter to them when they choose a product. It helps you decide what to build, what to emphasise and what to leave out.",
        },
        {
          q: "What is the difference between consumer preferences and consumer behavior?",
          a: "Preferences are what people say they want. Behavior is what they actually do. Stated preferences are a good guide, but test big decisions against real purchases where you can.",
        },
        {
          q: "Why use a ranking question in a preference survey?",
          a: "Rating scales let people mark everything as important. A ranking forces a choice, which shows you what matters most when something has to give.",
        },
        {
          q: "How many questions should a consumer preference survey have?",
          a: "About ten is plenty. This template stays short by asking people who wouldn't switch brands about loyalty instead of the product they'd switch for.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "corporate-social-responsibility-csr-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["hr-people", "marketing", "operations"],
    searchName: "Corporate social responsibility survey",
    title: "CSR survey",
    icon: "Leaf",
    metaDescription:
      "Ask employees, customers and partners which social and environmental issues matter, what they know of your efforts and whether they believe them. Plan CSR with it.",
    description: "Learn which causes matter to your people and whether your current efforts feel real.",
    blurb:
      "Separates three things that usually get mixed up: how much people care, how much they know about what you already do, and whether they believe it. People who know nothing about your work skip the credibility question, and people who find your efforts unconvincing are asked what would change their mind.",
    tags: ["CSR survey", "corporate social responsibility", "sustainability survey", "ESG survey", "employee engagement"],
    greeting: "We're deciding where to focus our social and environmental work, and we'd like your view. About four minutes.",
    questions: [
      {
        ref: "relationship",
        type: "single_select",
        title: "What's your connection to us?",
        required: true,
        options: [
          { label: "I work here" },
          { label: "I'm a customer" },
          { label: "I'm a supplier or partner" },
          { label: "I live or work nearby" },
          { label: "Something else" },
        ],
      },
      {
        ref: "importance",
        type: "opinion_scale",
        title: "How much does it matter to you that we act responsibly toward people and the planet?",
        required: true,
        steps: 5,
        labelLow: "Not at all",
        labelHigh: "A great deal",
      },
      {
        ref: "awareness",
        type: "single_select",
        title: "How much do you know about what we currently do in this area?",
        required: true,
        options: [
          { label: "Nothing at all" },
          { label: "A little" },
          { label: "A fair amount" },
          { label: "A lot" },
        ],
      },
      {
        ref: "credibility",
        type: "opinion_scale",
        title: "How genuine do our current efforts seem to you?",
        required: true,
        steps: 5,
        labelLow: "Mostly talk",
        labelHigh: "Real and visible",
      },
      {
        ref: "make_it_real",
        type: "long_text",
        title: "What would make our efforts feel more real to you?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "Which issues should we focus on? Put them in order.",
        required: true,
        items: [
          "Reducing our environmental impact",
          "Fair pay and treatment of workers",
          "Diversity and inclusion",
          "Supporting local communities",
          "Ethical sourcing",
          "Protecting customer data",
        ],
      },
      {
        ref: "one_thing",
        type: "long_text",
        title: "If we could do one thing better next year, what should it be?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "influence",
        type: "single_select",
        title: "Does a company's record on these issues affect whether you buy from or work with them?",
        required: true,
        options: [{ label: "Yes, a lot" }, { label: "Somewhat" }, { label: "Not really" }],
      },
      {
        ref: "take_part",
        type: "multi_select",
        title: "Would you like to take part in any of these?",
        required: false,
        options: [
          { label: "Volunteering days" },
          { label: "Fundraising" },
          { label: "Sharing ideas in a working group" },
          { label: "Not right now" },
        ],
      },
      {
        ref: "updates",
        type: "single_select",
        title: "How would you like to hear about our progress?",
        required: false,
        options: [
          { label: "A short yearly report" },
          { label: "Occasional email updates" },
          { label: "Posts on our website or social pages" },
          { label: "I'd rather not hear about it" },
        ],
      },
    ],
    branches: [
      { when: "awareness", is: "Nothing at all", then: "priorities" },
      { when: "credibility", op: "gte", is: 4, then: "priorities" },
    ],
    ending: {
      title: "Thank you for helping us choose",
      body: "We'll publish what we heard and the priorities we set because of it.",
    },
    guide: {
      questionsToConsider: [
        "Which groups do you most need to hear from: staff, customers, suppliers or neighbours?",
        "Which issues can your organisation realistically act on, and should the list stop there?",
        "Are you ready to publish the results, including the unflattering ones?",
        "Who owns CSR decisions, and when will they review the answers?",
      ],
      howToUseResponses:
        "Separate awareness from credibility before you plan anything. If most people know nothing about your work, the problem is communication; if they know and don't believe it, the problem is the work itself, and the answers about what would make it feel real tell you where to start. Compare the priority rankings of staff and customers, and choose focus areas where both groups agree and you can act.",
      customizeSteps: [
        "Edit the priority list to the issues relevant to your industry, and add any commitments you've already made public.",
        "Send the link to staff, customers and partners separately if you want to compare the groups cleanly.",
        "Review the ranking and credibility scores in the dashboard, or export them to CSV for your CSR report.",
      ],
      faqs: [
        {
          q: "What is a CSR survey?",
          a: "A corporate social responsibility survey asks employees, customers or partners which social and environmental issues matter to them and how they see your current efforts. It helps you choose priorities that people care about.",
        },
        {
          q: "Who should answer a CSR survey?",
          a: "Anyone affected by your work: staff, customers, suppliers and the local community. Record which group each person belongs to so you can compare them rather than blending everyone together.",
        },
        {
          q: "What questions should a CSR survey include?",
          a: "Ask how important the topic is to the person, what they know of your current work, how credible it seems, which issues to prioritise and how they'd like to hear about progress.",
        },
        {
          q: "Should a CSR survey be anonymous?",
          a: "For employees, usually yes, so people can say honestly when efforts feel like talk. For customers and partners it matters less, but avoid asking for contact details you won't use.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "customer-analysis-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["marketing", "sales", "product-research"],
    searchName: "Customer analysis survey",
    title: "Customer analysis",
    icon: "PieChart",
    metaDescription:
      "Learn who your customers are and why they buy: their situation, the problem they had, the options they weighed and why they chose you. For B2B and consumer buyers.",
    description: "Understand who buys from you, what problem they had and why they chose you.",
    blurb:
      "Starts by asking whether the customer bought for themselves or for a business, then asks the background questions that fit: company size and role for business buyers, age range for everyone else. After that everyone describes the problem they had, the alternatives they weighed and the real reason they chose you.",
    tags: ["customer analysis survey", "customer profile", "customer research", "buyer persona", "why customers buy"],
    greeting: "Thanks for being a customer. We'd love to understand you a little better. It takes about four minutes.",
    questions: [
      {
        ref: "buyer_type",
        type: "single_select",
        title: "Did you buy from us for yourself or for work?",
        required: true,
        options: [{ label: "For myself or my household" }, { label: "For my business or employer" }],
      },
      {
        ref: "company_size",
        type: "single_select",
        title: "How many people work at your organisation?",
        required: true,
        options: [
          { label: "Just me" },
          { label: "2–10" },
          { label: "11–50" },
          { label: "51–250" },
          { label: "More than 250" },
        ],
      },
      {
        ref: "job_role",
        type: "short_text",
        title: "What's your role there?",
        required: false,
        maxLength: 120,
      },
      {
        ref: "age_range",
        type: "single_select",
        title: "Which age group are you in?",
        required: false,
        options: [
          { label: "Under 25" },
          { label: "25–34" },
          { label: "35–44" },
          { label: "45–54" },
          { label: "55 or over" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "discovery",
        type: "single_select",
        title: "How did you first hear about us?",
        required: true,
        allowOther: true,
        options: [
          { label: "Search engine" },
          { label: "Recommendation" },
          { label: "Social media" },
          { label: "An ad" },
          { label: "Review or comparison site" },
        ],
      },
      {
        ref: "problem",
        type: "long_text",
        title: "What were you trying to sort out when you first bought from us?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "alternatives",
        type: "multi_select",
        title: "What else did you consider?",
        required: true,
        options: [
          { label: "Another company" },
          { label: "Doing it myself" },
          { label: "Doing nothing for now" },
          { label: "Nothing, we were the only option I looked at" },
        ],
      },
      {
        ref: "why_us",
        type: "single_select",
        title: "What was the main reason you chose us?",
        required: true,
        allowOther: true,
        options: [
          { label: "Price" },
          { label: "Quality" },
          { label: "A specific feature or service" },
          { label: "A recommendation" },
          { label: "Speed or convenience" },
          { label: "I trusted the brand" },
        ],
      },
      {
        ref: "frequency",
        type: "single_select",
        title: "How often do you buy from us or use what you bought?",
        required: true,
        options: [
          { label: "Daily" },
          { label: "Weekly" },
          { label: "Monthly" },
          { label: "Now and then" },
          { label: "It was a one-off" },
        ],
      },
      {
        ref: "satisfaction",
        type: "rating",
        title: "How well are we meeting your needs?",
        required: true,
        scale: 5,
      },
      {
        ref: "recommend",
        type: "nps",
        title: "How likely are you to recommend us to someone like you?",
        required: true,
      },
      {
        ref: "more_help",
        type: "long_text",
        title: "Is there anything else you wish we could help you with?",
        required: false,
        maxLength: 600,
      },
    ],
    branches: [
      { when: "buyer_type", is: "For my business or employer", then: "company_size" },
      { when: "job_role", always: true, then: "discovery" },
      { when: "buyer_type", is: "For myself or my household", then: "age_range" },
    ],
    ending: {
      title: "Thank you, that helps a lot",
      body: "Answers like yours tell us who we're really serving and how to do it better.",
    },
    guide: {
      questionsToConsider: [
        "Do you sell to both consumers and businesses, or can you drop one path entirely?",
        "Which customer details would change a decision, such as company size, role or age?",
        "Which alternatives do customers really weigh you against, including doing nothing?",
        "Should this go to every customer, or to recent buyers only while the decision is fresh?",
      ],
      howToUseResponses:
        "Group the responses by buyer type and then by the main reason people chose you; those groups are a far better starting point for personas than demographics alone. Read the problem answers for the words customers use, and reuse that language in your marketing. Where many people considered doing nothing, your real competitor is inertia, and your messaging should explain why acting now is worth it.",
      customizeSteps: [
        "Remove the business or consumer path if you only sell to one, and edit the company size bands to fit your market.",
        "Replace the reason list with the strengths you think win customers, and keep an Other option to catch the ones you missed.",
        "Send it to recent customers, then sort the answers by buyer type in the dashboard or export them to CSV.",
      ],
      faqs: [
        {
          q: "What is a customer analysis survey?",
          a: "It asks your customers who they are, what problem they had, what they considered and why they chose you. It adds the reasons behind purchases to what your sales data already shows.",
        },
        {
          q: "What questions should a customer analysis survey include?",
          a: "Background that matters to your market, how they found you, the problem they were solving, the alternatives they weighed, the main reason they chose you and how well you meet their needs.",
        },
        {
          q: "Can I use this for building buyer personas?",
          a: "Yes. Grouping answers by buyer type, problem and reason for choosing you gives you personas based on what customers said rather than guesses.",
        },
        {
          q: "How is customer analysis different from a satisfaction survey?",
          a: "A satisfaction survey asks how well you're doing. Customer analysis asks who your customers are and why they bought, so you can find and serve more people like them.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "customer-attitudes-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["marketing", "customer-success", "product-research"],
    searchName: "Customer attitudes survey",
    title: "Customer attitudes",
    icon: "ThumbsUp",
    metaDescription:
      "Measure how customers feel about your product and why. Positive, neutral and negative customers each get their own follow-up, then all rate five statements.",
    description: "See how customers feel about your product, with the reasons behind every rating.",
    blurb:
      "Asks for a feeling first, then the reason behind it, with a different follow-up for positive, lukewarm and negative customers. A grid of agree-or-disagree statements covers value, trust, ease of use and how you compare, and a closing question on how views have shifted shows whether things are heading the right way.",
    tags: ["customer attitudes survey", "customer opinion survey", "customer sentiment", "attitude survey", "product feedback"],
    greeting: "We'd like to hear how you honestly feel about our product. It takes about three minutes.",
    questions: [
      {
        ref: "tenure",
        type: "single_select",
        title: "How long have you been using our product?",
        required: true,
        options: [
          { label: "Less than a month" },
          { label: "1–6 months" },
          { label: "6–12 months" },
          { label: "More than a year" },
        ],
      },
      {
        ref: "feeling",
        type: "opinion_scale",
        title: "Overall, how do you feel about it?",
        required: true,
        steps: 5,
        labelLow: "Very negative",
        labelHigh: "Very positive",
      },
      {
        ref: "positive_why",
        type: "long_text",
        title: "Glad to hear it. What would you tell a friend about it?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "neutral_why",
        type: "long_text",
        title: "What's keeping it from being great for you?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "negative_why",
        type: "long_text",
        title: "Sorry it's not working for you. What has shaped that view most?",
        description: "A specific moment, like a bill, a bug or a support call, helps us most.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "statements",
        type: "matrix",
        title: "How much do you agree with each of these?",
        required: true,
        rows: [
          "It's worth what I pay",
          "It does what it promises",
          "I trust the company behind it",
          "It's easy to use",
          "It's better than the alternatives",
        ],
        columns: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
      },
      {
        ref: "drew_you",
        type: "single_select",
        title: "What first drew you to it?",
        required: true,
        allowOther: true,
        options: [
          { label: "The price" },
          { label: "A particular feature" },
          { label: "How easy it looked" },
          { label: "A recommendation" },
          { label: "The brand" },
        ],
      },
      {
        ref: "view_shift",
        type: "single_select",
        title: "Compared with when you started, has your view of it changed?",
        required: true,
        options: [
          { label: "It's got better" },
          { label: "It's about the same" },
          { label: "It's got worse" },
        ],
      },
      {
        ref: "buy_again",
        type: "single_select",
        title: "If you were choosing again today, would you pick us?",
        required: true,
        options: [
          { label: "Definitely" },
          { label: "Probably" },
          { label: "Not sure" },
          { label: "Probably not" },
          { label: "Definitely not" },
        ],
      },
      {
        ref: "improve",
        type: "long_text",
        title: "What one change would improve your opinion of us the most?",
        required: false,
        maxLength: 600,
      },
    ],
    branches: [
      { when: "feeling", op: "gte", is: 4, then: "positive_why" },
      { when: "positive_why", always: true, then: "statements" },
      { when: "feeling", op: "eq", is: 3, then: "neutral_why" },
      { when: "neutral_why", always: true, then: "statements" },
      { when: "feeling", op: "lte", is: 2, then: "negative_why" },
    ],
    ending: {
      title: "Thank you for your honesty",
      body: "The team reads every answer, and the reasons you gave help us decide what to change first.",
    },
    guide: {
      questionsToConsider: [
        "Is this about one product, a service or the company as a whole, and does the wording say so?",
        "Which statements in the grid reflect claims you make in your marketing?",
        "Do you want to compare new and long-standing customers, and is the tenure question enough for that?",
        "Who will act on the negative answers, and how quickly?",
      ],
      howToUseResponses:
        "Read the written reasons alongside the feeling score, because the same score can come from very different experiences. In the statement grid, look for rows where agreement is weak; those are the promises customers don't believe yet. Compare new and long-standing customers, and if views get worse with time, look at what happens after the first few months rather than at your onboarding.",
      customizeSteps: [
        "Name your product in the greeting and the first questions so there's no doubt what people are rating.",
        "Rewrite the grid statements to match the claims you make, such as saves time or good for beginners.",
        "Send it to active customers and track the feeling score over time in the dashboard, or export results to CSV.",
      ],
      faqs: [
        {
          q: "What is a customer attitudes survey?",
          a: "It measures how customers feel about your product, service or brand and, importantly, why. It combines a rating with open questions so each score comes with context.",
        },
        {
          q: "How is an attitude different from a preference?",
          a: "An attitude is a broad opinion or feeling about something. A preference is a choice between options. This survey covers attitudes; a consumer preference survey covers choices.",
        },
        {
          q: "Why use agree and disagree statements?",
          a: "Statements let you test specific beliefs, such as whether customers think you're worth the price, in a way you can compare over time. Keep each statement to one idea so the answer is clear.",
        },
        {
          q: "How often should I run a customer attitudes survey?",
          a: "Every six months or so works for most products, and after any major change such as a redesign or price change. Keep the core questions the same to compare results.",
        },
      ],
    },
  }),
];
