import { defineTemplate, type TemplateSeed } from "../define.js";

export const SURVEY_MARKETING_2: TemplateSeed[] = [
  defineTemplate({
    slug: "customer-loss-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["customer-success", "marketing", "sales"],
    searchName: "Customer loss survey",
    title: "Lost customer survey",
    icon: "DoorOpen",
    metaDescription:
      "Ask customers who stopped buying what changed, whether they told you, and how the business they use now compares. Anyone open to a chat can ask for a call.",
    description: "Learn what changed for a customer who stopped buying, and how you compare with where they went.",
    blurb:
      "For customers who drifted away rather than formally cancelling, such as a client who stopped reordering or a regular who stopped coming in. It asks what changed and whether they ever told you, which shows how many losses you could have seen coming. Price leavers get a pricing question, people who moved elsewhere compare you side by side, and anyone open to a conversation reaches an ending that promises a call.",
    tags: ["customer loss survey", "lost customer survey", "lapsed customer survey", "win back customers", "why customers stop buying"],
    greeting: "We noticed we haven't seen you in a while. Would you tell us what changed? It takes about three minutes.",
    questions: [
      {
        ref: "customer_since",
        type: "dropdown",
        title: "How long were you buying from us?",
        required: true,
        options: [
          { label: "Less than 3 months" },
          { label: "3 to 12 months" },
          { label: "1 to 3 years" },
          { label: "More than 3 years" },
        ],
      },
      {
        ref: "last_bought",
        type: "single_select",
        title: "Roughly when did you last buy from us?",
        required: true,
        options: [
          { label: "In the last 3 months" },
          { label: "3 to 6 months ago" },
          { label: "6 to 12 months ago" },
          { label: "More than a year ago" },
        ],
      },
      {
        ref: "main_reason",
        type: "single_select",
        title: "What changed that made you stop?",
        required: true,
        options: [
          { label: "The price" },
          { label: "Something I needed was missing" },
          { label: "Quality or reliability slipped" },
          { label: "Service let me down" },
          { label: "Somewhere else became more convenient" },
          { label: "My needs changed" },
          { label: "Something else" },
        ],
      },
      {
        ref: "price_view",
        type: "single_select",
        title: "Compared with what else is out there, how did our price feel?",
        required: true,
        options: [
          { label: "Much too high" },
          { label: "A bit high" },
          { label: "Fair, but I couldn't justify it any more" },
          { label: "Fair, the budget just went away" },
        ],
      },
      {
        ref: "reason_detail",
        type: "long_text",
        title: "When did you first notice it, and what happened?",
        required: false,
        maxLength: 1200,
      },
      {
        ref: "told_us",
        type: "yes_no",
        title: "Did you mention any of this to us before you stopped?",
        required: true,
      },
      {
        ref: "moved_to",
        type: "single_select",
        title: "Where do you get this now?",
        required: true,
        options: [
          { label: "From another business" },
          { label: "We do it ourselves now" },
          { label: "Nowhere, we stopped needing it" },
          { label: "Still deciding" },
        ],
      },
      {
        ref: "compare",
        type: "matrix",
        title: "How does the business you use now compare with us?",
        required: false,
        rows: ["Price", "Quality", "Convenience", "Service", "Range on offer"],
        columns: ["They're worse", "About the same", "They're better"],
      },
      {
        ref: "experience",
        type: "rating",
        title: "Before things changed, how happy were you with us?",
        required: true,
        scale: 5,
      },
      {
        ref: "bring_back",
        type: "long_text",
        title: "What would we need to change for you to buy from us again?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "contact_ok",
        type: "yes_no",
        title: "Would you be open to a short call about your experience?",
        description: "No sales pitch. We just want to understand it properly.",
        required: true,
      },
      {
        ref: "contact_email",
        type: "email",
        title: "Great, what's the best email to reach you?",
        required: true,
      },
    ],
    branches: [
      { when: "main_reason", is: "The price", then: "price_view" },
      { when: "main_reason", is: "Something I needed was missing", then: "reason_detail" },
      { when: "main_reason", is: "Quality or reliability slipped", then: "reason_detail" },
      { when: "main_reason", is: "Service let me down", then: "reason_detail" },
      { when: "main_reason", is: "Somewhere else became more convenient", then: "reason_detail" },
      { when: "main_reason", is: "My needs changed", then: "reason_detail" },
      { when: "main_reason", is: "Something else", then: "reason_detail" },
      { when: "moved_to", is: "From another business", then: "compare" },
      { when: "moved_to", is: "We do it ourselves now", then: "experience" },
      { when: "moved_to", is: "Nowhere, we stopped needing it", then: "experience" },
      { when: "moved_to", is: "Still deciding", then: "experience" },
      { when: "contact_ok", is: false, then: "end_thanks" },
      { when: "contact_email", always: true, then: "end_call" },
    ],
    ending: {
      title: "Thank you for being honest with us",
      body: "We read every answer, and it goes to the people who look after the part of the experience you mentioned.",
    },
    endings: [
      {
        ref: "end_call",
        title: "Thanks, we'll be in touch 📞",
        body: "Someone from the team will email you to find a time that suits you. It will be a conversation, not a pitch.",
      },
    ],
    guide: {
      questionsToConsider: [
        "How will you decide who counts as lost: no order in three months, six months, a year?",
        "Which reasons for leaving can your team actually act on, and are they all in the list?",
        "Do you want to know which business people moved to by name, or only how you compare?",
        "Who will make the follow-up calls, and how quickly can they reach people who asked?",
      ],
      howToUseResponses:
        "Start with the question about whether people told you before they stopped. Every loss where the answer is no is one you had no chance to prevent, so look at what those customers had in common and where they might have spoken up. Then group the reasons by how long each person was a customer, and read the comparison grid for the rows where rivals keep coming out ahead. Email everyone who agreed to a call within a few days.",
      customizeSteps: [
        "Replace the reasons with the ones your team hears most, and change the comparison rows to what customers weigh when choosing between you and a rival.",
        "Adjust the pricing answers and the timing bands to how often your customers usually buy.",
        "Send the link to customers who have gone quiet past your cut-off, and check the call requests in the dashboard every day.",
      ],
      faqs: [
        {
          q: "What should a customer loss survey ask?",
          a: "What changed, whether the customer raised it with you, where they buy now and how that compares, and what would bring them back. Keep it short, because they owe you nothing.",
        },
        {
          q: "When should I send a lost customer survey?",
          a: "Once a customer has gone quiet for longer than their usual gap between purchases. Waiting much longer than that means the reason has blurred and fewer people reply.",
        },
        {
          q: "How is a customer loss survey different from a churn survey?",
          a: "A churn survey usually runs at the moment someone cancels a subscription. A customer loss survey goes to people who simply stopped buying, often without telling you, so it also asks whether they ever raised the problem.",
        },
        {
          q: "Should a customer loss survey try to win people back?",
          a: "Not directly. Its first job is to understand the decision. This version offers a call only to people who say yes, and promises it will not be a sales pitch.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "customer-retention-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["customer-success", "marketing"],
    searchName: "Customer retention survey",
    title: "Customer retention survey",
    icon: "HeartHandshake",
    metaDescription:
      "Find out why current customers stay, what nearly made them leave and whether they expect to renew. Anyone who came close to leaving gets extra follow-ups.",
    description: "Ask current customers what keeps them with you and what could change their mind.",
    blurb:
      "Built for customers who are still with you, which is when their answers are most useful. It measures the value they get and why they stay, then asks one direct question: has anything come close to making you leave? Those who say yes are asked what happened and what you should fix first, and everyone says whether they expect to still be a customer a year from now, so at-risk accounts surface before they cancel.",
    tags: ["customer retention survey", "renewal survey", "at-risk customers", "why customers stay", "retention questions"],
    greeting: "You've been with us a while, and we'd like to keep earning that. Mind answering a few questions?",
    questions: [
      {
        ref: "tenure",
        type: "dropdown",
        title: "How long have you been a customer?",
        required: true,
        options: [
          { label: "Less than 6 months" },
          { label: "6 to 12 months" },
          { label: "1 to 2 years" },
          { label: "More than 2 years" },
        ],
      },
      {
        ref: "usage",
        type: "single_select",
        title: "How often do you use us these days?",
        required: true,
        options: [
          { label: "Daily" },
          { label: "A few times a week" },
          { label: "A few times a month" },
          { label: "Rarely" },
        ],
      },
      {
        ref: "value",
        type: "opinion_scale",
        title: "How much value do you get for what you pay?",
        required: true,
        steps: 10,
        startAt: 1,
        labelLow: "Very little",
        labelHigh: "A great deal",
      },
      {
        ref: "why_stay",
        type: "multi_select",
        title: "What keeps you with us? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        allowOther: true,
        options: [
          { label: "It does the job well" },
          { label: "Good value for money" },
          { label: "Helpful support" },
          { label: "It fits how we already work" },
          { label: "Switching would be a hassle" },
          { label: "I trust the company" },
        ],
      },
      {
        ref: "aspects",
        type: "matrix",
        title: "How are we doing on each of these?",
        required: false,
        rows: ["Quality", "Reliability", "Support", "Keeping you informed", "Price"],
        columns: ["Poor", "Okay", "Good", "Excellent"],
      },
      {
        ref: "considered_leaving",
        type: "yes_no",
        title: "Has anything ever come close to making you leave us?",
        required: true,
      },
      {
        ref: "leaving_trigger",
        type: "long_text",
        title: "What happened?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "fix_first",
        type: "single_select",
        title: "If we could fix one thing first, what should it be?",
        required: true,
        allowOther: true,
        options: [
          { label: "The price" },
          { label: "A missing feature or service" },
          { label: "Reliability" },
          { label: "Response times from support" },
          { label: "How we communicate changes" },
        ],
      },
      {
        ref: "one_improvement",
        type: "long_text",
        title: "What's one improvement that would make you even more likely to stay?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "stay_next_year",
        type: "single_select",
        title: "A year from now, do you expect to still be a customer?",
        required: true,
        options: [
          { label: "Definitely" },
          { label: "Probably" },
          { label: "Not sure" },
          { label: "Probably not" },
        ],
      },
    ],
    branches: [{ when: "considered_leaving", is: false, then: "one_improvement" }],
    ending: {
      title: "Thank you for sticking with us",
      body: "Your answers go straight to the team, and we'll share what we change because of them.",
    },
    guide: {
      questionsToConsider: [
        "Which parts of your service do customers mention most, and should they replace the rows in the rating grid?",
        "Should the question about staying a year from now match your renewal cycle, such as the next contract or the next season?",
        "Who contacts a customer who says something nearly made them leave, and how soon?",
        "Do you want to send this to every customer or only to those past their first renewal?",
      ],
      howToUseResponses:
        "Pull out every response where something came close to making the customer leave, or where they are unsure about the next year, and treat it as an at-risk account: read what triggered it and what they want fixed first, and get the owner of that account to reply. Across everyone else, compare the reasons people stay with how often they use you. Customers who stay only because switching is a hassle are less secure than they look.",
      customizeSteps: [
        "Edit the reasons for staying so they describe what you actually sell, and keep the switching-hassle option since it is an honest warning sign.",
        "Add the customer's account name or plan as a hidden field so each at-risk answer can be traced back.",
        "Send it a month or two before renewals come round, then export the at-risk answers to CSV for your account team.",
      ],
      faqs: [
        {
          q: "What questions should a customer retention survey include?",
          a: "How much value customers get, why they stay, how you perform on the things that matter to them, and whether anything has nearly made them leave. That last one is the question most surveys avoid and the one that tells you the most.",
        },
        {
          q: "When should I run a customer retention survey?",
          a: "Once or twice a year, and ideally before a renewal date rather than after it, so there is still time to act on what people say.",
        },
        {
          q: "What is the difference between retention and satisfaction surveys?",
          a: "A satisfaction survey asks how happy people are. A retention survey asks whether they will stay and what could change that, which is a more useful question for planning.",
        },
        {
          q: "How do I find at-risk customers from the results?",
          a: "Filter for anyone who said something nearly made them leave or who is unsure they will be a customer next year, and look at low value scores alongside falling usage. Those accounts deserve a personal follow-up.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "fashion-marketing-questionnaire",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["marketing", "product-research"],
    searchName: "Fashion marketing questionnaire",
    title: "Fashion shopper questionnaire",
    icon: "ShoppingBag",
    metaDescription:
      "Learn how your fashion audience shops: their style, budget, where they buy and what makes them trust a brand. Online and in-store shoppers get their own follow-ups.",
    description: "Understand your fashion customers' style, spending and what persuades them to buy.",
    blurb:
      "A questionnaire for clothing and accessory brands that want to know their audience beyond age and location. It covers style, budget and what they weigh when buying, and the shopping channel decides the next question: online shoppers are asked what helps them buy without trying on, and in-store shoppers what draws them through the door.",
    tags: ["fashion marketing questionnaire", "fashion survey", "clothing brand survey", "shopping habits survey", "style preferences"],
    greeting: "Hi! We're a fashion brand trying to understand how you like to shop. It takes about three minutes.",
    questions: [
      {
        ref: "age_range",
        type: "dropdown",
        title: "Which age group are you in?",
        required: true,
        options: [
          { label: "Under 18" },
          { label: "18 to 24" },
          { label: "25 to 34" },
          { label: "35 to 44" },
          { label: "45 to 54" },
          { label: "55 or over" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "style",
        type: "multi_select",
        title: "Which of these describe your style? Choose up to three.",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "Classic and timeless" },
          { label: "Casual and comfortable" },
          { label: "Minimal" },
          { label: "Streetwear" },
          { label: "Trend-led" },
          { label: "Vintage or second-hand" },
          { label: "Sporty" },
          { label: "Workwear and tailoring" },
        ],
      },
      {
        ref: "shop_channel",
        type: "single_select",
        title: "Where do you buy most of your clothes?",
        required: true,
        options: [{ label: "Mostly online" }, { label: "Mostly in stores" }, { label: "About half and half" }],
      },
      {
        ref: "online_confidence",
        type: "multi_select",
        title: "When buying online, what helps you feel sure about an item?",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        options: [
          { label: "A detailed size guide" },
          { label: "Photos on different body types" },
          { label: "Customer reviews that mention fit" },
          { label: "Easy, free returns" },
          { label: "Fabric and care details" },
          { label: "Short videos of the item worn" },
        ],
      },
      {
        ref: "store_draw",
        type: "multi_select",
        title: "What makes you choose to shop in a store?",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        options: [
          { label: "Trying things on" },
          { label: "Seeing the quality up close" },
          { label: "Taking it home the same day" },
          { label: "Advice from staff" },
          { label: "Browsing is part of the fun" },
        ],
      },
      {
        ref: "frequency",
        type: "single_select",
        title: "How often do you buy new clothes or accessories?",
        required: true,
        options: [
          { label: "Every week or two" },
          { label: "About once a month" },
          { label: "A few times a year" },
          { label: "Only when I need something" },
        ],
      },
      {
        ref: "factors",
        type: "ranking",
        title: "Rank what matters most when you decide to buy.",
        required: true,
        items: ["Price", "Fit", "Quality and fabric", "How it's made", "The brand", "Being on trend"],
      },
      {
        ref: "sustainability",
        type: "opinion_scale",
        title: "How much does how a piece was made affect your choice?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not at all",
        labelHigh: "It decides it",
      },
      {
        ref: "discovery",
        type: "multi_select",
        title: "Where do you usually discover new brands?",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        allowOther: true,
        options: [
          { label: "Instagram or TikTok" },
          { label: "Friends and family" },
          { label: "Online marketplaces" },
          { label: "Fashion magazines or blogs" },
          { label: "Walking past a store" },
          { label: "Search engines" },
        ],
      },
      {
        ref: "wish",
        type: "long_text",
        title: "What's something you wish fashion brands did better?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "early_access",
        type: "yes_no",
        title: "Would you like early access to new collections?",
        required: true,
      },
      {
        ref: "email",
        type: "email",
        title: "Where should we send it?",
        required: true,
      },
    ],
    branches: [
      { when: "shop_channel", is: "Mostly in stores", then: "store_draw" },
      { when: "online_confidence", always: true, then: "frequency" },
      { when: "early_access", is: false, then: "end_thanks" },
    ],
    ending: {
      title: "Thanks, that's really helpful ✨",
      body: "Your answers shape what we design, how we photograph it and where you'll hear about it.",
    },
    guide: {
      questionsToConsider: [
        "Are the style options the words your customers use, or the words your design team uses?",
        "Do you sell in physical stores at all? If not, the in-store follow-up can become a question about pop-ups or events.",
        "Which buying factors would change your product or photography decisions if they ranked highly?",
        "Is early access the right thing to offer, or would a lookbook or size advice be more welcome?",
      ],
      howToUseResponses:
        "Split the results by style and age group before reading anything else, since a streetwear customer and a tailoring customer rarely want the same thing. Look at what online shoppers need to feel confident: if fit reviews and body-type photos rank high, that is a product page change, not a marketing one. Use the discovery channels to decide where your next campaign budget goes.",
      customizeSteps: [
        "Swap the style list for the aesthetics your collections actually cover, and add your own categories such as shoes or jewellery if they matter.",
        "Change the early-access offer at the end to whatever you can really deliver, and say how often you will email.",
        "Share the link from your social profiles and order confirmation emails, then export results to CSV to compare segments.",
      ],
      faqs: [
        {
          q: "What should a fashion marketing questionnaire ask?",
          a: "Style, how often and where people shop, what they weigh when buying, how they discover brands and what they wish brands did better. Add budget only if it will change a decision.",
        },
        {
          q: "How do I get customers to fill in a fashion survey?",
          a: "Keep it short and give something real in return, like early access to a collection. Asking one question at a time in a chat also feels lighter than a long page of boxes.",
        },
        {
          q: "Should I ask about sustainability?",
          a: "Yes, but as a scale rather than a yes or no. Most people will say it matters; the useful signal is whether it actually decides the purchase.",
        },
        {
          q: "Can I add photos of products to the questions?",
          a: "You can attach an image to any question when you edit the template, which is useful if you want reactions to a specific piece or look.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "firmographics-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "generate-leads"],
    roles: ["marketing", "sales", "product-research"],
    searchName: "Firmographics survey",
    title: "Firmographics survey",
    icon: "Building2",
    metaDescription:
      "Collect company size, industry, location, business model and buying role from B2B respondents, with an optional follow-up for those who want to talk to sales.",
    description: "Profile the companies in your audience by size, sector, model and who makes buying decisions.",
    blurb:
      "The company facts that give B2B research and sales conversations context: industry, headcount, revenue band, locations and business model. It also asks the respondent's part in buying decisions, skipping the budget question for people who are not involved, and anyone who wants a follow-up leaves their details and gets their own ending.",
    tags: ["firmographics survey", "firmographic data", "B2B survey", "company profile questions", "market segmentation"],
    greeting: "Hello! We're learning about the businesses we work with. A few quick questions about your company.",
    questions: [
      {
        ref: "industry",
        type: "dropdown",
        title: "Which industry is your company in?",
        required: true,
        options: [
          { label: "Software and technology" },
          { label: "Financial services" },
          { label: "Healthcare" },
          { label: "Manufacturing" },
          { label: "Retail and e-commerce" },
          { label: "Professional services" },
          { label: "Education" },
          { label: "Construction and real estate" },
          { label: "Hospitality and travel" },
          { label: "Non-profit" },
          { label: "Public sector" },
          { label: "Other" },
        ],
      },
      {
        ref: "headcount",
        type: "single_select",
        title: "Roughly how many people work there?",
        required: true,
        options: [
          { label: "Just me" },
          { label: "2 to 10" },
          { label: "11 to 50" },
          { label: "51 to 200" },
          { label: "201 to 1,000" },
          { label: "More than 1,000" },
        ],
      },
      {
        ref: "revenue",
        type: "dropdown",
        title: "Which band is your annual revenue in, in US dollars?",
        description: "A rough band is fine, and you can skip this one.",
        required: false,
        options: [
          { label: "Under $1 million" },
          { label: "$1 to 10 million" },
          { label: "$10 to 50 million" },
          { label: "$50 to 250 million" },
          { label: "Over $250 million" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "hq",
        type: "address",
        title: "Where is your head office?",
        required: true,
        fields: ["city", "country"],
      },
      {
        ref: "locations",
        type: "single_select",
        title: "How many locations or offices do you operate?",
        required: true,
        options: [{ label: "One" }, { label: "2 to 5" }, { label: "6 to 20" }, { label: "More than 20" }, { label: "We're fully remote" }],
      },
      {
        ref: "model",
        type: "multi_select",
        title: "Who do you sell to?",
        required: true,
        minSelections: 1,
        maxSelections: 4,
        options: [
          { label: "Other businesses" },
          { label: "Consumers" },
          { label: "Government" },
          { label: "Through partners or resellers" },
        ],
      },
      {
        ref: "your_team",
        type: "dropdown",
        title: "Which team are you in?",
        required: true,
        options: [
          { label: "Leadership" },
          { label: "Sales" },
          { label: "Marketing" },
          { label: "Operations" },
          { label: "Finance" },
          { label: "IT or engineering" },
          { label: "HR" },
          { label: "Customer support" },
          { label: "Other" },
        ],
      },
      {
        ref: "buying_role",
        type: "single_select",
        title: "What's your part in choosing new tools or suppliers?",
        required: true,
        options: [
          { label: "I make the final decision" },
          { label: "I recommend options" },
          { label: "I use what's chosen" },
          { label: "I'm not involved" },
        ],
      },
      {
        ref: "budget_timing",
        type: "single_select",
        title: "When does your company usually set budgets for new purchases?",
        required: false,
        options: [
          { label: "Once a year" },
          { label: "Every quarter" },
          { label: "Whenever a need comes up" },
          { label: "Not sure" },
        ],
      },
      {
        ref: "growth",
        type: "single_select",
        title: "Over the next year, do you expect your team to...",
        required: true,
        options: [{ label: "Grow" }, { label: "Stay about the same" }, { label: "Shrink" }, { label: "Hard to say" }],
      },
      {
        ref: "follow_up",
        type: "yes_no",
        title: "Would you like someone from our team to follow up with you?",
        required: true,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Who should we contact?",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
    ],
    branches: [
      { when: "buying_role", is: "I'm not involved", then: "growth" },
      { when: "buying_role", is: "I use what's chosen", then: "growth" },
      { when: "follow_up", is: false, then: "end_thanks" },
      { when: "contact", always: true, then: "end_follow_up" },
    ],
    ending: {
      title: "Thank you for helping with our research",
      body: "Your answers are used together with everyone else's to understand the businesses we serve.",
    },
    endings: [
      {
        ref: "end_follow_up",
        title: "Thanks, we'll be in touch",
        body: "Someone from our team will email you within a couple of working days.",
      },
    ],
    guide: {
      questionsToConsider: [
        "Which company traits actually change how you sell or what you build: size, sector, region or business model?",
        "Do you need a revenue band at all, or does headcount tell you enough?",
        "Which currency and revenue bands fit the companies you usually talk to?",
        "Do you want to use this for research only, or also to pass interested respondents to sales?",
      ],
      howToUseResponses:
        "Treat each response as a company profile and build segments from the combinations that matter, such as mid-sized B2B firms in professional services. Compare those segments against your other research or deal history rather than assuming every company of one size behaves the same. Send the respondents who asked for a follow-up to sales with their buying role, so the first call starts at the right level.",
      customizeSteps: [
        "Trim the industry list to the sectors you sell into, keeping an Other option, and set the revenue bands and currency to match your market.",
        "Remove the follow-up question if this is pure research, so nobody feels the survey was a sales form in disguise.",
        "Embed it on a resource or research page, or send it to an existing list, then export responses to CSV to segment them.",
      ],
      faqs: [
        {
          q: "What are firmographics?",
          a: "Facts that describe an organisation, such as industry, size, revenue, location and business model. They do for companies what demographics do for people.",
        },
        {
          q: "What firmographic questions should I ask?",
          a: "Industry, number of employees, revenue band, headquarters location, number of sites and who the company sells to. Add the respondent's team and buying role if the results feed sales.",
        },
        {
          q: "Should I ask for exact revenue?",
          a: "No. Bands are easier to answer and just as useful for segmenting. Make the question optional, since some people cannot share it.",
        },
        {
          q: "How do I use firmographic data in marketing?",
          a: "Group respondents into segments by the traits that change their needs, then tailor messages, offers and sales focus to each group instead of treating every business the same.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "food-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["marketing", "product-research", "operations"],
    searchName: "Food survey",
    title: "Food preferences survey",
    icon: "Utensils",
    metaDescription:
      "Ask about diets, allergies, favourite cuisines and what people value in a meal. Use it to plan a menu, test a food idea or learn what your customers like to eat.",
    description: "Learn what people like to eat, what they avoid and what they value when choosing food.",
    blurb:
      "A food preferences survey for restaurants, caterers and food brands. It starts with diets and allergies, asking for details only from people who have an allergy, then covers cuisines, spice, eating-out habits and what matters most in a meal, finishing with the dish people wish they could find.",
    tags: ["food survey", "food preferences survey", "menu planning survey", "dietary requirements", "restaurant survey"],
    greeting: "Hungry for a quick chat? We'd love to hear what you like to eat.",
    questions: [
      {
        ref: "diet",
        type: "multi_select",
        title: "Do you follow any of these diets?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        allowOther: true,
        options: [
          { label: "No particular diet" },
          { label: "Vegetarian" },
          { label: "Vegan" },
          { label: "Pescatarian" },
          { label: "Halal" },
          { label: "Kosher" },
          { label: "Gluten-free" },
          { label: "Low-carb" },
        ],
      },
      {
        ref: "has_allergy",
        type: "yes_no",
        title: "Do you have any food allergies or intolerances?",
        required: true,
      },
      {
        ref: "allergy_detail",
        type: "short_text",
        title: "Which ones should we know about?",
        required: true,
        maxLength: 200,
      },
      {
        ref: "cuisines",
        type: "multi_select",
        title: "Which cuisines do you enjoy most?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        allowOther: true,
        options: [
          { label: "Italian" },
          { label: "Indian" },
          { label: "Chinese" },
          { label: "Japanese" },
          { label: "Mexican" },
          { label: "Thai" },
          { label: "Middle Eastern" },
          { label: "Mediterranean" },
          { label: "American" },
        ],
      },
      {
        ref: "spice",
        type: "opinion_scale",
        title: "How spicy do you like your food?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "No heat at all",
        labelHigh: "As hot as it gets",
      },
      {
        ref: "adventurous",
        type: "opinion_scale",
        title: "How keen are you to try dishes you've never had before?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "I stick to what I know",
        labelHigh: "Always up for it",
      },
      {
        ref: "eat_out",
        type: "single_select",
        title: "How often do you eat out or order in?",
        required: true,
        options: [
          { label: "Several times a week" },
          { label: "About once a week" },
          { label: "A few times a month" },
          { label: "Rarely" },
        ],
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "When choosing a meal, rank what matters most to you.",
        required: true,
        items: ["Taste", "Price", "Healthiness", "Portion size", "Speed", "Fresh, local ingredients"],
      },
      {
        ref: "spend",
        type: "number",
        title: "Roughly how much do you usually spend on a meal out, in your local currency?",
        required: false,
        min: 0,
      },
      {
        ref: "wish_dish",
        type: "long_text",
        title: "Is there a dish or kind of food you wish was easier to find near you?",
        required: false,
        maxLength: 500,
      },
    ],
    branches: [{ when: "has_allergy", is: false, then: "cuisines" }],
    ending: {
      title: "Thanks, that's given us plenty to chew on 🍽️",
      body: "Your answers help us decide what goes on the menu next.",
    },
    guide: {
      questionsToConsider: [
        "Is this for a menu, a new product or general research? The cuisine list should match that goal.",
        "Which diets and allergies do you genuinely cater for, and should the list reflect only those?",
        "Do you need a spend figure, or would a question about value for money tell you more?",
        "Should you add a question about specific dishes you are thinking of launching?",
      ],
      howToUseResponses:
        "Start with diets and allergies, because they tell you which options your menu must include before any question of taste. Then look at the ranking of priorities alongside eating-out frequency: regulars who rank speed and price highly want something different from occasional diners who rank taste first. Read the wished-for dishes together, since a repeated request is a ready-made menu idea.",
      customizeSteps: [
        "Edit the cuisine list to fit your kitchen or product range, and replace the spend question with price bands if you prefer.",
        "Add a question that shows one or two dishes you are considering and asks people to rate them.",
        "Share the link on a receipt, table card or social post, and read the allergy answers in the dashboard before planning anything.",
      ],
      faqs: [
        {
          q: "What questions should a food survey include?",
          a: "Diets and allergies, favourite cuisines, spice tolerance, how often people eat out, what they value in a meal and what they wish they could find. Tailor the list to the decision you are making.",
        },
        {
          q: "How can I use a food survey to plan a menu?",
          a: "Use the diet and allergy answers to set what the menu must cover, the cuisines and spice level to shape the dishes, and the priorities ranking to decide portion size and pricing.",
        },
        {
          q: "Should I ask about allergies in a food survey?",
          a: "Yes. It tells you how much demand there is for allergen-free options. This template only asks for details from people who say they have one.",
        },
        {
          q: "Can I use this for a food product idea rather than a restaurant?",
          a: "Yes. Replace the eating-out question with where people buy food, and add a question describing your product so they can react to it.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "magazine-reader-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["marketing", "product-research"],
    searchName: "Magazine reader survey",
    title: "Magazine reader survey",
    icon: "BookOpen",
    metaDescription:
      "Ask readers how they read your magazine, which sections they skip and what they want more of. Happy readers name a favourite piece; unhappy ones say what fell flat.",
    description: "Find out which sections readers value, which they skip and what would make them stay.",
    blurb:
      "A reader survey for print and digital magazines. It covers format, reading habits and a section-by-section grid, then splits on the overall rating: readers who love it name the piece that stayed with them, and readers who do not are asked what disappoints them. It closes by asking whether they plan to keep reading.",
    tags: ["magazine reader survey", "reader survey", "publication feedback", "readership survey", "editorial feedback"],
    greeting: "Thanks for reading us. We'd like to know what you love, what you skip and what's missing.",
    questions: [
      {
        ref: "format",
        type: "single_select",
        title: "How do you usually read the magazine?",
        required: true,
        options: [{ label: "In print" }, { label: "On our website" }, { label: "In the app or as a digital edition" }, { label: "A mix of these" }],
      },
      {
        ref: "reader_since",
        type: "dropdown",
        title: "How long have you been reading us?",
        required: true,
        options: [
          { label: "This is one of my first issues" },
          { label: "Less than a year" },
          { label: "1 to 3 years" },
          { label: "More than 3 years" },
        ],
      },
      {
        ref: "how_much",
        type: "single_select",
        title: "How much of an issue do you usually read?",
        required: true,
        options: [
          { label: "Nearly all of it" },
          { label: "About half" },
          { label: "A few pieces that catch my eye" },
          { label: "Very little" },
        ],
      },
      {
        ref: "sections",
        type: "matrix",
        title: "How often do you read each section?",
        required: false,
        rows: ["News and short reads", "Long features", "Interviews", "Reviews", "How-to guides", "Opinion columns"],
        columns: ["Always", "Sometimes", "Rarely", "Skip it"],
      },
      {
        ref: "more_of",
        type: "multi_select",
        title: "Which topics would you like to see more of?",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "Practical advice" },
          { label: "In-depth investigations" },
          { label: "People and profiles" },
          { label: "Trends and what's next" },
          { label: "Local stories" },
          { label: "Reader contributions" },
        ],
      },
      {
        ref: "overall",
        type: "rating",
        title: "Overall, how would you rate the magazine right now?",
        required: true,
        scale: 5,
      },
      {
        ref: "favourite_piece",
        type: "long_text",
        title: "Which recent piece stayed with you, and why?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "disappoints",
        type: "long_text",
        title: "What's letting the magazine down for you at the moment?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "keep_reading",
        type: "single_select",
        title: "How likely are you to keep reading over the next year?",
        required: true,
        options: [
          { label: "Definitely" },
          { label: "Probably" },
          { label: "Not sure" },
          { label: "Probably not" },
        ],
      },
      {
        ref: "one_change",
        type: "short_text",
        title: "If you were editor for a day, what's the one thing you'd change?",
        required: false,
        maxLength: 300,
      },
    ],
    branches: [
      { when: "overall", op: "lte", is: 3, then: "disappoints" },
      { when: "favourite_piece", always: true, then: "keep_reading" },
    ],
    ending: {
      title: "Thank you, the editors will read this 📖",
      body: "Reader answers go straight into planning the next issues.",
    },
    guide: {
      questionsToConsider: [
        "Do the section names in the grid match what readers see on your contents page?",
        "Are you deciding something specific, like dropping a section or changing frequency, that deserves its own question?",
        "Should print and digital readers be asked different questions about the reading experience?",
        "Do you want readers to be able to volunteer for interviews or contribute stories?",
      ],
      howToUseResponses:
        "Read the section grid first: sections most readers skip are candidates for a rethink, and those read by long-time readers but skipped by new ones may need a better introduction. Put the favourite pieces and the disappointments side by side, since the patterns in each tell editors what to do more and less of. Keep an eye on readers who say they probably will not keep reading and what they wrote about why.",
      customizeSteps: [
        "Rename the grid rows to your real sections and adjust the topics list to your beat.",
        "Change the format options to the ways your magazine is actually published, such as a newsletter edition or podcast.",
        "Put the link in the next issue, on the website and in subscriber emails, then compare answers from print and digital readers in the dashboard.",
      ],
      faqs: [
        {
          q: "What should a magazine reader survey ask?",
          a: "How people read, how much of each issue they get through, which sections they read or skip, what they want more of, and whether they plan to keep reading.",
        },
        {
          q: "How often should a magazine run a reader survey?",
          a: "Once a year is enough for most publications, plus a short one when you are about to make a big change such as a redesign.",
        },
        {
          q: "How do I get more readers to respond?",
          a: "Tell them their answers will shape the next issues, keep it short and share the link in several places. A chat that asks one question at a time also feels less like homework.",
        },
        {
          q: "Can I use this survey for a newsletter or blog?",
          a: "Yes, with a few edits to the format and section names. For email newsletters there is also a dedicated newsletter feedback survey.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "market-segmentation-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["marketing", "product-research"],
    searchName: "Market segmentation survey",
    title: "Market segmentation survey",
    icon: "PieChart",
    metaDescription:
      "Group your audience by needs, habits and buying behaviour, not labels alone. Asks about goals, current solutions and attitudes, with background questions last.",
    description: "Find meaningful groups in your audience based on needs and behaviour.",
    blurb:
      "Segments built only on age or job title rarely predict what people buy. This survey asks about needs first: the problem, how often it happens, what people use today and how they choose, with background questions saved for the end. People already using something rate it, and people using nothing are asked why, which often reveals a segment of its own.",
    tags: ["market segmentation survey", "customer segmentation", "needs-based segmentation", "audience research", "buyer personas"],
    greeting: "Hi! We're trying to understand the different kinds of people we could help. This takes about four minutes.",
    questions: [
      {
        ref: "main_goal",
        type: "ranking",
        title: "Rank these goals by how important they are to you right now.",
        description: "Replace these with the goals your product or service helps with.",
        required: true,
        items: ["Saving time", "Saving money", "Getting better results", "Reducing stress", "Learning something new"],
      },
      {
        ref: "problem_frequency",
        type: "single_select",
        title: "How often do you run into the problem you'd most like solved?",
        required: true,
        options: [{ label: "Every day" }, { label: "Every week" }, { label: "Every month or so" }, { label: "Rarely" }],
      },
      {
        ref: "current_solution",
        type: "single_select",
        title: "How do you deal with it today?",
        required: true,
        options: [
          { label: "A paid product or service" },
          { label: "A free tool or app" },
          { label: "Spreadsheets or my own system" },
          { label: "Someone else does it for me" },
          { label: "Nothing, I manage without" },
        ],
      },
      {
        ref: "current_satisfaction",
        type: "rating",
        title: "How well does that work for you?",
        required: true,
        scale: 5,
      },
      {
        ref: "why_nothing",
        type: "long_text",
        title: "What's stopped you from using something for it?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "how_choose",
        type: "single_select",
        title: "When you buy something like this, which sounds most like you?",
        required: true,
        options: [
          { label: "I research a lot and compare options" },
          { label: "I go with what people I trust recommend" },
          { label: "I pick the cheapest that does the job" },
          { label: "I pay more for the best quality" },
          { label: "I buy quickly and switch if it doesn't work" },
        ],
      },
      {
        ref: "attitudes",
        type: "matrix",
        title: "How much do you agree with each statement?",
        required: false,
        rows: [
          "I like trying new products early",
          "I'd pay more to save time",
          "I prefer to do things myself",
          "Price is usually the deciding factor",
        ],
        columns: ["Disagree", "Neutral", "Agree"],
      },
      {
        ref: "willingness",
        type: "opinion_scale",
        title: "How much would a better solution be worth to you?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not much",
        labelHigh: "A lot",
      },
      {
        ref: "age_range",
        type: "dropdown",
        title: "A little background: which age group are you in?",
        required: false,
        options: [
          { label: "18 to 24" },
          { label: "25 to 34" },
          { label: "35 to 44" },
          { label: "45 to 54" },
          { label: "55 to 64" },
          { label: "65 or over" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "situation",
        type: "single_select",
        title: "Which best describes your situation?",
        required: false,
        options: [
          { label: "Employed" },
          { label: "Self-employed or running a business" },
          { label: "Student" },
          { label: "Not working right now" },
          { label: "Retired" },
        ],
      },
      {
        ref: "region",
        type: "short_text",
        title: "Which country or region do you live in?",
        required: false,
        maxLength: 100,
      },
    ],
    branches: [
      { when: "current_solution", is: "Nothing, I manage without", then: "why_nothing" },
      { when: "current_satisfaction", always: true, then: "how_choose" },
    ],
    ending: {
      title: "Thank you, this really helps",
      body: "Your answers are combined with everyone else's, and never shared in a way that identifies you.",
    },
    guide: {
      questionsToConsider: [
        "Which goals and problems does your product actually address, and are they in the ranking?",
        "What decision will the segments inform: messaging, pricing, product focus or who to target first?",
        "Which background questions do you truly need, and which just add length?",
        "Are the attitude statements ones that would split your audience, or would everyone agree with them?",
      ],
      howToUseResponses:
        "Look for groups that differ in what they need and how they buy, not just who they are: for example, frequent sufferers who already pay for a solution and are unhappy with it, versus occasional sufferers who manage without. Export the responses to CSV and cross-tabulate goals, current solution and buying style before bringing in age or situation. A segment is only useful if you could reach it and would treat it differently.",
      customizeSteps: [
        "Rewrite the goals and the problem question around what your product helps with, keeping the options in plain language.",
        "Edit the attitude statements so each one would genuinely divide your audience.",
        "Share it with a broad sample, not only existing customers, and export to CSV when you have enough responses to compare groups.",
      ],
      faqs: [
        {
          q: "What is a market segmentation survey?",
          a: "A survey that collects needs, behaviour, attitudes and background so you can split a market into groups that want different things and can be reached in different ways.",
        },
        {
          q: "What questions should a segmentation survey ask?",
          a: "Goals and problems, how often they occur, what people use today, how they make buying decisions, attitude statements and a few background questions. Needs and behaviour usually matter more than demographics.",
        },
        {
          q: "Why are the demographic questions at the end?",
          a: "People answer more thoughtfully about their needs when they have not just been asked to put themselves in a box. Background questions are also optional here, which keeps more people going.",
        },
        {
          q: "How many responses do I need for segmentation?",
          a: "It depends on how many groups you expect and how different they are. A small sample can suggest segments worth exploring, but confirming them takes a larger and broader one.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "media-usage-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["marketing", "product-research"],
    searchName: "Media usage survey",
    title: "Media habits survey",
    icon: "MonitorPlay",
    metaDescription:
      "Find out which channels your audience uses for news and entertainment, how often and why. Covers trust, paid subscriptions and how people feel about ads.",
    description: "Learn where your audience gets news and entertainment, and why they choose each channel.",
    blurb:
      "Useful for planning where to advertise, publish or partner. It maps which channels people use and how often, why they turn to media at all and which sources they trust, then asks whether they pay for any subscriptions, with a follow-up only for those who do.",
    tags: ["media usage survey", "media consumption survey", "media habits", "audience research", "channel planning"],
    greeting: "Hi! We're curious how you keep up with news and entertainment. A few quick questions.",
    questions: [
      {
        ref: "channel_frequency",
        type: "matrix",
        title: "How often do you use each of these?",
        required: true,
        rows: [
          "Social media",
          "Video streaming services",
          "YouTube or other online video",
          "Podcasts",
          "Radio",
          "TV",
          "News websites or apps",
          "Email newsletters",
          "Printed newspapers or magazines",
        ],
        columns: ["Daily", "Weekly", "Rarely", "Never"],
      },
      {
        ref: "daily_time",
        type: "single_select",
        title: "On a typical day, how much time do you spend with media of any kind?",
        required: true,
        options: [
          { label: "Less than 1 hour" },
          { label: "1 to 3 hours" },
          { label: "3 to 5 hours" },
          { label: "More than 5 hours" },
        ],
      },
      {
        ref: "reasons",
        type: "ranking",
        title: "Rank why you turn to media, most important first.",
        required: true,
        items: ["Staying informed", "Entertainment", "Learning something", "Relaxing", "Keeping up with friends", "Work"],
      },
      {
        ref: "news_source",
        type: "dropdown",
        title: "Where do you get most of your news?",
        required: true,
        options: [
          { label: "Social media" },
          { label: "News websites or apps" },
          { label: "TV" },
          { label: "Radio" },
          { label: "Podcasts" },
          { label: "Newsletters" },
          { label: "Print" },
          { label: "Friends and family" },
          { label: "I don't really follow the news" },
        ],
      },
      {
        ref: "trust",
        type: "opinion_scale",
        title: "How much do you trust the news you come across online?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not at all",
        labelHigh: "Completely",
      },
      {
        ref: "devices",
        type: "multi_select",
        title: "Which devices do you use for media most?",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        options: [
          { label: "Phone" },
          { label: "Laptop or computer" },
          { label: "Tablet" },
          { label: "TV" },
          { label: "Smart speaker" },
          { label: "Car radio" },
        ],
      },
      {
        ref: "pays",
        type: "yes_no",
        title: "Do you pay for any media subscriptions right now?",
        required: true,
      },
      {
        ref: "paid_for",
        type: "multi_select",
        title: "Which kinds?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        options: [
          { label: "Video streaming" },
          { label: "Music streaming" },
          { label: "News" },
          { label: "Magazines" },
          { label: "Podcasts or audiobooks" },
          { label: "A creator I follow" },
        ],
      },
      {
        ref: "ads",
        type: "single_select",
        title: "Which sounds closest to how you feel about ads?",
        required: true,
        options: [
          { label: "Fine if they're relevant" },
          { label: "I tolerate them for free content" },
          { label: "I avoid them whenever I can" },
          { label: "I'd pay to never see them" },
        ],
      },
      {
        ref: "discovered",
        type: "long_text",
        title: "What's the last show, podcast, channel or publication you discovered, and how did you find it?",
        required: false,
        maxLength: 500,
      },
    ],
    branches: [{ when: "pays", is: false, then: "ads" }],
    ending: {
      title: "Thanks for sharing your habits",
      body: "Your answers help us decide where and how to reach people like you.",
    },
    guide: {
      questionsToConsider: [
        "Which channels are you actually choosing between for your next campaign or content plan?",
        "Do you need to know about news specifically, or is entertainment the focus?",
        "Should the channel list include platforms specific to your region or industry?",
        "Is attitude to ads relevant, or would you rather ask about sponsored content or influencers?",
      ],
      howToUseResponses:
        "Use the frequency grid to see which channels your audience touches daily, then weigh that against why they use media: a channel people use to relax is a different place to reach them than one they use for work. Compare trust and ad attitudes across heavy and light users. The answers about recent discoveries are often the clearest clue to which channels actually lead people to something new.",
      customizeSteps: [
        "Edit the grid rows so they list the channels you are deciding between, and remove any you would never use.",
        "Add a question naming specific publications, shows or creators if you are choosing partners.",
        "Share it with your audience or a panel, and export to CSV to compare channel habits by age or other segments.",
      ],
      faqs: [
        {
          q: "What is a media usage survey?",
          a: "A survey that asks which media channels people use, how often, on which devices and why. It helps marketers and publishers decide where to spend time and budget.",
        },
        {
          q: "What questions should a media consumption survey include?",
          a: "Channel use and frequency, daily time spent, reasons for using media, main news source, trust, devices, subscriptions and attitudes to advertising.",
        },
        {
          q: "Why use a grid for channel frequency?",
          a: "It gathers answers for many channels in one question, which keeps the survey short and makes channels easy to compare in the results.",
        },
        {
          q: "Can I use this for a school or research project?",
          a: "Yes. Copy it, edit the channels and wording for your group and share the link. You can read every response in the dashboard or export them to CSV.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "meeting-feedback-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback"],
    roles: ["operations", "hr-people"],
    searchName: "Meeting feedback survey",
    title: "Meeting feedback",
    icon: "MessagesSquare",
    metaDescription:
      "Ask attendees whether a meeting was worth their time, had a clear purpose and ended with clear next steps. Low scores and unclear actions get their own follow-ups.",
    description: "Find out whether a meeting was worth it and what would make the next one better.",
    blurb:
      "A short check to send right after a meeting. It rates purpose, participation, timekeeping and decisions in one grid, then asks whether it was worth the time: anyone who says no is asked how it could have worked better. Anyone unsure of the next steps is asked what is unclear, so it can be fixed before work stalls.",
    tags: ["meeting feedback survey", "meeting effectiveness", "post-meeting survey", "team meetings", "meeting evaluation"],
    greeting: "Thanks for joining the meeting. Two minutes to help make the next one better?",
    questions: [
      {
        ref: "meeting",
        type: "short_text",
        title: "Which meeting are you giving feedback on?",
        required: true,
        maxLength: 150,
      },
      {
        ref: "your_role",
        type: "single_select",
        title: "What was your part in it?",
        required: true,
        options: [{ label: "I ran it" }, { label: "I presented" }, { label: "I took part" }, { label: "I mostly listened" }],
      },
      {
        ref: "aspects",
        type: "matrix",
        title: "How did the meeting do on each of these?",
        required: true,
        rows: [
          "Clear purpose",
          "The right people were there",
          "Started and ended on time",
          "Everyone could speak",
          "Decisions were made",
        ],
        columns: ["Poor", "Okay", "Good"],
      },
      {
        ref: "worth_time",
        type: "opinion_scale",
        title: "Was the meeting worth your time?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not at all",
        labelHigh: "Completely",
      },
      {
        ref: "better_format",
        type: "single_select",
        title: "What would have worked better?",
        required: true,
        allowOther: true,
        options: [
          { label: "An email or written update" },
          { label: "A shorter meeting" },
          { label: "Fewer people" },
          { label: "A clearer agenda sent beforehand" },
          { label: "I didn't need to be there" },
        ],
      },
      {
        ref: "next_steps_clear",
        type: "yes_no",
        title: "Do you know what you need to do next as a result?",
        required: true,
      },
      {
        ref: "unclear",
        type: "long_text",
        title: "What's unclear about the next steps?",
        required: true,
        maxLength: 500,
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "What's one thing that would make the next meeting better?",
        required: false,
        maxLength: 500,
      },
    ],
    branches: [
      { when: "worth_time", op: "gte", is: 3, then: "next_steps_clear" },
      { when: "next_steps_clear", is: true, then: "one_change" },
    ],
    ending: {
      title: "Thanks, noted for next time",
      body: "The organiser will see your answers and follow up on anything that's unclear.",
    },
    guide: {
      questionsToConsider: [
        "Should the form be anonymous so people feel free to say a meeting was not worth it?",
        "Which meetings are worth surveying: recurring ones, all-hands, or client meetings?",
        "Do the grid rows match what you want from this meeting, such as brainstorming rather than decisions?",
        "Who follows up when someone says the next steps are unclear?",
      ],
      howToUseResponses:
        "Act on unclear next steps the same day by sending a short written summary of who does what. For recurring meetings, watch the worth-your-time score across weeks and read what people say would work better: repeated votes for a written update suggest the meeting could become one. Look at the grid by role, since presenters and listeners often experience the same meeting very differently.",
      customizeSteps: [
        "Change the grid rows to match the meeting's purpose, and remove the role question if everyone plays the same part.",
        "Prefill the meeting name from the link with a URL parameter so attendees don't have to type it each time.",
        "Send the link at the end of the meeting or in the calendar follow-up, and review responses in the dashboard before the next one.",
      ],
      faqs: [
        {
          q: "What questions should I ask after a meeting?",
          a: "Whether it had a clear purpose, the right people and enough time to speak, whether it was worth attending, and whether everyone knows their next steps.",
        },
        {
          q: "Should meeting feedback be anonymous?",
          a: "For internal meetings, usually yes. People are more honest about wasted time when their name is not attached. Keep the meeting name so you can still compare sessions.",
        },
        {
          q: "When should I send a meeting feedback survey?",
          a: "Within an hour of the meeting ending, while details are fresh. For a weekly meeting, asking every few weeks avoids survey fatigue.",
        },
        {
          q: "How do I measure meeting effectiveness?",
          a: "Track how many people say it was worth their time and how many leave with clear next steps. Both are easy to compare from one meeting to the next.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "mystery-shopper-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["operations", "customer-success"],
    searchName: "Mystery shopper survey",
    title: "Mystery shopper report",
    icon: "Search",
    metaDescription:
      "A structured report for mystery shoppers: visit details, greeting, store condition, staff knowledge, stock and checkout, with photo uploads and factual notes.",
    description: "Give mystery shoppers a clear, factual way to report each visit.",
    blurb:
      "Written for the shopper to fill in straight after a visit, with questions that ask what happened rather than how it felt. In-store visits get a question about the shop's condition that phone and online visits skip, and a missing item prompts a follow-up about what was offered instead. Photos of receipts or displays can be attached as evidence.",
    tags: ["mystery shopper survey", "mystery shopping form", "store audit", "customer experience audit", "retail evaluation"],
    greeting: "Thanks for completing this visit. Please fill this in as soon as you can, while the details are fresh.",
    questions: [
      {
        ref: "shopper",
        type: "contact_info",
        title: "Your details",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
      {
        ref: "location",
        type: "short_text",
        title: "Which store or branch did you visit?",
        required: true,
        maxLength: 150,
      },
      {
        ref: "visit_time",
        type: "date",
        title: "When did the visit take place?",
        required: true,
        includeTime: true,
      },
      {
        ref: "visit_channel",
        type: "single_select",
        title: "How did you contact the business?",
        required: true,
        options: [{ label: "In store" }, { label: "By phone" }, { label: "Online chat or website" }],
      },
      {
        ref: "store_condition",
        type: "matrix",
        title: "How did the store look?",
        required: true,
        rows: ["Entrance and windows", "Shelves and displays", "Floors and aisles", "Fitting rooms or seating", "Checkout area"],
        columns: ["Poor", "Acceptable", "Good", "Not applicable"],
      },
      {
        ref: "greeted",
        type: "single_select",
        title: "How soon were you greeted or answered?",
        required: true,
        options: [
          { label: "Straight away" },
          { label: "Within a couple of minutes" },
          { label: "After a long wait" },
          { label: "Not at all" },
        ],
      },
      {
        ref: "staff_knowledge",
        type: "rating",
        title: "How well could staff answer your questions about the product?",
        required: true,
        scale: 5,
      },
      {
        ref: "item_found",
        type: "yes_no",
        title: "Was the item you asked about available?",
        required: true,
      },
      {
        ref: "alternative_offered",
        type: "single_select",
        title: "What did staff do when it wasn't available?",
        required: true,
        options: [
          { label: "Offered to order it" },
          { label: "Suggested an alternative" },
          { label: "Told me to check back later" },
          { label: "Nothing" },
        ],
      },
      {
        ref: "checkout",
        type: "rating",
        title: "How smooth was the checkout or next step?",
        required: true,
        scale: 5,
      },
      {
        ref: "observations",
        type: "long_text",
        title: "Describe the visit in your own words, sticking to what you saw and heard.",
        description: "Include staff names or descriptions, times and anything that stood out.",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "evidence",
        type: "file_upload",
        title: "Upload your receipt and any photos you took.",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 5,
        maxSizeMB: 10,
      },
      {
        ref: "overall",
        type: "opinion_scale",
        title: "Overall, how close was the visit to the standard you were briefed on?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Far below",
        labelHigh: "Fully met",
      },
    ],
    branches: [
      { when: "visit_channel", is: "By phone", then: "greeted" },
      { when: "visit_channel", is: "Online chat or website", then: "greeted" },
      { when: "item_found", is: true, then: "checkout" },
    ],
    ending: {
      title: "Report received, thank you",
      body: "We'll review it and be in touch if anything needs clarifying.",
    },
    guide: {
      questionsToConsider: [
        "What standards were shoppers briefed on, and does each one have a matching question?",
        "Which store areas belong in the condition grid for your type of business?",
        "Do you want receipts as proof of visit, and how will you handle any personal details on them?",
        "Should shoppers name staff, or describe them, given your policies?",
      ],
      howToUseResponses:
        "Compare reports across branches and visit times rather than reacting to a single visit, since one bad afternoon is not a pattern. Look at greeting times, stock availability and what staff did when an item was missing, which are the most coachable moments. Share specific, factual observations with store managers, and use the overall score against the brief to track each location over time.",
      customizeSteps: [
        "Edit the questions so they match your brief exactly, and replace the store-condition rows with your own checklist.",
        "Add the store or branch as a URL parameter in each shopper's link so it arrives prefilled.",
        "Send each shopper their link before the visit, then export reports to CSV to compare branches side by side.",
      ],
      faqs: [
        {
          q: "What should a mystery shopper survey include?",
          a: "Visit details, how quickly the shopper was greeted, store condition, staff knowledge, product availability, the checkout and a factual written account, with space for receipts or photos.",
        },
        {
          q: "How do I keep mystery shopper reports objective?",
          a: "Ask what happened, not how it felt: times, actions and what staff said. Rating questions work best when the scale is tied to the standard the shopper was briefed on.",
        },
        {
          q: "Can mystery shoppers upload receipts and photos?",
          a: "Yes. This template includes an upload question that accepts images and PDFs, so shoppers can attach proof of visit and any photos they are allowed to take.",
        },
        {
          q: "Does it work for phone or online mystery shopping?",
          a: "Yes. Choosing a phone or online visit skips the question about the store's condition, and the rest of the report still applies.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "newsletter-feedback-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback"],
    roles: ["marketing"],
    searchName: "Newsletter feedback survey",
    title: "Newsletter feedback",
    icon: "Mail",
    metaDescription:
      "Ask subscribers which parts of your newsletter they read, how often they want it and what would improve it. Occasional readers are asked what stops them opening it.",
    description: "Find out whether your newsletter is useful and what would keep people reading.",
    blurb:
      "A short survey to send your subscribers. It asks how they read the newsletter, and the answer decides the next question: engaged readers name their favourite part, while people who open it only now and then, or rarely, are asked what stops them. Everyone then weighs in on frequency, length and topics, and gets a chance to recommend it.",
    tags: ["newsletter feedback survey", "email newsletter survey", "subscriber survey", "reader feedback", "email marketing"],
    greeting: "Hi! You get our newsletter, and we want to make it worth opening. Got a minute?",
    questions: [
      {
        ref: "read_habit",
        type: "single_select",
        title: "How do you usually read the newsletter?",
        required: true,
        options: [
          { label: "I read most of every issue" },
          { label: "I skim for what interests me" },
          { label: "I open it now and then" },
          { label: "I rarely open it" },
        ],
      },
      {
        ref: "favourite",
        type: "long_text",
        title: "Which part do you look forward to most?",
        required: false,
        maxLength: 400,
      },
      {
        ref: "rarely_why",
        type: "multi_select",
        title: "What usually stops you opening it?",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "It arrives too often" },
          { label: "The topics aren't relevant to me" },
          { label: "It's too long" },
          { label: "The subject lines don't grab me" },
          { label: "My inbox is just too full" },
        ],
      },
      {
        ref: "usefulness",
        type: "rating",
        title: "How useful is the newsletter to you?",
        required: true,
        scale: 5,
      },
      {
        ref: "frequency",
        type: "single_select",
        title: "How often would you like to hear from us?",
        required: true,
        options: [
          { label: "More often" },
          { label: "About the same as now" },
          { label: "Less often" },
        ],
      },
      {
        ref: "length",
        type: "opinion_scale",
        title: "How do you feel about the length?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Too short",
        labelHigh: "Too long",
      },
      {
        ref: "more_topics",
        type: "multi_select",
        title: "What would you like more of?",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "Practical tips" },
          { label: "News and updates" },
          { label: "Stories and case studies" },
          { label: "Recommended links and reading" },
          { label: "Offers and early access" },
          { label: "Behind the scenes" },
        ],
      },
      {
        ref: "recommend",
        type: "nps",
        title: "How likely are you to recommend the newsletter to a friend?",
        required: true,
      },
      {
        ref: "suggestion",
        type: "long_text",
        title: "Anything else that would make it better?",
        required: false,
        maxLength: 600,
      },
    ],
    branches: [
      { when: "read_habit", is: "I open it now and then", then: "rarely_why" },
      { when: "read_habit", is: "I rarely open it", then: "rarely_why" },
      { when: "favourite", always: true, then: "usefulness" },
    ],
    ending: {
      title: "Thanks for helping us improve ✉️",
      body: "We'll use your answers to shape the next issues.",
    },
    guide: {
      questionsToConsider: [
        "Which sections or regular features should readers be able to name or rate?",
        "Are you considering a change in frequency or format that you want readers to weigh in on first?",
        "Should the topics list reflect what you could realistically write more of?",
        "Do you want to send it to everyone, or only to people who have been subscribed for a while?",
      ],
      howToUseResponses:
        "Compare the frequency and length answers between engaged readers and those who rarely open it, because they often want opposite things. The reasons people give for not opening are the most actionable part: a pile of votes for subject lines is a quick fix, while irrelevant topics may mean splitting the list. Use the favourite parts to decide what to keep, and repeat the survey after a change to see if it helped.",
      customizeSteps: [
        "Replace the topic options with the kinds of content you actually publish, and name your regular sections in the favourite-part question if you like.",
        "Add the subscriber's list or segment as a URL parameter so you can compare answers across audiences.",
        "Put the link in an issue with a line explaining why you are asking, and read results in the dashboard before planning the next issues.",
      ],
      faqs: [
        {
          q: "What questions should I ask in a newsletter feedback survey?",
          a: "How people read it, which parts they value, how useful it is, how often and how long they want it, what topics they want more of and whether they would recommend it.",
        },
        {
          q: "How do I get subscribers to answer a newsletter survey?",
          a: "Put the link near the top of an issue, keep it to a minute or two and say what you will do with the answers. Sharing the results in a later issue earns more replies next time.",
        },
        {
          q: "How often should I survey newsletter readers?",
          a: "Once or twice a year is plenty, plus a quick check after a big change to the format or schedule.",
        },
        {
          q: "Why ask people who rarely open it?",
          a: "They are the readers you are losing. This survey asks them what stops them opening it, which is usually more useful than hearing from fans alone.",
        },
      ],
    },
  }),
];
