import { defineTemplate, type TemplateSeed } from "../define.js";

export const SURVEY_MARKETING_3: TemplateSeed[] = [
  defineTemplate({
    slug: "online-community-needs-assessment-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["marketing", "customer-success"],
    searchName: "Online community needs assessment survey",
    title: "Community needs assessment",
    icon: "Users",
    metaDescription:
      "Ask members what they joined for, what they want more of and what stops them taking part. Members who offer to help get their own follow-up and sign-off.",
    description: "Find out what members need before you plan the next event, channel or program.",
    blurb:
      "Starts with how long someone has been around and how they take part, so a quiet lurker and a daily poster can be read separately. Members who feel they don't belong are asked what would change that, and anyone who offers to help run something is asked for an email and gets their own thank-you.",
    tags: ["community survey", "needs assessment", "member survey", "online community", "community manager"],
    greeting: "You make this community what it is. Help us decide what to build next? It takes about four minutes.",
    questions: [
      {
        ref: "member_length",
        type: "single_select",
        title: "How long have you been part of the community?",
        required: true,
        options: [{ label: "Less than a month" }, { label: "1–6 months" }, { label: "6–12 months" }, { label: "More than a year" }],
      },
      {
        ref: "participation",
        type: "single_select",
        title: "Which of these sounds most like you?",
        required: true,
        options: [
          { label: "I mostly read" },
          { label: "I post or comment now and then" },
          { label: "I'm in most conversations" },
          { label: "I host or help run things" },
        ],
      },
      {
        ref: "reasons",
        type: "multi_select",
        title: "What did you join for? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 7,
        allowOther: true,
        options: [
          { label: "Learning from people who've done it" },
          { label: "Getting help with a specific problem" },
          { label: "Meeting people in my field" },
          { label: "Sharing my own work" },
          { label: "Finding jobs, clients or collaborators" },
          { label: "Keeping up with news" },
        ],
      },
      {
        ref: "needs_met",
        type: "matrix",
        title: "How well does the community meet each of these needs today?",
        required: false,
        rows: ["Getting answers to questions", "Meeting new people", "Learning new skills", "Feeling welcome as a newcomer"],
        columns: ["Not at all", "Somewhat", "Well", "Very well"],
      },
      {
        ref: "priorities",
        type: "ranking",
        title: "If we could add more of one thing, what should it be? Put your top pick first.",
        required: true,
        items: [
          "Live events and workshops",
          "Q&A sessions with experts",
          "A library of guides and resources",
          "Small peer groups",
          "A board for jobs and projects",
          "Member spotlights",
        ],
      },
      {
        ref: "barriers",
        type: "multi_select",
        title: "What makes it harder to take part?",
        required: true,
        minSelections: 1,
        maxSelections: 7,
        allowOther: true,
        options: [
          { label: "Not enough time" },
          { label: "Events are at a bad time for my time zone" },
          { label: "Hard to find conversations that matter to me" },
          { label: "I feel nervous posting" },
          { label: "Too many notifications" },
          { label: "Nothing, I take part as much as I want" },
        ],
      },
      {
        ref: "belonging",
        type: "opinion_scale",
        title: "How much do you feel you belong here?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Like an outsider",
        labelHigh: "Right at home",
      },
      {
        ref: "belong_more",
        type: "long_text",
        title: "What would help you feel more at home here?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "one_thing",
        type: "long_text",
        title: "If you could add one thing to the community tomorrow, what would it be?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "help_out",
        type: "yes_no",
        title: "Would you be up for helping run something, like hosting a session or welcoming new members?",
        required: true,
      },
      {
        ref: "volunteer_email",
        type: "email",
        title: "Great! What's the best email to reach you on?",
        required: true,
      },
    ],
    branches: [
      { when: "belonging", op: "lte", is: 2, then: "belong_more" },
      { when: "belonging", op: "gte", is: 3, then: "one_thing" },
      { when: "help_out", is: false, then: "end_thanks" },
      { when: "volunteer_email", always: true, then: "end_volunteer" },
    ],
    endings: [
      {
        ref: "end_volunteer",
        title: "You're a star 🙌",
        body: "Thanks for offering to help. Someone from the team will email you within a week to talk about what you'd enjoy running.",
      },
    ],
    ending: {
      title: "Thank you for helping shape the community",
      body: "We'll share what we heard and what we're planning next with all members.",
    },
    guide: {
      questionsToConsider: [
        "Do you want to hear from quiet readers as much as active posters, and how will you reach the ones who never open announcements?",
        "Which options in the priorities list can you actually deliver in the next six months?",
        "Should newcomers and long-time members get the same survey, or does one group need extra questions?",
        "Who will follow up with the members who volunteer, and how quickly?",
      ],
      howToUseResponses:
        "Split the answers by how long people have been members and how they take part, because newcomers and hosts often want different things. Treat the barriers question separately from the wishlist: a time-zone or confidence problem is about access, and fixing it can matter more than the most popular new idea. Post a short summary back to the community saying what you will do first and why.",
      customizeSteps: [
        "Replace the ranking items with activities you could realistically launch, and remove any you can't staff.",
        "Adjust the participation options to match your platform, such as a forum, a chat server or a paid membership.",
        "Share the link in your main channel and send it by direct message to quieter members, so the results aren't only the loudest voices.",
      ],
      faqs: [
        {
          q: "What is a community needs assessment survey?",
          a: "It asks members what they need from a community, what stops them taking part and what they'd like added. You run it before deciding on new events, content or programs.",
        },
        {
          q: "Who should answer a community needs survey?",
          a: "Current members first, including the ones who only read. If you are trying to reach a new group, invite them too and keep their answers separate.",
        },
        {
          q: "How often should I run a community needs assessment?",
          a: "Once a year works for most communities, plus a shorter check after a big change such as a new platform or a new membership tier.",
        },
        {
          q: "Can I make the survey anonymous?",
          a: "Yes. Only members who offer to volunteer are asked for an email, so everyone else can answer without leaving contact details.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "path-to-purchase-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["marketing", "product-research", "sales"],
    searchName: "Path to purchase survey",
    title: "Path to purchase",
    icon: "ShoppingCart",
    metaDescription:
      "Trace how a recent customer went from noticing a need to buying: what triggered it, where they researched, what they compared and what almost stopped them.",
    description: "Map the steps real customers took from first need to final purchase.",
    blurb:
      "Anchored on one recent purchase, so customers describe what they actually did rather than what they usually do. People who seriously considered a competitor are asked what tipped them your way, and everyone ranks the factors that decided it.",
    tags: ["path to purchase", "customer journey survey", "buyer journey", "purchase decision", "marketing research"],
    greeting: "Thanks for your recent purchase! We'd love to hear how you got here. It's about three minutes.",
    questions: [
      {
        ref: "purchase",
        type: "short_text",
        title: "What did you buy from us most recently?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "trigger",
        type: "single_select",
        title: "What first made you start looking for it?",
        required: true,
        allowOther: true,
        options: [
          { label: "Something I had broke or ran out" },
          { label: "A new need or a change in my life or work" },
          { label: "Someone recommended it" },
          { label: "I saw it in an ad or a post" },
          { label: "I was just browsing" },
        ],
      },
      {
        ref: "discovery",
        type: "single_select",
        title: "Where did you first come across us?",
        required: true,
        allowOther: true,
        options: [
          { label: "Search engine" },
          { label: "Social media" },
          { label: "A friend or colleague" },
          { label: "A review or comparison site" },
          { label: "In a shop" },
          { label: "An ad" },
        ],
      },
      {
        ref: "research_sources",
        type: "multi_select",
        title: "Where did you look for information before deciding? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 8,
        options: [
          { label: "Our website" },
          { label: "Customer reviews" },
          { label: "Comparison sites" },
          { label: "Social media or forums" },
          { label: "Asked friends or family" },
          { label: "Saw it in a shop" },
          { label: "Videos" },
          { label: "I didn't research" },
        ],
      },
      {
        ref: "decision_time",
        type: "single_select",
        title: "From first looking to buying, how long did it take?",
        required: true,
        options: [{ label: "The same day" }, { label: "A few days" }, { label: "1–4 weeks" }, { label: "More than a month" }],
      },
      {
        ref: "compared",
        type: "yes_no",
        title: "Did you seriously consider buying from someone else?",
        required: true,
      },
      {
        ref: "alternatives",
        type: "long_text",
        title: "Who else were you considering, and what made you pick us in the end?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "deciding_factors",
        type: "ranking",
        title: "Put these in order of how much they mattered to your final decision.",
        required: true,
        items: ["Price", "Quality", "Reviews", "Delivery speed", "Trust in the brand", "Returns policy"],
      },
      {
        ref: "where_bought",
        type: "single_select",
        title: "Where did you complete the purchase?",
        required: true,
        options: [{ label: "Our website" }, { label: "Our app" }, { label: "In a shop" }, { label: "An online marketplace" }, { label: "By phone" }],
      },
      {
        ref: "info_ease",
        type: "opinion_scale",
        title: "How easy was it to find the information you needed to decide?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Very hard",
        labelHigh: "Very easy",
      },
      {
        ref: "hesitation",
        type: "long_text",
        title: "Was anything close to stopping you from buying?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [{ when: "compared", is: false, then: "deciding_factors" }],
    ending: {
      title: "Thanks, that's really useful",
      body: "Your answers help us make the next person's decision easier.",
    },
    guide: {
      questionsToConsider: [
        "Which purchase should people answer about? Naming the product, or passing it in with the link, gives far more accurate answers.",
        "Do you sell online, in shops or both? Trim the channel options so every choice is one a customer could really have used.",
        "Which competitors would you like named? Leave the question open if you'd rather not put names in front of customers.",
        "How soon after purchase will you send it, so the decision is still fresh?",
      ],
      howToUseResponses:
        "Lay the answers out as a sequence: trigger, first contact, research, comparison, purchase. Look for the step where the most people say information was hard to find, and fix the content there first. Read the answers about competitors and hesitation together, since they tell you what your pages need to address before a buyer has to ask.",
      customizeSteps: [
        "Edit the discovery and research options to match the channels you actually market on.",
        "Add the product or order as a hidden field from your order email so the first question can be skipped or prefilled.",
        "Send the link within a week of purchase, in the order confirmation or a follow-up email.",
      ],
      faqs: [
        {
          q: "What is a path to purchase survey?",
          a: "It asks recent buyers how they got from noticing a need to buying: what set it off, where they looked, what they compared and why they chose you.",
        },
        {
          q: "When should I send a path to purchase survey?",
          a: "Within a week or two of the purchase. After that, people remember the product better than the decision.",
        },
        {
          q: "What is the difference between a path to purchase and a customer journey?",
          a: "The path to purchase covers the steps up to buying. A customer journey also covers what happens afterwards, such as delivery, support and repeat purchases.",
        },
        {
          q: "Should I ask people who didn't buy?",
          a: "It helps, but it is a different survey. Buyers explain what worked; people who left explain what was missing.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "phone-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["customer-success", "operations", "product-research"],
    searchName: "Phone survey",
    title: "Phone survey script",
    icon: "Phone",
    metaDescription:
      "A phone survey script your callers fill in as they talk: log the call outcome, confirm consent, read each question aloud and record answers in the caller's words.",
    description: "An interviewer script for customer calls that logs outcomes, callbacks and answers.",
    blurb:
      "Written for the person making the call, with every question worded to be read aloud. The first answer routes the rest: a declined or unanswered call ends straight away, a callback request asks for a time and closes on its own ending, and only a completed call goes on to the questions.",
    tags: ["phone survey", "telephone survey script", "phone interview", "customer call", "cati"],
    greeting: "Interviewer: open this before you dial, and fill it in as the call goes. Read the questions exactly as written.",
    questions: [
      { ref: "interviewer", type: "short_text", title: "Your name (interviewer)", required: true, maxLength: 80 },
      { ref: "number_called", type: "phone", title: "Number called", required: true },
      {
        ref: "call_outcome",
        type: "single_select",
        title: "How did the call go?",
        required: true,
        options: [
          { label: "Reached them and they have time now" },
          { label: "Asked us to call back" },
          { label: "Declined to take part" },
          { label: "No answer or voicemail" },
        ],
      },
      {
        ref: "callback_time",
        type: "date",
        title: "When did they ask to be called back?",
        required: true,
        includeTime: true,
        disablePast: true,
      },
      {
        ref: "consent",
        type: "yes_no",
        title: "Read aloud: \"This takes about five minutes and your answers are only used to improve our service. Is it all right to go ahead?\" Did they agree?",
        required: true,
      },
      {
        ref: "customer_since",
        type: "single_select",
        title: "Read aloud: \"How long have you been a customer? Less than a year, one to three years, or more than three years?\"",
        required: true,
        options: [{ label: "Less than a year" }, { label: "1–3 years" }, { label: "More than 3 years" }, { label: "Not sure" }],
      },
      {
        ref: "satisfaction",
        type: "rating",
        title: "Read aloud: \"On a scale of one to five, where five is very satisfied, how satisfied are you with us overall?\"",
        required: true,
        scale: 5,
        shape: "number",
      },
      {
        ref: "reason",
        type: "long_text",
        title: "Read aloud: \"What's the main reason for that score?\" Note their words as closely as you can.",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "contact_channel",
        type: "single_select",
        title: "Read aloud: \"When you need to reach us, do you usually phone, email, use chat, or come in person?\"",
        required: true,
        options: [{ label: "Phone" }, { label: "Email" }, { label: "Chat" }, { label: "In person" }, { label: "They haven't needed to" }],
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "Read aloud: \"If you could change one thing about dealing with us, what would it be?\"",
        required: false,
        maxLength: 1500,
      },
      {
        ref: "recommend",
        type: "nps",
        title: "Read aloud: \"From zero to ten, how likely are you to recommend us to a friend or colleague?\"",
        required: true,
      },
      {
        ref: "wants_follow_up",
        type: "yes_no",
        title: "Did they ask for someone to follow up on anything they raised?",
        required: true,
      },
      {
        ref: "follow_up_topic",
        type: "long_text",
        title: "What should the follow-up be about, and when is a good time to reach them?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "notes",
        type: "long_text",
        title: "Your notes: anything about the call the team should know",
        required: false,
        maxLength: 1500,
      },
    ],
    branches: [
      { when: "call_outcome", is: "Reached them and they have time now", then: "consent" },
      { when: "call_outcome", is: "Asked us to call back", then: "callback_time" },
      { when: "call_outcome", is: "Declined to take part", then: "end_not_completed" },
      { when: "call_outcome", is: "No answer or voicemail", then: "end_not_completed" },
      { when: "callback_time", always: true, then: "end_callback" },
      { when: "consent", is: false, then: "end_not_completed" },
      { when: "wants_follow_up", is: false, then: "notes" },
    ],
    endings: [
      {
        ref: "end_callback",
        title: "Callback logged 📞",
        body: "The time is saved with this record. Thank them and end the call politely.",
      },
      {
        ref: "end_not_completed",
        title: "Call logged",
        body: "No interview this time. Thank them for their time if you spoke, and move on to the next number.",
      },
    ],
    ending: {
      title: "Interview saved",
      body: "Thank them for their time and let them know their answers will be read by the team.",
    },
    guide: {
      questionsToConsider: [
        "What will your callers say in the first ten seconds to explain who they are and why they are calling?",
        "Which questions can be answered from a short list read aloud, and which need the person's own words?",
        "Do you need to tell people the call is being noted or recorded, and what does your consent line need to say where you operate?",
        "How many attempts will you make on a number before marking it as no answer for good?",
      ],
      howToUseResponses:
        "Filter by call outcome first, so completed interviews, callbacks and refusals are counted separately and your response rate is honest. Book every callback from the logged times the same day. Read the reason and one-change answers next to the satisfaction score, and pass every follow-up request to the right team with its topic and the interviewer's notes attached.",
      customizeSteps: [
        "Rewrite the consent line and the questions in the words your callers will actually say, then read them aloud to check they sound natural.",
        "Swap the customer questions for your own topic, keeping each list short enough to remember after hearing it once.",
        "Share the link with your callers, or open it on each caller's screen, and export the results to CSV at the end of each calling session.",
      ],
      faqs: [
        {
          q: "Does this phone survey template make the calls?",
          a: "No. It is the script and answer sheet your interviewer fills in while they talk. Dialling and any call recording happen outside the form.",
        },
        {
          q: "How do you write questions for a phone survey?",
          a: "Keep them short, offer only a few options and read the options aloud as part of the question. Anything that needs a chart or a long list works better in a written survey.",
        },
        {
          q: "How long should a phone survey be?",
          a: "Aim for five minutes or less, and say how long it takes before you start. People on the phone give up faster than people reading.",
        },
        {
          q: "Why log calls that didn't go ahead?",
          a: "Refusals and unanswered calls tell you your real response rate and which numbers to try again. Without them you only see the people who said yes.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "podcast-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["marketing"],
    searchName: "Podcast survey",
    title: "Podcast listener survey",
    icon: "Mic",
    metaDescription:
      "Ask listeners how they found the show, when they listen, which formats they enjoy and what topics or guests they want next. Low ratings get their own follow-up.",
    description: "Learn who your listeners are, how they listen and what they want next.",
    blurb:
      "Covers the questions podcasters actually argue about: episode length, format, where people listen and what they'd cut. Listeners who rate the show highly are asked which episode stuck with them, and anyone less keen is asked what would win them back.",
    tags: ["podcast survey", "listener survey", "podcast feedback", "audience survey", "podcast audience"],
    greeting: "Hey, thanks for listening! Got three minutes to help us plan the next season?",
    questions: [
      {
        ref: "listening_since",
        type: "single_select",
        title: "How long have you been listening?",
        required: true,
        options: [
          { label: "This is my first episode" },
          { label: "A few months" },
          { label: "About a year" },
          { label: "Since the early episodes" },
        ],
      },
      {
        ref: "found_us",
        type: "single_select",
        title: "How did you find the show?",
        required: true,
        allowOther: true,
        options: [
          { label: "Recommended in my podcast app" },
          { label: "Searched for the topic" },
          { label: "A friend told me" },
          { label: "Social media" },
          { label: "Heard a host or guest on another show" },
        ],
      },
      {
        ref: "how_often",
        type: "single_select",
        title: "How many episodes do you listen to?",
        required: true,
        options: [
          { label: "Every one" },
          { label: "Most of them" },
          { label: "Only when the topic grabs me" },
          { label: "Now and then" },
        ],
      },
      {
        ref: "where_listen",
        type: "multi_select",
        title: "Where are you usually when you listen?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        options: [
          { label: "Commuting or driving" },
          { label: "Working out" },
          { label: "Working" },
          { label: "Doing chores" },
          { label: "Winding down before sleep" },
          { label: "Sitting down to really focus" },
        ],
      },
      {
        ref: "length",
        type: "single_select",
        title: "What episode length suits you best?",
        required: true,
        options: [
          { label: "Under 20 minutes" },
          { label: "20–40 minutes" },
          { label: "40–60 minutes" },
          { label: "Over an hour is fine" },
          { label: "Length doesn't matter if it's good" },
        ],
      },
      {
        ref: "formats",
        type: "ranking",
        title: "Put these formats in order, favourite first.",
        required: true,
        items: ["Guest interviews", "Solo deep dives", "Panel discussions", "Listener questions", "Short news roundups"],
      },
      {
        ref: "rating",
        type: "rating",
        title: "How would you rate the show overall?",
        required: true,
        scale: 5,
      },
      {
        ref: "best_moment",
        type: "long_text",
        title: "Which episode or moment has stuck with you, and why?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "win_back",
        type: "long_text",
        title: "What would make the show better for you? Be as blunt as you like.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "next_topics",
        type: "long_text",
        title: "Which topic or guest would you love to hear next?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "recommend",
        type: "nps",
        title: "How likely are you to recommend the show to a friend?",
        required: true,
      },
      {
        ref: "email",
        type: "email",
        title: "Want to hear if your idea makes it into an episode? Leave your email (optional).",
        required: false,
      },
    ],
    branches: [
      { when: "rating", op: "gte", is: 4, then: "best_moment" },
      { when: "rating", op: "lte", is: 3, then: "win_back" },
      { when: "best_moment", always: true, then: "next_topics" },
    ],
    ending: {
      title: "Thanks for listening, and for this 🎧",
      body: "We read every answer while planning episodes. See you in the next one.",
    },
    guide: {
      questionsToConsider: [
        "Which decision are you about to make, such as episode length, a new format or release day? Keep the questions that feed it.",
        "Do you want to hear from brand-new listeners, or only regulars? That changes where you share the link.",
        "Would you give listeners a reason to answer, like a shout-out on the show?",
        "Do you need an email for anything, or can the survey stay anonymous?",
      ],
      howToUseResponses:
        "Compare answers from long-time listeners with first-timers: regulars tell you what to protect, newcomers tell you what hooked them. Use the length and listening-place answers together, since commuters and gym listeners often want shorter episodes. Pull the topic and guest ideas into your planning list, and read every low-rating reply, because those listeners are the ones closest to leaving.",
      customizeSteps: [
        "Put your show's name in the greeting and swap the formats for the ones you actually make or are thinking about.",
        "Mention the survey link in an episode and in the show notes, since most listeners never visit your website.",
        "Read the answers in the dashboard after a couple of weeks, and export them to CSV if you want to sort the topic ideas.",
      ],
      faqs: [
        {
          q: "What questions should I ask in a podcast survey?",
          a: "How people found the show, how and where they listen, what length and format they prefer, what they rate it, and what they want next. Leave room for their own words.",
        },
        {
          q: "How do I get podcast listeners to fill out a survey?",
          a: "Ask on the show itself and put the link in the episode notes. Saying it takes three minutes and that you'll act on it helps more than any prize.",
        },
        {
          q: "Should a podcast survey ask about guests?",
          a: "Yes, if your show has guests. Ask what listeners want to learn from a guest, not only names, so you can judge whether a suggestion fits.",
        },
        {
          q: "Can listeners answer on their phone?",
          a: "Yes. The survey runs as a chat, one question at a time, which suits people answering straight from their podcast app.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "presentation-feedback-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback"],
    roles: ["education", "marketing", "hr-people"],
    searchName: "Presentation feedback survey",
    title: "Presentation feedback survey",
    icon: "MonitorPlay",
    metaDescription:
      "Ask your audience if they could follow the talk, whether it delivered what it promised and how the delivery landed, in the room or online. Replies go to the speaker.",
    description: "Hear whether the audience could follow the talk and how the delivery landed.",
    blurb:
      "Built around the question speakers rarely ask: how much of it could you follow? Anyone who lost the thread is asked where, people who watched online are asked about sound and slides, and anyone with an unanswered question can ask the speaker for a reply and reach their own ending.",
    tags: ["presentation feedback survey", "speaker evaluation", "talk feedback", "audience survey", "conference session feedback"],
    greeting: "Thanks for coming to the talk. Two minutes of honest feedback would help the speaker a lot.",
    questions: [
      { ref: "talk", type: "short_text", title: "Which talk or session are you giving feedback on?", required: true, maxLength: 120 },
      {
        ref: "attended_how",
        type: "single_select",
        title: "How did you watch it?",
        required: true,
        options: [{ label: "In the room" }, { label: "Online, live" }, { label: "Watched the recording" }],
      },
      {
        ref: "online_issues",
        type: "multi_select",
        title: "Did anything get in the way of watching online?",
        required: true,
        minSelections: 1,
        maxSelections: 5,
        options: [
          { label: "The sound was hard to hear" },
          { label: "The slides were hard to read on screen" },
          { label: "The video froze or lagged" },
          { label: "I couldn't ask a question" },
          { label: "No problems" },
        ],
      },
      {
        ref: "matched_promise",
        type: "single_select",
        title: "Did the talk deliver what its title and description promised?",
        required: true,
        options: [{ label: "Yes" }, { label: "Mostly" }, { label: "Not really" }],
      },
      {
        ref: "relevance",
        type: "opinion_scale",
        title: "How relevant was the content to your work or interests?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not relevant",
        labelHigh: "Spot on",
      },
      {
        ref: "follow",
        type: "single_select",
        title: "How much of the talk could you follow?",
        required: true,
        options: [{ label: "All of it" }, { label: "Most of it" }, { label: "About half" }, { label: "I lost the thread early" }],
      },
      {
        ref: "lost_thread",
        type: "long_text",
        title: "Roughly where did you lose the thread, and what would have helped you keep up?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "delivery",
        type: "matrix",
        title: "How did the speaker do on each of these?",
        required: true,
        rows: [
          "Easy to hear and understand",
          "Spoke at a comfortable pace",
          "Slides were readable and helped",
          "Kept my attention",
          "Handled questions well",
        ],
        columns: ["Poor", "Fair", "Good", "Excellent"],
      },
      {
        ref: "see_again",
        type: "single_select",
        title: "Would you go to another talk by this speaker?",
        required: true,
        options: [{ label: "Yes" }, { label: "Maybe" }, { label: "No" }],
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "If the speaker changed one thing for next time, what should it be?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "open_question",
        type: "long_text",
        title: "Is there a question you didn't get to ask?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "wants_reply",
        type: "yes_no",
        title: "Would you like the speaker to reply to you?",
        required: true,
      },
      { ref: "reply_email", type: "email", title: "Where should the reply go?", required: true },
    ],
    branches: [
      { when: "attended_how", is: "In the room", then: "matched_promise" },
      { when: "follow", is: "About half", then: "lost_thread" },
      { when: "follow", is: "I lost the thread early", then: "lost_thread" },
      { when: "follow", is: "All of it", then: "delivery" },
      { when: "follow", is: "Most of it", then: "delivery" },
      { when: "wants_reply", is: false, then: "end_thanks" },
      { when: "reply_email", always: true, then: "end_reply" },
    ],
    endings: [
      {
        ref: "end_reply",
        title: "Got it, a reply is on its way ✉️",
        body: "The speaker will get back to you by email. Thanks for taking the time.",
      },
    ],
    ending: {
      title: "Thank you for the feedback",
      body: "It goes straight to the speaker and shapes the next version of this talk.",
    },
    guide: {
      questionsToConsider: [
        "Is the feedback for the speaker's own growth, or for an organiser choosing next year's speakers? Organisers may want the see-again question most.",
        "Was the talk streamed or recorded? If it was only in person, remove the viewing question and the online problems that follow it.",
        "Should people name the session, or will you send a separate link per talk with the name prefilled?",
        "Who will answer the unasked questions, and how soon?",
      ],
      howToUseResponses:
        "Start with the follow question and the notes from people who lost the thread: if several point to the same moment, that section needs reworking before anything else. Use the delivery grid to separate how the talk was given from what was in it, and compare online viewers with people in the room, since sound and slide problems often only hit one group. Reply to every open question, and pick two concrete changes for the next time the talk is given.",
      customizeSteps: [
        "Rename the delivery grid rows if the talk had no slides, or included a demo or hands-on exercise.",
        "Add the session name as a hidden field on each link so attendees of a multi-talk event skip the first question.",
        "Put the link or a QR code on the last slide and in the recording's description, and give the room a minute to answer before people leave.",
      ],
      faqs: [
        {
          q: "What should I ask on a presentation feedback survey?",
          a: "Whether people could follow the talk, whether it delivered what it promised, how relevant it was, and how the speaker did on sound, pace, slides and questions. One open question about what to change gives the speaker something to act on.",
        },
        {
          q: "When should I send a presentation feedback survey?",
          a: "Before people leave, or within the hour. Show the link on the closing slide so they can answer on their phone.",
        },
        {
          q: "How do I get feedback from people who watched online?",
          a: "Share the same link in the stream chat and with the recording. This survey asks how each person watched, so you can read online and in-room answers separately.",
        },
        {
          q: "Can the feedback be anonymous?",
          a: "Yes. The survey only asks for an email if the person wants a reply from the speaker.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "pricing-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["marketing", "product-research", "sales"],
    searchName: "Pricing survey",
    title: "Pricing survey",
    icon: "Calculator",
    metaDescription:
      "Find out how buyers read your pricing: their first reaction, what was hard to work out, whether it feels fair and what they compared it with before deciding.",
    description: "Find out whether your price is clear, feels fair and holds up against the alternatives.",
    blurb:
      "Focuses on how the price is presented and judged rather than on the number alone. People who found the pricing confusing are asked exactly what was hard to work out, anyone who thinks it's too high is asked what would make it worth paying, and everyone says what they compared you with.",
    tags: ["pricing survey", "pricing page feedback", "value perception", "pricing research", "competitor pricing"],
    greeting: "We're reviewing how we price and explain what we sell. Could you give us three minutes?",
    questions: [
      {
        ref: "relationship",
        type: "single_select",
        title: "Where are you with us right now?",
        required: true,
        options: [
          { label: "I'm a current customer" },
          { label: "I used to be a customer" },
          { label: "I'm thinking about buying" },
          { label: "I looked at you but chose someone else" },
        ],
      },
      {
        ref: "first_reaction",
        type: "single_select",
        title: "When you first saw our price, what was your reaction?",
        required: true,
        options: [
          { label: "Less than I expected" },
          { label: "About what I expected" },
          { label: "More than I expected" },
          { label: "I couldn't tell what it would cost me" },
        ],
      },
      {
        ref: "clarity",
        type: "opinion_scale",
        title: "How easy was it to work out what you would pay?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Very confusing",
        labelHigh: "Completely clear",
      },
      {
        ref: "confusing",
        type: "multi_select",
        title: "What was hard to work out? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        allowOther: true,
        options: [
          { label: "Which option was right for me" },
          { label: "What each option includes" },
          { label: "Extra fees or add-ons" },
          { label: "How the price changes as I use more" },
          { label: "Tax, delivery or currency" },
        ],
      },
      {
        ref: "value",
        type: "single_select",
        title: "For what you get, how does the price feel?",
        required: true,
        options: [
          { label: "Too expensive" },
          { label: "A bit expensive" },
          { label: "About right" },
          { label: "Good value" },
          { label: "Surprisingly cheap" },
        ],
      },
      {
        ref: "worth_it",
        type: "long_text",
        title: "What would need to change for the price to feel worth it?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "compared_with",
        type: "multi_select",
        title: "What did you compare our price with? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        options: [
          { label: "A direct competitor" },
          { label: "A free alternative" },
          { label: "Doing it myself" },
          { label: "Hiring someone to do it" },
          { label: "Not buying anything at all" },
          { label: "I didn't compare" },
        ],
      },
      {
        ref: "comparison_detail",
        type: "long_text",
        title: "How did we look next to the option you compared us with most closely?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "fair_factors",
        type: "ranking",
        title: "What most makes a price feel fair to you? Put the biggest first.",
        required: true,
        items: ["Quality of the product", "Help when I need it", "No hidden extras", "A guarantee or easy refunds", "What others charge", "Discounts for loyal customers"],
      },
      {
        ref: "packaging",
        type: "single_select",
        title: "Which way of pricing would suit you best?",
        required: true,
        options: [
          { label: "One simple price for everything" },
          { label: "A few options at different prices" },
          { label: "A basic price plus extras I choose" },
          { label: "Pay only for what I use" },
        ],
      },
      {
        ref: "anything_else",
        type: "long_text",
        title: "Anything else about our pricing we should know?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "clarity", op: "lte", is: 3, then: "confusing" },
      { when: "clarity", op: "gte", is: 4, then: "value" },
      { when: "value", is: "Too expensive", then: "worth_it" },
      { when: "value", is: "A bit expensive", then: "worth_it" },
      { when: "value", is: "About right", then: "compared_with" },
      { when: "value", is: "Good value", then: "compared_with" },
      { when: "value", is: "Surprisingly cheap", then: "compared_with" },
    ],
    ending: {
      title: "Thank you, that's a real help",
      body: "We'll weigh every answer before we change anything, and we'll announce changes well ahead of time.",
    },
    guide: {
      questionsToConsider: [
        "Is the problem the price itself, or how it's explained? This survey is strongest on the second, so pair it with a separate price test if you need a number.",
        "Which page or quote should people have in mind? Link to it in the greeting so everyone judges the same thing.",
        "Do you want to hear from people who chose a competitor? They are often the most useful and the hardest to reach.",
        "What will you actually be able to change: the price, the options you offer or just the wording?",
      ],
      howToUseResponses:
        "Split the results by the first answer, because current customers, lost customers and prospects judge price from different places. If many people couldn't tell what it would cost, fix the pricing page before touching the numbers, and use the list of what was hard to work out as your to-do list. Read the worth-it answers next to the comparisons: they often point to a missing or badly explained feature rather than a price that is simply too high.",
      customizeSteps: [
        "Edit the confusing options to match how you really charge, such as per seat, per order or per visit.",
        "Replace the fairness ranking items with things you could realistically change or promise.",
        "Send it separately to customers, lapsed customers and prospects, or add a hidden field to each link so you can filter the results.",
      ],
      faqs: [
        {
          q: "What questions should a pricing survey include?",
          a: "Ask how clear the price is, what was hard to understand, whether it feels fair for what's included and what people compared it with. Ask lapsed customers and lost prospects as well as current ones.",
        },
        {
          q: "What's the difference between a pricing survey and a price sensitivity survey?",
          a: "A price sensitivity survey asks at what prices something feels cheap or too expensive, to find an acceptable range. A pricing survey like this one looks at how people read and judge the price you already show them.",
        },
        {
          q: "Should I ask people directly what they would pay?",
          a: "A single \"what would you pay?\" question tends to get low answers. Asking about clarity, value and comparisons tells you more about why people hesitate.",
        },
        {
          q: "How many people do I need for a pricing survey?",
          a: "Enough from each group you care about to see a pattern. Read the open answers too, since a handful of clear complaints about hidden fees can matter more than the averages.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "process-improvement-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["operations", "hr-people"],
    searchName: "Process improvement survey",
    title: "Process improvement survey",
    icon: "Wrench",
    metaDescription:
      "Ask the people who run a process where time is lost, what goes wrong and which fixes would help most. Workarounds and follow-up offers get their own questions.",
    description: "Find the friction in a workflow by asking the people who do the work.",
    blurb:
      "Asks about one named process, so answers stay concrete. It collects the last real mistake, the workarounds people have built for themselves and a ranked list of fixes, and anyone willing to talk it through leaves an email and reaches a separate sign-off.",
    tags: ["process improvement survey", "workflow feedback", "operations survey", "continuous improvement", "bottleneck"],
    greeting: "You know this process better than anyone. Help us find what's slowing it down? About four minutes.",
    questions: [
      {
        ref: "process",
        type: "short_text",
        title: "Which process are you giving feedback on?",
        description: "For example: customer onboarding, month-end close, order fulfilment.",
        required: true,
        maxLength: 120,
      },
      {
        ref: "role",
        type: "single_select",
        title: "What's your part in it?",
        required: true,
        options: [
          { label: "I do it every day" },
          { label: "I do it now and then" },
          { label: "I hand work into it" },
          { label: "I rely on what comes out of it" },
          { label: "I manage it" },
        ],
      },
      {
        ref: "smoothness",
        type: "opinion_scale",
        title: "How smoothly does it run today?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Constantly stuck",
        labelHigh: "Runs smoothly",
      },
      {
        ref: "time_lost",
        type: "multi_select",
        title: "Where does time go that shouldn't? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 8,
        allowOther: true,
        options: [
          { label: "Waiting for approvals" },
          { label: "Typing the same information twice" },
          { label: "Chasing people for updates" },
          { label: "Fixing mistakes" },
          { label: "Looking for files or information" },
          { label: "Not knowing who owns a step" },
          { label: "Switching between too many tools" },
        ],
      },
      {
        ref: "hours_lost",
        type: "number",
        title: "Roughly how many hours a week do you lose to these?",
        required: false,
        min: 0,
        max: 60,
      },
      {
        ref: "last_mistake",
        type: "long_text",
        title: "Think of the last time something went wrong in this process. What happened?",
        required: false,
        maxLength: 1200,
      },
      {
        ref: "has_workaround",
        type: "yes_no",
        title: "Do you use a workaround of your own, like a personal spreadsheet or checklist?",
        required: true,
      },
      {
        ref: "workaround",
        type: "long_text",
        title: "What is it, and what does it fix?",
        required: true,
        maxLength: 800,
      },
      {
        ref: "fixes",
        type: "ranking",
        title: "Which fixes would help you most? Put the biggest first.",
        required: true,
        items: [
          "Fewer approval steps",
          "A clear owner for each step",
          "One place for all files",
          "Checklists or templates",
          "Automating repeat data entry",
          "Better training",
        ],
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "If you could change one thing tomorrow, what would it be?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "talk_through",
        type: "yes_no",
        title: "Would you be happy to walk someone through the process in a short call?",
        required: true,
      },
      { ref: "email", type: "email", title: "What's the best email to reach you on?", required: true },
    ],
    branches: [
      { when: "has_workaround", is: false, then: "fixes" },
      { when: "talk_through", is: false, then: "end_thanks" },
      { when: "email", always: true, then: "end_walkthrough" },
    ],
    endings: [
      {
        ref: "end_walkthrough",
        title: "Thanks, we'll be in touch 🛠️",
        body: "Someone working on the review will email you to find a time. Seeing it done is the fastest way for us to understand it.",
      },
    ],
    ending: {
      title: "Thanks for your honesty",
      body: "We'll share what we find and what we're changing with everyone who took part.",
    },
    guide: {
      questionsToConsider: [
        "Is the survey about one process, or several? Send a separate link per process so answers don't blur together.",
        "Will people answer honestly if their manager can see the results? Decide who reads them and say so up front.",
        "Which fixes in the ranking list are actually in your power to make?",
        "Do you want to hear from people upstream and downstream of the process, not only the ones inside it?",
      ],
      howToUseResponses:
        "Group answers by role: the people doing the work see different problems from the people handing work in or relying on the result. Workarounds are the most useful answers here, because each one marks a gap someone has already solved for themselves and could be made standard. Take the top-ranked fix and the most common time sink, pick one to change first, and tell everyone what you chose and why.",
      customizeSteps: [
        "Put the process name in the greeting, or add it as a hidden field and remove the first question.",
        "Replace the time-sink options and the ranking items with the steps and tools your process really uses.",
        "Share the link with everyone who touches the process, then book walk-throughs with the people who offered.",
      ],
      faqs: [
        {
          q: "What is a process improvement survey?",
          a: "It asks the people who work in a process where time is lost, where mistakes happen and what would help. It is usually the first step before redesigning a workflow.",
        },
        {
          q: "What questions should I ask to improve a process?",
          a: "Ask where time goes, what went wrong recently, what workarounds people use and which fixes they would choose. Concrete recent examples are worth more than general ratings.",
        },
        {
          q: "Should a process improvement survey be anonymous?",
          a: "Often, yes, especially if the process crosses teams. This template only asks for an email from people who volunteer for a follow-up call.",
        },
        {
          q: "What do I do after the survey?",
          a: "Share a summary, pick one change to try first, and check back with the same people a few weeks later to see if it helped.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "program-satisfaction-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback"],
    roles: ["education", "operations", "hr-people"],
    searchName: "Program satisfaction survey",
    title: "Program satisfaction survey",
    icon: "ClipboardCheck",
    metaDescription:
      "Ask participants if a program met their needs, which parts helped and what got in the way. People who left early are asked why, so you hear from them too.",
    description: "Hear how participants found a program, including the ones who didn't finish.",
    blurb:
      "Works for training courses, mentoring schemes, community programs and more. It asks where each person is in the program, so someone who left early is asked why before rating the parts they did use. Participants who want to hear about the next stage leave an email and get their own sign-off.",
    tags: ["program satisfaction survey", "program evaluation", "participant feedback", "training program", "nonprofit program"],
    greeting: "Thanks for taking part in the program. Could you tell us how it's going? It takes about four minutes.",
    questions: [
      { ref: "program", type: "short_text", title: "Which program did you take part in?", required: true, maxLength: 120 },
      {
        ref: "stage",
        type: "single_select",
        title: "Where are you in the program?",
        required: true,
        options: [
          { label: "Just started" },
          { label: "About halfway" },
          { label: "Finished" },
          { label: "I left before the end" },
        ],
      },
      {
        ref: "why_left",
        type: "long_text",
        title: "What made you stop? There's no wrong answer, and it helps us fix things.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "need_met",
        type: "single_select",
        title: "Did the program meet the need you joined it for?",
        required: true,
        options: [{ label: "Yes, fully" }, { label: "Partly" }, { label: "Not yet" }, { label: "No" }],
      },
      { ref: "overall", type: "rating", title: "Overall, how satisfied are you with the program?", required: true, scale: 5 },
      {
        ref: "parts",
        type: "matrix",
        title: "How useful was each part for you?",
        required: true,
        rows: [
          "Sessions or classes",
          "Materials and resources",
          "Support from staff or mentors",
          "Meeting other participants",
          "Updates about times and changes",
        ],
        columns: ["Not useful", "Somewhat useful", "Very useful", "Didn't use it"],
      },
      {
        ref: "most_helpful",
        type: "long_text",
        title: "What helped you most, and how?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "barriers",
        type: "multi_select",
        title: "Did anything make it harder to take part?",
        required: true,
        minSelections: 1,
        maxSelections: 7,
        allowOther: true,
        options: [
          { label: "Session times" },
          { label: "Travel or location" },
          { label: "Workload" },
          { label: "Technology or access" },
          { label: "Not enough support" },
          { label: "Personal circumstances" },
          { label: "Nothing got in the way" },
        ],
      },
      {
        ref: "next_stage",
        type: "long_text",
        title: "What would make the next stage or the next round more useful?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "recommend",
        type: "nps",
        title: "How likely are you to recommend this program to someone in your position?",
        required: true,
      },
      {
        ref: "stay_in_touch",
        type: "yes_no",
        title: "Would you like to hear about the next stage or related programs?",
        required: true,
      },
      { ref: "email", type: "email", title: "Where should we send the details?", required: true },
    ],
    branches: [
      { when: "stage", is: "Just started", then: "need_met" },
      { when: "stage", is: "About halfway", then: "need_met" },
      { when: "stage", is: "Finished", then: "need_met" },
      { when: "stay_in_touch", is: false, then: "end_thanks" },
      { when: "email", always: true, then: "end_next" },
    ],
    endings: [
      {
        ref: "end_next",
        title: "You're on the list 📬",
        body: "We'll email you when the next stage opens. Thanks for your feedback on this one.",
      },
    ],
    ending: {
      title: "Thank you for your feedback",
      body: "The program team reads every response and uses it to plan the next round.",
    },
    guide: {
      questionsToConsider: [
        "Will you send this once at the end, or at the start, middle and end as well? The stage question lets one form cover all three.",
        "What did the program promise participants? Make sure the rows in the grid cover each of those things.",
        "How will you reach people who left early, since they're the least likely to open an email from you?",
        "Do funders or partners need any of these answers in a report? Add the measures they ask for now.",
      ],
      howToUseResponses:
        "Read the answers from people who left early first, because they point at the problems that cost you participants. Compare the usefulness grid by stage to see whether a part of the program helps at the start but fades later. Use the barriers question to separate what you can fix, like session times, from personal circumstances, and share a short \"you said, we did\" note with the next cohort.",
      customizeSteps: [
        "Rename the grid rows to the actual parts of your program, such as workshops, mentoring or site visits.",
        "Add the program or cohort name as a hidden field on each link so you can compare groups in the dashboard.",
        "Send it at the end of each stage, and a short reminder a few days later to the people who haven't answered.",
      ],
      faqs: [
        {
          q: "What is a program satisfaction survey?",
          a: "It asks participants whether a program met their needs, which parts helped, what got in the way and what should change. It's used for training, mentoring, health, education and community programs.",
        },
        {
          q: "What questions should I ask in a program satisfaction survey?",
          a: "Whether the program met the need they joined for, how useful each part was, what made it hard to take part and what to change. Include people who left early.",
        },
        {
          q: "When should I send a program satisfaction survey?",
          a: "At the end, and ideally partway through too, so you can still fix things for the current group.",
        },
        {
          q: "Is this the same as a program evaluation?",
          a: "Not quite. Satisfaction is how participants experienced it; an evaluation also measures outcomes, such as skills gained or goals reached. This survey is a good input to one.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "quality-assurance-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback"],
    roles: ["operations", "customer-success"],
    searchName: "Quality assurance survey",
    title: "Quality assurance review",
    icon: "ShieldCheck",
    metaDescription:
      "A QA review for reviewers to record what they checked, the result and any issues found. Failed checks capture severity, evidence, a fix owner and a due date.",
    description: "Log each quality review the same way, from checks done to fixes assigned.",
    blurb:
      "Gives every reviewer the same checklist, whether they're checking a product batch, a support conversation or a document. A pass goes straight to the closing notes, while anything with issues asks for severity and evidence, and corrective action gets an owner and a due date.",
    tags: ["quality assurance survey", "qa checklist", "quality review", "qa audit form", "quality control"],
    greeting: "Ready to log a quality review? Have the item and your notes to hand.",
    questions: [
      { ref: "reviewer", type: "short_text", title: "Reviewer name", required: true, maxLength: 80 },
      { ref: "review_date", type: "date", title: "Date of the review", required: true },
      {
        ref: "item_type",
        type: "single_select",
        title: "What are you reviewing?",
        required: true,
        allowOther: true,
        options: [
          { label: "A product or batch" },
          { label: "A service visit" },
          { label: "A support conversation" },
          { label: "A document or deliverable" },
        ],
      },
      {
        ref: "item_ref",
        type: "short_text",
        title: "Reference number or name of the item",
        required: true,
        maxLength: 120,
      },
      {
        ref: "checks",
        type: "matrix",
        title: "How did it measure up against each standard?",
        required: true,
        rows: ["Accuracy", "Completeness", "Safety", "Presentation", "On time", "Followed the documented procedure"],
        columns: ["Meets", "Partly meets", "Does not meet", "Not checked"],
      },
      {
        ref: "result",
        type: "single_select",
        title: "Overall result",
        required: true,
        options: [{ label: "Passed" }, { label: "Passed with minor issues" }, { label: "Failed" }],
      },
      {
        ref: "issues",
        type: "long_text",
        title: "Describe what you found. Where was it, and what should it have been?",
        required: true,
        maxLength: 2000,
      },
      {
        ref: "severity",
        type: "single_select",
        title: "How serious is the worst issue?",
        required: true,
        options: [
          { label: "Minor: cosmetic, no effect on the customer" },
          { label: "Major: affects the customer or needs rework" },
          { label: "Critical: safety, legal or must not go out" },
        ],
      },
      {
        ref: "evidence",
        type: "file_upload",
        title: "Add photos, screenshots or files that show the issue",
        required: false,
        accept: ["image/*", "application/pdf"],
        maxFiles: 5,
        maxSizeMB: 10,
      },
      {
        ref: "needs_action",
        type: "yes_no",
        title: "Does this need corrective action?",
        required: true,
      },
      { ref: "fix_owner", type: "short_text", title: "Who should own the fix?", required: true, maxLength: 80 },
      { ref: "fix_due", type: "date", title: "When should it be fixed by?", required: true, disablePast: true },
      {
        ref: "process_notes",
        type: "long_text",
        title: "Anything about the checklist or review process itself that needs attention?",
        required: false,
        maxLength: 1000,
      },
    ],
    branches: [
      { when: "result", is: "Passed", then: "process_notes" },
      { when: "needs_action", is: false, then: "process_notes" },
    ],
    ending: {
      title: "Review logged",
      body: "Thanks. It's saved with the others, and any corrective action is on record with its owner and date.",
    },
    guide: {
      questionsToConsider: [
        "What are the standards your reviewers check against? Replace the grid rows with your own checklist.",
        "What counts as minor, major and critical for your work? Write the definitions into the options so reviewers agree.",
        "Who gets told when a review fails, and how quickly?",
        "Do you need evidence for every issue, or only for major and critical ones?",
      ],
      howToUseResponses:
        "Filter by result and severity each week so critical findings never sit unread. Look at the grid across many reviews to find the standard that fails most often, since that points at a process problem rather than one bad item. Track the fix owners and due dates to closure, and compare reviewers' results on similar items to check they are applying the standards the same way.",
      customizeSteps: [
        "Rewrite the grid rows and the item types to match what your team actually reviews.",
        "Put your own definitions of minor, major and critical into the severity options.",
        "Share the link with reviewers or bookmark it on the inspection device, and export the results to CSV for your monthly quality report.",
      ],
      faqs: [
        {
          q: "What is a quality assurance survey?",
          a: "It's a structured form a reviewer fills in to record what they checked, what they found and what needs fixing, so every review is logged the same way.",
        },
        {
          q: "What should a QA checklist include?",
          a: "The standards being checked, a clear result, a description of each issue with its severity, supporting evidence and who owns the fix by when.",
        },
        {
          q: "Can reviewers attach photos?",
          a: "Yes. The evidence question accepts images and PDFs, up to five files per review.",
        },
        {
          q: "How do I keep reviewers consistent?",
          a: "Define each severity level in plain words, use the same checklist every time, and now and then have two reviewers check the same item and compare.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "retrospective-survey",
    type: "survey",
    category: "marketing",
    goals: ["collect-feedback"],
    roles: ["operations", "product-research", "hr-people"],
    searchName: "Retrospective survey",
    title: "Team retrospective",
    icon: "ListChecks",
    metaDescription:
      "Gather each person's view before the team retro: what went well, what slowed you down, how the team did against last time and one thing to try next.",
    description: "Collect everyone's view of a sprint or project before the retro meeting.",
    blurb:
      "Filled in privately before the meeting, so quieter people get heard and the discussion starts from real answers. It compares this period with the last one, asks for one concrete thing to try, and anyone who didn't feel safe raising problems gets a gentle follow-up question.",
    tags: ["retrospective survey", "sprint retrospective", "retro questions", "agile retro", "project retrospective"],
    greeting: "Retro time. Answer on your own before we meet, so we can spend the meeting on what matters.",
    questions: [
      {
        ref: "period",
        type: "short_text",
        title: "Which sprint, project or period is this for?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "mood",
        type: "opinion_scale",
        title: "How did this stretch of work feel for you?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Rough",
        labelHigh: "Great",
      },
      {
        ref: "goal_met",
        type: "single_select",
        title: "Did we deliver what we set out to do?",
        required: true,
        options: [{ label: "Yes" }, { label: "Mostly" }, { label: "Partly" }, { label: "No" }],
      },
      {
        ref: "went_well",
        type: "long_text",
        title: "What went well that we should keep doing?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "slowed_down",
        type: "multi_select",
        title: "What slowed you down? Pick all that apply.",
        required: true,
        minSelections: 1,
        maxSelections: 8,
        allowOther: true,
        options: [
          { label: "Unclear priorities" },
          { label: "Waiting on other people" },
          { label: "Requirements changed" },
          { label: "Too many meetings" },
          { label: "Tools or environment problems" },
          { label: "Unplanned work" },
          { label: "Nothing major" },
        ],
      },
      {
        ref: "biggest_blocker",
        type: "long_text",
        title: "Pick the biggest thing that got in the way. What happened?",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "compared",
        type: "matrix",
        title: "Compared with last time, how did we do on these?",
        required: true,
        rows: ["Planning", "Communication in the team", "Working with other teams", "Quality of what we delivered", "Spreading the workload"],
        columns: ["Worse", "About the same", "Better"],
      },
      {
        ref: "try_next",
        type: "long_text",
        title: "What's one thing we should try next time?",
        required: true,
        maxLength: 600,
      },
      {
        ref: "speak_up",
        type: "opinion_scale",
        title: "How comfortable did you feel raising problems during this period?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not at all",
        labelHigh: "Completely",
      },
      {
        ref: "speak_up_help",
        type: "long_text",
        title: "What would make it easier to speak up? You can keep this general.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "shout_out",
        type: "long_text",
        title: "Anyone you'd like to thank for something specific?",
        required: false,
        maxLength: 600,
      },
    ],
    branches: [
      { when: "speak_up", op: "lte", is: 2, then: "speak_up_help" },
      { when: "speak_up", op: "gte", is: 3, then: "shout_out" },
    ],
    ending: {
      title: "Thanks, see you at the retro 👋",
      body: "We'll go through the answers together and agree on what to try next.",
    },
    guide: {
      questionsToConsider: [
        "Will answers be anonymous? For a small team, say plainly who will read them and whether names are shown.",
        "Do you want to compare with last time? Keep the grid rows the same every retro so the trend means something.",
        "How long before the meeting should people answer, so the facilitator has time to group the replies?",
        "Did the team agree on actions last time? Consider adding a question about whether they happened.",
      ],
      howToUseResponses:
        "Before the meeting, group the slowed-down answers and the try-next ideas into themes, and bring the top two or three into the room rather than reading every reply. Use the comparison grid to show whether last retro's actions made a difference. If several people score low on speaking up, raise it carefully as a team topic, not an individual one, and agree on no more than two actions with a named owner each.",
      customizeSteps: [
        "Edit the slowed-down options to match the problems your team really runs into.",
        "Put the sprint or project name in the link as a hidden field, so the first question fills itself.",
        "Share the link a day before the retro and read the answers in the dashboard while you prepare.",
      ],
      faqs: [
        {
          q: "What questions should I ask in a retrospective?",
          a: "What went well, what slowed you down, and what to try next are the core three. Comparing with the previous period and asking about psychological safety add useful depth.",
        },
        {
          q: "Why run a retrospective survey before the meeting?",
          a: "People answer more honestly on their own, and quieter team members get the same voice as the loudest. The meeting then starts with real input instead of a blank board.",
        },
        {
          q: "Should retrospective feedback be anonymous?",
          a: "It often helps, especially in teams where people are new or there's tension. Don't add a name question unless the team agrees to it.",
        },
        {
          q: "Can I use this for project retrospectives, not just sprints?",
          a: "Yes. The first question names the period, so it works for a sprint, a launch, a quarter or a whole project.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "skin-care-survey",
    type: "survey",
    category: "marketing",
    goals: ["conduct-research"],
    roles: ["marketing", "product-research"],
    searchName: "Skin care survey",
    title: "Skin care survey",
    icon: "Sparkles",
    metaDescription:
      "Ask customers about their skin type, routine, goals and what they look for when choosing products. People keen to test new products can sign up at the end.",
    description: "Learn how people care for their skin and what makes them choose a product.",
    blurb:
      "Built for skincare brands and shops researching their customers, not for diagnosis. It asks about routine, goals and buying habits, gives anyone who's had a reaction a place to describe it, and invites adults who want to test new products to leave an email for a product-testing ending. Anyone under 18 skips the tester invitation.",
    tags: ["skin care survey", "skincare questionnaire", "beauty survey", "customer research", "product testing"],
    greeting: "Tell us about your skincare routine? It takes about three minutes, and this isn't a skin assessment, just your habits and preferences.",
    questions: [
      {
        ref: "skin_type",
        type: "single_select",
        title: "How would you describe your skin most days?",
        required: true,
        options: [
          { label: "Oily" },
          { label: "Dry" },
          { label: "Combination" },
          { label: "Balanced" },
          { label: "Sensitive" },
          { label: "Not sure" },
        ],
      },
      {
        ref: "goals",
        type: "multi_select",
        title: "What would you most like your routine to help with? Pick up to three.",
        required: true,
        minSelections: 1,
        maxSelections: 3,
        options: [
          { label: "Hydration" },
          { label: "Breakouts" },
          { label: "Dark spots or uneven tone" },
          { label: "Fine lines" },
          { label: "Redness" },
          { label: "Sun protection" },
          { label: "Keeping it simple" },
        ],
      },
      {
        ref: "routine_steps",
        type: "single_select",
        title: "How many products do you usually use in a day?",
        required: true,
        options: [{ label: "None really" }, { label: "1–2" }, { label: "3–4" }, { label: "5 or more" }],
      },
      {
        ref: "products_used",
        type: "multi_select",
        title: "Which of these do you use at least a few times a week?",
        required: true,
        minSelections: 1,
        maxSelections: 8,
        options: [
          { label: "Cleanser" },
          { label: "Moisturiser" },
          { label: "Sunscreen" },
          { label: "Serum" },
          { label: "Exfoliant" },
          { label: "Retinoid" },
          { label: "Eye cream" },
          { label: "None of these" },
        ],
      },
      {
        ref: "routine_happiness",
        type: "rating",
        title: "How happy are you with your current routine?",
        required: true,
        scale: 5,
      },
      {
        ref: "choice_factors",
        type: "ranking",
        title: "When choosing a new product, what matters most? Put the biggest first.",
        required: true,
        items: ["Ingredients", "Price", "Reviews", "A professional's recommendation", "Fragrance free", "Sustainable packaging", "The brand"],
      },
      {
        ref: "where_buy",
        type: "multi_select",
        title: "Where do you usually buy skincare?",
        required: true,
        minSelections: 1,
        maxSelections: 6,
        options: [
          { label: "Pharmacy" },
          { label: "Beauty shop" },
          { label: "A brand's own website" },
          { label: "Online marketplace" },
          { label: "Supermarket" },
          { label: "Salon or clinic" },
        ],
      },
      {
        ref: "had_reaction",
        type: "yes_no",
        title: "Has a skincare product ever irritated your skin?",
        required: true,
      },
      {
        ref: "reaction_detail",
        type: "long_text",
        title: "What kind of product was it, and what happened?",
        description: "This helps us understand what to avoid. We can't give medical advice.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "wish",
        type: "long_text",
        title: "Is there a product you wish existed?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "age_range",
        type: "dropdown",
        title: "Which age group are you in?",
        required: false,
        options: [
          { label: "Under 18" },
          { label: "18–24" },
          { label: "25–34" },
          { label: "35–44" },
          { label: "45–54" },
          { label: "55 or over" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "tester",
        type: "yes_no",
        title: "Would you like to test new products and tell us what you think?",
        required: true,
      },
      { ref: "tester_email", type: "email", title: "Where should we send tester invitations?", required: true },
    ],
    branches: [
      { when: "had_reaction", is: false, then: "wish" },
      { when: "age_range", is: "Under 18", then: "end_thanks" },
      { when: "tester", is: false, then: "end_thanks" },
      { when: "tester_email", always: true, then: "end_tester" },
    ],
    endings: [
      {
        ref: "end_tester",
        title: "Welcome to the testing panel ✨",
        body: "We'll email you when there's a product to try. You can say no to any invitation.",
      },
    ],
    ending: {
      title: "Thank you!",
      body: "Your answers help us make products that fit real routines.",
    },
    guide: {
      questionsToConsider: [
        "Are you researching a new product, a whole range or just your customers in general? Cut the questions that don't feed that decision.",
        "Do you need the age question, and can you explain why you're asking?",
        "Which ingredients or concerns matter for your products? Add them to the goals list.",
        "If people mention a reaction, who reads those answers and what do they do with them?",
      ],
      howToUseResponses:
        "Compare goals and routine length by skin type to see which groups your range serves well and which it misses. The ranking of choice factors tells you what to lead with on labels and product pages. Read the reaction answers for patterns in product types and ingredients, and invite testers whose skin type and goals match the product you're developing.",
      customizeSteps: [
        "Edit the product and goal options to reflect your own range and the concerns you focus on.",
        "Put your brand name in the greeting and say what you'll do with the answers.",
        "Share the link after a purchase or with your mailing list, and export tester emails to CSV when you're ready to send samples.",
      ],
      faqs: [
        {
          q: "What questions should a skin care survey ask?",
          a: "Skin type, goals, the products someone uses now, how happy they are with their routine, what matters when they choose a product and where they buy.",
        },
        {
          q: "Can a skin care survey diagnose skin problems?",
          a: "No. It records what people tell you about their habits and preferences. Anyone with a skin concern should see a doctor or dermatologist.",
        },
        {
          q: "How do I use a skin care survey to recruit product testers?",
          a: "Ask at the end whether they want to test products and collect an email only from those who say yes. You can then pick testers by skin type and goals.",
        },
        {
          q: "Should I ask for age in a skincare survey?",
          a: "It can help, since routines and concerns change with age, but make it optional and include a prefer not to say choice.",
        },
      ],
    },
  }),
];
