import { defineTemplate, type TemplateSeed } from "../define.js";

export const SURVEY_OTHER_2: TemplateSeed[] = [
  defineTemplate({
    slug: "happiness-survey",
    type: "survey",
    category: "other",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["hr-people", "operations", "education"],
    searchName: "Happiness survey",
    title: "Happiness check-in",
    icon: "SmilePlus",
    metaDescription:
      "A short happiness check-in for a team, program or community. Tracks mood over time, asks what is changing it, and offers a private follow-up to anyone who wants one.",
    description: "A quick, honest check-in on how people feel, with a private follow-up for anyone who asks.",
    blurb:
      "A happiness survey that asks why, not just how much. People who say they are less happy than before are asked what changed, people doing well are asked what is working, and anyone can ask for a private conversation without putting their name on every answer.",
    tags: ["happiness survey", "wellbeing check-in", "team mood survey", "employee happiness", "community survey"],
    greeting:
      "Hi! This is a quick check-in on how you're feeling here lately. It takes about three minutes, and there are no wrong answers.",
    questions: [
      {
        ref: "happiness",
        type: "opinion_scale",
        title: "Over the past month, how happy have you felt here?",
        description: "Think about this team, program or group specifically, not life in general.",
        required: true,
        steps: 10,
        startAt: 1,
        labelLow: "Very unhappy",
        labelHigh: "Very happy",
      },
      {
        ref: "trend",
        type: "single_select",
        title: "Compared with a few months ago, is that...",
        required: true,
        options: [{ label: "Happier than before" }, { label: "About the same" }, { label: "Less happy than before" }],
      },
      {
        ref: "best_moment",
        type: "long_text",
        title: "What's one recent moment that made you glad to be part of this?",
        required: false,
        maxLength: 600,
      },
      {
        ref: "what_changed",
        type: "long_text",
        title: "What's changed for you? Anything you're comfortable sharing helps.",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "happiness_sources",
        type: "multi_select",
        title: "Which of these add most to your happiness here?",
        required: true,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "The people I spend time with" },
          { label: "Feeling that what I do matters" },
          { label: "Learning and growing" },
          { label: "Being recognised for my effort" },
          { label: "Freedom to decide how I work" },
          { label: "A manageable amount on my plate" },
        ],
      },
      {
        ref: "belonging",
        type: "matrix",
        title: "How much do you agree with each of these?",
        required: false,
        rows: [
          "I feel like I belong here",
          "I look forward to the time I spend here",
          "My effort is noticed",
          "I have energy left for the rest of my life",
        ],
        columns: ["Disagree", "Somewhat disagree", "Somewhat agree", "Agree"],
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "If you could change one thing to make this a happier place, what would it be?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "want_chat",
        type: "yes_no",
        title: "Would you like someone to reach out for a private chat about how you're doing?",
        required: true,
      },
      {
        ref: "contact_email",
        type: "email",
        title: "What's the best email to reach you on?",
        description: "Only the person following up will see this.",
        required: true,
      },
    ],
    branches: [
      { when: "trend", is: "Happier than before", then: "best_moment" },
      { when: "trend", is: "About the same", then: "best_moment" },
      { when: "trend", is: "Less happy than before", then: "what_changed" },
      { when: "best_moment", always: true, then: "happiness_sources" },
      { when: "want_chat", is: false, then: "end_thanks" },
      { when: "want_chat", is: true, then: "contact_email" },
      { when: "contact_email", always: true, then: "end_followup" },
    ],
    ending: {
      title: "Thanks for checking in 😊",
      body: "We look at the answers together, not one by one, and share what we're changing because of them.",
    },
    endings: [
      {
        ref: "end_followup",
        title: "Thank you, we'll be in touch",
        body: "Someone will email you within a few days to find a time that suits you. The conversation stays between the two of you.",
      },
    ],
    guide: {
      questionsToConsider: [
        "Which group is this about: a team, a whole organisation, a course cohort or a volunteer community?",
        "Will you run it once, or every month or quarter so you can see the trend?",
        "Who follows up with people who ask for a private chat, and are they someone people trust?",
        "Should answers be anonymous apart from the email of those who ask to be contacted?",
      ],
      howToUseResponses:
        "Look at the average happiness score and the split between happier, same and less happy, then read the written answers from the less happy group first, since they point at what to fix. Compare the belonging grid between check-ins to see which statement is moving. Reply to every private chat request within a few days, and tell the whole group one thing you changed because of the survey before you run it again.",
      customizeSteps: [
        "Name the team, program or community in the greeting and the first question so nobody answers about their life in general.",
        "Swap the options in the happiness question for the things your group actually offers, such as events, mentoring or flexible hours.",
        "Share the link on the same day each month or quarter, so the scores stay comparable from one check-in to the next.",
      ],
      faqs: [
        {
          q: "What questions should a happiness survey include?",
          a: "A simple overall score, whether things are getting better or worse, what adds to people's happiness and one open question about what to change. This template covers all four and asks a different follow-up depending on the trend.",
        },
        {
          q: "How often should you run a happiness survey?",
          a: "Monthly or quarterly works for most groups. Often enough to catch a change early, but not so often that people stop reading the questions.",
        },
        {
          q: "Should a happiness survey be anonymous?",
          a: "Mostly, yes. People answer more honestly when they are not named. This one only asks for an email from people who want a private follow-up.",
        },
        {
          q: "Can I use this happiness survey outside of work?",
          a: "Yes. It is written for any group, such as a class, a club or a volunteer program. Change the wording in the first question to name yours.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "political-survey",
    type: "survey",
    category: "other",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["product-research", "marketing"],
    searchName: "Political survey",
    title: "Political opinion survey",
    icon: "Flag",
    metaDescription:
      "A neutral political survey on public issues. Ranks what people care about, measures trust and priorities, and asks those unhappy with the direction why.",
    description: "Ask people where they stand on public issues, in neutral wording that leaves room for every view.",
    blurb:
      "Built for researchers, student groups, local organisations and campaigns who want honest answers rather than the ones a leading question produces. Every question has a balanced set of options, people who think things are on the wrong track are asked why, and the demographic questions are optional and come last.",
    tags: ["political survey", "public opinion survey", "voter survey", "issues survey", "community priorities"],
    greeting:
      "Hi! We're asking people in the area about the public issues that matter to them. It takes about four minutes, and every view is welcome.",
    questions: [
      {
        ref: "area",
        type: "short_text",
        title: "Which town, city or area do you live in?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "direction",
        type: "single_select",
        title: "In general, do you think things in your area are heading in the right direction or on the wrong track?",
        required: true,
        options: [{ label: "Right direction" }, { label: "Wrong track" }, { label: "Mixed or not sure" }],
      },
      {
        ref: "wrong_track_why",
        type: "long_text",
        title: "What makes you feel things are on the wrong track?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "top_issues",
        type: "ranking",
        title: "Put these issues in order of how much they matter to you, most important first.",
        required: true,
        items: [
          "Cost of living",
          "Housing",
          "Healthcare",
          "Jobs and the economy",
          "Education",
          "Public safety",
          "Environment and climate",
          "Immigration",
        ],
      },
      {
        ref: "priorities",
        type: "matrix",
        title: "How much of a priority should each of these be for local government?",
        required: false,
        rows: [
          "Building more affordable homes",
          "Improving public transport",
          "Keeping local taxes low",
          "Funding police and emergency services",
          "Protecting parks and green space",
        ],
        columns: ["Low", "Medium", "High", "Not sure"],
      },
      {
        ref: "trust",
        type: "opinion_scale",
        title: "How much do you trust your elected officials to act in residents' best interests?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not at all",
        labelHigh: "Completely",
      },
      {
        ref: "voting",
        type: "single_select",
        title: "How often do you vote in elections?",
        required: true,
        options: [
          { label: "In every election" },
          { label: "In most elections" },
          { label: "Now and then" },
          { label: "Rarely or never" },
          { label: "I'm not eligible to vote" },
        ],
      },
      {
        ref: "news_sources",
        type: "multi_select",
        title: "Where do you usually get news about politics?",
        required: false,
        allowOther: true,
        options: [
          { label: "TV or radio" },
          { label: "Newspapers or news websites" },
          { label: "Social media" },
          { label: "Podcasts or video channels" },
          { label: "Friends, family or neighbours" },
          { label: "I don't follow political news" },
        ],
      },
      {
        ref: "leaning",
        type: "single_select",
        title: "Which of these best describes your political views?",
        description: "Optional, and only used to compare answers across groups.",
        required: false,
        options: [
          { label: "Left" },
          { label: "Centre-left" },
          { label: "Centre" },
          { label: "Centre-right" },
          { label: "Right" },
          { label: "None of these" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "age_group",
        type: "dropdown",
        title: "Which age group are you in?",
        required: false,
        options: [
          { label: "18–24" },
          { label: "25–34" },
          { label: "35–44" },
          { label: "45–54" },
          { label: "55–64" },
          { label: "65 or over" },
          { label: "Prefer not to say" },
        ],
      },
      {
        ref: "missing_issue",
        type: "long_text",
        title: "Is there an issue we didn't ask about that matters to you?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "direction", is: "Wrong track", then: "wrong_track_why" },
      { when: "direction", is: "Right direction", then: "top_issues" },
      { when: "direction", is: "Mixed or not sure", then: "top_issues" },
    ],
    ending: {
      title: "Thank you for sharing your views",
      body: "Your answers are combined with everyone else's, and no single response is published.",
    },
    guide: {
      questionsToConsider: [
        "Who is running the survey, and will you say so in the greeting? People answer more openly when they know.",
        "Is the focus local, national or one specific issue, and do the ranking items match it?",
        "Do the options on every question cover the full range of views, including a neutral or unsure choice?",
        "Which demographic questions do you really need to compare groups, and can they stay optional?",
      ],
      howToUseResponses:
        "Start with the ranking, since the order of issues is the clearest single result. Then split the priorities grid and the trust score by age group and political leaning to see where groups agree and where they don't. Read the reasons given by people who feel things are on the wrong track, and group them into themes before reporting. When you publish results, report the question wording alongside the numbers so readers can judge them fairly.",
      customizeSteps: [
        "Name who is running the survey and why in the greeting, and replace the ranking items with the issues that are live in your area.",
        "Adjust the priorities grid to the decisions your local council, school board or parliament is actually facing.",
        "Share the link in places that reach a mix of views, not only your own supporters, and export the answers to CSV to analyse them.",
      ],
      faqs: [
        {
          q: "How do you write unbiased political survey questions?",
          a: "Describe each issue in plain, neutral terms, give balanced answer options and always include a way to say you're unsure. Avoid words that signal which answer you prefer.",
        },
        {
          q: "What should a political survey ask?",
          a: "Which issues matter most, how people feel about the direction of things, how much they trust their representatives and a few optional background questions to compare groups.",
        },
        {
          q: "Should a political survey ask about party or voting?",
          a: "Only if you need it to compare groups. This template asks about general political leaning with a prefer-not-to-say option, rather than naming parties, and keeps it optional.",
        },
        {
          q: "Can I keep political survey responses anonymous?",
          a: "Yes. This template never asks for a name or email. If you add contact details, make them optional and say why you are asking.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "user-persona-survey",
    type: "survey",
    category: "other",
    goals: ["conduct-research"],
    roles: ["product-research", "marketing"],
    searchName: "User persona survey",
    title: "User persona research",
    icon: "Users",
    metaDescription:
      "Collect the goals, daily tasks, current tools and frustrations that shape your users, then invite the most useful respondents to a follow-up interview.",
    description: "Gather the goals, habits and frustrations you need to build personas from real answers.",
    blurb:
      "Personas are only as good as the answers behind them, so this survey asks about what people actually do rather than what they would like. It covers role, goals, how often the task comes up, today's tools and what makes people switch, then routes anyone willing to talk to an interview sign-up.",
    tags: ["user persona survey", "persona research", "customer profile survey", "user research", "jobs to be done"],
    greeting:
      "Hi! We're trying to understand the people we build for. A few questions about your work and how you get it done, about four minutes.",
    questions: [
      {
        ref: "role",
        type: "single_select",
        title: "Which of these best describes your role?",
        required: true,
        allowOther: true,
        options: [
          { label: "Founder or owner" },
          { label: "Manager or team lead" },
          { label: "Individual contributor" },
          { label: "Freelancer or consultant" },
          { label: "Student" },
        ],
      },
      {
        ref: "team_size",
        type: "single_select",
        title: "How many people work in your organisation?",
        required: true,
        options: [
          { label: "Just me" },
          { label: "2–10" },
          { label: "11–50" },
          { label: "51–250" },
          { label: "More than 250" },
        ],
      },
      {
        ref: "main_goal",
        type: "long_text",
        title: "What are you ultimately trying to achieve when you do this kind of work?",
        description: "Think about the outcome you want, not the tool you use.",
        required: true,
        maxLength: 800,
      },
      {
        ref: "frequency",
        type: "single_select",
        title: "How often does this task come up for you?",
        required: true,
        options: [
          { label: "Several times a day" },
          { label: "Daily" },
          { label: "Weekly" },
          { label: "Monthly" },
          { label: "A few times a year" },
        ],
      },
      {
        ref: "current_tools",
        type: "multi_select",
        title: "How do you handle it today?",
        required: true,
        allowOther: true,
        options: [
          { label: "Spreadsheets" },
          { label: "A dedicated app or software" },
          { label: "Email and chat messages" },
          { label: "Pen and paper" },
          { label: "Someone else does it for me" },
        ],
      },
      {
        ref: "biggest_obstacle",
        type: "long_text",
        title: "Walk us through the last time it was frustrating. What happened?",
        required: true,
        maxLength: 1200,
      },
      {
        ref: "what_matters",
        type: "ranking",
        title: "When choosing a tool for this, what matters most to you? Most important first.",
        required: true,
        items: ["Easy to learn", "Saves time", "Price", "Reliability", "Works with my other tools", "Good support"],
      },
      {
        ref: "tech_comfort",
        type: "opinion_scale",
        title: "How comfortable are you trying new software?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "I avoid it",
        labelHigh: "I love it",
      },
      {
        ref: "switched",
        type: "yes_no",
        title: "Have you looked for a better way to do this in the past year?",
        required: true,
      },
      {
        ref: "switch_story",
        type: "long_text",
        title: "What made you look, and what did you end up doing?",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "interview",
        type: "yes_no",
        title: "Would you be open to a 30-minute follow-up call about your answers?",
        required: true,
      },
      {
        ref: "contact",
        type: "contact_info",
        title: "Great! How can we reach you to set it up?",
        required: true,
        fields: ["first_name", "email"],
      },
    ],
    branches: [
      { when: "switched", is: true, then: "switch_story" },
      { when: "switched", is: false, then: "interview" },
      { when: "interview", is: false, then: "end_thanks" },
      { when: "interview", is: true, then: "contact" },
      { when: "contact", always: true, then: "end_interview" },
    ],
    ending: {
      title: "Thanks, this is really useful",
      body: "Your answers go straight into the research that shapes what we build next.",
    },
    endings: [
      {
        ref: "end_interview",
        title: "Thank you, we'll email you soon 🙌",
        body: "Someone from the research team will be in touch within a week to find a time for the call.",
      },
    ],
    guide: {
      questionsToConsider: [
        "Which task or problem are you researching? Name it in the greeting so every answer is about the same thing.",
        "What segments do you expect, such as company size or role, and does the survey ask enough to tell them apart?",
        "Which answers would change a product decision, and are those questions required?",
        "How many interviews can you run, and should only certain roles be offered one?",
      ],
      howToUseResponses:
        "Export the answers to CSV and group respondents by role, team size and how often the task comes up. Look for clusters that share a goal and a frustration, and read their written stories side by side; those clusters are your draft personas. Use the ranking to see what each cluster values, then book interviews with a few people from each cluster to test whether the persona holds up.",
      customizeSteps: [
        "Replace \"this kind of work\" and \"this task\" with the specific job you are researching, such as running payroll or planning a trip.",
        "Change the tool options to the real alternatives your users choose between today, including the manual ones.",
        "Share the link with existing users and with people who don't use your product yet, so the personas are not only about current customers.",
      ],
      faqs: [
        {
          q: "What questions should a user persona survey include?",
          a: "Questions about role and context, the goal behind the work, how often it happens, how people do it today, what frustrates them and what they value when choosing a tool.",
        },
        {
          q: "How many responses do you need to build personas?",
          a: "Enough to see clear groups form, which depends on how varied your users are. Pair the survey with a handful of interviews per group to fill in the detail.",
        },
        {
          q: "Should a persona survey use open or closed questions?",
          a: "Both. Closed questions let you group people, and open questions about a real recent experience give you the detail personas need. The AI follow-ups in this template help when an open answer is too vague to use.",
        },
        {
          q: "Can I recruit interview participants with this survey?",
          a: "Yes. The last question asks if people are open to a call, and only those who say yes are asked for contact details.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "employee-performance-survey",
    type: "survey",
    category: "other",
    goals: ["collect-feedback"],
    roles: ["hr-people", "operations"],
    searchName: "Employee performance survey",
    title: "Performance review input",
    icon: "TrendingUp",
    metaDescription:
      "Collect input on one employee from their manager and colleagues before a review: goals, a standout piece of work, core skills and one specific thing to improve.",
    description: "Gather input from the people who work with someone, ahead of their performance review.",
    blurb:
      "A survey the people around an employee fill in, so the review draws on more than one view. Only their manager is asked about agreed goals, a missed goal gets asked what got in the way, and everyone gives a real work example, rates the same skills and names one specific thing to improve.",
    tags: ["employee performance survey", "manager review form", "peer feedback survey", "360 feedback", "employee evaluation"],
    greeting:
      "Hi! You've been asked for input on a colleague's performance ahead of their review. It takes about five minutes, and specific examples help far more than general praise or criticism.",
    questions: [
      {
        ref: "employee_name",
        type: "short_text",
        title: "Whose performance are you giving input on?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "relationship",
        type: "single_select",
        title: "How do you work with them?",
        required: true,
        options: [
          { label: "I'm their manager" },
          { label: "I work alongside them on the same team" },
          { label: "I work with them from another team" },
          { label: "They manage me" },
        ],
      },
      {
        ref: "goals_progress",
        type: "single_select",
        title: "How did they do against the goals you agreed for this period?",
        required: true,
        options: [
          { label: "Went beyond them" },
          { label: "Met them" },
          { label: "Partly met them" },
          { label: "Didn't meet them" },
        ],
      },
      {
        ref: "goals_context",
        type: "long_text",
        title: "What got in the way of the goals they didn't reach?",
        description: "Include anything outside their control, such as changed priorities or missing resources.",
        required: true,
        maxLength: 1200,
      },
      {
        ref: "work_example",
        type: "long_text",
        title: "Describe one piece of their work from this period that stood out. What did they do, and what came of it?",
        required: true,
        maxLength: 1500,
      },
      {
        ref: "skills",
        type: "matrix",
        title: "From what you've seen, how do they do on each of these?",
        required: true,
        rows: [
          "Quality of their work",
          "Delivering what they promise, on time",
          "Keeping others informed",
          "Working with people across teams",
          "Solving problems without being asked",
          "Taking feedback on board",
        ],
        columns: ["Below what the role needs", "Getting there", "What the role needs", "Beyond what the role needs"],
      },
      {
        ref: "under_pressure",
        type: "opinion_scale",
        title: "How easy are they to work with when things get busy?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Very hard",
        labelHigh: "Very easy",
      },
      {
        ref: "keep_doing",
        type: "long_text",
        title: "What should they keep doing?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "improve",
        type: "long_text",
        title: "What's one thing that would make them more effective? Be specific, and kind.",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "develop",
        type: "multi_select",
        title: "Where do you think they'd benefit most from development?",
        required: true,
        maxSelections: 2,
        allowOther: true,
        options: [
          { label: "Job-specific skills" },
          { label: "Leading or mentoring others" },
          { label: "Communication" },
          { label: "Planning and prioritising" },
          { label: "Understanding the wider business" },
        ],
      },
      {
        ref: "attribution",
        type: "single_select",
        title: "How should your input be shared with them?",
        required: true,
        options: [{ label: "With my name on it" }, { label: "Without my name" }],
      },
    ],
    branches: [
      { when: "relationship", is: "I'm their manager", then: "goals_progress" },
      { when: "relationship", is: "I work alongside them on the same team", then: "work_example" },
      { when: "relationship", is: "I work with them from another team", then: "work_example" },
      { when: "relationship", is: "They manage me", then: "work_example" },
      { when: "goals_progress", is: "Went beyond them", then: "work_example" },
      { when: "goals_progress", is: "Met them", then: "work_example" },
      { when: "goals_progress", is: "Partly met them", then: "goals_context" },
      { when: "goals_progress", is: "Didn't meet them", then: "goals_context" },
    ],
    ending: {
      title: "Thanks, your input is in",
      body: "It will be read alongside the other responses before the review, and shared the way you asked.",
    },
    guide: {
      questionsToConsider: [
        "Who should be asked for input on each person: only their manager, or also two or three colleagues and anyone they manage?",
        "Do the skill rows match what your organisation actually reviews against for this role?",
        "Will the employee see the answers word for word, as a summary, or only through their manager?",
        "Do colleagues know the goals well enough to comment on them, or should that stay with the manager as it does here?",
      ],
      howToUseResponses:
        "Filter the responses by the employee's name and read them side by side before the review. Look for points that more than one person raises, since those carry more weight than a single comment, and note where the manager's view differs from colleagues'. Turn the work examples into specific praise and the \"one thing to improve\" answers into one or two development goals. Respect the sharing choice each person made when you pass their words on.",
      customizeSteps: [
        "Rename the skill rows to your organisation's competencies or values, and add the review period to the greeting.",
        "Replace the name question with a dropdown of the people being reviewed this cycle if you run it for a whole team.",
        "Send each reviewer the link a week or two before the review meeting, and remind them that examples matter more than ratings.",
      ],
      faqs: [
        {
          q: "What should an employee performance survey include?",
          a: "Progress against agreed goals, a real example of the person's work, ratings on the skills the role needs, and one specific thing that would make them more effective.",
        },
        {
          q: "Who should give feedback on an employee's performance?",
          a: "Their manager at least, and ideally a few colleagues who work with them closely. This template asks each person how they work with the employee, so their answers can be read in that light.",
        },
        {
          q: "Should performance feedback from colleagues be anonymous?",
          a: "Give people the choice. Some are more candid without their name attached, others are happy to stand behind their words. The last question lets each reviewer decide.",
        },
        {
          q: "Is this the same as a self-assessment?",
          a: "No. This survey collects other people's view of the employee. Pair it with a self-review so the conversation can compare the two.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "performance-management-survey",
    type: "survey",
    category: "other",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["hr-people", "operations"],
    searchName: "Performance management survey",
    title: "Performance process review",
    icon: "Gauge",
    metaDescription:
      "Ask staff whether your goal setting, feedback and review process helps them improve. Managers get their own questions, and a low score asks what isn't working.",
    description: "Find out whether your goals, feedback and reviews actually help people do better work.",
    blurb:
      "A survey about the performance process itself, not anyone's performance. Managers are asked what would help them run better reviews, everyone rates how clear, fair and useful the process is, and anyone who rates it 3 or below is asked where it lets them down so you know what to fix first.",
    tags: ["performance management survey", "performance review process", "feedback culture", "goal setting", "HR survey"],
    greeting:
      "Hi! We want to know whether the way we set goals, give feedback and run reviews is actually helping. This is about the process, not your performance, and it takes about four minutes.",
    questions: [
      {
        ref: "role_type",
        type: "single_select",
        title: "Do you manage other people?",
        required: true,
        options: [{ label: "Yes, I manage people" }, { label: "No, I don't manage anyone" }],
      },
      {
        ref: "manager_needs",
        type: "multi_select",
        title: "What would help you run better review conversations?",
        required: false,
        allowOther: true,
        options: [
          { label: "Training on giving feedback" },
          { label: "Clearer guidance on ratings" },
          { label: "Simpler forms and templates" },
          { label: "More time set aside for reviews" },
          { label: "Comparing notes with other managers" },
        ],
      },
      {
        ref: "expectations_clear",
        type: "opinion_scale",
        title: "How clear are the expectations for your own role?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Very unclear",
        labelHigh: "Completely clear",
      },
      {
        ref: "goal_setting",
        type: "single_select",
        title: "How are your goals usually set?",
        required: true,
        options: [
          { label: "Together with my manager" },
          { label: "My manager sets them for me" },
          { label: "I set them myself" },
          { label: "I don't have formal goals" },
        ],
      },
      {
        ref: "feedback_frequency",
        type: "single_select",
        title: "How often do you get useful feedback on your work?",
        required: true,
        options: [
          { label: "Every week" },
          { label: "Every month" },
          { label: "Every few months" },
          { label: "Only at formal reviews" },
          { label: "Rarely or never" },
        ],
      },
      {
        ref: "process_ratings",
        type: "matrix",
        title: "How much do you agree with each of these?",
        required: true,
        rows: [
          "My goals reflect the work I actually do",
          "Feedback I get is specific enough to act on",
          "Reviews are fair and consistent across teams",
          "My rating reflects my real contribution",
          "Reviews lead to a real plan for my development",
        ],
        columns: ["Strongly disagree", "Disagree", "Agree", "Strongly agree"],
      },
      {
        ref: "overall_useful",
        type: "rating",
        title: "Overall, how useful is our performance process in helping you improve?",
        required: true,
        scale: 5,
      },
      {
        ref: "what_works",
        type: "long_text",
        title: "What part of the process helps you most?",
        required: false,
        maxLength: 800,
      },
      {
        ref: "what_fails",
        type: "long_text",
        title: "Where does the process let you down? A recent example helps.",
        required: true,
        maxLength: 1200,
      },
      {
        ref: "time_spent",
        type: "single_select",
        title: "Is the time spent on reviews about right?",
        required: true,
        options: [{ label: "Too much" }, { label: "About right" }, { label: "Too little" }],
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "If you could change one thing about how performance is managed here, what would it be?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "role_type", is: "Yes, I manage people", then: "manager_needs" },
      { when: "role_type", is: "No, I don't manage anyone", then: "expectations_clear" },
      { when: "overall_useful", op: "gte", is: 4, then: "what_works" },
      { when: "overall_useful", op: "lte", is: 3, then: "what_fails" },
      { when: "what_works", always: true, then: "time_spent" },
    ],
    ending: {
      title: "Thank you for the honest answers",
      body: "We'll share what we heard and what we plan to change before the next review cycle starts.",
    },
    guide: {
      questionsToConsider: [
        "Which parts of your process do you want judged: goal setting, regular check-ins, formal reviews, ratings or all of them?",
        "Should managers and employees see different questions, beyond the manager block already here?",
        "When will you run it: straight after a review cycle, or halfway between two?",
        "Who will own the changes, and how will you tell staff what changed?",
      ],
      howToUseResponses:
        "Compare the agreement grid between managers and non-managers, because a gap there often shows where the process breaks down. Look at the statements with the most disagreement first, then read the written answers from people who scored the process low to understand why. Use the manager answers to plan training or better guidance, and repeat the survey after the next cycle to see if the changes worked.",
      customizeSteps: [
        "Rename goals, check-ins and reviews to the terms your organisation uses, such as objectives, one-to-ones or appraisals.",
        "Edit the agreement grid so each row matches a step in your process that you could actually change.",
        "Send it within two weeks of a review cycle closing, while people still remember how it went.",
      ],
      faqs: [
        {
          q: "What is a performance management survey?",
          a: "A survey that asks staff how well the goal setting, feedback and review process works for them. It judges the process, not any one person's performance.",
        },
        {
          q: "What questions should a performance management survey ask?",
          a: "Whether expectations are clear, how goals are set, how often useful feedback happens, whether reviews feel fair and whether they lead to development.",
        },
        {
          q: "Should a performance management survey be anonymous?",
          a: "Yes, in most cases. This template asks only whether someone manages people, so you can compare the two groups without identifying anyone.",
        },
        {
          q: "How is this different from an employee performance survey?",
          a: "An employee performance survey is about one person's work. This one is about the system everyone goes through, so you can fix what isn't helping.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "work-life-balance-survey",
    type: "survey",
    category: "other",
    goals: ["collect-feedback", "conduct-research"],
    roles: ["hr-people", "operations"],
    searchName: "Work-life balance survey",
    title: "Work-life balance survey",
    icon: "Leaf",
    metaDescription:
      "Understand how work fits with life outside it: hours, after-hours contact, boundaries and flexibility. Low scores get asked what's making balance hardest.",
    description: "See where workload and boundaries are slipping, and which support would help most.",
    blurb:
      "Covers the practical things that decide balance: hours, how often work spills into evenings, whether people can switch off and use their leave. Anyone who rates their balance low is asked what's making it hardest, and everyone ranks the kinds of flexibility that would help them most.",
    tags: ["work-life balance survey", "employee wellbeing", "workload survey", "flexible working", "burnout survey"],
    greeting:
      "Hi! We want to understand how work fits with the rest of your life, and what would make it fit better. About four minutes, and your answers are anonymous.",
    questions: [
      {
        ref: "arrangement",
        type: "single_select",
        title: "How do you mostly work at the moment?",
        required: true,
        options: [{ label: "On site" }, { label: "Hybrid" }, { label: "Fully remote" }],
      },
      {
        ref: "weekly_hours",
        type: "single_select",
        title: "In a typical week, how many hours do you actually work?",
        required: true,
        options: [
          { label: "Fewer than 35" },
          { label: "35–40" },
          { label: "41–45" },
          { label: "46–50" },
          { label: "More than 50" },
        ],
      },
      {
        ref: "after_hours",
        type: "single_select",
        title: "How often do you work in the evenings or at weekends?",
        required: true,
        options: [
          { label: "Rarely or never" },
          { label: "Once or twice a month" },
          { label: "Most weeks" },
          { label: "Almost every day" },
        ],
      },
      {
        ref: "balance",
        type: "opinion_scale",
        title: "How would you rate your balance between work and life outside it right now?",
        required: true,
        steps: 10,
        startAt: 1,
        labelLow: "Very poor",
        labelHigh: "Excellent",
      },
      {
        ref: "what_helps",
        type: "long_text",
        title: "What helps you keep a good balance? We'd like to do more of it.",
        required: false,
        maxLength: 800,
      },
      {
        ref: "pressures",
        type: "multi_select",
        title: "What's making balance hardest for you?",
        required: true,
        allowOther: true,
        options: [
          { label: "More work than fits in my hours" },
          { label: "Too many meetings" },
          { label: "Messages outside working hours" },
          { label: "Unclear or shifting priorities" },
          { label: "Staff shortages on my team" },
          { label: "Commute" },
          { label: "Caring responsibilities at home" },
        ],
      },
      {
        ref: "pressure_detail",
        type: "long_text",
        title: "Is there anything else about that you'd like us to know?",
        required: false,
        maxLength: 1000,
      },
      {
        ref: "boundaries",
        type: "matrix",
        title: "How often is each of these true for you?",
        required: true,
        rows: [
          "My workload fits in my normal hours",
          "I can switch off after work",
          "I feel able to take all my leave",
          "My manager respects my time outside work",
          "I can adjust my hours when life needs it",
        ],
        columns: ["Rarely", "Sometimes", "Usually", "Always"],
      },
      {
        ref: "support_ranking",
        type: "ranking",
        title: "Which of these would help your balance most? Most helpful first.",
        required: true,
        items: [
          "Flexible start and finish times",
          "More days working from home",
          "Meeting-free time blocks",
          "Clear rules on after-hours messages",
          "Support with caring responsibilities",
          "A more realistic workload",
        ],
      },
      {
        ref: "one_change",
        type: "long_text",
        title: "What's one change we could make that would make the biggest difference for you?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "balance", op: "gte", is: 6, then: "what_helps" },
      { when: "balance", op: "lte", is: 5, then: "pressures" },
      { when: "what_helps", always: true, then: "boundaries" },
    ],
    ending: {
      title: "Thank you for being open with us 🌿",
      body: "We'll share what we learn and the changes we plan to try within the next few weeks.",
    },
    guide: {
      questionsToConsider: [
        "Do you already offer flexibility, such as remote days or flexible hours, that people may not know about?",
        "Are the hour bands right for your contracts, including part-time staff?",
        "Do you want results by team or location, and are the groups big enough to stay anonymous?",
        "Which of the support options could you realistically offer if people ask for it?",
      ],
      howToUseResponses:
        "Start with the balance score split by work arrangement, then look at how many people work most evenings or weekends. The boundary grid shows whether the problem is workload, switching off or leave, and each needs a different fix. Read the pressures chosen by people with low scores to find the causes, and use the ranking to pick one or two changes to try. Run the survey again a few months later to see if the scores move.",
      customizeSteps: [
        "Edit the support options in the ranking to the policies you could actually introduce or expand.",
        "Adjust the hour bands and the work arrangement options to match your contracts and locations.",
        "Tell people in the greeting when you'll share results, then keep that promise so they answer next time.",
      ],
      faqs: [
        {
          q: "What questions should a work-life balance survey ask?",
          a: "How many hours people really work, how often work spills into evenings and weekends, whether they can switch off and take leave, and what support would help.",
        },
        {
          q: "How do you measure work-life balance?",
          a: "Combine a direct rating with concrete measures such as weekly hours and after-hours work. The concrete answers show whether a low rating comes from workload, boundaries or something outside work.",
        },
        {
          q: "Should a work-life balance survey be anonymous?",
          a: "Yes. People are less likely to admit to overwork or struggles at home if they can be identified. This template never asks for a name.",
        },
        {
          q: "How often should we run a work-life balance survey?",
          a: "Once or twice a year works for most teams, plus a quick repeat after any big change in workload, staffing or working arrangements.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "training-needs-assessment-survey",
    type: "survey",
    category: "other",
    goals: ["conduct-research", "collect-feedback"],
    roles: ["hr-people", "education", "operations"],
    searchName: "Training needs assessment survey",
    title: "Training needs assessment",
    icon: "GraduationCap",
    metaDescription:
      "Find skill gaps before you plan training. Staff rate their confidence on key skills, describe where they got stuck, and pick the formats and topics that would help.",
    description: "Find the real skill gaps and preferred formats before you spend a training budget.",
    blurb:
      "A needs assessment that asks about real work, not wish lists. People rate their confidence on the skills their job depends on, describe a recent moment where more training would have helped, and rank how they like to learn. Anyone confident enough to teach a topic is asked what they could share.",
    tags: ["training needs assessment", "skills gap survey", "learning needs", "employee training survey", "L&D survey"],
    greeting:
      "Hi! We're planning training for the months ahead and want it to fit the work you really do. It takes about five minutes.",
    questions: [
      {
        ref: "team",
        type: "short_text",
        title: "Which team or department are you in?",
        required: true,
        maxLength: 120,
      },
      {
        ref: "time_in_role",
        type: "single_select",
        title: "How long have you been in your current role?",
        required: true,
        options: [
          { label: "Less than 6 months" },
          { label: "6 months to 2 years" },
          { label: "2 to 5 years" },
          { label: "More than 5 years" },
        ],
      },
      {
        ref: "main_tasks",
        type: "long_text",
        title: "Which tasks take up most of your working week?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "skill_confidence",
        type: "matrix",
        title: "How confident are you in each of these areas?",
        required: true,
        rows: [
          "The main software and systems I use",
          "Communicating with customers or clients",
          "Planning and prioritising my work",
          "Working with data and reports",
          "Leading or coaching others",
          "Safety, compliance and procedures",
        ],
        columns: ["I need training", "Some gaps", "Confident", "I could teach it"],
      },
      {
        ref: "stuck_moment",
        type: "long_text",
        title: "Describe a recent moment at work when more training or support would have helped.",
        required: true,
        maxLength: 1200,
      },
      {
        ref: "topics",
        type: "multi_select",
        title: "Which topics would help you most in the next six months? Pick up to three.",
        required: true,
        maxSelections: 3,
        allowOther: true,
        options: [
          { label: "Job-specific technical skills" },
          { label: "Software and tools" },
          { label: "Customer service" },
          { label: "Project management" },
          { label: "Managing people" },
          { label: "Writing and presenting" },
          { label: "Health, safety and compliance" },
        ],
      },
      {
        ref: "format",
        type: "ranking",
        title: "How do you prefer to learn? Put your favourite first.",
        required: true,
        items: [
          "Hands-on workshop",
          "Short online lessons",
          "One-to-one coaching",
          "Shadowing a colleague",
          "Written guides I can look up",
        ],
      },
      {
        ref: "time_available",
        type: "single_select",
        title: "How much time could you realistically give to training each month?",
        required: true,
        options: [
          { label: "Less than 2 hours" },
          { label: "2–4 hours" },
          { label: "5–8 hours" },
          { label: "More than 8 hours" },
        ],
      },
      {
        ref: "can_teach",
        type: "yes_no",
        title: "Is there anything you know well enough to teach colleagues?",
        required: true,
      },
      {
        ref: "teach_topic",
        type: "short_text",
        title: "What could you teach, and to whom?",
        required: true,
        maxLength: 300,
      },
      {
        ref: "teacher_contact",
        type: "contact_info",
        title: "Who should we contact about it?",
        description: "Only used to follow up about teaching.",
        required: true,
        fields: ["first_name", "last_name", "email"],
      },
    ],
    branches: [
      { when: "can_teach", is: false, then: "end_thanks" },
      { when: "can_teach", is: true, then: "teach_topic" },
      { when: "teacher_contact", always: true, then: "end_teacher" },
    ],
    ending: {
      title: "Thanks, this shapes the training plan",
      body: "We'll share the plan once it's ready, based on what you and your colleagues told us.",
    },
    endings: [
      {
        ref: "end_teacher",
        title: "Thank you, we may take you up on that",
        body: "Sharing what you know is one of the best ways a team learns. We'll get in touch if your topic comes up in the plan.",
      },
    ],
    guide: {
      questionsToConsider: [
        "Which skills does each role truly depend on? Those belong in the confidence grid.",
        "Do you need answers split by team or seniority, and does the form ask enough to do that?",
        "Is there a set budget or time for training, and should the time question reflect it?",
        "Will managers also assess their teams, so you can compare self-ratings with theirs?",
      ],
      howToUseResponses:
        "Count the \"I need training\" and \"Some gaps\" answers in the confidence grid for each team to find the biggest shared gaps. Read the stuck moments to understand what the gap looks like in practice, which helps a trainer pitch the content right. Match topics to the most popular formats and the time people can give, and use the people who said they could teach as in-house trainers or mentors before paying for outside courses.",
      customizeSteps: [
        "Replace the rows in the confidence grid with the skills your roles need, such as a named system, a sales process or a clinical procedure.",
        "Edit the topic list to the training you could actually provide this year.",
        "Share the link with each team through their manager, and export the answers to CSV to compare teams side by side.",
      ],
      faqs: [
        {
          q: "What is a training needs assessment survey?",
          a: "A survey that finds the gaps between the skills people have and the skills their work needs, so you plan training around real needs rather than guesses.",
        },
        {
          q: "What questions should a training needs assessment include?",
          a: "Questions about current tasks, confidence in key skills, recent situations where people got stuck, the topics they want and how they prefer to learn.",
        },
        {
          q: "When should you run a training needs assessment?",
          a: "Before planning a training budget or calendar, and after a big change such as new software, a new process or a new team structure.",
        },
        {
          q: "Can I find in-house trainers with this survey?",
          a: "Yes. Near the end it asks whether people could teach a topic, and only those who say yes are asked what they could share and how to reach them.",
        },
      ],
    },
  }),

  defineTemplate({
    slug: "training-satisfaction-survey",
    type: "survey",
    category: "other",
    goals: ["collect-feedback"],
    roles: ["hr-people", "education"],
    searchName: "Training satisfaction survey",
    title: "Training satisfaction",
    icon: "ThumbsUp",
    metaDescription:
      "Find out how satisfied people were with a training session, from content and trainer to materials and setup, and what lifted or lowered their overall rating.",
    description: "Hear how a training session landed, and which part lifted or sank the overall score.",
    blurb:
      "A satisfaction survey that pins the overall score to a cause. A high rating asks which part made the session, a lower one asks what let it down and what would have fixed it, and everyone rates their satisfaction with the content, trainer, materials, length and setup.",
    tags: ["training satisfaction survey", "training feedback form", "course satisfaction survey", "workshop feedback", "trainer feedback"],
    greeting:
      "Thanks for taking part in the training! Two or three minutes of feedback helps us make the next session better.",
    questions: [
      {
        ref: "session",
        type: "short_text",
        title: "Which training session did you attend?",
        required: true,
        maxLength: 150,
      },
      {
        ref: "attended_how",
        type: "single_select",
        title: "How did you take part?",
        required: true,
        options: [{ label: "In person" }, { label: "Live online" }, { label: "Watched a recording" }],
      },
      {
        ref: "overall",
        type: "rating",
        title: "Overall, how satisfied were you with the training?",
        required: true,
        scale: 5,
      },
      {
        ref: "best_part",
        type: "single_select",
        title: "Which part did the most to make it a good session?",
        required: true,
        allowOther: true,
        options: [
          { label: "The content itself" },
          { label: "The way the trainer explained things" },
          { label: "The hands-on practice" },
          { label: "The handouts and materials" },
          { label: "Discussion with other participants" },
        ],
      },
      {
        ref: "letdown",
        type: "single_select",
        title: "What let the session down most?",
        required: true,
        allowOther: true,
        options: [
          { label: "It wasn't relevant to my job" },
          { label: "It was hard to follow" },
          { label: "The pace was off" },
          { label: "The materials weren't much use" },
          { label: "Problems with the room, sound or connection" },
          { label: "It ran too long" },
        ],
      },
      {
        ref: "letdown_fix",
        type: "long_text",
        title: "What would have fixed that for you?",
        required: true,
        maxLength: 1000,
      },
      {
        ref: "satisfaction",
        type: "matrix",
        title: "How satisfied were you with each of these?",
        required: true,
        rows: [
          "How relevant the content was to my work",
          "The trainer's delivery",
          "Handouts, slides and other materials",
          "The length of the session",
          "The room or online setup",
          "Joining instructions beforehand",
        ],
        columns: ["Dissatisfied", "Neutral", "Satisfied", "Very satisfied"],
      },
      {
        ref: "expectations",
        type: "single_select",
        title: "Did the session match what its description promised?",
        required: true,
        options: [{ label: "It was better than described" }, { label: "It was about what I expected" }, { label: "It fell short of the description" }],
      },
      {
        ref: "confidence",
        type: "opinion_scale",
        title: "How confident do you feel putting what you learned into practice?",
        required: true,
        steps: 5,
        startAt: 1,
        labelLow: "Not confident",
        labelHigh: "Very confident",
      },
      {
        ref: "same_trainer",
        type: "yes_no",
        title: "Would you sign up for another session with this trainer?",
        required: true,
      },
      {
        ref: "anything_else",
        type: "long_text",
        title: "Anything else the trainer or organisers should know?",
        required: false,
        maxLength: 800,
      },
    ],
    branches: [
      { when: "overall", op: "gte", is: 4, then: "best_part" },
      { when: "overall", op: "lte", is: 3, then: "letdown" },
      { when: "best_part", always: true, then: "satisfaction" },
    ],
    ending: {
      title: "Thank you for the feedback 🙏",
      body: "Every response is read before the next session is planned.",
    },
    guide: {
      questionsToConsider: [
        "Will you use one link per session, or one form for many sessions with the name asked or prefilled?",
        "If several trainers run the same course, do you need the trainer's name as its own question?",
        "Does the setup row matter for your format, or should it name the venue or online platform you used?",
        "Who needs the results: the trainer, the course owner or the participants' managers?",
      ],
      howToUseResponses:
        "Sort responses by overall rating and read the \"what let it down\" answers from the lower scores first; the most common cause is usually the first thing to fix. Use the satisfaction grid to spot a weak area that even happy participants rated poorly, such as materials or joining instructions. Compare in-person and online answers, since setup problems often hit one group only. Share the \"best part\" answers and the repeat-trainer question with the trainer so they know what to keep.",
      customizeSteps: [
        "Turn the session question into a dropdown of your courses, or prefill it from the link you send for each one.",
        "Edit the grid rows to match your format, for example naming the venue, the online platform or the pre-reading.",
        "Share the link in the last few minutes of the session, before people leave the room or the call.",
      ],
      faqs: [
        {
          q: "What questions should a training satisfaction survey ask?",
          a: "An overall satisfaction rating with the reason behind it, then satisfaction with the content, trainer, materials, length and setup, plus whether the session matched its description.",
        },
        {
          q: "When should you send a training satisfaction survey?",
          a: "At the end of the session, while the details are fresh. Waiting even a day lowers how many people answer and how much they remember.",
        },
        {
          q: "What is the difference between training satisfaction and training effectiveness?",
          a: "Satisfaction is how people felt about the session. Effectiveness is whether they learned and use it. This template adds a confidence question as an early signal, but a follow-up weeks later tells you more.",
        },
        {
          q: "Can I use one survey for several training sessions?",
          a: "Yes. The first question asks which session someone attended, so you can filter or compare sessions when you export the answers to CSV.",
        },
      ],
    },
  }),
];
