/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1Forms200Item,
  GetV1FormsById404,
  PostV1ChatSessionsBySidMessagesBody,
  PostV1FormsByIdChatSessions200,
  PostV1FormsByIdChatSessionsBody
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getV1FormsResponse200 = {
  data: GetV1Forms200Item[]
  status: 200
}

export type getV1FormsResponseSuccess = (getV1FormsResponse200) & {
  headers: Headers;
};
;

export type getV1FormsResponse = (getV1FormsResponseSuccess)

export const getGetV1FormsUrl = () => {




  return `/v1/forms`
}

/**
 * @summary List published forms (API key)
 */
export const getV1Forms = async ( options?: Parameters<typeof customFetch>[1]): Promise<getV1FormsResponse> => {

  return customFetch<getV1FormsResponse>(getGetV1FormsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1FormsQueryKey = () => {
    return [
    `/v1/forms`
    ] as const;
    }


export const getGetV1FormsQueryOptions = <TData = Awaited<ReturnType<typeof getV1Forms>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1Forms>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1FormsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Forms>>> = ({ signal }) => getV1Forms({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Forms>>, TError, TData> & { queryKey: QueryKey }
}

export type GetV1FormsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Forms>>>
export type GetV1FormsQueryError = unknown


/**
 * @summary List published forms (API key)
 */

export function useGetV1Forms<TData = Awaited<ReturnType<typeof getV1Forms>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1Forms>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetV1FormsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getV1FormsByIdResponse200 = {
  data: void
  status: 200
}

export type getV1FormsByIdResponse404 = {
  data: GetV1FormsById404
  status: 404
}

export type getV1FormsByIdResponseSuccess = (getV1FormsByIdResponse200) & {
  headers: Headers;
};
export type getV1FormsByIdResponseError = (getV1FormsByIdResponse404) & {
  headers: Headers;
};

export type getV1FormsByIdResponse = (getV1FormsByIdResponseSuccess | getV1FormsByIdResponseError)

export const getGetV1FormsByIdUrl = (id: string,) => {




  return `/v1/forms/${id}`
}

/**
 * @summary Get a published form's public config
 */
export const getV1FormsById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<getV1FormsByIdResponse> => {

  return customFetch<getV1FormsByIdResponse>(getGetV1FormsByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1FormsByIdQueryKey = (id: string,) => {
    return [
    `/v1/forms/${id}`
    ] as const;
    }


export const getGetV1FormsByIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1FormsById>>, TError = GetV1FormsById404>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1FormsById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1FormsByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1FormsById>>> = ({ signal }) => getV1FormsById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1FormsById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetV1FormsByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1FormsById>>>
export type GetV1FormsByIdQueryError = GetV1FormsById404


/**
 * @summary Get a published form's public config
 */

export function useGetV1FormsById<TData = Awaited<ReturnType<typeof getV1FormsById>>, TError = GetV1FormsById404>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1FormsById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetV1FormsByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postV1FormsByIdChatSessionsResponse200 = {
  data: PostV1FormsByIdChatSessions200
  status: 200
}

export type postV1FormsByIdChatSessionsResponse404 = {
  data: void
  status: 404
}

export type postV1FormsByIdChatSessionsResponseSuccess = (postV1FormsByIdChatSessionsResponse200) & {
  headers: Headers;
};
export type postV1FormsByIdChatSessionsResponseError = (postV1FormsByIdChatSessionsResponse404) & {
  headers: Headers;
};

export type postV1FormsByIdChatSessionsResponse = (postV1FormsByIdChatSessionsResponseSuccess | postV1FormsByIdChatSessionsResponseError)

export const getPostV1FormsByIdChatSessionsUrl = (id: string,) => {




  return `/v1/forms/${id}/chat/sessions`
}

/**
 * @summary Start a chat session (headless)
 */
export const postV1FormsByIdChatSessions = async (id: string,
    postV1FormsByIdChatSessionsBody: PostV1FormsByIdChatSessionsBody, options?: Parameters<typeof customFetch>[1]): Promise<postV1FormsByIdChatSessionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postV1FormsByIdChatSessionsResponse>(getPostV1FormsByIdChatSessionsUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1FormsByIdChatSessionsBody)
  }
);}





export const getPostV1FormsByIdChatSessionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FormsByIdChatSessions>>, TError,PostV1FormsByIdChatSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FormsByIdChatSessions>>, TError,PostV1FormsByIdChatSessionsMutationVariables, TContext> => {

const mutationKey = ['postV1FormsByIdChatSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FormsByIdChatSessions>>, PostV1FormsByIdChatSessionsMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  postV1FormsByIdChatSessions(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1FormsByIdChatSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FormsByIdChatSessions>>>
    export type PostV1FormsByIdChatSessionsMutationBody = PostV1FormsByIdChatSessionsBody
    export type PostV1FormsByIdChatSessionsMutationError = void
    export type PostV1FormsByIdChatSessionsMutationVariables = {id: string;data: PostV1FormsByIdChatSessionsBody}

    /**
 * @summary Start a chat session (headless)
 */
export const usePostV1FormsByIdChatSessions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FormsByIdChatSessions>>, TError,PostV1FormsByIdChatSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1FormsByIdChatSessions>>,
        TError,
        PostV1FormsByIdChatSessionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostV1FormsByIdChatSessionsMutationOptions(options));
    }
    export type postV1ChatSessionsBySidMessagesResponse200 = {
  data: void
  status: 200
}

export type postV1ChatSessionsBySidMessagesResponse400 = {
  data: void
  status: 400
}

export type postV1ChatSessionsBySidMessagesResponseSuccess = (postV1ChatSessionsBySidMessagesResponse200) & {
  headers: Headers;
};
export type postV1ChatSessionsBySidMessagesResponseError = (postV1ChatSessionsBySidMessagesResponse400) & {
  headers: Headers;
};

export type postV1ChatSessionsBySidMessagesResponse = (postV1ChatSessionsBySidMessagesResponseSuccess | postV1ChatSessionsBySidMessagesResponseError)

export const getPostV1ChatSessionsBySidMessagesUrl = (sid: string,) => {




  return `/v1/chat/sessions/${sid}/messages`
}

/**
 * @summary Send a message / structured answer — synchronous response with next question
 */
export const postV1ChatSessionsBySidMessages = async (sid: string,
    postV1ChatSessionsBySidMessagesBody: PostV1ChatSessionsBySidMessagesBody, options?: Parameters<typeof customFetch>[1]): Promise<postV1ChatSessionsBySidMessagesResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postV1ChatSessionsBySidMessagesResponse>(getPostV1ChatSessionsBySidMessagesUrl(sid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postV1ChatSessionsBySidMessagesBody)
  }
);}





export const getPostV1ChatSessionsBySidMessagesMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ChatSessionsBySidMessages>>, TError,PostV1ChatSessionsBySidMessagesMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1ChatSessionsBySidMessages>>, TError,PostV1ChatSessionsBySidMessagesMutationVariables, TContext> => {

const mutationKey = ['postV1ChatSessionsBySidMessages'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ChatSessionsBySidMessages>>, PostV1ChatSessionsBySidMessagesMutationVariables> = (props) => {
          const {sid,data} = props ?? {};

          return  postV1ChatSessionsBySidMessages(sid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ChatSessionsBySidMessagesMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ChatSessionsBySidMessages>>>
    export type PostV1ChatSessionsBySidMessagesMutationBody = PostV1ChatSessionsBySidMessagesBody
    export type PostV1ChatSessionsBySidMessagesMutationError = void
    export type PostV1ChatSessionsBySidMessagesMutationVariables = {sid: string;data: PostV1ChatSessionsBySidMessagesBody}

    /**
 * @summary Send a message / structured answer — synchronous response with next question
 */
export const usePostV1ChatSessionsBySidMessages = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ChatSessionsBySidMessages>>, TError,PostV1ChatSessionsBySidMessagesMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1ChatSessionsBySidMessages>>,
        TError,
        PostV1ChatSessionsBySidMessagesMutationVariables,
        TContext
      > => {
      return useMutation(getPostV1ChatSessionsBySidMessagesMutationOptions(options));
    }
    export type getV1ChatSessionsBySidResponse200 = {
  data: unknown
  status: 200
}

export type getV1ChatSessionsBySidResponseSuccess = (getV1ChatSessionsBySidResponse200) & {
  headers: Headers;
};
;

export type getV1ChatSessionsBySidResponse = (getV1ChatSessionsBySidResponseSuccess)

export const getGetV1ChatSessionsBySidUrl = (sid: string,) => {




  return `/v1/chat/sessions/${sid}`
}

/**
 * @summary Get session state (status, answers, progress)
 */
export const getV1ChatSessionsBySid = async (sid: string, options?: Parameters<typeof customFetch>[1]): Promise<getV1ChatSessionsBySidResponse> => {

  return customFetch<getV1ChatSessionsBySidResponse>(getGetV1ChatSessionsBySidUrl(sid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ChatSessionsBySidQueryKey = (sid: string,) => {
    return [
    `/v1/chat/sessions/${sid}`
    ] as const;
    }


export const getGetV1ChatSessionsBySidQueryOptions = <TData = Awaited<ReturnType<typeof getV1ChatSessionsBySid>>, TError = unknown>(sid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1ChatSessionsBySid>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ChatSessionsBySidQueryKey(sid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1ChatSessionsBySid>>> = ({ signal }) => getV1ChatSessionsBySid(sid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: sid !== null && sid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1ChatSessionsBySid>>, TError, TData> & { queryKey: QueryKey }
}

export type GetV1ChatSessionsBySidQueryResult = NonNullable<Awaited<ReturnType<typeof getV1ChatSessionsBySid>>>
export type GetV1ChatSessionsBySidQueryError = unknown


/**
 * @summary Get session state (status, answers, progress)
 */

export function useGetV1ChatSessionsBySid<TData = Awaited<ReturnType<typeof getV1ChatSessionsBySid>>, TError = unknown>(
 sid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1ChatSessionsBySid>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetV1ChatSessionsBySidQueryOptions(sid,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






