/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiBillingEntitlements200,
  GetApiBillingPlans200,
  GetApiBillingUsage200,
  PostApiBillingChangePlanBody,
  PostApiBillingCheckout200,
  PostApiBillingCheckoutBody,
  PostApiBillingPortal200,
  PostApiBillingPreviewChangeBody
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiBillingPlansResponse200 = {
  data: GetApiBillingPlans200
  status: 200
}

export type getApiBillingPlansResponseSuccess = (getApiBillingPlansResponse200) & {
  headers: Headers;
};
;

export type getApiBillingPlansResponse = (getApiBillingPlansResponseSuccess)

export const getGetApiBillingPlansUrl = () => {




  return `http://localhost:8787/api/billing/plans`
}

/**
 * @summary Public plan catalogue
 */
export const getApiBillingPlans = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiBillingPlansResponse> => {

  return customFetch<getApiBillingPlansResponse>(getGetApiBillingPlansUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBillingPlansQueryKey = () => {
    return [
    `http://localhost:8787/api/billing/plans`
    ] as const;
    }


export const getGetApiBillingPlansQueryOptions = <TData = Awaited<ReturnType<typeof getApiBillingPlans>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingPlans>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBillingPlansQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillingPlans>>> = ({ signal }) => getApiBillingPlans({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBillingPlans>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBillingPlansQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBillingPlans>>>
export type GetApiBillingPlansQueryError = unknown


/**
 * @summary Public plan catalogue
 */

export function useGetApiBillingPlans<TData = Awaited<ReturnType<typeof getApiBillingPlans>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingPlans>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiBillingPlansQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiBillingEntitlementsResponse200 = {
  data: GetApiBillingEntitlements200
  status: 200
}

export type getApiBillingEntitlementsResponseSuccess = (getApiBillingEntitlementsResponse200) & {
  headers: Headers;
};
;

export type getApiBillingEntitlementsResponse = (getApiBillingEntitlementsResponseSuccess)

export const getGetApiBillingEntitlementsUrl = () => {




  return `http://localhost:8787/api/billing/entitlements`
}

/**
 * @summary Plan, features, limits, usage and permissions for the active organization
 */
export const getApiBillingEntitlements = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiBillingEntitlementsResponse> => {

  return customFetch<getApiBillingEntitlementsResponse>(getGetApiBillingEntitlementsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBillingEntitlementsQueryKey = () => {
    return [
    `http://localhost:8787/api/billing/entitlements`
    ] as const;
    }


export const getGetApiBillingEntitlementsQueryOptions = <TData = Awaited<ReturnType<typeof getApiBillingEntitlements>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingEntitlements>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBillingEntitlementsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillingEntitlements>>> = ({ signal }) => getApiBillingEntitlements({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBillingEntitlements>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBillingEntitlementsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBillingEntitlements>>>
export type GetApiBillingEntitlementsQueryError = unknown


/**
 * @summary Plan, features, limits, usage and permissions for the active organization
 */

export function useGetApiBillingEntitlements<TData = Awaited<ReturnType<typeof getApiBillingEntitlements>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingEntitlements>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiBillingEntitlementsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiBillingUsageResponse200 = {
  data: GetApiBillingUsage200
  status: 200
}

export type getApiBillingUsageResponseSuccess = (getApiBillingUsageResponse200) & {
  headers: Headers;
};
;

export type getApiBillingUsageResponse = (getApiBillingUsageResponseSuccess)

export const getGetApiBillingUsageUrl = () => {




  return `http://localhost:8787/api/billing/usage`
}

/**
 * @summary Current usage vs plan limits
 */
export const getApiBillingUsage = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiBillingUsageResponse> => {

  return customFetch<getApiBillingUsageResponse>(getGetApiBillingUsageUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBillingUsageQueryKey = () => {
    return [
    `http://localhost:8787/api/billing/usage`
    ] as const;
    }


export const getGetApiBillingUsageQueryOptions = <TData = Awaited<ReturnType<typeof getApiBillingUsage>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingUsage>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBillingUsageQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillingUsage>>> = ({ signal }) => getApiBillingUsage({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBillingUsage>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBillingUsageQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBillingUsage>>>
export type GetApiBillingUsageQueryError = unknown


/**
 * @summary Current usage vs plan limits
 */

export function useGetApiBillingUsage<TData = Awaited<ReturnType<typeof getApiBillingUsage>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingUsage>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiBillingUsageQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiBillingCheckoutResponse200 = {
  data: PostApiBillingCheckout200
  status: 200
}

export type postApiBillingCheckoutResponse409 = {
  data: void
  status: 409
}

export type postApiBillingCheckoutResponse503 = {
  data: void
  status: 503
}

export type postApiBillingCheckoutResponseSuccess = (postApiBillingCheckoutResponse200) & {
  headers: Headers;
};
export type postApiBillingCheckoutResponseError = (postApiBillingCheckoutResponse409 | postApiBillingCheckoutResponse503) & {
  headers: Headers;
};

export type postApiBillingCheckoutResponse = (postApiBillingCheckoutResponseSuccess | postApiBillingCheckoutResponseError)

export const getPostApiBillingCheckoutUrl = () => {




  return `http://localhost:8787/api/billing/checkout`
}

/**
 * @summary Start a Dodo checkout for a plan
 */
export const postApiBillingCheckout = async (postApiBillingCheckoutBody: PostApiBillingCheckoutBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiBillingCheckoutResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiBillingCheckoutResponse>(getPostApiBillingCheckoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiBillingCheckoutBody)
  }
);}





export const getPostApiBillingCheckoutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingCheckout>>, TError,PostApiBillingCheckoutMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBillingCheckout>>, TError,PostApiBillingCheckoutMutationVariables, TContext> => {

const mutationKey = ['postApiBillingCheckout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBillingCheckout>>, PostApiBillingCheckoutMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiBillingCheckout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBillingCheckoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBillingCheckout>>>
    export type PostApiBillingCheckoutMutationBody = PostApiBillingCheckoutBody
    export type PostApiBillingCheckoutMutationError = void
    export type PostApiBillingCheckoutMutationVariables = {data: PostApiBillingCheckoutBody}

    /**
 * @summary Start a Dodo checkout for a plan
 */
export const usePostApiBillingCheckout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingCheckout>>, TError,PostApiBillingCheckoutMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiBillingCheckout>>,
        TError,
        PostApiBillingCheckoutMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiBillingCheckoutMutationOptions(options));
    }
    export type postApiBillingPortalResponse200 = {
  data: PostApiBillingPortal200
  status: 200
}

export type postApiBillingPortalResponse404 = {
  data: void
  status: 404
}

export type postApiBillingPortalResponseSuccess = (postApiBillingPortalResponse200) & {
  headers: Headers;
};
export type postApiBillingPortalResponseError = (postApiBillingPortalResponse404) & {
  headers: Headers;
};

export type postApiBillingPortalResponse = (postApiBillingPortalResponseSuccess | postApiBillingPortalResponseError)

export const getPostApiBillingPortalUrl = () => {




  return `http://localhost:8787/api/billing/portal`
}

/**
 * @summary Open the Dodo customer portal
 */
export const postApiBillingPortal = async ( options?: Parameters<typeof customFetch>[1]): Promise<postApiBillingPortalResponse> => {

  return customFetch<postApiBillingPortalResponse>(getPostApiBillingPortalUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiBillingPortalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingPortal>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBillingPortal>>, TError,void, TContext> => {

const mutationKey = ['postApiBillingPortal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBillingPortal>>, void> = () => {


          return  postApiBillingPortal(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBillingPortalMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBillingPortal>>>

    export type PostApiBillingPortalMutationError = void


    /**
 * @summary Open the Dodo customer portal
 */
export const usePostApiBillingPortal = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingPortal>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiBillingPortal>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiBillingPortalMutationOptions(options));
    }
    export type postApiBillingPreviewChangeResponse200 = {
  data: void
  status: 200
}

export type postApiBillingPreviewChangeResponse404 = {
  data: void
  status: 404
}

export type postApiBillingPreviewChangeResponseSuccess = (postApiBillingPreviewChangeResponse200) & {
  headers: Headers;
};
export type postApiBillingPreviewChangeResponseError = (postApiBillingPreviewChangeResponse404) & {
  headers: Headers;
};

export type postApiBillingPreviewChangeResponse = (postApiBillingPreviewChangeResponseSuccess | postApiBillingPreviewChangeResponseError)

export const getPostApiBillingPreviewChangeUrl = () => {




  return `http://localhost:8787/api/billing/preview-change`
}

/**
 * @summary Quote a plan change before committing to it
 */
export const postApiBillingPreviewChange = async (postApiBillingPreviewChangeBody: PostApiBillingPreviewChangeBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiBillingPreviewChangeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiBillingPreviewChangeResponse>(getPostApiBillingPreviewChangeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiBillingPreviewChangeBody)
  }
);}





export const getPostApiBillingPreviewChangeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingPreviewChange>>, TError,PostApiBillingPreviewChangeMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBillingPreviewChange>>, TError,PostApiBillingPreviewChangeMutationVariables, TContext> => {

const mutationKey = ['postApiBillingPreviewChange'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBillingPreviewChange>>, PostApiBillingPreviewChangeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiBillingPreviewChange(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBillingPreviewChangeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBillingPreviewChange>>>
    export type PostApiBillingPreviewChangeMutationBody = PostApiBillingPreviewChangeBody
    export type PostApiBillingPreviewChangeMutationError = void
    export type PostApiBillingPreviewChangeMutationVariables = {data: PostApiBillingPreviewChangeBody}

    /**
 * @summary Quote a plan change before committing to it
 */
export const usePostApiBillingPreviewChange = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingPreviewChange>>, TError,PostApiBillingPreviewChangeMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiBillingPreviewChange>>,
        TError,
        PostApiBillingPreviewChangeMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiBillingPreviewChangeMutationOptions(options));
    }
    export type postApiBillingChangePlanResponse200 = {
  data: void
  status: 200
}

export type postApiBillingChangePlanResponse404 = {
  data: void
  status: 404
}

export type postApiBillingChangePlanResponseSuccess = (postApiBillingChangePlanResponse200) & {
  headers: Headers;
};
export type postApiBillingChangePlanResponseError = (postApiBillingChangePlanResponse404) & {
  headers: Headers;
};

export type postApiBillingChangePlanResponse = (postApiBillingChangePlanResponseSuccess | postApiBillingChangePlanResponseError)

export const getPostApiBillingChangePlanUrl = () => {




  return `http://localhost:8787/api/billing/change-plan`
}

/**
 * @summary Upgrade or downgrade an existing subscription
 */
export const postApiBillingChangePlan = async (postApiBillingChangePlanBody: PostApiBillingChangePlanBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiBillingChangePlanResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiBillingChangePlanResponse>(getPostApiBillingChangePlanUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiBillingChangePlanBody)
  }
);}





export const getPostApiBillingChangePlanMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingChangePlan>>, TError,PostApiBillingChangePlanMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBillingChangePlan>>, TError,PostApiBillingChangePlanMutationVariables, TContext> => {

const mutationKey = ['postApiBillingChangePlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBillingChangePlan>>, PostApiBillingChangePlanMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiBillingChangePlan(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBillingChangePlanMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBillingChangePlan>>>
    export type PostApiBillingChangePlanMutationBody = PostApiBillingChangePlanBody
    export type PostApiBillingChangePlanMutationError = void
    export type PostApiBillingChangePlanMutationVariables = {data: PostApiBillingChangePlanBody}

    /**
 * @summary Upgrade or downgrade an existing subscription
 */
export const usePostApiBillingChangePlan = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingChangePlan>>, TError,PostApiBillingChangePlanMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiBillingChangePlan>>,
        TError,
        PostApiBillingChangePlanMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiBillingChangePlanMutationOptions(options));
    }
    export type getApiBillingInvoicesResponse200 = {
  data: void
  status: 200
}

export type getApiBillingInvoicesResponseSuccess = (getApiBillingInvoicesResponse200) & {
  headers: Headers;
};
;

export type getApiBillingInvoicesResponse = (getApiBillingInvoicesResponseSuccess)

export const getGetApiBillingInvoicesUrl = () => {




  return `http://localhost:8787/api/billing/invoices`
}

/**
 * @summary Payment history
 */
export const getApiBillingInvoices = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiBillingInvoicesResponse> => {

  return customFetch<getApiBillingInvoicesResponse>(getGetApiBillingInvoicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBillingInvoicesQueryKey = () => {
    return [
    `http://localhost:8787/api/billing/invoices`
    ] as const;
    }


export const getGetApiBillingInvoicesQueryOptions = <TData = Awaited<ReturnType<typeof getApiBillingInvoices>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingInvoices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBillingInvoicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillingInvoices>>> = ({ signal }) => getApiBillingInvoices({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBillingInvoices>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBillingInvoicesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBillingInvoices>>>
export type GetApiBillingInvoicesQueryError = unknown


/**
 * @summary Payment history
 */

export function useGetApiBillingInvoices<TData = Awaited<ReturnType<typeof getApiBillingInvoices>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingInvoices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiBillingInvoicesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiBillingConfigCheckResponse200 = {
  data: void
  status: 200
}

export type getApiBillingConfigCheckResponseSuccess = (getApiBillingConfigCheckResponse200) & {
  headers: Headers;
};
;

export type getApiBillingConfigCheckResponse = (getApiBillingConfigCheckResponseSuccess)

export const getGetApiBillingConfigCheckUrl = () => {




  return `http://localhost:8787/api/billing/config-check`
}

/**
 * @summary Report missing billing configuration
 */
export const getApiBillingConfigCheck = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiBillingConfigCheckResponse> => {

  return customFetch<getApiBillingConfigCheckResponse>(getGetApiBillingConfigCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBillingConfigCheckQueryKey = () => {
    return [
    `http://localhost:8787/api/billing/config-check`
    ] as const;
    }


export const getGetApiBillingConfigCheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiBillingConfigCheck>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingConfigCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBillingConfigCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillingConfigCheck>>> = ({ signal }) => getApiBillingConfigCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBillingConfigCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBillingConfigCheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBillingConfigCheck>>>
export type GetApiBillingConfigCheckQueryError = unknown


/**
 * @summary Report missing billing configuration
 */

export function useGetApiBillingConfigCheck<TData = Awaited<ReturnType<typeof getApiBillingConfigCheck>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingConfigCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiBillingConfigCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






