/**
 * Generated by orval 🍺
 * Do not edit manually.
 * chatform API
 * Agentic chatbot forms platform. /p/* = public respondent surface, /v1/* = developer API (API key), /api/* = dashboard (session auth).
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiFormsById200,
  DeleteApiKeysById200,
  DeleteApiWebhooksById200,
  GetApiAuthOk200,
  GetApiBillingUsage200,
  GetApiForms200Item,
  GetApiFormsById200,
  GetApiFormsById404,
  GetApiFormsByIdAnalytics200,
  GetApiFormsByIdSubmissions200Item,
  GetApiFormsByIdSubmissionsParams,
  GetApiKeys200Item,
  GetApiTemplates200Item,
  GetApiWebhooks200Item,
  PostApiAiAddBlocks200,
  PostApiAiAddBlocksBody,
  PostApiAiGenerateForm200,
  PostApiAiGenerateFormBody,
  PostApiBillingCheckout200,
  PostApiBillingCheckoutBody,
  PostApiForms200,
  PostApiForms403,
  PostApiFormsBody,
  PostApiFormsByIdPreviewSessions200,
  PostApiFormsByIdPublish200,
  PostApiFormsByIdPublish422,
  PostApiKeys200,
  PostApiKeysBody,
  PostApiWebhooks200,
  PostApiWebhooksBody,
  PostApiWebhooksByIdTest200,
  PutApiFormsByIdDoc200,
  PutApiFormsByIdDocBody
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiAuthOkResponse200 = {
  data: GetApiAuthOk200
  status: 200
}

export type getApiAuthOkResponseSuccess = (getApiAuthOkResponse200) & {
  headers: Headers;
};
;

export type getApiAuthOkResponse = (getApiAuthOkResponseSuccess)

export const getGetApiAuthOkUrl = () => {




  return `http://localhost:8787/api/auth/ok`
}

/**
 * @summary Auth liveness check
 */
export const getApiAuthOk = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiAuthOkResponse> => {

  return customFetch<getApiAuthOkResponse>(getGetApiAuthOkUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAuthOkQueryKey = () => {
    return [
    `http://localhost:8787/api/auth/ok`
    ] as const;
    }


export const getGetApiAuthOkQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthOkQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthOk>>> = ({ signal }) => getApiAuthOk({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAuthOkQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthOk>>>
export type GetApiAuthOkQueryError = unknown


/**
 * @summary Auth liveness check
 */

export function useGetApiAuthOk<TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAuthOkQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiFormsResponse200 = {
  data: GetApiForms200Item[]
  status: 200
}

export type getApiFormsResponseSuccess = (getApiFormsResponse200) & {
  headers: Headers;
};
;

export type getApiFormsResponse = (getApiFormsResponseSuccess)

export const getGetApiFormsUrl = () => {




  return `http://localhost:8787/api/forms`
}

/**
 * @summary List forms in the active workspace
 */
export const getApiForms = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiFormsResponse> => {

  return customFetch<getApiFormsResponse>(getGetApiFormsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFormsQueryKey = () => {
    return [
    `http://localhost:8787/api/forms`
    ] as const;
    }


export const getGetApiFormsQueryOptions = <TData = Awaited<ReturnType<typeof getApiForms>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiForms>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFormsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiForms>>> = ({ signal }) => getApiForms({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiForms>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiFormsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiForms>>>
export type GetApiFormsQueryError = unknown


/**
 * @summary List forms in the active workspace
 */

export function useGetApiForms<TData = Awaited<ReturnType<typeof getApiForms>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiForms>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiFormsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiFormsResponse200 = {
  data: PostApiForms200
  status: 200
}

export type postApiFormsResponse403 = {
  data: PostApiForms403
  status: 403
}

export type postApiFormsResponseSuccess = (postApiFormsResponse200) & {
  headers: Headers;
};
export type postApiFormsResponseError = (postApiFormsResponse403) & {
  headers: Headers;
};

export type postApiFormsResponse = (postApiFormsResponseSuccess | postApiFormsResponseError)

export const getPostApiFormsUrl = () => {




  return `http://localhost:8787/api/forms`
}

/**
 * @summary Create a form
 */
export const postApiForms = async (postApiFormsBody: PostApiFormsBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiFormsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiFormsResponse>(getPostApiFormsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiFormsBody)
  }
);}





export const getPostApiFormsMutationOptions = <TError = PostApiForms403,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiForms>>, TError,PostApiFormsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiForms>>, TError,PostApiFormsMutationVariables, TContext> => {

const mutationKey = ['postApiForms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiForms>>, PostApiFormsMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiForms(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiFormsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiForms>>>
    export type PostApiFormsMutationBody = PostApiFormsBody
    export type PostApiFormsMutationError = PostApiForms403
    export type PostApiFormsMutationVariables = {data: PostApiFormsBody}

    /**
 * @summary Create a form
 */
export const usePostApiForms = <TError = PostApiForms403,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiForms>>, TError,PostApiFormsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiForms>>,
        TError,
        PostApiFormsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiFormsMutationOptions(options));
    }
    export type deleteApiFormsByIdResponse200 = {
  data: DeleteApiFormsById200
  status: 200
}

export type deleteApiFormsByIdResponseSuccess = (deleteApiFormsByIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiFormsByIdResponse = (deleteApiFormsByIdResponseSuccess)

export const getDeleteApiFormsByIdUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}`
}

/**
 * @summary Soft-delete a form
 */
export const deleteApiFormsById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteApiFormsByIdResponse> => {

  return customFetch<deleteApiFormsByIdResponse>(getDeleteApiFormsByIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiFormsByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFormsById>>, TError,DeleteApiFormsByIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiFormsById>>, TError,DeleteApiFormsByIdMutationVariables, TContext> => {

const mutationKey = ['deleteApiFormsById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiFormsById>>, DeleteApiFormsByIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiFormsById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiFormsByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiFormsById>>>

    export type DeleteApiFormsByIdMutationError = unknown
    export type DeleteApiFormsByIdMutationVariables = {id: string}

    /**
 * @summary Soft-delete a form
 */
export const useDeleteApiFormsById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFormsById>>, TError,DeleteApiFormsByIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiFormsById>>,
        TError,
        DeleteApiFormsByIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiFormsByIdMutationOptions(options));
    }
    export type getApiFormsByIdResponse200 = {
  data: GetApiFormsById200
  status: 200
}

export type getApiFormsByIdResponse404 = {
  data: GetApiFormsById404
  status: 404
}

export type getApiFormsByIdResponseSuccess = (getApiFormsByIdResponse200) & {
  headers: Headers;
};
export type getApiFormsByIdResponseError = (getApiFormsByIdResponse404) & {
  headers: Headers;
};

export type getApiFormsByIdResponse = (getApiFormsByIdResponseSuccess | getApiFormsByIdResponseError)

export const getGetApiFormsByIdUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}`
}

/**
 * @summary Get a form with its working document
 */
export const getApiFormsById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<getApiFormsByIdResponse> => {

  return customFetch<getApiFormsByIdResponse>(getGetApiFormsByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFormsByIdQueryKey = (id: string,) => {
    return [
    `http://localhost:8787/api/forms/${id}`
    ] as const;
    }


export const getGetApiFormsByIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiFormsById>>, TError = GetApiFormsById404>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFormsByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFormsById>>> = ({ signal }) => getApiFormsById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFormsById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiFormsByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFormsById>>>
export type GetApiFormsByIdQueryError = GetApiFormsById404


/**
 * @summary Get a form with its working document
 */

export function useGetApiFormsById<TData = Awaited<ReturnType<typeof getApiFormsById>>, TError = GetApiFormsById404>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsById>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiFormsByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putApiFormsByIdDocResponse200 = {
  data: PutApiFormsByIdDoc200
  status: 200
}

export type putApiFormsByIdDocResponseSuccess = (putApiFormsByIdDocResponse200) & {
  headers: Headers;
};
;

export type putApiFormsByIdDocResponse = (putApiFormsByIdDocResponseSuccess)

export const getPutApiFormsByIdDocUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}/doc`
}

/**
 * @summary Update the working document (autosave target)
 */
export const putApiFormsByIdDoc = async (id: string,
    putApiFormsByIdDocBody: PutApiFormsByIdDocBody, options?: Parameters<typeof customFetch>[1]): Promise<putApiFormsByIdDocResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<putApiFormsByIdDocResponse>(getPutApiFormsByIdDocUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(putApiFormsByIdDocBody)
  }
);}





export const getPutApiFormsByIdDocMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiFormsByIdDoc>>, TError,PutApiFormsByIdDocMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiFormsByIdDoc>>, TError,PutApiFormsByIdDocMutationVariables, TContext> => {

const mutationKey = ['putApiFormsByIdDoc'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiFormsByIdDoc>>, PutApiFormsByIdDocMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putApiFormsByIdDoc(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiFormsByIdDocMutationResult = NonNullable<Awaited<ReturnType<typeof putApiFormsByIdDoc>>>
    export type PutApiFormsByIdDocMutationBody = PutApiFormsByIdDocBody
    export type PutApiFormsByIdDocMutationError = unknown
    export type PutApiFormsByIdDocMutationVariables = {id: string;data: PutApiFormsByIdDocBody}

    /**
 * @summary Update the working document (autosave target)
 */
export const usePutApiFormsByIdDoc = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiFormsByIdDoc>>, TError,PutApiFormsByIdDocMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putApiFormsByIdDoc>>,
        TError,
        PutApiFormsByIdDocMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiFormsByIdDocMutationOptions(options));
    }
    export type postApiFormsByIdPublishResponse200 = {
  data: PostApiFormsByIdPublish200
  status: 200
}

export type postApiFormsByIdPublishResponse422 = {
  data: PostApiFormsByIdPublish422
  status: 422
}

export type postApiFormsByIdPublishResponseSuccess = (postApiFormsByIdPublishResponse200) & {
  headers: Headers;
};
export type postApiFormsByIdPublishResponseError = (postApiFormsByIdPublishResponse422) & {
  headers: Headers;
};

export type postApiFormsByIdPublishResponse = (postApiFormsByIdPublishResponseSuccess | postApiFormsByIdPublishResponseError)

export const getPostApiFormsByIdPublishUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}/publish`
}

/**
 * @summary Publish the working document as a new version
 */
export const postApiFormsByIdPublish = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiFormsByIdPublishResponse> => {

  return customFetch<postApiFormsByIdPublishResponse>(getPostApiFormsByIdPublishUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiFormsByIdPublishMutationOptions = <TError = PostApiFormsByIdPublish422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFormsByIdPublish>>, TError,PostApiFormsByIdPublishMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiFormsByIdPublish>>, TError,PostApiFormsByIdPublishMutationVariables, TContext> => {

const mutationKey = ['postApiFormsByIdPublish'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiFormsByIdPublish>>, PostApiFormsByIdPublishMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  postApiFormsByIdPublish(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiFormsByIdPublishMutationResult = NonNullable<Awaited<ReturnType<typeof postApiFormsByIdPublish>>>

    export type PostApiFormsByIdPublishMutationError = PostApiFormsByIdPublish422
    export type PostApiFormsByIdPublishMutationVariables = {id: string}

    /**
 * @summary Publish the working document as a new version
 */
export const usePostApiFormsByIdPublish = <TError = PostApiFormsByIdPublish422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFormsByIdPublish>>, TError,PostApiFormsByIdPublishMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiFormsByIdPublish>>,
        TError,
        PostApiFormsByIdPublishMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiFormsByIdPublishMutationOptions(options));
    }
    export type postApiAiGenerateFormResponse200 = {
  data: PostApiAiGenerateForm200
  status: 200
}

export type postApiAiGenerateFormResponse502 = {
  data: void
  status: 502
}

export type postApiAiGenerateFormResponse503 = {
  data: void
  status: 503
}

export type postApiAiGenerateFormResponseSuccess = (postApiAiGenerateFormResponse200) & {
  headers: Headers;
};
export type postApiAiGenerateFormResponseError = (postApiAiGenerateFormResponse502 | postApiAiGenerateFormResponse503) & {
  headers: Headers;
};

export type postApiAiGenerateFormResponse = (postApiAiGenerateFormResponseSuccess | postApiAiGenerateFormResponseError)

export const getPostApiAiGenerateFormUrl = () => {




  return `http://localhost:8787/api/ai/generate-form`
}

/**
 * @summary Generate a form document from a natural-language prompt
 */
export const postApiAiGenerateForm = async (postApiAiGenerateFormBody: PostApiAiGenerateFormBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiAiGenerateFormResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiAiGenerateFormResponse>(getPostApiAiGenerateFormUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAiGenerateFormBody)
  }
);}





export const getPostApiAiGenerateFormMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAiGenerateForm>>, TError,PostApiAiGenerateFormMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAiGenerateForm>>, TError,PostApiAiGenerateFormMutationVariables, TContext> => {

const mutationKey = ['postApiAiGenerateForm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAiGenerateForm>>, PostApiAiGenerateFormMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAiGenerateForm(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAiGenerateFormMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAiGenerateForm>>>
    export type PostApiAiGenerateFormMutationBody = PostApiAiGenerateFormBody
    export type PostApiAiGenerateFormMutationError = void
    export type PostApiAiGenerateFormMutationVariables = {data: PostApiAiGenerateFormBody}

    /**
 * @summary Generate a form document from a natural-language prompt
 */
export const usePostApiAiGenerateForm = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAiGenerateForm>>, TError,PostApiAiGenerateFormMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAiGenerateForm>>,
        TError,
        PostApiAiGenerateFormMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAiGenerateFormMutationOptions(options));
    }
    export type postApiAiAddBlocksResponse200 = {
  data: PostApiAiAddBlocks200
  status: 200
}

export type postApiAiAddBlocksResponse503 = {
  data: void
  status: 503
}

export type postApiAiAddBlocksResponseSuccess = (postApiAiAddBlocksResponse200) & {
  headers: Headers;
};
export type postApiAiAddBlocksResponseError = (postApiAiAddBlocksResponse503) & {
  headers: Headers;
};

export type postApiAiAddBlocksResponse = (postApiAiAddBlocksResponseSuccess | postApiAiAddBlocksResponseError)

export const getPostApiAiAddBlocksUrl = () => {




  return `http://localhost:8787/api/ai/add-blocks`
}

/**
 * @summary AI-generate additional blocks appended to an existing form
 */
export const postApiAiAddBlocks = async (postApiAiAddBlocksBody: PostApiAiAddBlocksBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiAiAddBlocksResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiAiAddBlocksResponse>(getPostApiAiAddBlocksUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAiAddBlocksBody)
  }
);}





export const getPostApiAiAddBlocksMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAiAddBlocks>>, TError,PostApiAiAddBlocksMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAiAddBlocks>>, TError,PostApiAiAddBlocksMutationVariables, TContext> => {

const mutationKey = ['postApiAiAddBlocks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAiAddBlocks>>, PostApiAiAddBlocksMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAiAddBlocks(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAiAddBlocksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAiAddBlocks>>>
    export type PostApiAiAddBlocksMutationBody = PostApiAiAddBlocksBody
    export type PostApiAiAddBlocksMutationError = void
    export type PostApiAiAddBlocksMutationVariables = {data: PostApiAiAddBlocksBody}

    /**
 * @summary AI-generate additional blocks appended to an existing form
 */
export const usePostApiAiAddBlocks = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAiAddBlocks>>, TError,PostApiAiAddBlocksMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAiAddBlocks>>,
        TError,
        PostApiAiAddBlocksMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAiAddBlocksMutationOptions(options));
    }
    export type getApiFormsByIdSubmissionsResponse200 = {
  data: GetApiFormsByIdSubmissions200Item[]
  status: 200
}

export type getApiFormsByIdSubmissionsResponseSuccess = (getApiFormsByIdSubmissionsResponse200) & {
  headers: Headers;
};
;

export type getApiFormsByIdSubmissionsResponse = (getApiFormsByIdSubmissionsResponseSuccess)

export const getGetApiFormsByIdSubmissionsUrl = (id: string,
    params?: GetApiFormsByIdSubmissionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8787/api/forms/${id}/submissions?${stringifiedParams}` : `http://localhost:8787/api/forms/${id}/submissions`
}

/**
 * @summary List submissions (with answers + transcripts)
 */
export const getApiFormsByIdSubmissions = async (id: string,
    params?: GetApiFormsByIdSubmissionsParams, options?: Parameters<typeof customFetch>[1]): Promise<getApiFormsByIdSubmissionsResponse> => {

  return customFetch<getApiFormsByIdSubmissionsResponse>(getGetApiFormsByIdSubmissionsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFormsByIdSubmissionsQueryKey = (id: string,
    params?: GetApiFormsByIdSubmissionsParams,) => {
    return [
    `http://localhost:8787/api/forms/${id}/submissions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiFormsByIdSubmissionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>, TError = unknown>(id: string,
    params?: GetApiFormsByIdSubmissionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFormsByIdSubmissionsQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>> = ({ signal }) => getApiFormsByIdSubmissions(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiFormsByIdSubmissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>>
export type GetApiFormsByIdSubmissionsQueryError = unknown


/**
 * @summary List submissions (with answers + transcripts)
 */

export function useGetApiFormsByIdSubmissions<TData = Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>, TError = unknown>(
 id: string,
    params?: GetApiFormsByIdSubmissionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdSubmissions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiFormsByIdSubmissionsQueryOptions(id,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiFormsByIdSubmissionsExportResponse200 = {
  data: string
  status: 200
}

export type getApiFormsByIdSubmissionsExportResponse404 = {
  data: void
  status: 404
}

export type getApiFormsByIdSubmissionsExportResponseSuccess = (getApiFormsByIdSubmissionsExportResponse200) & {
  headers: Headers;
};
export type getApiFormsByIdSubmissionsExportResponseError = (getApiFormsByIdSubmissionsExportResponse404) & {
  headers: Headers;
};

export type getApiFormsByIdSubmissionsExportResponse = (getApiFormsByIdSubmissionsExportResponseSuccess | getApiFormsByIdSubmissionsExportResponseError)

export const getGetApiFormsByIdSubmissionsExportUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}/submissions/export`
}

/**
 * @summary Export submissions as CSV
 */
export const getApiFormsByIdSubmissionsExport = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<getApiFormsByIdSubmissionsExportResponse> => {

  return customFetch<getApiFormsByIdSubmissionsExportResponse>(getGetApiFormsByIdSubmissionsExportUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFormsByIdSubmissionsExportQueryKey = (id: string,) => {
    return [
    `http://localhost:8787/api/forms/${id}/submissions/export`
    ] as const;
    }


export const getGetApiFormsByIdSubmissionsExportQueryOptions = <TData = Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>, TError = void>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFormsByIdSubmissionsExportQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>> = ({ signal }) => getApiFormsByIdSubmissionsExport(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiFormsByIdSubmissionsExportQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>>
export type GetApiFormsByIdSubmissionsExportQueryError = void


/**
 * @summary Export submissions as CSV
 */

export function useGetApiFormsByIdSubmissionsExport<TData = Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>, TError = void>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdSubmissionsExport>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiFormsByIdSubmissionsExportQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiFormsByIdAnalyticsResponse200 = {
  data: GetApiFormsByIdAnalytics200
  status: 200
}

export type getApiFormsByIdAnalyticsResponseSuccess = (getApiFormsByIdAnalyticsResponse200) & {
  headers: Headers;
};
;

export type getApiFormsByIdAnalyticsResponse = (getApiFormsByIdAnalyticsResponseSuccess)

export const getGetApiFormsByIdAnalyticsUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}/analytics`
}

/**
 * @summary Analytics summary (counts + per-block funnel)
 */
export const getApiFormsByIdAnalytics = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<getApiFormsByIdAnalyticsResponse> => {

  return customFetch<getApiFormsByIdAnalyticsResponse>(getGetApiFormsByIdAnalyticsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFormsByIdAnalyticsQueryKey = (id: string,) => {
    return [
    `http://localhost:8787/api/forms/${id}/analytics`
    ] as const;
    }


export const getGetApiFormsByIdAnalyticsQueryOptions = <TData = Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFormsByIdAnalyticsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>> = ({ signal }) => getApiFormsByIdAnalytics(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiFormsByIdAnalyticsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>>
export type GetApiFormsByIdAnalyticsQueryError = unknown


/**
 * @summary Analytics summary (counts + per-block funnel)
 */

export function useGetApiFormsByIdAnalytics<TData = Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiFormsByIdAnalytics>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiFormsByIdAnalyticsQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiKeysResponse200 = {
  data: GetApiKeys200Item[]
  status: 200
}

export type getApiKeysResponseSuccess = (getApiKeysResponse200) & {
  headers: Headers;
};
;

export type getApiKeysResponse = (getApiKeysResponseSuccess)

export const getGetApiKeysUrl = () => {




  return `http://localhost:8787/api/keys`
}

/**
 * @summary List my API keys (metadata only)
 */
export const getApiKeys = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiKeysResponse> => {

  return customFetch<getApiKeysResponse>(getGetApiKeysUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiKeysQueryKey = () => {
    return [
    `http://localhost:8787/api/keys`
    ] as const;
    }


export const getGetApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof getApiKeys>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiKeysQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiKeys>>> = ({ signal }) => getApiKeys({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getApiKeys>>>
export type GetApiKeysQueryError = unknown


/**
 * @summary List my API keys (metadata only)
 */

export function useGetApiKeys<TData = Awaited<ReturnType<typeof getApiKeys>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiKeysQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiKeysResponse200 = {
  data: PostApiKeys200
  status: 200
}

export type postApiKeysResponseSuccess = (postApiKeysResponse200) & {
  headers: Headers;
};
;

export type postApiKeysResponse = (postApiKeysResponseSuccess)

export const getPostApiKeysUrl = () => {




  return `http://localhost:8787/api/keys`
}

/**
 * @summary Create an API key — raw key shown ONCE
 */
export const postApiKeys = async (postApiKeysBody: PostApiKeysBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiKeysResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiKeysResponse>(getPostApiKeysUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiKeysBody)
  }
);}





export const getPostApiKeysMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiKeys>>, TError,PostApiKeysMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiKeys>>, TError,PostApiKeysMutationVariables, TContext> => {

const mutationKey = ['postApiKeys'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiKeys>>, PostApiKeysMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiKeys(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiKeysMutationResult = NonNullable<Awaited<ReturnType<typeof postApiKeys>>>
    export type PostApiKeysMutationBody = PostApiKeysBody
    export type PostApiKeysMutationError = unknown
    export type PostApiKeysMutationVariables = {data: PostApiKeysBody}

    /**
 * @summary Create an API key — raw key shown ONCE
 */
export const usePostApiKeys = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiKeys>>, TError,PostApiKeysMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiKeys>>,
        TError,
        PostApiKeysMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiKeysMutationOptions(options));
    }
    export type deleteApiKeysByIdResponse200 = {
  data: DeleteApiKeysById200
  status: 200
}

export type deleteApiKeysByIdResponseSuccess = (deleteApiKeysByIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiKeysByIdResponse = (deleteApiKeysByIdResponseSuccess)

export const getDeleteApiKeysByIdUrl = (id: string,) => {




  return `http://localhost:8787/api/keys/${id}`
}

/**
 * @summary Revoke an API key
 */
export const deleteApiKeysById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteApiKeysByIdResponse> => {

  return customFetch<deleteApiKeysByIdResponse>(getDeleteApiKeysByIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiKeysByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysById>>, TError,DeleteApiKeysByIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysById>>, TError,DeleteApiKeysByIdMutationVariables, TContext> => {

const mutationKey = ['deleteApiKeysById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiKeysById>>, DeleteApiKeysByIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiKeysById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiKeysByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiKeysById>>>

    export type DeleteApiKeysByIdMutationError = unknown
    export type DeleteApiKeysByIdMutationVariables = {id: string}

    /**
 * @summary Revoke an API key
 */
export const useDeleteApiKeysById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysById>>, TError,DeleteApiKeysByIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiKeysById>>,
        TError,
        DeleteApiKeysByIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiKeysByIdMutationOptions(options));
    }
    export type getApiWebhooksResponse200 = {
  data: GetApiWebhooks200Item[]
  status: 200
}

export type getApiWebhooksResponseSuccess = (getApiWebhooksResponse200) & {
  headers: Headers;
};
;

export type getApiWebhooksResponse = (getApiWebhooksResponseSuccess)

export const getGetApiWebhooksUrl = () => {




  return `http://localhost:8787/api/webhooks`
}

/**
 * @summary List webhooks
 */
export const getApiWebhooks = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiWebhooksResponse> => {

  return customFetch<getApiWebhooksResponse>(getGetApiWebhooksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiWebhooksQueryKey = () => {
    return [
    `http://localhost:8787/api/webhooks`
    ] as const;
    }


export const getGetApiWebhooksQueryOptions = <TData = Awaited<ReturnType<typeof getApiWebhooks>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiWebhooks>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWebhooksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWebhooks>>> = ({ signal }) => getApiWebhooks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWebhooks>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiWebhooksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWebhooks>>>
export type GetApiWebhooksQueryError = unknown


/**
 * @summary List webhooks
 */

export function useGetApiWebhooks<TData = Awaited<ReturnType<typeof getApiWebhooks>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiWebhooks>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiWebhooksQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiWebhooksResponse200 = {
  data: PostApiWebhooks200
  status: 200
}

export type postApiWebhooksResponseSuccess = (postApiWebhooksResponse200) & {
  headers: Headers;
};
;

export type postApiWebhooksResponse = (postApiWebhooksResponseSuccess)

export const getPostApiWebhooksUrl = () => {




  return `http://localhost:8787/api/webhooks`
}

/**
 * @summary Create a webhook (secret returned once)
 */
export const postApiWebhooks = async (postApiWebhooksBody: PostApiWebhooksBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiWebhooksResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiWebhooksResponse>(getPostApiWebhooksUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiWebhooksBody)
  }
);}





export const getPostApiWebhooksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWebhooks>>, TError,PostApiWebhooksMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWebhooks>>, TError,PostApiWebhooksMutationVariables, TContext> => {

const mutationKey = ['postApiWebhooks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWebhooks>>, PostApiWebhooksMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiWebhooks(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiWebhooksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWebhooks>>>
    export type PostApiWebhooksMutationBody = PostApiWebhooksBody
    export type PostApiWebhooksMutationError = unknown
    export type PostApiWebhooksMutationVariables = {data: PostApiWebhooksBody}

    /**
 * @summary Create a webhook (secret returned once)
 */
export const usePostApiWebhooks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWebhooks>>, TError,PostApiWebhooksMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiWebhooks>>,
        TError,
        PostApiWebhooksMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiWebhooksMutationOptions(options));
    }
    export type deleteApiWebhooksByIdResponse200 = {
  data: DeleteApiWebhooksById200
  status: 200
}

export type deleteApiWebhooksByIdResponseSuccess = (deleteApiWebhooksByIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiWebhooksByIdResponse = (deleteApiWebhooksByIdResponseSuccess)

export const getDeleteApiWebhooksByIdUrl = (id: string,) => {




  return `http://localhost:8787/api/webhooks/${id}`
}

/**
 * @summary Delete a webhook
 */
export const deleteApiWebhooksById = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<deleteApiWebhooksByIdResponse> => {

  return customFetch<deleteApiWebhooksByIdResponse>(getDeleteApiWebhooksByIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiWebhooksByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWebhooksById>>, TError,DeleteApiWebhooksByIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiWebhooksById>>, TError,DeleteApiWebhooksByIdMutationVariables, TContext> => {

const mutationKey = ['deleteApiWebhooksById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiWebhooksById>>, DeleteApiWebhooksByIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiWebhooksById(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiWebhooksByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiWebhooksById>>>

    export type DeleteApiWebhooksByIdMutationError = unknown
    export type DeleteApiWebhooksByIdMutationVariables = {id: string}

    /**
 * @summary Delete a webhook
 */
export const useDeleteApiWebhooksById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWebhooksById>>, TError,DeleteApiWebhooksByIdMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiWebhooksById>>,
        TError,
        DeleteApiWebhooksByIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiWebhooksByIdMutationOptions(options));
    }
    export type getApiWebhooksByIdDeliveriesResponse200 = {
  data: unknown[]
  status: 200
}

export type getApiWebhooksByIdDeliveriesResponseSuccess = (getApiWebhooksByIdDeliveriesResponse200) & {
  headers: Headers;
};
;

export type getApiWebhooksByIdDeliveriesResponse = (getApiWebhooksByIdDeliveriesResponseSuccess)

export const getGetApiWebhooksByIdDeliveriesUrl = (id: string,) => {




  return `http://localhost:8787/api/webhooks/${id}/deliveries`
}

/**
 * @summary Recent deliveries for a webhook
 */
export const getApiWebhooksByIdDeliveries = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<getApiWebhooksByIdDeliveriesResponse> => {

  return customFetch<getApiWebhooksByIdDeliveriesResponse>(getGetApiWebhooksByIdDeliveriesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiWebhooksByIdDeliveriesQueryKey = (id: string,) => {
    return [
    `http://localhost:8787/api/webhooks/${id}/deliveries`
    ] as const;
    }


export const getGetApiWebhooksByIdDeliveriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWebhooksByIdDeliveriesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>> = ({ signal }) => getApiWebhooksByIdDeliveries(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiWebhooksByIdDeliveriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>>
export type GetApiWebhooksByIdDeliveriesQueryError = unknown


/**
 * @summary Recent deliveries for a webhook
 */

export function useGetApiWebhooksByIdDeliveries<TData = Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiWebhooksByIdDeliveries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiWebhooksByIdDeliveriesQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiWebhooksByIdTestResponse200 = {
  data: PostApiWebhooksByIdTest200
  status: 200
}

export type postApiWebhooksByIdTestResponseSuccess = (postApiWebhooksByIdTestResponse200) & {
  headers: Headers;
};
;

export type postApiWebhooksByIdTestResponse = (postApiWebhooksByIdTestResponseSuccess)

export const getPostApiWebhooksByIdTestUrl = (id: string,) => {




  return `http://localhost:8787/api/webhooks/${id}/test`
}

/**
 * @summary Send a signed test event
 */
export const postApiWebhooksByIdTest = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiWebhooksByIdTestResponse> => {

  return customFetch<postApiWebhooksByIdTestResponse>(getPostApiWebhooksByIdTestUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiWebhooksByIdTestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWebhooksByIdTest>>, TError,PostApiWebhooksByIdTestMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWebhooksByIdTest>>, TError,PostApiWebhooksByIdTestMutationVariables, TContext> => {

const mutationKey = ['postApiWebhooksByIdTest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWebhooksByIdTest>>, PostApiWebhooksByIdTestMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  postApiWebhooksByIdTest(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiWebhooksByIdTestMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWebhooksByIdTest>>>

    export type PostApiWebhooksByIdTestMutationError = unknown
    export type PostApiWebhooksByIdTestMutationVariables = {id: string}

    /**
 * @summary Send a signed test event
 */
export const usePostApiWebhooksByIdTest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWebhooksByIdTest>>, TError,PostApiWebhooksByIdTestMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiWebhooksByIdTest>>,
        TError,
        PostApiWebhooksByIdTestMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiWebhooksByIdTestMutationOptions(options));
    }
    export type getApiBillingUsageResponse200 = {
  data: GetApiBillingUsage200
  status: 200
}

export type getApiBillingUsageResponseSuccess = (getApiBillingUsageResponse200) & {
  headers: Headers;
};
;

export type getApiBillingUsageResponse = (getApiBillingUsageResponseSuccess)

export const getGetApiBillingUsageUrl = () => {




  return `http://localhost:8787/api/billing/usage`
}

/**
 * @summary Current usage vs plan limits
 */
export const getApiBillingUsage = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiBillingUsageResponse> => {

  return customFetch<getApiBillingUsageResponse>(getGetApiBillingUsageUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBillingUsageQueryKey = () => {
    return [
    `http://localhost:8787/api/billing/usage`
    ] as const;
    }


export const getGetApiBillingUsageQueryOptions = <TData = Awaited<ReturnType<typeof getApiBillingUsage>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingUsage>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBillingUsageQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBillingUsage>>> = ({ signal }) => getApiBillingUsage({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBillingUsage>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiBillingUsageQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBillingUsage>>>
export type GetApiBillingUsageQueryError = unknown


/**
 * @summary Current usage vs plan limits
 */

export function useGetApiBillingUsage<TData = Awaited<ReturnType<typeof getApiBillingUsage>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiBillingUsage>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiBillingUsageQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiBillingCheckoutResponse200 = {
  data: PostApiBillingCheckout200
  status: 200
}

export type postApiBillingCheckoutResponse503 = {
  data: void
  status: 503
}

export type postApiBillingCheckoutResponseSuccess = (postApiBillingCheckoutResponse200) & {
  headers: Headers;
};
export type postApiBillingCheckoutResponseError = (postApiBillingCheckoutResponse503) & {
  headers: Headers;
};

export type postApiBillingCheckoutResponse = (postApiBillingCheckoutResponseSuccess | postApiBillingCheckoutResponseError)

export const getPostApiBillingCheckoutUrl = () => {




  return `http://localhost:8787/api/billing/checkout`
}

/**
 * @summary Create a Dodo checkout session
 */
export const postApiBillingCheckout = async (postApiBillingCheckoutBody: PostApiBillingCheckoutBody, options?: Parameters<typeof customFetch>[1]): Promise<postApiBillingCheckoutResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<postApiBillingCheckoutResponse>(getPostApiBillingCheckoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiBillingCheckoutBody)
  }
);}





export const getPostApiBillingCheckoutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingCheckout>>, TError,PostApiBillingCheckoutMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBillingCheckout>>, TError,PostApiBillingCheckoutMutationVariables, TContext> => {

const mutationKey = ['postApiBillingCheckout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBillingCheckout>>, PostApiBillingCheckoutMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiBillingCheckout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBillingCheckoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBillingCheckout>>>
    export type PostApiBillingCheckoutMutationBody = PostApiBillingCheckoutBody
    export type PostApiBillingCheckoutMutationError = void
    export type PostApiBillingCheckoutMutationVariables = {data: PostApiBillingCheckoutBody}

    /**
 * @summary Create a Dodo checkout session
 */
export const usePostApiBillingCheckout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBillingCheckout>>, TError,PostApiBillingCheckoutMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiBillingCheckout>>,
        TError,
        PostApiBillingCheckoutMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiBillingCheckoutMutationOptions(options));
    }
    export type postApiFormsByIdPreviewSessionsResponse200 = {
  data: PostApiFormsByIdPreviewSessions200
  status: 200
}

export type postApiFormsByIdPreviewSessionsResponse404 = {
  data: void
  status: 404
}

export type postApiFormsByIdPreviewSessionsResponseSuccess = (postApiFormsByIdPreviewSessionsResponse200) & {
  headers: Headers;
};
export type postApiFormsByIdPreviewSessionsResponseError = (postApiFormsByIdPreviewSessionsResponse404) & {
  headers: Headers;
};

export type postApiFormsByIdPreviewSessionsResponse = (postApiFormsByIdPreviewSessionsResponseSuccess | postApiFormsByIdPreviewSessionsResponseError)

export const getPostApiFormsByIdPreviewSessionsUrl = (id: string,) => {




  return `http://localhost:8787/api/forms/${id}/preview/sessions`
}

/**
 * @summary Start a preview chat session against the working draft
 */
export const postApiFormsByIdPreviewSessions = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiFormsByIdPreviewSessionsResponse> => {

  return customFetch<postApiFormsByIdPreviewSessionsResponse>(getPostApiFormsByIdPreviewSessionsUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiFormsByIdPreviewSessionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFormsByIdPreviewSessions>>, TError,PostApiFormsByIdPreviewSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiFormsByIdPreviewSessions>>, TError,PostApiFormsByIdPreviewSessionsMutationVariables, TContext> => {

const mutationKey = ['postApiFormsByIdPreviewSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiFormsByIdPreviewSessions>>, PostApiFormsByIdPreviewSessionsMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  postApiFormsByIdPreviewSessions(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiFormsByIdPreviewSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiFormsByIdPreviewSessions>>>

    export type PostApiFormsByIdPreviewSessionsMutationError = void
    export type PostApiFormsByIdPreviewSessionsMutationVariables = {id: string}

    /**
 * @summary Start a preview chat session against the working draft
 */
export const usePostApiFormsByIdPreviewSessions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFormsByIdPreviewSessions>>, TError,PostApiFormsByIdPreviewSessionsMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiFormsByIdPreviewSessions>>,
        TError,
        PostApiFormsByIdPreviewSessionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiFormsByIdPreviewSessionsMutationOptions(options));
    }
    export type getApiTemplatesResponse200 = {
  data: GetApiTemplates200Item[]
  status: 200
}

export type getApiTemplatesResponseSuccess = (getApiTemplatesResponse200) & {
  headers: Headers;
};
;

export type getApiTemplatesResponse = (getApiTemplatesResponseSuccess)

export const getGetApiTemplatesUrl = () => {




  return `http://localhost:8787/api/templates`
}

/**
 * @summary List official templates
 */
export const getApiTemplates = async ( options?: Parameters<typeof customFetch>[1]): Promise<getApiTemplatesResponse> => {

  return customFetch<getApiTemplatesResponse>(getGetApiTemplatesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiTemplatesQueryKey = () => {
    return [
    `http://localhost:8787/api/templates`
    ] as const;
    }


export const getGetApiTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiTemplates>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiTemplates>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTemplatesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTemplates>>> = ({ signal }) => getApiTemplates({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTemplates>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTemplates>>>
export type GetApiTemplatesQueryError = unknown


/**
 * @summary List official templates
 */

export function useGetApiTemplates<TData = Awaited<ReturnType<typeof getApiTemplates>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiTemplates>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiTemplatesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiTemplatesBySlugUseResponse200 = {
  data: void
  status: 200
}

export type postApiTemplatesBySlugUseResponseSuccess = (postApiTemplatesBySlugUseResponse200) & {
  headers: Headers;
};
;

export type postApiTemplatesBySlugUseResponse = (postApiTemplatesBySlugUseResponseSuccess)

export const getPostApiTemplatesBySlugUseUrl = (slug: string,) => {




  return `http://localhost:8787/api/templates/${slug}/use`
}

/**
 * @summary Create a form from a template
 */
export const postApiTemplatesBySlugUse = async (slug: string, options?: Parameters<typeof customFetch>[1]): Promise<postApiTemplatesBySlugUseResponse> => {

  return customFetch<postApiTemplatesBySlugUseResponse>(getPostApiTemplatesBySlugUseUrl(slug),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiTemplatesBySlugUseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTemplatesBySlugUse>>, TError,PostApiTemplatesBySlugUseMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTemplatesBySlugUse>>, TError,PostApiTemplatesBySlugUseMutationVariables, TContext> => {

const mutationKey = ['postApiTemplatesBySlugUse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTemplatesBySlugUse>>, PostApiTemplatesBySlugUseMutationVariables> = (props) => {
          const {slug} = props ?? {};

          return  postApiTemplatesBySlugUse(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTemplatesBySlugUseMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTemplatesBySlugUse>>>

    export type PostApiTemplatesBySlugUseMutationError = unknown
    export type PostApiTemplatesBySlugUseMutationVariables = {slug: string}

    /**
 * @summary Create a form from a template
 */
export const usePostApiTemplatesBySlugUse = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTemplatesBySlugUse>>, TError,PostApiTemplatesBySlugUseMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiTemplatesBySlugUse>>,
        TError,
        PostApiTemplatesBySlugUseMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiTemplatesBySlugUseMutationOptions(options));
    }
