/**
 * Writes `src/generated/openapi.ts` from the API's own spec.
 *
 * The SDK's types used to be written by hand, which made them the one place the
 * API's shapes were copied, and the copy drifted: missing fields, wrong enums,
 * `Record<string, unknown>` where the spec had the whole shape. Now every type
 * the SDK exposes is an alias into this file, so a change to a route's schema
 * reaches the SDK the next time this runs, and `pnpm sdk:verify` fails CI until
 * it has.
 *
 * Only what an API key can call is generated: `/v1`, minus operations the API
 * marks internal or deprecated. The generator runs through a pinned `pnpm dlx`
 * so it adds nothing to the lockfile and nothing to what the package installs.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const GENERATOR = "openapi-typescript@7.13.0";
const METHODS = ["get", "post", "put", "patch", "delete"];

const here = dirname(fileURLToPath(import.meta.url));
const SPEC = join(here, "../../../openapi.json");
const OUT = join(here, "../src/generated/openapi.ts");

const spec = JSON.parse(readFileSync(SPEC, "utf8"));
const paths = {};
for (const [path, item] of Object.entries(spec.paths)) {
  if (!path.startsWith("/v1/")) continue;
  const kept = {};
  for (const [key, value] of Object.entries(item)) {
    if (METHODS.includes(key) && (value["x-internal"] || value.deprecated)) continue;
    kept[key] = value;
  }
  if (Object.keys(kept).some((key) => METHODS.includes(key))) paths[path] = kept;
}

const dir = mkdtempSync(join(tmpdir(), "chatform-sdk-"));
const input = join(dir, "openapi.json");
writeFileSync(input, JSON.stringify({ ...spec, paths, tags: undefined }));
execFileSync("pnpm", ["dlx", GENERATOR, input, "--output", OUT, "--root-types", "--alphabetize"], {
  stdio: ["ignore", "ignore", "inherit"],
});

const header =
  "// Generated by scripts/gen-types.mjs from openapi.json. Do not edit.\n" +
  "// Run `pnpm --filter @chatformhq/js gen:types` after changing an API route.\n\n";
writeFileSync(OUT, header + readFileSync(OUT, "utf8"));
console.log(`wrote ${OUT} (${Object.keys(paths).length} paths)`);
