/**
 * Generates `tooling/seed-templates.sql` from the catalogue in `tooling/templates/`.
 *
 * Same shape as `gen-seed-plans.ts`, for the same reason: the catalogue is the
 * authoring path and `form_templates` is the runtime read path. Templates used
 * to be a `SEEDS` array inside the route that served them, which meant the
 * table declared in the first migration was never once read, adding a template
 * was a deploy, and nothing counted how often one was used.
 *
 * Run: `pnpm gen:templates`. Also writes the public catalogue the marketing
 * site renders; see `writeWebCatalogue`. The output is committed and
 * `pnpm templates:verify` fails on drift. Apply with `pnpm seed:templates`.
 */

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  CATEGORIES_BY_TYPE,
  GOALS,
  ROLES,
  TEMPLATE_TYPES,
  TEMPLATES,
  TYPE_META,
  type TemplateSeed,
} from "./templates/index.js";
import { templatePreset } from "./templates/define.js";

/**
 * A fixed timestamp, not `Date.now()`.
 *
 * The file is committed and verified by regenerating it and diffing, so any
 * value that moves would fail that check on every run. `created_at` is never
 * updated on conflict either, so a re-seed does not rewrite history.
 */
const CREATED_AT = 1_770_000_000_000;

const q = (value: string) => `'${value.replaceAll("'", "''")}'`;

/** `lead-capture` → `tpl_leadcapture`. Deterministic, so re-seeding upserts. */
function idFor(slug: string): string {
  return `tpl_${slug.replace(/[^a-z0-9]/g, "").slice(0, 24)}`;
}

/**
 * What the app's gallery files a template under.
 *
 * The type ("Survey") rather than the category: the in-app gallery filters by
 * one chip row, and three types read as a choice where forty categories would
 * read as a directory. The category is the first tag instead, so the card still
 * says which kind of survey it is.
 */
function appCategory(t: TemplateSeed): string {
  return TYPE_META[t.type].label;
}

function appTags(t: TemplateSeed): string[] {
  const label = (CATEGORIES_BY_TYPE[t.type] as Record<string, string>)[t.category]!;
  return [label.toLowerCase(), ...t.tags.filter((tag) => tag.toLowerCase() !== label.toLowerCase())];
}

function sqlFor(): string {
  const lines: string[] = [
    "-- GENERATED by tooling/gen-seed-templates.ts from tooling/templates/. Do not edit by hand.",
    "-- Regenerate with: pnpm gen:templates",
    "-- Apply with:      pnpm seed:templates",
    "--",
    "-- `usage_count` is deliberately absent from the conflict update: it is runtime",
    "-- data the API increments, and re-seeding must not reset it to zero. Same for",
    "-- `created_at`, so a template keeps the date it first appeared.",
    "",
  ];

  const ids = new Set<string>();
  for (const t of TEMPLATES) {
    const id = idFor(t.slug);
    if (ids.has(id)) throw new Error(`two templates map to the id ${id}; rename one slug`);
    ids.add(id);

    lines.push(
      `INSERT INTO form_templates (id, slug, title, category, description, blurb, tags, icon, accent, est_minutes, block_count, schema_json, thumbnail_r2_key, official, organization_id, usage_count, created_at)`,
      `VALUES (${q(id)}, ${q(t.slug)}, ${q(t.searchName)}, ${q(appCategory(t))}, ${q(t.description)}, ${q(t.blurb)}, ${q(JSON.stringify(appTags(t)))}, ${q(t.icon)}, ${q(t.accent)}, ${t.estMinutes}, ${t.blockCount}, ${q(JSON.stringify(t.doc))}, NULL, 1, NULL, 0, ${CREATED_AT})`,
      `ON CONFLICT (id) DO UPDATE SET`,
      `  slug = excluded.slug,`,
      `  title = excluded.title,`,
      `  category = excluded.category,`,
      `  description = excluded.description,`,
      `  blurb = excluded.blurb,`,
      `  tags = excluded.tags,`,
      `  icon = excluded.icon,`,
      `  accent = excluded.accent,`,
      `  est_minutes = excluded.est_minutes,`,
      `  block_count = excluded.block_count,`,
      `  schema_json = excluded.schema_json,`,
      `  official = excluded.official;`,
      "",
    );
  }

  /**
   * Anything official that is no longer in the catalogue is removed.
   *
   * Without this, deleting a template from the source leaves it in the
   * gallery forever on every database that was seeded before the deletion.
   * Scoped to `official = 1` so a workspace's own saved templates are never
   * touched.
   */
  const keep = TEMPLATES.map((t) => q(idFor(t.slug))).join(", ");
  lines.push(
    "-- Retire official templates that have left the catalogue. Never touches",
    "-- templates an organization saved for itself.",
    `DELETE FROM form_templates WHERE official = 1 AND organization_id IS NULL AND id NOT IN (${keep});`,
    "",
  );

  return lines.join("\n");
}

/**
 * What a card's thumbnail shows: the template's own opening, as the chat would
 * draw it. The greeting, the first question, and a reply only when that
 * question offers choices (its first option), so nothing a respondent never
 * said is put in their mouth. Without choices the thumbnail shows the next
 * question instead, the same shape the dashboard card uses.
 */
function previewOf(t: TemplateSeed): { preset: string; greeting: string; question: string; answer?: string; next?: string } {
  const asked = t.doc.blocks.filter((b) => b.type !== "welcome" && b.type !== "statement");
  const first = asked[0] as { title: string; options?: { label: string }[] } | undefined;
  const second = asked[1] as { title: string } | undefined;
  const greeting = t.doc.blocks.find((b) => b.type === "welcome")?.title ?? t.title;
  const answer = first?.options?.[0]?.label;
  return {
    preset: templatePreset(t.slug),
    greeting,
    question: first?.title ?? "",
    ...(answer ? { answer } : second ? { next: second.title } : {}),
  };
}

/**
 * The same catalogue, as JSON, for the public pages at `/form-templates`.
 *
 * The API serves templates only to a signed-in workspace, which is right for
 * the app and useless to a crawler. The marketing pages are statically
 * rendered, so they read these files at build time instead.
 *
 * Split in two because the whole catalogue is several megabytes of documents:
 * - `index.generated.json` holds the taxonomy and every card, without
 *   documents, for the gallery, the hubs and the sitemap;
 * - `docs/<slug>.json` holds one template's document and guide, and only that
 *   template's page imports it, through `docs/loaders.generated.ts`.
 *
 * `usage_count` is deliberately absent: it is runtime data, and a committed
 * number would be wrong the day after it was generated.
 */
function writeWebCatalogue(root: string): void {
  const index = {
    taxonomy: {
      types: TEMPLATE_TYPES.map((type) => ({
        type,
        ...TYPE_META[type],
        categories: Object.entries(CATEGORIES_BY_TYPE[type]).map(([slug, label]) => ({ slug, label })),
      })),
      goals: Object.entries(GOALS).map(([slug, label]) => ({ slug, label })),
      roles: Object.entries(ROLES).map(([slug, label]) => ({ slug, label })),
    },
    templates: TEMPLATES.map((t) => ({
      slug: t.slug,
      title: t.title,
      searchName: t.searchName,
      type: t.type,
      category: t.category,
      goals: t.goals,
      roles: t.roles,
      description: t.description,
      metaDescription: t.metaDescription,
      blurb: t.blurb,
      tags: t.tags,
      icon: t.icon,
      accent: t.accent,
      blockCount: t.blockCount,
      estMinutes: t.estMinutes,
      facts: t.facts,
      preview: previewOf(t),
    })),
  };
  writeFileSync(join(root, "index.generated.json"), `${JSON.stringify(index, null, 1)}\n`);

  // Just what a card's thumbnail needs, for the app's own gallery and the new
  // form dialog: small enough to ship with the dashboard, where the full index
  // is not.
  const tiles = Object.fromEntries(
    TEMPLATES.map((t) => [
      t.slug,
      {
        kind: `${TYPE_META[t.type].label} · ${(CATEGORIES_BY_TYPE[t.type] as Record<string, string>)[t.category]}`,
        preview: previewOf(t),
      },
    ]),
  );
  writeFileSync(join(root, "tiles.generated.json"), `${JSON.stringify(tiles)}\n`);

  const docs = join(root, "docs");
  mkdirSync(docs, { recursive: true });
  const keep = new Set(TEMPLATES.map((t) => `${t.slug}.json`));
  for (const file of readdirSync(docs)) {
    if (file.endsWith(".json") && !keep.has(file)) rmSync(join(docs, file));
  }
  for (const t of TEMPLATES) {
    writeFileSync(join(docs, `${t.slug}.json`), `${JSON.stringify({ guide: t.guide, doc: t.doc })}\n`);
  }
  const loaders = [
    "// GENERATED by tooling/gen-seed-templates.ts. Do not edit by hand.",
    "// One lazy import per template, so a page bundles only the document it shows.",
    "",
    "export const DOC_LOADERS: Record<string, () => Promise<{ default: unknown }>> = {",
    ...TEMPLATES.map((t) => `  ${JSON.stringify(t.slug)}: () => import("./${t.slug}.json"),`),
    "};",
    "",
  ];
  writeFileSync(join(docs, "loaders.generated.ts"), loaders.join("\n"));
}

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "seed-templates.sql");
writeFileSync(out, sqlFor());
console.log(`wrote ${out}: ${TEMPLATES.length} templates`);

const webRoot = join(here, "../apps/web/src/content/templates");
rmSync(join(webRoot, "catalogue.generated.json"), { force: true });
writeWebCatalogue(webRoot);
console.log(`wrote ${webRoot}/index.generated.json and docs/`);
