/**
 * Generates `tooling/seed-plans.sql` from the `@repo/entitlements` catalogue.
 *
 * The catalogue is the authoring path; `plans` rows are the runtime read path. Writing
 * the SQL by hand would guarantee they drift, and a drifted `plans` row is a gate that
 * disagrees with the pricing page.
 *
 * Run: `pnpm gen:plans`. The output is committed, and `pnpm setup` applies it — without
 * it `plans` is empty and every checkout 503s, which is exactly the state the repo was in.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PLAN_LIST } from "@repo/entitlements";

/**
 * Dodo product ids are per-environment, so they are never baked into the seed. They are
 * set from env after the products exist in the Dodo dashboard:
 *
 *   UPDATE plans SET dodo_product_monthly_id = ? WHERE id = 'pro';
 *
 * `GET /api/billing/config-check` reports which ones are still missing, so a
 * misconfigured environment says so instead of failing at checkout.
 */
function sqlFor(): string {
  const lines: string[] = [
    "-- GENERATED by tooling/gen-seed-plans.ts from @repo/entitlements — do not edit by hand.",
    "-- Regenerate with: pnpm gen:plans",
    "-- Apply with:      pnpm seed:plans",
    "--",
    "-- Dodo product ids are per-environment and deliberately absent here; set them after",
    "-- creating the products, and check with GET /api/billing/config-check.",
    "",
  ];

  for (const plan of PLAN_LIST) {
    const features = JSON.stringify(plan.features).replaceAll("'", "''");
    const limits = JSON.stringify(plan.limits).replaceAll("'", "''");
    lines.push(
      `INSERT INTO plans (id, slug, name, price_monthly_cents, price_yearly_cents, seat_price_cents, currency, features_json, limits_json, is_active, sort_order)`,
      `VALUES ('${plan.id}', '${plan.id}', '${plan.name}', ${plan.priceMonthlyCents}, ${plan.priceYearlyCents}, ${plan.seatPriceCents}, '${plan.currency}', '${features}', '${limits}', 1, ${plan.sortOrder})`,
      `ON CONFLICT (id) DO UPDATE SET`,
      `  slug = excluded.slug,`,
      `  name = excluded.name,`,
      `  price_monthly_cents = excluded.price_monthly_cents,`,
      `  price_yearly_cents = excluded.price_yearly_cents,`,
      `  seat_price_cents = excluded.seat_price_cents,`,
      `  currency = excluded.currency,`,
      `  features_json = excluded.features_json,`,
      `  limits_json = excluded.limits_json,`,
      `  is_active = excluded.is_active,`,
      `  sort_order = excluded.sort_order;`,
      "",
    );
  }

  return lines.join("\n");
}

const out = join(dirname(fileURLToPath(import.meta.url)), "seed-plans.sql");
writeFileSync(out, sqlFor());
console.log(`wrote ${out} — ${PLAN_LIST.length} plans`);
