/**
 * Generates `tooling/seed-templates.sql` from the catalogue in `tooling/templates/`.
 *
 * Same shape as `gen-seed-plans.ts`, for the same reason: the catalogue is the
 * authoring path and `form_templates` is the runtime read path. Templates used
 * to be a `SEEDS` array inside the route that served them, which meant the
 * table declared in the first migration was never once read, adding a template
 * was a deploy, and nothing counted how often one was used.
 *
 * Run: `pnpm gen:templates`. The output is committed and `pnpm templates:verify`
 * fails on drift. Apply with `pnpm seed:templates`.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { TEMPLATES } from "./templates/index.js";

/**
 * A fixed timestamp, not `Date.now()`.
 *
 * The file is committed and verified by regenerating it and diffing, so any
 * value that moves would fail that check on every run. `created_at` is never
 * updated on conflict either, so a re-seed does not rewrite history.
 */
const CREATED_AT = 1_770_000_000_000;

const q = (value: string) => `'${value.replaceAll("'", "''")}'`;

/** `lead-capture` → `tpl_leadcapture`. Deterministic, so re-seeding upserts. */
function idFor(slug: string): string {
  return `tpl_${slug.replace(/[^a-z0-9]/g, "").slice(0, 24)}`;
}

function sqlFor(): string {
  const lines: string[] = [
    "-- GENERATED by tooling/gen-seed-templates.ts from tooling/templates/ — do not edit by hand.",
    "-- Regenerate with: pnpm gen:templates",
    "-- Apply with:      pnpm seed:templates",
    "--",
    "-- `usage_count` is deliberately absent from the conflict update: it is runtime",
    "-- data the API increments, and re-seeding must not reset it to zero. Same for",
    "-- `created_at`, so a template keeps the date it first appeared.",
    "",
  ];

  const seen = new Set<string>();
  for (const t of TEMPLATES) {
    if (seen.has(t.slug)) throw new Error(`duplicate template slug: ${t.slug}`);
    seen.add(t.slug);

    lines.push(
      `INSERT INTO form_templates (id, slug, title, category, description, blurb, tags, icon, accent, est_minutes, block_count, schema_json, thumbnail_r2_key, official, organization_id, usage_count, created_at)`,
      `VALUES (${q(idFor(t.slug))}, ${q(t.slug)}, ${q(t.title)}, ${q(t.category)}, ${q(t.description)}, ${q(t.blurb)}, ${q(JSON.stringify(t.tags))}, ${q(t.icon)}, ${q(t.accent)}, ${t.estMinutes}, ${t.blockCount}, ${q(JSON.stringify(t.doc))}, NULL, 1, NULL, 0, ${CREATED_AT})`,
      `ON CONFLICT (id) DO UPDATE SET`,
      `  slug = excluded.slug,`,
      `  title = excluded.title,`,
      `  category = excluded.category,`,
      `  description = excluded.description,`,
      `  blurb = excluded.blurb,`,
      `  tags = excluded.tags,`,
      `  icon = excluded.icon,`,
      `  accent = excluded.accent,`,
      `  est_minutes = excluded.est_minutes,`,
      `  block_count = excluded.block_count,`,
      `  schema_json = excluded.schema_json,`,
      `  official = excluded.official;`,
      "",
    );
  }

  /**
   * Anything official that is no longer in the catalogue is removed.
   *
   * Without this, deleting a template from the source leaves it in the
   * gallery forever on every database that was seeded before the deletion.
   * Scoped to `official = 1` so a workspace's own saved templates are never
   * touched.
   */
  const keep = TEMPLATES.map((t) => q(idFor(t.slug))).join(", ");
  lines.push(
    "-- Retire official templates that have left the catalogue. Never touches",
    "-- templates an organization saved for itself.",
    `DELETE FROM form_templates WHERE official = 1 AND organization_id IS NULL AND id NOT IN (${keep});`,
    "",
  );

  return lines.join("\n");
}

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "seed-templates.sql");
writeFileSync(out, sqlFor());
console.log(`wrote ${out} — ${TEMPLATES.length} templates`);
