/**
 * Collects chatform's own respondent-facing text into one list.
 *
 * The runtime writes its interface text in English at the call site, as
 * `t("Send")` or `msg("…")`, and looks the translation up by that English. The
 * API translates the list this script writes, so a string that is not on it is
 * never translated and stays English on every form.
 *
 * Read from source rather than maintained by hand for that reason: a list
 * somebody has to remember to update is a list that is one string short. CI
 * runs this and fails on a diff (`pnpm interface-text:verify`).
 *
 * The call must be a plain string literal. A string built at runtime cannot be
 * found here, which is why interpolation is `{name}` placeholders with the
 * values passed beside it.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Everywhere a respondent's text is written. */
const SOURCES = [
  "apps/web/src/components/chat",
  "packages/form-schema/src/engine/validators.ts",
  "apps/api/src/lib/phrasing.ts",
  "apps/api/src/do/session-do.ts",
];

function files(path: string): string[] {
  const full = join(ROOT, path);
  if (statSync(full).isFile()) return [full];
  return readdirSync(full, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory() ? files(join(path, entry.name)) : /\.tsx?$/.test(entry.name) ? [join(full, entry.name)] : [],
  );
}

// `t("…")`, `this.t('…')`, `msg(`…`)`: the first argument, when it is a literal.
const CALL = /(?<![\w$])(?:t|msg)\(\s*("(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|`(?:[^`\\$]|\\.)*`)/g;

function literal(raw: string): string {
  const body = raw.slice(1, -1);
  // The three quote styles differ only in which quote needs escaping.
  return JSON.parse(`"${body.replace(/\\(['`])/g, "$1").replace(/(?<!\\)"/g, '\\"').replace(/\n/g, "\\n")}"`) as string;
}

const found = new Set<string>();
for (const source of SOURCES) {
  for (const file of files(source)) {
    const text = readFileSync(file, "utf8");
    for (const match of text.matchAll(CALL)) {
      const value = literal(match[1]!);
      if (value.trim()) found.add(value);
    }
  }
}

const list = [...found].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
const out = `// Generated by \`pnpm gen:interface-text\` from every \`t("…")\` in the respondent
// runtime. Do not edit: change the call site and regenerate.
export const INTERFACE_TEXT: readonly string[] = [
${list.map((text) => `  ${JSON.stringify(text)},`).join("\n")}
];
`;
writeFileSync(join(ROOT, "packages/form-schema/src/interface-text.generated.ts"), out);
console.log(`${list.length} interface strings`);
