-- GENERATED by tooling/gen-seed-plans.ts from @repo/entitlements — do not edit by hand.
-- Regenerate with: pnpm gen:plans
-- Apply with:      pnpm seed:plans
--
-- Dodo product ids are per-environment and deliberately absent here; set them after
-- creating the products, and check with GET /api/billing/config-check.

INSERT INTO plans (id, slug, name, price_monthly_cents, price_yearly_cents, seat_price_cents, currency, features_json, limits_json, is_active, sort_order)
VALUES ('free', 'free', 'Free', 0, 0, 0, 'USD', '[]', '{"responses_per_month":null,"responses_ceiling_per_month":5000,"ai_conversations_per_month":200,"ai_tokens_per_month":500000,"ai_generations_per_month":10,"api_requests_per_month":0,"emails_per_month":500,"followups_shared_domain_per_month":0,"forms_count":100,"workspaces_count":1,"seats":1,"file_storage_mb":10,"max_upload_mb_per_file":5,"blocks_per_form":100,"webhooks_per_form":2,"knowledge_sources_count":0,"knowledge_bytes":0,"agent_max_turns":50,"agent_token_budget":60000}', 1, 0)
ON CONFLICT (id) DO UPDATE SET
  slug = excluded.slug,
  name = excluded.name,
  price_monthly_cents = excluded.price_monthly_cents,
  price_yearly_cents = excluded.price_yearly_cents,
  seat_price_cents = excluded.seat_price_cents,
  currency = excluded.currency,
  features_json = excluded.features_json,
  limits_json = excluded.limits_json,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

INSERT INTO plans (id, slug, name, price_monthly_cents, price_yearly_cents, seat_price_cents, currency, features_json, limits_json, is_active, sort_order)
VALUES ('pro', 'pro', 'Pro', 2400, 19200, 0, 'USD', '["custom_fonts","brand_logo","remove_branding","duplicate_prevention","multi_language","respondent_auth_google","respondent_auth_phone","collect_payments","partial_responses","advanced_analytics","conversation_analytics","export_partials","form_metadata","completion_redirect","auto_reply_email","followup_email","custom_domain","refill_link","tracking_pixels","api_access","agent_persona","agent_knowledge","agent_guardrails","team_roles"]', '{"responses_per_month":null,"responses_ceiling_per_month":50000,"ai_conversations_per_month":2000,"ai_tokens_per_month":6000000,"ai_generations_per_month":200,"api_requests_per_month":50000,"emails_per_month":10000,"followups_shared_domain_per_month":500,"forms_count":1000,"workspaces_count":10,"seats":3,"file_storage_mb":10240,"max_upload_mb_per_file":50,"blocks_per_form":300,"webhooks_per_form":10,"knowledge_sources_count":50,"knowledge_bytes":26214400,"agent_max_turns":100,"agent_token_budget":500000}', 1, 1)
ON CONFLICT (id) DO UPDATE SET
  slug = excluded.slug,
  name = excluded.name,
  price_monthly_cents = excluded.price_monthly_cents,
  price_yearly_cents = excluded.price_yearly_cents,
  seat_price_cents = excluded.seat_price_cents,
  currency = excluded.currency,
  features_json = excluded.features_json,
  limits_json = excluded.limits_json,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

INSERT INTO plans (id, slug, name, price_monthly_cents, price_yearly_cents, seat_price_cents, currency, features_json, limits_json, is_active, sort_order)
VALUES ('business', 'business', 'Business', 8400, 66000, 1000, 'USD', '["custom_fonts","brand_logo","remove_branding","duplicate_prevention","multi_language","respondent_auth_google","respondent_auth_phone","collect_payments","partial_responses","advanced_analytics","conversation_analytics","export_partials","form_metadata","completion_redirect","auto_reply_email","followup_email","custom_domain","refill_link","tracking_pixels","api_access","agent_persona","agent_knowledge","agent_guardrails","team_roles","verified_answers","one_response_per_identity","ai_insights","agent_model_picker","activity_log"]', '{"responses_per_month":null,"responses_ceiling_per_month":50000,"ai_conversations_per_month":10000,"ai_tokens_per_month":30000000,"ai_generations_per_month":1000,"api_requests_per_month":250000,"emails_per_month":50000,"followups_shared_domain_per_month":2000,"forms_count":1000,"workspaces_count":25,"seats":5,"file_storage_mb":51200,"max_upload_mb_per_file":100,"blocks_per_form":300,"webhooks_per_form":25,"knowledge_sources_count":500,"knowledge_bytes":262144000,"agent_max_turns":200,"agent_token_budget":1000000}', 1, 2)
ON CONFLICT (id) DO UPDATE SET
  slug = excluded.slug,
  name = excluded.name,
  price_monthly_cents = excluded.price_monthly_cents,
  price_yearly_cents = excluded.price_yearly_cents,
  seat_price_cents = excluded.seat_price_cents,
  currency = excluded.currency,
  features_json = excluded.features_json,
  limits_json = excluded.limits_json,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;
